export interface CentralAdministrationCopy {
  title: string;
  description: string;
  refresh: string;
  addInstitution: string;
  institutionName: string;
  ror: string;
  create: string;
  active: string;
  disabled: string;
  manage: string;
  members: string;
  apiKeys: string;
  admins: string;
  addAdmin: string;
  email: string;
  adminRole: string;
  remove: string;
  apiTitle: string;
  apiDescription: string;
  label: string;
  expires: string;
  createToken: string;
  revoke: string;
  tokenOnce: string;
  audit: string;
  none: string;
  loadCentralError: string;
  loadInstitutionError: string;
  requestError: string;
}

export const centralAdministrationTranslations: Record<string, CentralAdministrationCopy> = {
  bg:{title:'Централна администрация',description:'Управлявайте институции, институционални администратори и ограничени по обхват идентификационни данни за Admin API. Централният достъп не дава достъп до ръкописи.',refresh:'Обновяване',addInstitution:'Добавяне на институция',institutionName:'Име на институцията',ror:'ROR идентификатор',create:'Създаване',active:'Активна',disabled:'Деактивирана',manage:'Управление',members:'членове',apiKeys:'API идентификационни данни',admins:'Институционални администратори',addAdmin:'Добавяне на администратор',email:'Имейл на Studio профила',adminRole:'Роля',remove:'Премахване на администраторската роля',apiTitle:'Institution Admin API',apiDescription:'Токените са свързани с институция, ограничени по обхват и се показват само веднъж при създаване.',label:'Етикет на идентификационните данни',expires:'Изтича след дни',createToken:'Създаване на API токен',revoke:'Отмяна',tokenOnce:'Копирайте този токен сега. Той няма да бъде показан отново.',audit:'Последни одитни събития',none:'Все още няма записи.',loadCentralError:'Централната администрация не можа да бъде заредена.',loadInstitutionError:'Администрацията на институцията не можа да бъде заредена.',requestError:'Заявката към централната администрация е неуспешна.'},
  cs:{title:'Centrální správa',description:'Spravujte instituce, institucionální administrátory a přístupové údaje Admin API s omezeným rozsahem. Centrální přístup neposkytuje přístup k rukopisům.',refresh:'Obnovit',addInstitution:'Přidat instituci',institutionName:'Název instituce',ror:'Identifikátor ROR',create:'Vytvořit',active:'Aktivní',disabled:'Zakázaná',manage:'Spravovat',members:'členů',apiKeys:'Přístupové údaje API',admins:'Institucionální administrátoři',addAdmin:'Přidat administrátora',email:'E-mail účtu Studio',adminRole:'Role',remove:'Odebrat roli administrátora',apiTitle:'Institution Admin API',apiDescription:'Tokeny jsou vázané na instituci, mají omezený rozsah a při vytvoření se zobrazí pouze jednou.',label:'Název přístupového údaje',expires:'Platnost v dnech',createToken:'Vytvořit API token',revoke:'Odvolat',tokenOnce:'Zkopírujte token nyní. Znovu se už nezobrazí.',audit:'Nedávné auditní události',none:'Zatím žádné záznamy.',loadCentralError:'Centrální správu se nepodařilo načíst.',loadInstitutionError:'Správu instituce se nepodařilo načíst.',requestError:'Požadavek centrální správy selhal.'},
  da:{title:'Central administration',description:'Administrer institutioner, institutionsadministratorer og afgrænsede Admin API-legitimationsoplysninger. Central adgang giver ikke adgang til manuskripter.',refresh:'Opdater',addInstitution:'Tilføj institution',institutionName:'Institutionsnavn',ror:'ROR-id',create:'Opret',active:'Aktiv',disabled:'Deaktiveret',manage:'Administrer',members:'medlemmer',apiKeys:'API-legitimationsoplysninger',admins:'Institutionsadministratorer',addAdmin:'Tilføj administrator',email:'Studio-kontoens e-mail',adminRole:'Rolle',remove:'Fjern administratorrolle',apiTitle:'Institution Admin API',apiDescription:'Tokens er bundet til en institution, afgrænset efter rettigheder og vises kun én gang ved oprettelsen.',label:'Navn på legitimationsoplysning',expires:'Udløber om dage',createToken:'Opret API-token',revoke:'Tilbagekald',tokenOnce:'Kopiér dette token nu. Det vises ikke igen.',audit:'Seneste revisionshændelser',none:'Ingen poster endnu.',loadCentralError:'Central administration kunne ikke indlæses.',loadInstitutionError:'Institutionsadministration kunne ikke indlæses.',requestError:'Anmodningen til central administration mislykkedes.'},
  de:{title:'Zentrale Administration',description:'Institutionen, Institutionsadministratoren und bereichsgebundene Admin-API-Zugänge verwalten. Zentrale Rechte gewähren keinen Manuskriptzugriff.',refresh:'Aktualisieren',addInstitution:'Institution hinzufügen',institutionName:'Name der Institution',ror:'ROR-Kennung',create:'Erstellen',active:'Aktiv',disabled:'Deaktiviert',manage:'Verwalten',members:'Mitglieder',apiKeys:'API-Zugänge',admins:'Institutionsadministratoren',addAdmin:'Administrator hinzufügen',email:'E-Mail des Studio-Kontos',adminRole:'Rolle',remove:'Adminrolle entfernen',apiTitle:'Institution Admin API',apiDescription:'Tokens sind institutionsgebunden, bereichsbeschränkt und werden bei der Erstellung nur einmal angezeigt.',label:'Bezeichnung',expires:'Ablauf in Tagen',createToken:'API-Token erstellen',revoke:'Widerrufen',tokenOnce:'Kopieren Sie den Token jetzt. Er wird später nicht erneut angezeigt.',audit:'Letzte Audit-Ereignisse',none:'Noch keine Einträge.',loadCentralError:'Die zentrale Administration konnte nicht geladen werden.',loadInstitutionError:'Die Institutionsadministration konnte nicht geladen werden.',requestError:'Die Anfrage an die zentrale Administration ist fehlgeschlagen.'},
  el:{title:'Κεντρική διαχείριση',description:'Διαχειριστείτε ιδρύματα, διαχειριστές ιδρυμάτων και διαπιστευτήρια Admin API με περιορισμένα δικαιώματα. Η κεντρική πρόσβαση δεν παρέχει πρόσβαση σε χειρόγραφα.',refresh:'Ανανέωση',addInstitution:'Προσθήκη ιδρύματος',institutionName:'Όνομα ιδρύματος',ror:'Αναγνωριστικό ROR',create:'Δημιουργία',active:'Ενεργό',disabled:'Απενεργοποιημένο',manage:'Διαχείριση',members:'μέλη',apiKeys:'Διαπιστευτήρια API',admins:'Διαχειριστές ιδρύματος',addAdmin:'Προσθήκη διαχειριστή',email:'E-mail λογαριασμού Studio',adminRole:'Ρόλος',remove:'Αφαίρεση ρόλου διαχειριστή',apiTitle:'Institution Admin API',apiDescription:'Τα token συνδέονται με ίδρυμα, έχουν συγκεκριμένα δικαιώματα και εμφανίζονται μόνο μία φορά κατά τη δημιουργία.',label:'Ετικέτα διαπιστευτηρίου',expires:'Λήξη σε ημέρες',createToken:'Δημιουργία API token',revoke:'Ανάκληση',tokenOnce:'Αντιγράψτε τώρα αυτό το token. Δεν θα εμφανιστεί ξανά.',audit:'Πρόσφατα συμβάντα ελέγχου',none:'Δεν υπάρχουν ακόμη εγγραφές.',loadCentralError:'Δεν ήταν δυνατή η φόρτωση της κεντρικής διαχείρισης.',loadInstitutionError:'Δεν ήταν δυνατή η φόρτωση της διαχείρισης ιδρύματος.',requestError:'Το αίτημα κεντρικής διαχείρισης απέτυχε.'},
  en:{title:'Central administration',description:'Manage institutions, institutional administrators and scoped Admin API credentials. Central access does not grant manuscript access.',refresh:'Refresh',addInstitution:'Add institution',institutionName:'Institution name',ror:'ROR identifier',create:'Create',active:'Active',disabled:'Disabled',manage:'Manage',members:'members',apiKeys:'API credentials',admins:'Institution administrators',addAdmin:'Add administrator',email:'Studio account e-mail',adminRole:'Role',remove:'Remove admin role',apiTitle:'Institution Admin API',apiDescription:'Tokens are institution-bound, scoped and shown only once when created.',label:'Credential label',expires:'Expires in days',createToken:'Create API token',revoke:'Revoke',tokenOnce:'Copy this token now. It will not be shown again.',audit:'Recent audit events',none:'No records yet.',loadCentralError:'Central administration could not be loaded.',loadInstitutionError:'Institution administration could not be loaded.',requestError:'Central administration request failed.'},
  es:{title:'Administración central',description:'Gestione instituciones, administradores institucionales y credenciales del Admin API con ámbitos limitados. El acceso central no concede acceso a manuscritos.',refresh:'Actualizar',addInstitution:'Añadir institución',institutionName:'Nombre de la institución',ror:'Identificador ROR',create:'Crear',active:'Activa',disabled:'Deshabilitada',manage:'Gestionar',members:'miembros',apiKeys:'Credenciales API',admins:'Administradores institucionales',addAdmin:'Añadir administrador',email:'Correo de la cuenta Studio',adminRole:'Rol',remove:'Quitar rol de administrador',apiTitle:'Institution Admin API',apiDescription:'Los tokens están vinculados a una institución, tienen ámbitos limitados y solo se muestran una vez al crearlos.',label:'Etiqueta de credencial',expires:'Caduca en días',createToken:'Crear token API',revoke:'Revocar',tokenOnce:'Copie este token ahora. No volverá a mostrarse.',audit:'Eventos de auditoría recientes',none:'Aún no hay registros.',loadCentralError:'No se pudo cargar la administración central.',loadInstitutionError:'No se pudo cargar la administración institucional.',requestError:'La solicitud de administración central falló.'},
  et:{title:'Keskhaldus',description:'Hallake asutusi, asutuste administraatoreid ja piiratud õigustega Admin API mandaate. Keskne juurdepääs ei anna juurdepääsu käsikirjadele.',refresh:'Värskenda',addInstitution:'Lisa asutus',institutionName:'Asutuse nimi',ror:'ROR-tunnus',create:'Loo',active:'Aktiivne',disabled:'Keelatud',manage:'Halda',members:'liiget',apiKeys:'API mandaadid',admins:'Asutuse administraatorid',addAdmin:'Lisa administraator',email:'Studio konto e-post',adminRole:'Roll',remove:'Eemalda administraatori roll',apiTitle:'Institution Admin API',apiDescription:'Tokenid on seotud asutusega, piiratud õigustega ja neid näidatakse loomisel ainult üks kord.',label:'Mandaadi nimi',expires:'Aegub päevade pärast',createToken:'Loo API token',revoke:'Tühista',tokenOnce:'Kopeerige see token nüüd. Seda ei kuvata enam uuesti.',audit:'Hiljutised auditilogid',none:'Kirjeid veel pole.',loadCentralError:'Keskhaldust ei saanud laadida.',loadInstitutionError:'Asutuse haldust ei saanud laadida.',requestError:'Keskhalduse päring ebaõnnestus.'},
  fi:{title:'Keskushallinta',description:'Hallitse organisaatioita, organisaatioiden ylläpitäjiä ja rajattuja Admin API -tunnuksia. Keskitetty käyttöoikeus ei anna pääsyä käsikirjoituksiin.',refresh:'Päivitä',addInstitution:'Lisää organisaatio',institutionName:'Organisaation nimi',ror:'ROR-tunniste',create:'Luo',active:'Aktiivinen',disabled:'Poistettu käytöstä',manage:'Hallitse',members:'jäsentä',apiKeys:'API-tunnukset',admins:'Organisaation ylläpitäjät',addAdmin:'Lisää ylläpitäjä',email:'Studio-tilin sähköposti',adminRole:'Rooli',remove:'Poista ylläpitäjärooli',apiTitle:'Institution Admin API',apiDescription:'Tokenit on sidottu organisaatioon, rajattu oikeuksilla ja näytetään vain kerran luotaessa.',label:'Tunnuksen nimi',expires:'Voimassa päiviä',createToken:'Luo API-token',revoke:'Peruuta',tokenOnce:'Kopioi tämä token nyt. Sitä ei näytetä uudelleen.',audit:'Viimeisimmät auditointitapahtumat',none:'Ei vielä tietueita.',loadCentralError:'Keskushallintaa ei voitu ladata.',loadInstitutionError:'Organisaation hallintaa ei voitu ladata.',requestError:'Keskushallinnan pyyntö epäonnistui.'},
  fr:{title:'Administration centrale',description:'Gérez les institutions, leurs administrateurs et les identifiants Admin API à portée limitée. L’accès central ne donne pas accès aux manuscrits.',refresh:'Actualiser',addInstitution:'Ajouter une institution',institutionName:'Nom de l’institution',ror:'Identifiant ROR',create:'Créer',active:'Active',disabled:'Désactivée',manage:'Gérer',members:'membres',apiKeys:'Identifiants API',admins:'Administrateurs institutionnels',addAdmin:'Ajouter un administrateur',email:'E-mail du compte Studio',adminRole:'Rôle',remove:'Retirer le rôle administrateur',apiTitle:'Institution Admin API',apiDescription:'Les jetons sont liés à une institution, limités par portée et affichés une seule fois lors de leur création.',label:'Libellé de l’identifiant',expires:'Expiration en jours',createToken:'Créer un jeton API',revoke:'Révoquer',tokenOnce:'Copiez ce jeton maintenant. Il ne sera plus affiché.',audit:'Événements d’audit récents',none:'Aucun enregistrement pour le moment.',loadCentralError:'Impossible de charger l’administration centrale.',loadInstitutionError:'Impossible de charger l’administration institutionnelle.',requestError:'La requête d’administration centrale a échoué.'},
  ga:{title:'Riarachán lárnach',description:'Bainistigh institiúidí, riarthóirí institiúideacha agus dintiúir Admin API faoi scóip. Ní thugann rochtain lárnach rochtain ar lámhscríbhinní.',refresh:'Athnuaigh',addInstitution:'Cuir institiúid leis',institutionName:'Ainm na hinstitiúide',ror:'Aitheantóir ROR',create:'Cruthaigh',active:'Gníomhach',disabled:'Díchumasaithe',manage:'Bainistigh',members:'baill',apiKeys:'Dintiúir API',admins:'Riarthóirí institiúideacha',addAdmin:'Cuir riarthóir leis',email:'Ríomhphost chuntas Studio',adminRole:'Ról',remove:'Bain ról riarthóra',apiTitle:'Institution Admin API',apiDescription:'Tá na comharthaí ceangailte le hinstitiúid, faoi scóip agus ní thaispeántar iad ach uair amháin nuair a chruthaítear iad.',label:'Lipéad dintiúir',expires:'Éagann i laethanta',createToken:'Cruthaigh comhartha API',revoke:'Cúlghair',tokenOnce:'Cóipeáil an comhartha seo anois. Ní thaispeánfar arís é.',audit:'Imeachtaí iniúchta le déanaí',none:'Níl aon taifid ann fós.',loadCentralError:'Níorbh fhéidir an riarachán lárnach a lódáil.',loadInstitutionError:'Níorbh fhéidir riarachán na hinstitiúide a lódáil.',requestError:'Theip ar iarratas an riaracháin lárnaigh.'},
  hr:{title:'Središnja administracija',description:'Upravljajte institucijama, institucijskim administratorima i ograničenim vjerodajnicama Admin API-ja. Središnji pristup ne daje pristup rukopisima.',refresh:'Osvježi',addInstitution:'Dodaj instituciju',institutionName:'Naziv institucije',ror:'ROR identifikator',create:'Stvori',active:'Aktivna',disabled:'Onemogućena',manage:'Upravljaj',members:'članova',apiKeys:'API vjerodajnice',admins:'Institucijski administratori',addAdmin:'Dodaj administratora',email:'E-pošta Studio računa',adminRole:'Uloga',remove:'Ukloni administratorsku ulogu',apiTitle:'Institution Admin API',apiDescription:'Tokeni su vezani uz instituciju, ograničeni opsegom i prikazuju se samo jednom pri stvaranju.',label:'Naziv vjerodajnice',expires:'Istječe za dana',createToken:'Stvori API token',revoke:'Opozovi',tokenOnce:'Kopirajte ovaj token sada. Više se neće prikazati.',audit:'Nedavni zapisi nadzora',none:'Još nema zapisa.',loadCentralError:'Središnju administraciju nije moguće učitati.',loadInstitutionError:'Administraciju institucije nije moguće učitati.',requestError:'Zahtjev središnje administracije nije uspio.'},
  hu:{title:'Központi adminisztráció',description:'Intézmények, intézményi adminisztrátorok és scope-olt Admin API-hozzáférések kezelése. A központi jogosultság nem ad hozzáférést a kéziratokhoz.',refresh:'Frissítés',addInstitution:'Intézmény hozzáadása',institutionName:'Intézmény neve',ror:'ROR-azonosító',create:'Létrehozás',active:'Aktív',disabled:'Letiltva',manage:'Kezelés',members:'tag',apiKeys:'API-hozzáférések',admins:'Intézményi adminisztrátorok',addAdmin:'Adminisztrátor hozzáadása',email:'Studio-fiók e-mail-címe',adminRole:'Szerepkör',remove:'Adminjog visszavonása',apiTitle:'Intézményi Admin API',apiDescription:'A tokenek intézményhez kötöttek, scope-oltak, és létrehozáskor csak egyszer láthatók.',label:'API-hozzáférés neve',expires:'Lejárat napokban',createToken:'API-token létrehozása',revoke:'Visszavonás',tokenOnce:'Másold ki most a tokent. Később nem jelenik meg újra.',audit:'Legutóbbi auditbejegyzések',none:'Még nincs bejegyzés.',loadCentralError:'A központi adminisztráció nem tölthető be.',loadInstitutionError:'Az intézményi adminisztráció nem tölthető be.',requestError:'A központi adminisztrációs kérés sikertelen.'},
  it:{title:'Amministrazione centrale',description:'Gestisci istituzioni, amministratori istituzionali e credenziali Admin API con ambiti limitati. L’accesso centrale non concede accesso ai manoscritti.',refresh:'Aggiorna',addInstitution:'Aggiungi istituzione',institutionName:'Nome dell’istituzione',ror:'Identificatore ROR',create:'Crea',active:'Attiva',disabled:'Disabilitata',manage:'Gestisci',members:'membri',apiKeys:'Credenziali API',admins:'Amministratori istituzionali',addAdmin:'Aggiungi amministratore',email:'E-mail dell’account Studio',adminRole:'Ruolo',remove:'Rimuovi ruolo amministratore',apiTitle:'Institution Admin API',apiDescription:'I token sono legati all’istituzione, limitati per ambito e mostrati una sola volta alla creazione.',label:'Etichetta credenziale',expires:'Scade tra giorni',createToken:'Crea token API',revoke:'Revoca',tokenOnce:'Copia questo token ora. Non verrà mostrato di nuovo.',audit:'Eventi di audit recenti',none:'Nessun record ancora.',loadCentralError:'Impossibile caricare l’amministrazione centrale.',loadInstitutionError:'Impossibile caricare l’amministrazione istituzionale.',requestError:'La richiesta di amministrazione centrale non è riuscita.'},
  lt:{title:'Centrinis administravimas',description:'Tvarkykite institucijas, institucijų administratorius ir ribotos apimties Admin API kredencialus. Centrinė prieiga nesuteikia prieigos prie rankraščių.',refresh:'Atnaujinti',addInstitution:'Pridėti instituciją',institutionName:'Institucijos pavadinimas',ror:'ROR identifikatorius',create:'Sukurti',active:'Aktyvi',disabled:'Išjungta',manage:'Tvarkyti',members:'nariai',apiKeys:'API kredencialai',admins:'Institucijos administratoriai',addAdmin:'Pridėti administratorių',email:'Studio paskyros el. paštas',adminRole:'Vaidmuo',remove:'Pašalinti administratoriaus vaidmenį',apiTitle:'Institution Admin API',apiDescription:'Tokenai susieti su institucija, turi ribotą apimtį ir sukūrus rodomi tik vieną kartą.',label:'Kredencialo pavadinimas',expires:'Galioja dienų',createToken:'Sukurti API tokeną',revoke:'Atšaukti',tokenOnce:'Nukopijuokite šį tokeną dabar. Jis daugiau nebus rodomas.',audit:'Naujausi audito įvykiai',none:'Įrašų dar nėra.',loadCentralError:'Nepavyko įkelti centrinio administravimo.',loadInstitutionError:'Nepavyko įkelti institucijos administravimo.',requestError:'Centrinio administravimo užklausa nepavyko.'},
  lv:{title:'Centrālā administrēšana',description:'Pārvaldiet institūcijas, institūciju administratorus un ierobežota tvēruma Admin API akreditācijas datus. Centrālā piekļuve nepiešķir piekļuvi manuskriptiem.',refresh:'Atsvaidzināt',addInstitution:'Pievienot institūciju',institutionName:'Institūcijas nosaukums',ror:'ROR identifikators',create:'Izveidot',active:'Aktīva',disabled:'Atspējota',manage:'Pārvaldīt',members:'dalībnieki',apiKeys:'API akreditācijas dati',admins:'Institūcijas administratori',addAdmin:'Pievienot administratoru',email:'Studio konta e-pasts',adminRole:'Loma',remove:'Noņemt administratora lomu',apiTitle:'Institution Admin API',apiDescription:'Tokeni ir piesaistīti institūcijai, ar ierobežotu tvērumu un tiek parādīti tikai vienu reizi izveides brīdī.',label:'Akreditācijas datu nosaukums',expires:'Derīgs dienas',createToken:'Izveidot API tokenu',revoke:'Atsaukt',tokenOnce:'Nokopējiet šo tokenu tagad. Tas vairs netiks parādīts.',audit:'Nesenie audita notikumi',none:'Ierakstu vēl nav.',loadCentralError:'Neizdevās ielādēt centrālo administrēšanu.',loadInstitutionError:'Neizdevās ielādēt institūcijas administrēšanu.',requestError:'Centrālās administrēšanas pieprasījums neizdevās.'},
  mt:{title:'Amministrazzjoni ċentrali',description:'Immaniġġja istituzzjonijiet, amministraturi istituzzjonali u kredenzjali tal-Admin API b’ambitu limitat. L-aċċess ċentrali ma jagħtix aċċess għall-manuskritti.',refresh:'Aġġorna',addInstitution:'Żid istituzzjoni',institutionName:'Isem tal-istituzzjoni',ror:'Identifikatur ROR',create:'Oħloq',active:'Attiva',disabled:'Diżattivata',manage:'Immaniġġja',members:'membri',apiKeys:'Kredenzjali API',admins:'Amministraturi istituzzjonali',addAdmin:'Żid amministratur',email:'E-mail tal-kont Studio',adminRole:'Rwol',remove:'Neħħi r-rwol ta’ amministratur',apiTitle:'Institution Admin API',apiDescription:'It-tokens huma marbuta mal-istituzzjoni, limitati skont l-ambitu u jintwerew darba biss meta jinħolqu.',label:'Tikketta tal-kredenzjal',expires:'Jiskadi fi ġranet',createToken:'Oħloq token API',revoke:'Irrevoka',tokenOnce:'Ikkopja dan it-token issa. Mhux se jintwera mill-ġdid.',audit:'Avvenimenti ta’ verifika reċenti',none:'Għad m’hemmx rekords.',loadCentralError:'Ma setgħetx titgħabba l-amministrazzjoni ċentrali.',loadInstitutionError:'Ma setgħetx titgħabba l-amministrazzjoni tal-istituzzjoni.',requestError:'It-talba tal-amministrazzjoni ċentrali falliet.'},
  nl:{title:'Centrale administratie',description:'Beheer instellingen, instellingsbeheerders en begrensde Admin API-referenties. Centrale toegang geeft geen toegang tot manuscripten.',refresh:'Vernieuwen',addInstitution:'Instelling toevoegen',institutionName:'Naam van de instelling',ror:'ROR-id',create:'Aanmaken',active:'Actief',disabled:'Uitgeschakeld',manage:'Beheren',members:'leden',apiKeys:'API-referenties',admins:'Instellingsbeheerders',addAdmin:'Beheerder toevoegen',email:'E-mail van Studio-account',adminRole:'Rol',remove:'Beheerdersrol verwijderen',apiTitle:'Institution Admin API',apiDescription:'Tokens zijn aan een instelling gebonden, beperkt in reikwijdte en worden bij aanmaak slechts één keer getoond.',label:'Naam van referentie',expires:'Verloopt over dagen',createToken:'API-token aanmaken',revoke:'Intrekken',tokenOnce:'Kopieer dit token nu. Het wordt niet opnieuw getoond.',audit:'Recente auditgebeurtenissen',none:'Nog geen records.',loadCentralError:'Centrale administratie kon niet worden geladen.',loadInstitutionError:'Instellingsadministratie kon niet worden geladen.',requestError:'Verzoek aan centrale administratie is mislukt.'},
  pl:{title:'Administracja centralna',description:'Zarządzaj instytucjami, administratorami instytucjonalnymi i poświadczeniami Admin API o ograniczonym zakresie. Dostęp centralny nie daje dostępu do manuskryptów.',refresh:'Odśwież',addInstitution:'Dodaj instytucję',institutionName:'Nazwa instytucji',ror:'Identyfikator ROR',create:'Utwórz',active:'Aktywna',disabled:'Wyłączona',manage:'Zarządzaj',members:'członków',apiKeys:'Poświadczenia API',admins:'Administratorzy instytucjonalni',addAdmin:'Dodaj administratora',email:'E-mail konta Studio',adminRole:'Rola',remove:'Usuń rolę administratora',apiTitle:'Institution Admin API',apiDescription:'Tokeny są przypisane do instytucji, ograniczone zakresem i wyświetlane tylko raz przy tworzeniu.',label:'Nazwa poświadczenia',expires:'Wygasa za dni',createToken:'Utwórz token API',revoke:'Unieważnij',tokenOnce:'Skopiuj ten token teraz. Nie zostanie pokazany ponownie.',audit:'Ostatnie zdarzenia audytu',none:'Brak rekordów.',loadCentralError:'Nie udało się załadować administracji centralnej.',loadInstitutionError:'Nie udało się załadować administracji instytucji.',requestError:'Żądanie administracji centralnej nie powiodło się.'},
  pt:{title:'Administração central',description:'Gira instituições, administradores institucionais e credenciais do Admin API com âmbito limitado. O acesso central não concede acesso a manuscritos.',refresh:'Atualizar',addInstitution:'Adicionar instituição',institutionName:'Nome da instituição',ror:'Identificador ROR',create:'Criar',active:'Ativa',disabled:'Desativada',manage:'Gerir',members:'membros',apiKeys:'Credenciais API',admins:'Administradores institucionais',addAdmin:'Adicionar administrador',email:'E-mail da conta Studio',adminRole:'Função',remove:'Remover função de administrador',apiTitle:'Institution Admin API',apiDescription:'Os tokens estão ligados à instituição, limitados por âmbito e são mostrados apenas uma vez quando criados.',label:'Rótulo da credencial',expires:'Expira em dias',createToken:'Criar token API',revoke:'Revogar',tokenOnce:'Copie este token agora. Não será mostrado novamente.',audit:'Eventos de auditoria recentes',none:'Ainda não existem registos.',loadCentralError:'Não foi possível carregar a administração central.',loadInstitutionError:'Não foi possível carregar a administração da instituição.',requestError:'O pedido de administração central falhou.'},
  ro:{title:'Administrare centrală',description:'Gestionați instituțiile, administratorii instituționali și acreditările Admin API cu domeniu limitat. Accesul central nu oferă acces la manuscrise.',refresh:'Reîmprospătează',addInstitution:'Adaugă instituție',institutionName:'Numele instituției',ror:'Identificator ROR',create:'Creează',active:'Activă',disabled:'Dezactivată',manage:'Gestionează',members:'membri',apiKeys:'Acreditări API',admins:'Administratori instituționali',addAdmin:'Adaugă administrator',email:'E-mail cont Studio',adminRole:'Rol',remove:'Elimină rolul de administrator',apiTitle:'Institution Admin API',apiDescription:'Tokenurile sunt legate de instituție, limitate ca domeniu și sunt afișate o singură dată la creare.',label:'Etichetă acreditare',expires:'Expiră în zile',createToken:'Creează token API',revoke:'Revocă',tokenOnce:'Copiați acest token acum. Nu va mai fi afișat.',audit:'Evenimente recente de audit',none:'Nu există încă înregistrări.',loadCentralError:'Administrarea centrală nu a putut fi încărcată.',loadInstitutionError:'Administrarea instituției nu a putut fi încărcată.',requestError:'Cererea de administrare centrală a eșuat.'},
  sk:{title:'Centrálna správa',description:'Spravujte inštitúcie, inštitucionálnych administrátorov a poverenia Admin API s obmedzeným rozsahom. Centrálny prístup neposkytuje prístup k rukopisom.',refresh:'Obnoviť',addInstitution:'Pridať inštitúciu',institutionName:'Názov inštitúcie',ror:'Identifikátor ROR',create:'Vytvoriť',active:'Aktívna',disabled:'Zakázaná',manage:'Spravovať',members:'členov',apiKeys:'Poverenia API',admins:'Inštitucionálni administrátori',addAdmin:'Pridať administrátora',email:'E-mail účtu Studio',adminRole:'Rola',remove:'Odobrať rolu administrátora',apiTitle:'Institution Admin API',apiDescription:'Tokeny sú viazané na inštitúciu, majú obmedzený rozsah a pri vytvorení sa zobrazia iba raz.',label:'Názov poverenia',expires:'Platnosť v dňoch',createToken:'Vytvoriť API token',revoke:'Odvolať',tokenOnce:'Skopírujte token teraz. Znovu sa už nezobrazí.',audit:'Nedávne udalosti auditu',none:'Zatiaľ žiadne záznamy.',loadCentralError:'Centrálnu správu sa nepodarilo načítať.',loadInstitutionError:'Správu inštitúcie sa nepodarilo načítať.',requestError:'Požiadavka centrálnej správy zlyhala.'},
  sl:{title:'Centralno upravljanje',description:'Upravljajte institucije, institucionalne skrbnike in poverilnice Admin API z omejenim obsegom. Centralni dostop ne omogoča dostopa do rokopisov.',refresh:'Osveži',addInstitution:'Dodaj institucijo',institutionName:'Ime institucije',ror:'Identifikator ROR',create:'Ustvari',active:'Aktivna',disabled:'Onemogočena',manage:'Upravljaj',members:'članov',apiKeys:'Poverilnice API',admins:'Institucionalni skrbniki',addAdmin:'Dodaj skrbnika',email:'E-pošta računa Studio',adminRole:'Vloga',remove:'Odstrani skrbniško vlogo',apiTitle:'Institution Admin API',apiDescription:'Žetoni so vezani na institucijo, omejeni po obsegu in ob ustvarjanju prikazani samo enkrat.',label:'Oznaka poverilnice',expires:'Poteče čez dni',createToken:'Ustvari žeton API',revoke:'Prekliči',tokenOnce:'Kopirajte ta žeton zdaj. Ponovno ne bo prikazan.',audit:'Nedavni dogodki revizije',none:'Za zdaj ni zapisov.',loadCentralError:'Centralnega upravljanja ni bilo mogoče naložiti.',loadInstitutionError:'Upravljanja institucije ni bilo mogoče naložiti.',requestError:'Zahteva centralnega upravljanja ni uspela.'},
  sv:{title:'Central administration',description:'Hantera institutioner, institutionsadministratörer och avgränsade Admin API-referenser. Central åtkomst ger inte åtkomst till manuskript.',refresh:'Uppdatera',addInstitution:'Lägg till institution',institutionName:'Institutionsnamn',ror:'ROR-id',create:'Skapa',active:'Aktiv',disabled:'Inaktiverad',manage:'Hantera',members:'medlemmar',apiKeys:'API-referenser',admins:'Institutionsadministratörer',addAdmin:'Lägg till administratör',email:'E-post för Studio-konto',adminRole:'Roll',remove:'Ta bort administratörsroll',apiTitle:'Institution Admin API',apiDescription:'Token är bundna till en institution, avgränsade efter behörighet och visas bara en gång när de skapas.',label:'Namn på referens',expires:'Giltighet i dagar',createToken:'Skapa API-token',revoke:'Återkalla',tokenOnce:'Kopiera detta token nu. Det visas inte igen.',audit:'Senaste granskningshändelser',none:'Inga poster ännu.',loadCentralError:'Central administration kunde inte läsas in.',loadInstitutionError:'Institutionsadministration kunde inte läsas in.',requestError:'Begäran till central administration misslyckades.'},
};

export function getCentralAdministrationCopy(locale: string): CentralAdministrationCopy {
  return centralAdministrationTranslations[locale] ?? centralAdministrationTranslations.en;
}
