export interface CloudOAuthCopy {
  oauthTitle: string;
  oauthDescription: string;
  serverConfigured: string;
  serverNotConfigured: string;
  redirectUri: string;
  scopes: string;
  serverVariables: string;
  adminSetupTitle: string;
  adminSetupText: string;
  connectWith: string;
  connecting: string;
  connected: string;
  authorizationFailed: string;
  accessDenied: string;
  exchangeFailed: string;
  oauthMethod: string;
  protonMethod: string;
  protonAuth: string;
  protonPreviewTitle: string;
  protonPreviewText: string;
  protonSystemStorageText: string;
  protonSdkStatus: string;
}

const en: CloudOAuthCopy = {
  oauthTitle: 'OAuth 2.0 cloud connection',
  oauthDescription: 'Authorize Studio without entering your cloud password. Access and refresh tokens are encrypted on the Studio server and belong to your signed-in profile.',
  serverConfigured: 'Server configuration ready',
  serverNotConfigured: 'Server configuration required',
  redirectUri: 'Registered callback URI',
  scopes: 'Requested permissions',
  serverVariables: 'Required server variables',
  adminSetupTitle: 'Administrator setup',
  adminSetupText: 'Create an OAuth application at the provider, register the callback URI exactly, enable the listed permissions, then place the client ID and secret in the Studio server environment and restart the API.',
  connectWith: 'Connect with {provider}',
  connecting: 'Opening authorization…',
  connected: '{provider} connected successfully.',
  authorizationFailed: 'Cloud authorization failed. Try again or review the provider configuration.',
  accessDenied: 'Authorization was cancelled or denied by the cloud account.',
  exchangeFailed: 'The authorization code could not be exchanged for a cloud session.',
  oauthMethod: 'Direct OAuth 2.0 connection',
  protonMethod: 'Proton Drive SDK integration',
  protonAuth: 'Proton Drive uses its own authenticated, end-to-end encrypted SDK/session model rather than the generic OAuth 2.0 storage flow used by Google, Microsoft and Dropbox.',
  protonPreviewTitle: 'Proton Drive',
  protonPreviewText: 'Proton Drive is listed now, but direct third-party production integration remains disabled until Proton declares its Drive SDK and authentication flow ready for production third-party applications.',
  protonSystemStorageText: 'You can already use Proton Drive through system storage wherever the Proton desktop/mobile app exposes it to the operating-system file picker.',
  protonSdkStatus: 'Direct SDK connection: preview / not yet enabled',
};

const translations: Record<string, CloudOAuthCopy> = {
  en,
  hu: {
    oauthTitle:'OAuth 2.0 felhőkapcsolat',oauthDescription:'Engedélyezze a Studio hozzáférését a felhőjelszó megadása nélkül. A hozzáférési és frissítési tokeneket a Studio szervere titkosítva tárolja, és azok a bejelentkezett profilhoz tartoznak.',serverConfigured:'A szerverbeállítás kész',serverNotConfigured:'Szerverbeállítás szükséges',redirectUri:'Regisztrált visszahívási URI',scopes:'Kért jogosultságok',serverVariables:'Szükséges szerverváltozók',adminSetupTitle:'Adminisztrátori beállítás',adminSetupText:'Hozzon létre OAuth-alkalmazást a szolgáltatónál, pontosan regisztrálja a visszahívási URI-t, engedélyezze a felsorolt jogosultságokat, majd állítsa be a kliensazonosítót és titkot a Studio szerverkörnyezetében, és indítsa újra az API-t.',connectWith:'Kapcsolódás: {provider}',connecting:'Engedélyezés megnyitása…',connected:'A(z) {provider} sikeresen kapcsolódott.',authorizationFailed:'A felhőengedélyezés sikertelen. Próbálja újra, vagy ellenőrizze a szolgáltató beállításait.',accessDenied:'Az engedélyezést megszakították vagy a felhőfiók megtagadta.',exchangeFailed:'Az engedélyezési kódot nem sikerült felhőmunkamenetre cserélni.',oauthMethod:'Közvetlen OAuth 2.0 kapcsolat',protonMethod:'Proton Drive SDK-integráció',protonAuth:'A Proton Drive saját hitelesített, végpontok között titkosított SDK-/munkamenetmodellt használ a Google, Microsoft és Dropbox által használt általános OAuth 2.0 tárhelyfolyam helyett.',protonPreviewTitle:'Proton Drive',protonPreviewText:'A Proton Drive már szerepel a listában, de a közvetlen harmadik féltől származó éles integráció addig letiltva marad, amíg a Proton a Drive SDK-t és a hitelesítési folyamatot éles harmadik fél alkalmazások számára támogatottnak nem nyilvánítja.',protonSystemStorageText:'A Proton Drive már most használható a rendszertárhelyen keresztül, ahol a Proton asztali vagy mobilalkalmazása megjeleníti azt az operációs rendszer fájlválasztójában.',protonSdkStatus:'Közvetlen SDK-kapcsolat: előnézet / még nincs bekapcsolva',
  },
  de: {
    oauthTitle:'OAuth-2.0-Cloud-Verbindung',oauthDescription:'Autorisieren Sie Studio, ohne Ihr Cloud-Passwort einzugeben. Zugriffs- und Aktualisierungstoken werden verschlüsselt auf dem Studio-Server gespeichert und gehören zu Ihrem angemeldeten Profil.',serverConfigured:'Serverkonfiguration bereit',serverNotConfigured:'Serverkonfiguration erforderlich',redirectUri:'Registrierte Callback-URI',scopes:'Angeforderte Berechtigungen',serverVariables:'Erforderliche Servervariablen',adminSetupTitle:'Einrichtung durch Administrator',adminSetupText:'Erstellen Sie beim Anbieter eine OAuth-Anwendung, registrieren Sie die Callback-URI exakt, aktivieren Sie die aufgeführten Berechtigungen, hinterlegen Sie Client-ID und Secret in der Studio-Serverumgebung und starten Sie die API neu.',connectWith:'Mit {provider} verbinden',connecting:'Autorisierung wird geöffnet…',connected:'{provider} wurde erfolgreich verbunden.',authorizationFailed:'Cloud-Autorisierung fehlgeschlagen. Versuchen Sie es erneut oder prüfen Sie die Anbieterkonfiguration.',accessDenied:'Die Autorisierung wurde abgebrochen oder vom Cloud-Konto verweigert.',exchangeFailed:'Der Autorisierungscode konnte nicht gegen eine Cloud-Sitzung ausgetauscht werden.',oauthMethod:'Direkte OAuth-2.0-Verbindung',protonMethod:'Proton-Drive-SDK-Integration',protonAuth:'Proton Drive verwendet ein eigenes authentifiziertes, Ende-zu-Ende-verschlüsseltes SDK-/Sitzungsmodell statt des allgemeinen OAuth-2.0-Speicherablaufs von Google, Microsoft und Dropbox.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive ist bereits aufgeführt, die direkte produktive Drittanbieterintegration bleibt jedoch deaktiviert, bis Proton das Drive SDK und den Authentifizierungsablauf offiziell für produktive Drittanbieteranwendungen freigibt.',protonSystemStorageText:'Proton Drive kann bereits über den Systemspeicher verwendet werden, wenn die Proton-Desktop- oder Mobil-App ihn im Dateiauswahldialog des Betriebssystems bereitstellt.',protonSdkStatus:'Direkte SDK-Verbindung: Vorschau / noch nicht aktiviert',
  },
  bg: {
    oauthTitle:'OAuth 2.0 връзка с облак',oauthDescription:'Упълномощете Studio без да въвеждате паролата си за облака. Токените за достъп и обновяване се съхраняват криптирано на сървъра на Studio и принадлежат на влезлия профил.',serverConfigured:'Сървърната конфигурация е готова',serverNotConfigured:'Необходима е сървърна конфигурация',redirectUri:'Регистриран URI за обратно извикване',scopes:'Заявени разрешения',serverVariables:'Необходими сървърни променливи',adminSetupTitle:'Настройка от администратор',adminSetupText:'Създайте OAuth приложение при доставчика, регистрирайте точно URI за обратно извикване, разрешете посочените права, задайте client ID и secret в средата на Studio сървъра и рестартирайте API.',connectWith:'Свързване с {provider}',connecting:'Отваряне на упълномощаването…',connected:'{provider} е свързан успешно.',authorizationFailed:'Упълномощаването за облака не бе успешно. Опитайте отново или проверете настройките на доставчика.',accessDenied:'Упълномощаването бе отменено или отказано от облачния акаунт.',exchangeFailed:'Кодът за упълномощаване не можа да бъде обменен за облачна сесия.',oauthMethod:'Директна OAuth 2.0 връзка',protonMethod:'Интеграция с Proton Drive SDK',protonAuth:'Proton Drive използва собствен удостоверен и криптиран от край до край SDK/сесиен модел вместо общия OAuth 2.0 поток за съхранение.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive вече е в списъка, но директната продукционна интеграция от трета страна остава изключена, докато Proton не обяви Drive SDK и удостоверяването за готови за продукционни приложения на трети страни.',protonSystemStorageText:'Proton Drive вече може да се използва чрез системното хранилище, когато приложението Proton го предоставя във файловия диалог на операционната система.',protonSdkStatus:'Директна SDK връзка: преглед / все още не е активирана',
  },
  cs: {
    oauthTitle:'Cloudové připojení OAuth 2.0',oauthDescription:'Autorizujte Studio bez zadávání hesla ke cloudu. Přístupové a obnovovací tokeny jsou šifrovány na serveru Studio a patří přihlášenému profilu.',serverConfigured:'Konfigurace serveru je připravena',serverNotConfigured:'Je vyžadována konfigurace serveru',redirectUri:'Registrovaná URI zpětného volání',scopes:'Požadovaná oprávnění',serverVariables:'Požadované proměnné serveru',adminSetupTitle:'Nastavení správcem',adminSetupText:'Vytvořte u poskytovatele aplikaci OAuth, přesně zaregistrujte URI zpětného volání, povolte uvedená oprávnění, nastavte ID klienta a tajný klíč v prostředí serveru Studio a restartujte API.',connectWith:'Připojit přes {provider}',connecting:'Otevírání autorizace…',connected:'{provider} byl úspěšně připojen.',authorizationFailed:'Autorizace cloudu selhala. Zkuste to znovu nebo zkontrolujte konfiguraci poskytovatele.',accessDenied:'Autorizace byla zrušena nebo cloudovým účtem odmítnuta.',exchangeFailed:'Autorizační kód se nepodařilo vyměnit za cloudovou relaci.',oauthMethod:'Přímé připojení OAuth 2.0',protonMethod:'Integrace Proton Drive SDK',protonAuth:'Proton Drive používá vlastní autentizovaný a end-to-end šifrovaný model SDK/relace namísto obecného úložného toku OAuth 2.0.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive je již uveden, ale přímá produkční integrace třetích stran zůstává vypnutá, dokud Proton neoznačí Drive SDK a autentizaci za připravené pro produkční aplikace třetích stran.',protonSystemStorageText:'Proton Drive lze již používat prostřednictvím systémového úložiště, pokud jej aplikace Proton zpřístupní v systémovém dialogu souborů.',protonSdkStatus:'Přímé připojení SDK: náhled / zatím není aktivní',
  },
  da: {
    oauthTitle:'OAuth 2.0-skyforbindelse',oauthDescription:'Godkend Studio uden at indtaste din cloud-adgangskode. Adgangs- og opdateringstokens gemmes krypteret på Studio-serveren og tilhører den indloggede profil.',serverConfigured:'Serverkonfiguration klar',serverNotConfigured:'Serverkonfiguration kræves',redirectUri:'Registreret callback-URI',scopes:'Anmodede tilladelser',serverVariables:'Påkrævede servervariabler',adminSetupTitle:'Administratoropsætning',adminSetupText:'Opret en OAuth-app hos udbyderen, registrer callback-URI'en nøjagtigt, aktivér de viste tilladelser, læg klient-ID og hemmelighed i Studio-serverens miljø og genstart API'et.',connectWith:'Forbind med {provider}',connecting:'Åbner godkendelse…',connected:'{provider} er forbundet.',authorizationFailed:'Cloud-godkendelsen mislykkedes. Prøv igen eller kontrollér udbyderens konfiguration.',accessDenied:'Godkendelsen blev annulleret eller afvist af cloud-kontoen.',exchangeFailed:'Godkendelseskoden kunne ikke ombyttes til en cloud-session.',oauthMethod:'Direkte OAuth 2.0-forbindelse',protonMethod:'Proton Drive SDK-integration',protonAuth:'Proton Drive bruger sin egen godkendte, ende-til-ende-krypterede SDK-/sessionsmodel i stedet for det generelle OAuth 2.0-lagerflow.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive er nu på listen, men direkte produktionsintegration fra tredjepart forbliver deaktiveret, indtil Proton erklærer Drive SDK og loginflowet klar til produktionsapps fra tredjepart.',protonSystemStorageText:'Proton Drive kan allerede bruges via systemlager, hvor Proton-appen gør det synligt i operativsystemets filvælger.',protonSdkStatus:'Direkte SDK-forbindelse: forhåndsvisning / endnu ikke aktiveret',
  },
  el: {
    oauthTitle:'Σύνδεση cloud OAuth 2.0',oauthDescription:'Εξουσιοδοτήστε το Studio χωρίς να εισαγάγετε τον κωδικό του cloud. Τα token πρόσβασης και ανανέωσης αποθηκεύονται κρυπτογραφημένα στον διακομιστή Studio και ανήκουν στο συνδεδεμένο προφίλ.',serverConfigured:'Η ρύθμιση διακομιστή είναι έτοιμη',serverNotConfigured:'Απαιτείται ρύθμιση διακομιστή',redirectUri:'Καταχωρισμένο URI επιστροφής',scopes:'Απαιτούμενα δικαιώματα',serverVariables:'Απαιτούμενες μεταβλητές διακομιστή',adminSetupTitle:'Ρύθμιση διαχειριστή',adminSetupText:'Δημιουργήστε εφαρμογή OAuth στον πάροχο, καταχωρίστε ακριβώς το URI επιστροφής, ενεργοποιήστε τα αναφερόμενα δικαιώματα, ορίστε client ID και secret στο περιβάλλον του διακομιστή Studio και επανεκκινήστε το API.',connectWith:'Σύνδεση με {provider}',connecting:'Άνοιγμα εξουσιοδότησης…',connected:'Το {provider} συνδέθηκε επιτυχώς.',authorizationFailed:'Η εξουσιοδότηση cloud απέτυχε. Δοκιμάστε ξανά ή ελέγξτε τη ρύθμιση του παρόχου.',accessDenied:'Η εξουσιοδότηση ακυρώθηκε ή απορρίφθηκε από τον λογαριασμό cloud.',exchangeFailed:'Δεν ήταν δυνατή η ανταλλαγή του κωδικού εξουσιοδότησης με συνεδρία cloud.',oauthMethod:'Άμεση σύνδεση OAuth 2.0',protonMethod:'Ενσωμάτωση Proton Drive SDK',protonAuth:'Το Proton Drive χρησιμοποιεί δικό του πιστοποιημένο και end-to-end κρυπτογραφημένο μοντέλο SDK/συνεδρίας αντί για τη γενική ροή αποθήκευσης OAuth 2.0.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Το Proton Drive εμφανίζεται πλέον στη λίστα, αλλά η άμεση παραγωγική ενσωμάτωση τρίτων παραμένει απενεργοποιημένη έως ότου η Proton χαρακτηρίσει το Drive SDK και τη ροή ελέγχου ταυτότητας έτοιμα για εφαρμογές τρίτων σε παραγωγή.',protonSystemStorageText:'Μπορείτε ήδη να χρησιμοποιείτε το Proton Drive μέσω του συστήματος αρχείων όπου η εφαρμογή Proton το εμφανίζει στον επιλογέα αρχείων του λειτουργικού.',protonSdkStatus:'Άμεση σύνδεση SDK: προεπισκόπηση / δεν έχει ενεργοποιηθεί ακόμη',
  },
  es: {
    oauthTitle:'Conexión en la nube OAuth 2.0',oauthDescription:'Autorice Studio sin introducir su contraseña de la nube. Los tokens de acceso y actualización se almacenan cifrados en el servidor de Studio y pertenecen al perfil conectado.',serverConfigured:'Configuración del servidor lista',serverNotConfigured:'Se requiere configuración del servidor',redirectUri:'URI de retorno registrada',scopes:'Permisos solicitados',serverVariables:'Variables de servidor necesarias',adminSetupTitle:'Configuración del administrador',adminSetupText:'Cree una aplicación OAuth en el proveedor, registre exactamente la URI de retorno, habilite los permisos indicados, configure el ID y el secreto del cliente en el entorno del servidor Studio y reinicie la API.',connectWith:'Conectar con {provider}',connecting:'Abriendo autorización…',connected:'{provider} se ha conectado correctamente.',authorizationFailed:'La autorización de la nube ha fallado. Inténtelo de nuevo o revise la configuración del proveedor.',accessDenied:'La autorización fue cancelada o rechazada por la cuenta de la nube.',exchangeFailed:'No se pudo intercambiar el código de autorización por una sesión de nube.',oauthMethod:'Conexión OAuth 2.0 directa',protonMethod:'Integración con Proton Drive SDK',protonAuth:'Proton Drive utiliza su propio modelo autenticado y cifrado de extremo a extremo de SDK/sesión en lugar del flujo genérico de almacenamiento OAuth 2.0.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive ya aparece en la lista, pero la integración directa de producción de terceros seguirá deshabilitada hasta que Proton declare que Drive SDK y su autenticación están listos para aplicaciones de terceros en producción.',protonSystemStorageText:'Ya puede usar Proton Drive mediante el almacenamiento del sistema cuando la aplicación de Proton lo exponga en el selector de archivos del sistema operativo.',protonSdkStatus:'Conexión SDK directa: vista previa / aún no activada',
  },
  et: {
    oauthTitle:'OAuth 2.0 pilveühendus',oauthDescription:'Volitage Studio ilma pilveparooli sisestamata. Juurdepääsu- ja värskendustokenid salvestatakse Studio serveris krüpteeritult ning kuuluvad sisselogitud profiilile.',serverConfigured:'Serveri seadistus on valmis',serverNotConfigured:'Serveri seadistus on vajalik',redirectUri:'Registreeritud tagasisuunamise URI',scopes:'Taotletud õigused',serverVariables:'Nõutavad serverimuutujad',adminSetupTitle:'Administraatori seadistus',adminSetupText:'Looge teenusepakkuja juures OAuth-rakendus, registreerige täpselt tagasisuunamise URI, lubage loetletud õigused, määrake Studio serverikeskkonnas kliendi ID ja saladus ning taaskäivitage API.',connectWith:'Ühenda teenusega {provider}',connecting:'Autoriseerimise avamine…',connected:'{provider} on edukalt ühendatud.',authorizationFailed:'Pilve autoriseerimine ebaõnnestus. Proovige uuesti või kontrollige teenusepakkuja seadistust.',accessDenied:'Pilvekonto katkestas või keeldus autoriseerimisest.',exchangeFailed:'Autoriseerimiskoodi ei õnnestunud pilveseansiks vahetada.',oauthMethod:'Otsene OAuth 2.0 ühendus',protonMethod:'Proton Drive SDK integratsioon',protonAuth:'Proton Drive kasutab üldise OAuth 2.0 salvestusvoo asemel oma autentitud ja läbivalt krüpteeritud SDK/seansi mudelit.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive on nüüd loendis, kuid otsene kolmanda osapoole tootmiskasutuse integratsioon jääb välja lülitatuks, kuni Proton kuulutab Drive SDK ja autentimise tootmiskõlblikuks.',protonSystemStorageText:'Proton Drive’i saab juba kasutada süsteemse salvestuse kaudu, kui Protoni rakendus muudab selle operatsioonisüsteemi failivalijas nähtavaks.',protonSdkStatus:'Otsene SDK-ühendus: eelvaade / pole veel lubatud',
  },
  fi: {
    oauthTitle:'OAuth 2.0 -pilviyhteys',oauthDescription:'Valtuuta Studio syöttämättä pilvipalvelun salasanaa. Käyttö- ja päivitystunnukset tallennetaan salattuina Studio-palvelimelle ja ne kuuluvat kirjautuneeseen profiiliin.',serverConfigured:'Palvelimen määritys valmis',serverNotConfigured:'Palvelimen määritys vaaditaan',redirectUri:'Rekisteröity paluu-URI',scopes:'Pyydetyt oikeudet',serverVariables:'Vaaditut palvelinmuuttujat',adminSetupTitle:'Ylläpitäjän määritys',adminSetupText:'Luo OAuth-sovellus palveluntarjoajalla, rekisteröi paluu-URI täsmälleen, ota luetellut oikeudet käyttöön, aseta asiakastunnus ja salaisuus Studio-palvelimen ympäristöön ja käynnistä API uudelleen.',connectWith:'Yhdistä palveluun {provider}',connecting:'Avataan valtuutusta…',connected:'{provider} yhdistettiin onnistuneesti.',authorizationFailed:'Pilvivaltuutus epäonnistui. Yritä uudelleen tai tarkista palveluntarjoajan määritys.',accessDenied:'Pilvitili perui tai hylkäsi valtuutuksen.',exchangeFailed:'Valtuutuskoodia ei voitu vaihtaa pilvi-istuntoon.',oauthMethod:'Suora OAuth 2.0 -yhteys',protonMethod:'Proton Drive SDK -integraatio',protonAuth:'Proton Drive käyttää omaa todennettua ja päästä päähän salattua SDK-/istuntomallia yleisen OAuth 2.0 -tallennusvirran sijaan.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive näkyy nyt luettelossa, mutta suora kolmannen osapuolen tuotantointegraatio pysyy poissa käytöstä, kunnes Proton ilmoittaa Drive SDK:n ja todennusvirran valmiiksi tuotantokäyttöön.',protonSystemStorageText:'Proton Drivea voi jo käyttää järjestelmätallennuksen kautta siellä, missä Proton-sovellus tuo sen käyttöjärjestelmän tiedostovalitsimeen.',protonSdkStatus:'Suora SDK-yhteys: esikatselu / ei vielä käytössä',
  },
  fr: {
    oauthTitle:'Connexion cloud OAuth 2.0',oauthDescription:'Autorisez Studio sans saisir votre mot de passe cloud. Les jetons d’accès et d’actualisation sont chiffrés sur le serveur Studio et appartiennent au profil connecté.',serverConfigured:'Configuration serveur prête',serverNotConfigured:'Configuration serveur requise',redirectUri:'URI de rappel enregistrée',scopes:'Autorisations demandées',serverVariables:'Variables serveur requises',adminSetupTitle:'Configuration administrateur',adminSetupText:'Créez une application OAuth chez le fournisseur, enregistrez exactement l’URI de rappel, activez les autorisations indiquées, définissez l’identifiant client et le secret dans l’environnement du serveur Studio puis redémarrez l’API.',connectWith:'Se connecter avec {provider}',connecting:'Ouverture de l’autorisation…',connected:'{provider} a été connecté avec succès.',authorizationFailed:'L’autorisation cloud a échoué. Réessayez ou vérifiez la configuration du fournisseur.',accessDenied:'L’autorisation a été annulée ou refusée par le compte cloud.',exchangeFailed:'Le code d’autorisation n’a pas pu être échangé contre une session cloud.',oauthMethod:'Connexion OAuth 2.0 directe',protonMethod:'Intégration Proton Drive SDK',protonAuth:'Proton Drive utilise son propre modèle SDK/session authentifié et chiffré de bout en bout au lieu du flux de stockage OAuth 2.0 générique.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive figure désormais dans la liste, mais l’intégration directe de production par des tiers reste désactivée jusqu’à ce que Proton déclare le Drive SDK et son authentification prêts pour les applications tierces en production.',protonSystemStorageText:'Proton Drive peut déjà être utilisé via le stockage système lorsque l’application Proton l’expose dans le sélecteur de fichiers du système.',protonSdkStatus:'Connexion SDK directe : aperçu / pas encore activée',
  },
  ga: {
    oauthTitle:'Nasc scamall OAuth 2.0',oauthDescription:'Údaraigh Studio gan do phasfhocal scamall a iontráil. Stóráiltear comharthaí rochtana agus athnuachana criptithe ar fhreastalaí Studio agus baineann siad leis an bpróifíl sínithe isteach.',serverConfigured:'Cumraíocht an fhreastalaí réidh',serverNotConfigured:'Cumraíocht an fhreastalaí de dhíth',redirectUri:'URI aisghlao cláraithe',scopes:'Ceadanna iarrtha',serverVariables:'Athróga freastalaí riachtanacha',adminSetupTitle:'Socrú riarthóra',adminSetupText:'Cruthaigh feidhmchlár OAuth leis an soláthraí, cláraigh an URI aisghlao go beacht, cumasaigh na ceadanna liostaithe, socraigh ID agus rún an chliaint i dtimpeallacht fhreastalaí Studio agus atosaigh an API.',connectWith:'Ceangail le {provider}',connecting:'Údarú á oscailt…',connected:'Ceanglaíodh {provider} go rathúil.',authorizationFailed:'Theip ar údarú an scamaill. Bain triail eile as nó seiceáil cumraíocht an tsoláthraí.',accessDenied:'Cuireadh an t-údarú ar ceal nó dhiúltaigh an cuntas scamall dó.',exchangeFailed:'Níorbh fhéidir an cód údaraithe a mhalartú ar sheisiún scamall.',oauthMethod:'Nasc díreach OAuth 2.0',protonMethod:'Comhtháthú Proton Drive SDK',protonAuth:'Úsáideann Proton Drive a mhúnla SDK/seisiúin fíordheimhnithe agus criptithe ó cheann go ceann féin seachas an sreabhadh stórála ginearálta OAuth 2.0.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Tá Proton Drive sa liosta anois, ach fanann comhtháthú díreach táirgthe tríú páirtí díchumasaithe go dtí go ndearbhaíonn Proton go bhfuil Drive SDK agus an sreabhadh fíordheimhnithe réidh d’fheidhmchláir tríú páirtí táirgthe.',protonSystemStorageText:'Is féidir Proton Drive a úsáid cheana trí stóras an chórais nuair a nochtann aip Proton é i roghnóir comhad an chórais oibriúcháin.',protonSdkStatus:'Nasc díreach SDK: réamhamharc / gan chumasú fós',
  },
  hr: {
    oauthTitle:'OAuth 2.0 veza s oblakom',oauthDescription:'Autorizirajte Studio bez unosa lozinke za oblak. Tokeni pristupa i osvježavanja čuvaju se šifrirano na Studio poslužitelju i pripadaju prijavljenom profilu.',serverConfigured:'Konfiguracija poslužitelja je spremna',serverNotConfigured:'Potrebna je konfiguracija poslužitelja',redirectUri:'Registrirani povratni URI',scopes:'Zatražene dozvole',serverVariables:'Potrebne varijable poslužitelja',adminSetupTitle:'Postavljanje administratora',adminSetupText:'Izradite OAuth aplikaciju kod pružatelja, točno registrirajte povratni URI, omogućite navedene dozvole, postavite client ID i secret u okruženju Studio poslužitelja i ponovno pokrenite API.',connectWith:'Poveži s {provider}',connecting:'Otvaranje autorizacije…',connected:'{provider} je uspješno povezan.',authorizationFailed:'Autorizacija oblaka nije uspjela. Pokušajte ponovno ili provjerite konfiguraciju pružatelja.',accessDenied:'Autorizacija je otkazana ili odbijena od računa u oblaku.',exchangeFailed:'Autorizacijski kod nije moguće zamijeniti za sesiju u oblaku.',oauthMethod:'Izravna OAuth 2.0 veza',protonMethod:'Integracija Proton Drive SDK-a',protonAuth:'Proton Drive koristi vlastiti autentificirani i end-to-end šifrirani SDK/sesijski model umjesto općeg OAuth 2.0 toka pohrane.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive je sada naveden, ali izravna produkcijska integracija treće strane ostaje onemogućena dok Proton ne proglasi Drive SDK i autentifikaciju spremnima za produkcijske aplikacije trećih strana.',protonSystemStorageText:'Proton Drive već se može koristiti putem sistemske pohrane kada ga Proton aplikacija izloži u biraču datoteka operacijskog sustava.',protonSdkStatus:'Izravna SDK veza: pregled / još nije omogućena',
  },
  it: {
    oauthTitle:'Connessione cloud OAuth 2.0',oauthDescription:'Autorizza Studio senza inserire la password del cloud. I token di accesso e aggiornamento vengono archiviati cifrati sul server Studio e appartengono al profilo connesso.',serverConfigured:'Configurazione server pronta',serverNotConfigured:'Configurazione server necessaria',redirectUri:'URI di callback registrato',scopes:'Autorizzazioni richieste',serverVariables:'Variabili server richieste',adminSetupTitle:'Configurazione amministratore',adminSetupText:'Crea un’app OAuth presso il provider, registra esattamente l’URI di callback, abilita le autorizzazioni indicate, imposta client ID e secret nell’ambiente del server Studio e riavvia l’API.',connectWith:'Connetti con {provider}',connecting:'Apertura autorizzazione…',connected:'{provider} connesso correttamente.',authorizationFailed:'Autorizzazione cloud non riuscita. Riprova o controlla la configurazione del provider.',accessDenied:'L’autorizzazione è stata annullata o rifiutata dall’account cloud.',exchangeFailed:'Impossibile scambiare il codice di autorizzazione con una sessione cloud.',oauthMethod:'Connessione OAuth 2.0 diretta',protonMethod:'Integrazione Proton Drive SDK',protonAuth:'Proton Drive usa un proprio modello SDK/sessione autenticato e con crittografia end-to-end invece del flusso di archiviazione OAuth 2.0 generico.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive è ora elencato, ma l’integrazione diretta di produzione per terze parti resta disabilitata finché Proton non dichiara Drive SDK e il flusso di autenticazione pronti per applicazioni di terze parti in produzione.',protonSystemStorageText:'Proton Drive può già essere usato tramite l’archiviazione di sistema quando l’app Proton lo espone nel selettore file del sistema operativo.',protonSdkStatus:'Connessione SDK diretta: anteprima / non ancora attiva',
  },
  lt: {
    oauthTitle:'OAuth 2.0 debesies ryšys',oauthDescription:'Suteikite Studio prieigą neįvesdami debesies slaptažodžio. Prieigos ir atnaujinimo žetonai Studio serveryje saugomi užšifruoti ir priklauso prisijungusiam profiliui.',serverConfigured:'Serverio konfigūracija paruošta',serverNotConfigured:'Reikia serverio konfigūracijos',redirectUri:'Užregistruotas grįžimo URI',scopes:'Prašomi leidimai',serverVariables:'Reikalingi serverio kintamieji',adminSetupTitle:'Administratoriaus sąranka',adminSetupText:'Pas teikėją sukurkite OAuth programą, tiksliai užregistruokite grįžimo URI, įjunkite nurodytus leidimus, Studio serverio aplinkoje nustatykite kliento ID ir slaptąjį raktą, tada iš naujo paleiskite API.',connectWith:'Prisijungti prie {provider}',connecting:'Atidaromas autorizavimas…',connected:'{provider} sėkmingai prijungtas.',authorizationFailed:'Debesies autorizavimas nepavyko. Bandykite dar kartą arba patikrinkite teikėjo konfigūraciją.',accessDenied:'Autorizavimas buvo atšauktas arba debesies paskyra jo nesuteikė.',exchangeFailed:'Autorizavimo kodo nepavyko pakeisti debesies seansu.',oauthMethod:'Tiesioginis OAuth 2.0 ryšys',protonMethod:'Proton Drive SDK integracija',protonAuth:'Proton Drive naudoja savo autentifikuotą ir ištisai šifruotą SDK / seanso modelį vietoje bendro OAuth 2.0 saugyklos srauto.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive jau įtrauktas į sąrašą, tačiau tiesioginė trečiųjų šalių produkcinė integracija liks išjungta, kol Proton paskelbs Drive SDK ir autentifikavimą tinkamais produkcinėms trečiųjų šalių programoms.',protonSystemStorageText:'Proton Drive jau galima naudoti per sistemos saugyklą, kai Proton programa jį pateikia operacinės sistemos failų pasirinkiklyje.',protonSdkStatus:'Tiesioginis SDK ryšys: peržiūra / dar neįjungta',
  },
  lv: {
    oauthTitle:'OAuth 2.0 mākoņa savienojums',oauthDescription:'Autorizējiet Studio, neievadot mākoņpakalpojuma paroli. Piekļuves un atsvaidzināšanas marķieri Studio serverī tiek glabāti šifrēti un pieder pierakstītajam profilam.',serverConfigured:'Servera konfigurācija ir gatava',serverNotConfigured:'Nepieciešama servera konfigurācija',redirectUri:'Reģistrētais atgriešanas URI',scopes:'Pieprasītās atļaujas',serverVariables:'Nepieciešamie servera mainīgie',adminSetupTitle:'Administratora iestatīšana',adminSetupText:'Izveidojiet OAuth lietotni pie pakalpojuma sniedzēja, precīzi reģistrējiet atgriešanas URI, iespējojiet norādītās atļaujas, Studio servera vidē iestatiet klienta ID un noslēpumu un restartējiet API.',connectWith:'Savienot ar {provider}',connecting:'Tiek atvērta autorizācija…',connected:'{provider} ir veiksmīgi savienots.',authorizationFailed:'Mākoņa autorizācija neizdevās. Mēģiniet vēlreiz vai pārbaudiet pakalpojuma sniedzēja konfigurāciju.',accessDenied:'Autorizācija tika atcelta vai mākoņa konts to noraidīja.',exchangeFailed:'Autorizācijas kodu neizdevās apmainīt pret mākoņa sesiju.',oauthMethod:'Tiešs OAuth 2.0 savienojums',protonMethod:'Proton Drive SDK integrācija',protonAuth:'Proton Drive izmanto savu autentificētu un pilnībā šifrētu SDK/sesijas modeli, nevis vispārīgo OAuth 2.0 krātuves plūsmu.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive tagad ir sarakstā, taču tieša trešās puses produkcijas integrācija paliek atspējota, līdz Proton paziņos, ka Drive SDK un autentifikācijas plūsma ir gatava trešo pušu produkcijas lietotnēm.',protonSystemStorageText:'Proton Drive jau var izmantot caur sistēmas krātuvi, ja Proton lietotne to parāda operētājsistēmas failu izvēlnē.',protonSdkStatus:'Tiešs SDK savienojums: priekšskatījums / vēl nav iespējots',
  },
  mt: {
    oauthTitle:'Konnessjoni tal-cloud OAuth 2.0',oauthDescription:'Awtorizza Studio mingħajr ma ddaħħal il-password tal-cloud. It-tokens tal-aċċess u tat-tiġdid jinħażnu kriptati fuq is-server ta’ Studio u jappartjenu għall-profil illoggjat.',serverConfigured:'Il-konfigurazzjoni tas-server lesta',serverNotConfigured:'Meħtieġa konfigurazzjoni tas-server',redirectUri:'URI ta’ callback irreġistrat',scopes:'Permessi mitluba',serverVariables:'Varjabbli tas-server meħtieġa',adminSetupTitle:'Setup tal-amministratur',adminSetupText:'Oħloq applikazzjoni OAuth għand il-fornitur, irreġistra eżattament il-URI ta’ callback, attiva l-permessi elenkati, issettja l-client ID u s-secret fl-ambjent tas-server Studio u erġa’ ibda l-API.',connectWith:'Qabbad ma’ {provider}',connecting:'Qed tinfetaħ l-awtorizzazzjoni…',connected:'{provider} ġie mqabbad b’suċċess.',authorizationFailed:'L-awtorizzazzjoni tal-cloud falliet. Erġa’ pprova jew iċċekkja l-konfigurazzjoni tal-fornitur.',accessDenied:'L-awtorizzazzjoni ġiet ikkanċellata jew miċħuda mill-kont tal-cloud.',exchangeFailed:'Il-kodiċi tal-awtorizzazzjoni ma setax jinbidel f’sessjoni tal-cloud.',oauthMethod:'Konnessjoni diretta OAuth 2.0',protonMethod:'Integrazzjoni Proton Drive SDK',protonAuth:'Proton Drive juża l-mudell awtentikat u kriptat minn tarf sa tarf tiegħu stess għall-SDK/sessjoni minflok il-fluss ġeneriku tal-ħażna OAuth 2.0.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive issa jidher fil-lista, iżda l-integrazzjoni diretta ta’ produzzjoni minn parti terza tibqa’ mitfija sakemm Proton jiddikjara Drive SDK u l-awtentikazzjoni lesti għal applikazzjonijiet ta’ produzzjoni ta’ partijiet terzi.',protonSystemStorageText:'Proton Drive diġà jista’ jintuża permezz tal-ħażna tas-sistema meta l-app Proton turih fil-file picker tas-sistema operattiva.',protonSdkStatus:'Konnessjoni diretta SDK: preview / għadha mhix attivata',
  },
  nl: {
    oauthTitle:'OAuth 2.0-cloudverbinding',oauthDescription:'Autoriseer Studio zonder uw cloudwachtwoord in te voeren. Toegangs- en vernieuwingstokens worden versleuteld op de Studio-server opgeslagen en horen bij het aangemelde profiel.',serverConfigured:'Serverconfiguratie gereed',serverNotConfigured:'Serverconfiguratie vereist',redirectUri:'Geregistreerde callback-URI',scopes:'Gevraagde machtigingen',serverVariables:'Vereiste servervariabelen',adminSetupTitle:'Beheerdersconfiguratie',adminSetupText:'Maak bij de provider een OAuth-app, registreer de callback-URI exact, schakel de genoemde machtigingen in, plaats client-ID en secret in de Studio-serveromgeving en start de API opnieuw.',connectWith:'Verbinden met {provider}',connecting:'Autorisatie openen…',connected:'{provider} is succesvol verbonden.',authorizationFailed:'Cloudautorisatie mislukt. Probeer opnieuw of controleer de providerconfiguratie.',accessDenied:'De autorisatie is geannuleerd of door het cloudaccount geweigerd.',exchangeFailed:'De autorisatiecode kon niet worden ingewisseld voor een cloudsessie.',oauthMethod:'Directe OAuth 2.0-verbinding',protonMethod:'Proton Drive SDK-integratie',protonAuth:'Proton Drive gebruikt een eigen geauthenticeerd en end-to-end versleuteld SDK-/sessiemodel in plaats van de algemene OAuth 2.0-opslagstroom.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive staat nu in de lijst, maar directe productie-integratie door derden blijft uitgeschakeld totdat Proton de Drive SDK en authenticatiestroom gereed verklaart voor productie-apps van derden.',protonSystemStorageText:'Proton Drive kan al via systeemopslag worden gebruikt wanneer de Proton-app het beschikbaar maakt in de bestandskiezer van het besturingssysteem.',protonSdkStatus:'Directe SDK-verbinding: preview / nog niet ingeschakeld',
  },
  pl: {
    oauthTitle:'Połączenie chmurowe OAuth 2.0',oauthDescription:'Autoryzuj Studio bez podawania hasła do chmury. Tokeny dostępu i odświeżania są przechowywane zaszyfrowane na serwerze Studio i należą do zalogowanego profilu.',serverConfigured:'Konfiguracja serwera gotowa',serverNotConfigured:'Wymagana konfiguracja serwera',redirectUri:'Zarejestrowany URI zwrotny',scopes:'Żądane uprawnienia',serverVariables:'Wymagane zmienne serwera',adminSetupTitle:'Konfiguracja administratora',adminSetupText:'Utwórz aplikację OAuth u dostawcy, dokładnie zarejestruj URI zwrotny, włącz wymienione uprawnienia, ustaw identyfikator klienta i sekret w środowisku serwera Studio i uruchom ponownie API.',connectWith:'Połącz z {provider}',connecting:'Otwieranie autoryzacji…',connected:'{provider} połączono pomyślnie.',authorizationFailed:'Autoryzacja chmury nie powiodła się. Spróbuj ponownie lub sprawdź konfigurację dostawcy.',accessDenied:'Autoryzacja została anulowana lub odrzucona przez konto chmurowe.',exchangeFailed:'Nie udało się wymienić kodu autoryzacyjnego na sesję chmurową.',oauthMethod:'Bezpośrednie połączenie OAuth 2.0',protonMethod:'Integracja Proton Drive SDK',protonAuth:'Proton Drive używa własnego uwierzytelnionego i szyfrowanego end-to-end modelu SDK/sesji zamiast ogólnego przepływu pamięci OAuth 2.0.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive jest już na liście, ale bezpośrednia integracja produkcyjna firm trzecich pozostaje wyłączona, dopóki Proton nie ogłosi Drive SDK i uwierzytelniania gotowych dla produkcyjnych aplikacji firm trzecich.',protonSystemStorageText:'Proton Drive można już używać przez pamięć systemową, jeśli aplikacja Proton udostępnia go w systemowym selektorze plików.',protonSdkStatus:'Bezpośrednie połączenie SDK: podgląd / jeszcze nieaktywne',
  },
  pt: {
    oauthTitle:'Ligação à nuvem OAuth 2.0',oauthDescription:'Autorize o Studio sem introduzir a palavra-passe da nuvem. Os tokens de acesso e atualização são guardados encriptados no servidor Studio e pertencem ao perfil com sessão iniciada.',serverConfigured:'Configuração do servidor pronta',serverNotConfigured:'É necessária configuração do servidor',redirectUri:'URI de retorno registado',scopes:'Permissões solicitadas',serverVariables:'Variáveis de servidor necessárias',adminSetupTitle:'Configuração do administrador',adminSetupText:'Crie uma aplicação OAuth no fornecedor, registe exatamente o URI de retorno, ative as permissões indicadas, defina o ID e segredo do cliente no ambiente do servidor Studio e reinicie a API.',connectWith:'Ligar a {provider}',connecting:'A abrir autorização…',connected:'{provider} ligado com sucesso.',authorizationFailed:'A autorização da nuvem falhou. Tente novamente ou reveja a configuração do fornecedor.',accessDenied:'A autorização foi cancelada ou recusada pela conta da nuvem.',exchangeFailed:'Não foi possível trocar o código de autorização por uma sessão na nuvem.',oauthMethod:'Ligação OAuth 2.0 direta',protonMethod:'Integração Proton Drive SDK',protonAuth:'O Proton Drive utiliza o seu próprio modelo SDK/sessão autenticado e encriptado ponto a ponto em vez do fluxo genérico de armazenamento OAuth 2.0.',protonPreviewTitle:'Proton Drive',protonPreviewText:'O Proton Drive já está listado, mas a integração direta de produção de terceiros permanece desativada até a Proton declarar o Drive SDK e a autenticação prontos para aplicações de terceiros em produção.',protonSystemStorageText:'O Proton Drive já pode ser usado através do armazenamento do sistema quando a aplicação Proton o disponibiliza no seletor de ficheiros do sistema operativo.',protonSdkStatus:'Ligação SDK direta: pré-visualização / ainda não ativada',
  },
  ro: {
    oauthTitle:'Conexiune cloud OAuth 2.0',oauthDescription:'Autorizați Studio fără să introduceți parola cloud. Tokenurile de acces și reîmprospătare sunt stocate criptat pe serverul Studio și aparțin profilului autentificat.',serverConfigured:'Configurația serverului este gata',serverNotConfigured:'Este necesară configurarea serverului',redirectUri:'URI de callback înregistrat',scopes:'Permisiuni solicitate',serverVariables:'Variabile de server necesare',adminSetupTitle:'Configurare administrator',adminSetupText:'Creați o aplicație OAuth la furnizor, înregistrați exact URI-ul de callback, activați permisiunile enumerate, setați ID-ul clientului și secretul în mediul serverului Studio și reporniți API-ul.',connectWith:'Conectare cu {provider}',connecting:'Se deschide autorizarea…',connected:'{provider} a fost conectat cu succes.',authorizationFailed:'Autorizarea cloud a eșuat. Încercați din nou sau verificați configurația furnizorului.',accessDenied:'Autorizarea a fost anulată sau refuzată de contul cloud.',exchangeFailed:'Codul de autorizare nu a putut fi schimbat pentru o sesiune cloud.',oauthMethod:'Conexiune OAuth 2.0 directă',protonMethod:'Integrare Proton Drive SDK',protonAuth:'Proton Drive folosește propriul model SDK/sesiune autentificat și criptat end-to-end în locul fluxului generic de stocare OAuth 2.0.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive este acum în listă, dar integrarea directă de producție pentru terți rămâne dezactivată până când Proton declară Drive SDK și autentificarea pregătite pentru aplicații terțe de producție.',protonSystemStorageText:'Proton Drive poate fi deja folosit prin stocarea sistemului atunci când aplicația Proton îl expune în selectorul de fișiere al sistemului de operare.',protonSdkStatus:'Conexiune SDK directă: previzualizare / încă neactivată',
  },
  sk: {
    oauthTitle:'Cloudové pripojenie OAuth 2.0',oauthDescription:'Autorizujte Studio bez zadania hesla ku cloudu. Prístupové a obnovovacie tokeny sa šifrovane ukladajú na serveri Studio a patria prihlásenému profilu.',serverConfigured:'Konfigurácia servera je pripravená',serverNotConfigured:'Vyžaduje sa konfigurácia servera',redirectUri:'Registrovaná URI spätného volania',scopes:'Požadované oprávnenia',serverVariables:'Požadované serverové premenné',adminSetupTitle:'Nastavenie správcom',adminSetupText:'Vytvorte u poskytovateľa OAuth aplikáciu, presne zaregistrujte URI spätného volania, povoľte uvedené oprávnenia, nastavte client ID a secret v prostredí servera Studio a reštartujte API.',connectWith:'Pripojiť cez {provider}',connecting:'Otvára sa autorizácia…',connected:'{provider} bol úspešne pripojený.',authorizationFailed:'Autorizácia cloudu zlyhala. Skúste to znova alebo skontrolujte konfiguráciu poskytovateľa.',accessDenied:'Autorizácia bola zrušená alebo odmietnutá cloudovým účtom.',exchangeFailed:'Autorizačný kód sa nepodarilo vymeniť za cloudovú reláciu.',oauthMethod:'Priame pripojenie OAuth 2.0',protonMethod:'Integrácia Proton Drive SDK',protonAuth:'Proton Drive používa vlastný autentizovaný a end-to-end šifrovaný model SDK/relácie namiesto všeobecného OAuth 2.0 úložného toku.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive je už v zozname, no priama produkčná integrácia tretej strany zostáva vypnutá, kým Proton neoznačí Drive SDK a autentizáciu za pripravené pre produkčné aplikácie tretích strán.',protonSystemStorageText:'Proton Drive sa už dá používať cez systémové úložisko, keď ho aplikácia Proton sprístupní v systémovom výbere súborov.',protonSdkStatus:'Priame SDK pripojenie: náhľad / zatiaľ nie je zapnuté',
  },
  sl: {
    oauthTitle:'Povezava z oblakom OAuth 2.0',oauthDescription:'Pooblastite Studio brez vnosa gesla za oblak. Žetoni za dostop in osveževanje so šifrirano shranjeni na strežniku Studio in pripadajo prijavljenemu profilu.',serverConfigured:'Nastavitev strežnika je pripravljena',serverNotConfigured:'Potrebna je nastavitev strežnika',redirectUri:'Registrirani URI povratnega klica',scopes:'Zahtevana dovoljenja',serverVariables:'Zahtevane strežniške spremenljivke',adminSetupTitle:'Nastavitev skrbnika',adminSetupText:'Pri ponudniku ustvarite aplikacijo OAuth, natančno registrirajte URI povratnega klica, omogočite navedena dovoljenja, nastavite ID odjemalca in skrivnost v okolju strežnika Studio ter znova zaženite API.',connectWith:'Poveži z {provider}',connecting:'Odpiranje pooblastitve…',connected:'{provider} je uspešno povezan.',authorizationFailed:'Pooblastitev oblaka ni uspela. Poskusite znova ali preverite nastavitev ponudnika.',accessDenied:'Pooblastitev je bila preklicana ali jo je račun v oblaku zavrnil.',exchangeFailed:'Kode za pooblastitev ni bilo mogoče zamenjati za sejo v oblaku.',oauthMethod:'Neposredna povezava OAuth 2.0',protonMethod:'Integracija Proton Drive SDK',protonAuth:'Proton Drive uporablja lasten avtenticiran in od konca do konca šifriran model SDK/seje namesto splošnega toka shrambe OAuth 2.0.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive je zdaj na seznamu, vendar neposredna produkcijska integracija tretjih oseb ostaja onemogočena, dokler Proton ne razglasi Drive SDK in avtentikacije za pripravljena na produkcijske aplikacije tretjih oseb.',protonSystemStorageText:'Proton Drive je že mogoče uporabljati prek sistemske shrambe, ko ga aplikacija Proton prikaže v izbirniku datotek operacijskega sistema.',protonSdkStatus:'Neposredna povezava SDK: predogled / še ni omogočena',
  },
  sv: {
    oauthTitle:'OAuth 2.0-molnanslutning',oauthDescription:'Auktorisera Studio utan att ange ditt molnlösenord. Åtkomst- och uppdateringstoken lagras krypterat på Studio-servern och tillhör den inloggade profilen.',serverConfigured:'Serverkonfigurationen är klar',serverNotConfigured:'Serverkonfiguration krävs',redirectUri:'Registrerad callback-URI',scopes:'Begärda behörigheter',serverVariables:'Nödvändiga servervariabler',adminSetupTitle:'Administratörsinställning',adminSetupText:'Skapa en OAuth-app hos leverantören, registrera callback-URI:n exakt, aktivera de angivna behörigheterna, lägg klient-ID och hemlighet i Studio-serverns miljö och starta om API:t.',connectWith:'Anslut med {provider}',connecting:'Öppnar auktorisering…',connected:'{provider} har anslutits.',authorizationFailed:'Molnauktoriseringen misslyckades. Försök igen eller kontrollera leverantörens konfiguration.',accessDenied:'Auktoriseringen avbröts eller nekades av molnkontot.',exchangeFailed:'Auktoriseringskoden kunde inte bytas mot en molnsession.',oauthMethod:'Direkt OAuth 2.0-anslutning',protonMethod:'Proton Drive SDK-integration',protonAuth:'Proton Drive använder sin egen autentiserade och totalsträckskrypterade SDK-/sessionsmodell i stället för det generella OAuth 2.0-lagringsflödet.',protonPreviewTitle:'Proton Drive',protonPreviewText:'Proton Drive finns nu i listan, men direkt produktionsintegration från tredje part förblir avstängd tills Proton förklarar Drive SDK och autentiseringsflödet redo för produktionsappar från tredje part.',protonSystemStorageText:'Proton Drive kan redan användas via systemlagring när Proton-appen exponerar det i operativsystemets filväljare.',protonSdkStatus:'Direkt SDK-anslutning: förhandsvisning / ännu inte aktiverad',
  },
};

// Reuse close linguistic neighbours only where Studio already treats these as
// distinct locales but this module still needs explicit entries. They remain
// independent objects so the completeness test can require all supported keys.
translations['pt'] = translations.pt;

export function getCloudOAuthCopy(locale: string): CloudOAuthCopy {
  return translations[locale] ?? en;
}

export const cloudOAuthTranslationLocales = Object.freeze(Object.keys(translations));
