import type { HelpCopy } from './help';

type ExtraHelpLocale =
  | 'bg' | 'cs' | 'da' | 'el' | 'es' | 'et' | 'fi' | 'fr' | 'ga' | 'hr'
  | 'it' | 'lt' | 'lv' | 'mt' | 'nl' | 'pl' | 'pt' | 'ro' | 'sk' | 'sl' | 'sv';

const topics = (
  titles: string[],
  bodies: string[],
): HelpCopy['topics'] => titles.map((title, index) => ({ title, body: bodies[index] ?? '' }));

const extra: Record<ExtraHelpLocale, HelpCopy> = {
  bg: {
    navigation: 'Помощ', title: 'Помощ за Open Manuscript Studio',
    description: 'Ръководство за текущите функции за ръкописи, рецензиране, публикуване и експортиране в Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio редактира семантичен ръкопис: заглавия, раздели, бележки, цитати, фигури, таблици, формули и метаданни се пазят като структурирани обекти. При отваряне от OJS наличният документ и публикационните данни се импортират чрез интеграцията.',
    topics: topics([
      '1. Редактиране и семантично форматиране','2. Раздели, йерархия и номерация','3. Данни за ръкописа, front matter и езици','4. Сътрудници, институции, ORCID и ROR','5. Бележки и цитати в бележки','6. Цитати, библиография и стил на цитиране','7. Кръстосани препратки','8. Фигури, таблици и формули','9. Медийни файлове и OMI пакет','10. Импорт на DOCX','11. Интеграция с OJS','12. Рецензиране','13. Ревизии, история и цялост','14. Публикационни профили','15. Собствени издателски профили и защита','16. Export CSS и Print/PDF CSS','17. Формати за експортиране','18. HTML и проверка за публикуване','19. Облачно и файлово съхранение','20. Ако нещо не изглежда правилно'
    ],[
      'Редактирайте текста и структурата в основния редактор. Studio запазва семантиката на абзаци, заглавия и поддържано вътрешно форматиране за последващ износ.','Разделите образуват йерархия. Нивата и номерацията могат да се управляват от активния публикационен профил.','Управляват се заглавие, подзаглавие, мото, резюме, ключови думи, език и многоезични варианти на метаданните.','Управлявайте автори и други сътрудници, роли, институционални връзки, ORCID и, когато е налично, ROR.','Бележките под линия и крайните бележки са семантични обекти и могат да съдържат форматиран текст и цитати.','Източниците се пазят като структурирани библиографски записи, могат да се използват многократно и да се визуализират чрез CSL.','Вътрешните препратки сочат към обекти, така че номерацията не трябва да се поправя ръчно при промени в структурата.','Фигури, таблици и формули се пазят като структурирани научни обекти и се пренасят в поддържаните изходи.','Медийните файлове са активи на ръкописа; пълният OMI пакет може да пренася и тях, и данни за цялост.','При импорт от Word Studio се опитва да преобразува заглавия, форматиране, бележки, таблици и други разпознаваеми структури в OMI елементи.','При сесия, стартирана от OJS, ръкописът и наличните метаданни се обменят според разрешените обхвати, assignment и права.','Моделът разделя ръкописа, рецензентското назначение и рецензентската работа; достъпът през OJS е обвързан с назначението.','Промените се проследяват като ревизии; могат да се използват digest за цялост и tombstone данни за изтрити структурни обекти.','Профилът отделя съдържанието от издателските правила и може да задава страница, типография, номерация, бележки, надписи, метаданни и изходи.','Може да се създава и версионира собствен издателски профил; защитен профил се изменя чрез нова версия.','Собствен профил може да съдържа общ Export CSS и отделен Print/PDF CSS с @page, полета, прекъсвания и други правила за печат.','Налични са OMI, OMI JSON, JATS XML, семантичен HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB и работен поток за PDF чрез печат.','Семантичният HTML е без скриптове. Преди износ Studio проверява ръкописа спрямо активния профил и показва грешки и предупреждения.','Поддържат се локални и конфигурируеми външни хранилища; WebDAV/Nextcloud зависи от инсталацията и настройките.','Определете дали проблемът е в съдържанието, структурата, метаданните, интеграцията или визуализацията и проверете езиците, профила и диагностиката.'
    ]),
  },
  cs: {
    navigation: 'Nápověda', title: 'Nápověda Open Manuscript Studio',
    description: 'Průvodce aktuálními funkcemi rukopisu, recenzního řízení, publikování a exportu ve Studiu 0.1.0-alpha.1.',
    gettingStarted: 'Studio upravuje sémantický rukopis: nadpisy, oddíly, poznámky, citace, obrázky, tabulky, rovnice a metadata zůstávají strukturovanými objekty. Při otevření z OJS se dostupný dokument a publikační údaje načtou prostřednictvím integrace.',
    topics: topics([
      '1. Úprava rukopisu a sémantické formátování','2. Oddíly, hierarchie a číslování','3. Údaje rukopisu, front matter a jazyky','4. Přispěvatelé, instituce, ORCID a ROR','5. Poznámky a citace v poznámkách','6. Citace, bibliografie a citační styl','7. Křížové odkazy','8. Obrázky, tabulky a rovnice','9. Média a balíček OMI','10. Import DOCX','11. Integrace OJS','12. Peer review','13. Revize, historie a integrita','14. Publikační profily','15. Vlastní vydavatelské profily a ochrana','16. Export CSS a Print/PDF CSS','17. Exportní formáty','18. HTML a publikační kontrola','19. Cloudové a souborové úložiště','20. Když něco nevypadá správně'
    ],[
      'V hlavním editoru upravujte text i strukturu. Studio zachovává význam odstavců, nadpisů a podporovaného inline formátování pro další výstupy.','Oddíly tvoří hierarchii; úrovně a číslování může řídit aktivní publikační profil.','Spravujte název, podnázev, motto, abstrakt, klíčová slova, jazyk dokumentu a vícejazyčné varianty metadat.','Spravujte autory a další přispěvatele, role, afiliace, ORCID a tam, kde je dostupné, také ROR.','Poznámky pod čarou a vysvětlivky jsou sémantické objekty a mohou obsahovat formátovaný text i citace.','Zdroje jsou strukturované bibliografické záznamy, lze je opakovaně použít a vykreslovat pomocí CSL.','Vnitřní odkazy míří na cílové objekty, takže při změně struktury není nutné ručně opravovat číslování.','Obrázky, tabulky a rovnice jsou strukturované vědecké objekty a lze je přenášet do podporovaných exportů.','Média jsou připojena jako aktiva; úplný balíček OMI může nést soubory, rukopis i údaje o integritě.','Při importu Wordu se Studio pokouší převést nadpisy, formátování, poznámky, tabulky a další rozpoznatelné struktury na prvky OMI.','V relaci spuštěné z OJS se rukopis a dostupná metadata přenášejí podle povolených rozsahů, assignmentu a oprávnění.','Model odděluje rukopis, recenzní assignment a práci recenzenta; přístup přes OJS je vázán na assignment.','Změny stavu jsou sledovány jako revize; lze použít integritní digest a tombstone data pro odstraněné objekty.','Profil odděluje obsah od vydavatelských pravidel a může definovat stránku, typografii, číslování, poznámky, popisky, metadata a výstupy.','Lze vytvářet a verzovat vlastní vydavatelské profily; chráněný profil se mění vytvořením nové verze.','Vlastní profil může obsahovat obecný Export CSS a samostatný Print/PDF CSS s @page, okraji, zalomením a dalšími tiskovými pravidly.','K dispozici jsou OMI, OMI JSON, JATS XML, sémantické HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB a tiskový postup pro PDF.','Sémantický HTML export je bez skriptů. Před exportem Studio ověřuje rukopis proti aktivnímu profilu a hlásí chyby či varování.','Podporováno je místní i konfigurovatelné externí úložiště; WebDAV/Nextcloud závisí na instalaci a nastavení.','Určete, zda jde o problém obsahu, struktury, metadat, integrace nebo vzhledu, a zkontrolujte jazyky, profil a diagnostiku.'
    ]),
  },
  da: {
    navigation: 'Hjælp', title: 'Hjælp til Open Manuscript Studio',
    description: 'Vejledning til de aktuelle manuskript-, peer review-, publicerings- og eksportfunktioner i Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio redigerer et semantisk manuskript: overskrifter, afsnit, noter, citater, figurer, tabeller, ligninger og metadata bevares som strukturerede objekter. Når et manuskript åbnes fra OJS, importeres dokumentet og tilgængelige publikationsdata via integrationen.',
    topics: topics([
      '1. Manuskriptredigering og semantisk formatering','2. Afsnit, hierarki og nummerering','3. Manuskriptdata, front matter og sprog','4. Bidragydere, institutioner, ORCID og ROR','5. Noter og citater i noter','6. Citater, bibliografi og citationsstil','7. Krydshenvisninger','8. Figurer, tabeller og ligninger','9. Mediefiler og OMI-pakken','10. DOCX-import','11. OJS-integration','12. Peer review','13. Revisioner, historik og integritet','14. Publikationsprofiler','15. Egne udgiverprofiler og beskyttelse','16. Export CSS og Print/PDF CSS','17. Eksportformater','18. HTML og publikationskontrol','19. Cloud- og fillagring','20. Hvis noget ikke ser rigtigt ud'
    ],[
      'Redigér tekst og struktur i hovededitoren. Studio bevarer betydningen af afsnit, overskrifter og understøttet inline-formatering til senere output.','Afsnit danner et hierarki; niveauer og nummerering kan styres af den aktive publikationsprofil.','Administrér titel, undertitel, motto, resumé, nøgleord, dokumentsprog og flersprogede metadatafelter.','Administrér forfattere og andre bidragydere, roller, tilknytninger, ORCID og, hvor tilgængeligt, ROR.','Fodnoter og slutnoter er semantiske objekter og kan indeholde formateret tekst og citater.','Kilder gemmes som strukturerede bibliografiske poster, kan genbruges og vises via CSL.','Interne henvisninger peger på målobjekter, så nummerering ikke skal rettes manuelt ved strukturændringer.','Figurer, tabeller og ligninger behandles som strukturerede videnskabelige objekter og kan overføres til understøttede eksportformater.','Medier er knyttet som aktiver; en fuld OMI-pakke kan bære filer, manuskript og integritetsdata samlet.','Ved Word-import forsøger Studio at konvertere overskrifter, formatering, noter, tabeller og andre genkendelige strukturer til OMI-elementer.','I en OJS-startet session overføres manuskript og tilgængelige metadata efter de tilladte scopes, assignment og rettigheder.','Modellen adskiller manuskript, review-assignment og reviewerarbejde; OJS-adgang er knyttet til assignmentet.','Tilstandsændringer spores som revisioner; integritetsdigest og tombstone-data kan bevare revisionssporet.','Profilen adskiller indhold fra udgiverregler og kan definere sideformat, typografi, nummerering, noter, billedtekster, metadata og output.','Egne udgiverprofiler kan oprettes og versioneres; et beskyttet profil ændres ved at oprette en ny version.','Et eget profil kan have generel Export CSS og særskilt Print/PDF CSS med @page, margener, sideskift og andre printregler.','Der kan eksporteres til OMI, OMI JSON, JATS XML, semantisk HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB samt PDF via printworkflow.','Semantisk HTML er scriptfrit. Før eksport validerer Studio manuskriptet mod den aktive profil og viser fejl og advarsler.','Lokale og konfigurerbare eksterne lagre understøttes; WebDAV/Nextcloud afhænger af installation og indstillinger.','Afgør om problemet gælder indhold, struktur, metadata, integration eller visning, og kontrollér sprog, profil og diagnostik.'
    ]),
  },
  el: {
    navigation: 'Βοήθεια', title: 'Βοήθεια Open Manuscript Studio',
    description: 'Οδηγός για τις τρέχουσες λειτουργίες χειρογράφου, αξιολόγησης, δημοσίευσης και εξαγωγής στο Studio 0.1.0-alpha.1.',
    gettingStarted: 'Το Studio επεξεργάζεται σημασιολογικό χειρόγραφο: τίτλοι, ενότητες, σημειώσεις, παραπομπές, σχήματα, πίνακες, εξισώσεις και μεταδεδομένα διατηρούνται ως δομημένα αντικείμενα. Όταν το χειρόγραφο ανοίγει από OJS, το έγγραφο και τα διαθέσιμα δεδομένα δημοσίευσης εισάγονται μέσω της διασύνδεσης.',
    topics: topics([
      '1. Επεξεργασία χειρογράφου και σημασιολογική μορφοποίηση','2. Ενότητες, ιεραρχία και αρίθμηση','3. Δεδομένα χειρογράφου, front matter και γλώσσες','4. Συντελεστές, ιδρύματα, ORCID και ROR','5. Σημειώσεις και παραπομπές μέσα σε σημειώσεις','6. Παραπομπές, βιβλιογραφία και στυλ αναφορών','7. Εσωτερικές παραπομπές','8. Σχήματα, πίνακες και εξισώσεις','9. Αρχεία πολυμέσων και πακέτο OMI','10. Εισαγωγή DOCX','11. Ενσωμάτωση OJS','12. Peer review','13. Αναθεωρήσεις, ιστορικό και ακεραιότητα','14. Προφίλ δημοσίευσης','15. Προσαρμοσμένα προφίλ εκδότη και προστασία','16. Export CSS και Print/PDF CSS','17. Μορφές εξαγωγής','18. HTML και έλεγχος δημοσίευσης','19. Αποθήκευση cloud και αρχείων','20. Αν κάτι δεν εμφανίζεται σωστά'
    ],[
      'Επεξεργαστείτε κείμενο και δομή στον κύριο επεξεργαστή. Το Studio διατηρεί τη σημασία παραγράφων, επικεφαλίδων και υποστηριζόμενης μορφοποίησης για μεταγενέστερες εξαγωγές.','Οι ενότητες σχηματίζουν ιεραρχία και η αρίθμηση μπορεί να ελέγχεται από το ενεργό προφίλ δημοσίευσης.','Διαχειριστείτε τίτλο, υπότιτλο, μότο, περίληψη, λέξεις-κλειδιά, γλώσσα εγγράφου και πολύγλωσσες παραλλαγές μεταδεδομένων.','Διαχειριστείτε συγγραφείς και άλλους συντελεστές, ρόλους, affiliations, ORCID και, όπου διατίθεται, ROR.','Οι υποσημειώσεις και οι τελικές σημειώσεις είναι σημασιολογικά αντικείμενα και μπορούν να περιέχουν μορφοποιημένο κείμενο και παραπομπές.','Οι πηγές αποθηκεύονται ως δομημένες βιβλιογραφικές εγγραφές, επαναχρησιμοποιούνται και μπορούν να αποδοθούν με CSL.','Οι εσωτερικές αναφορές δείχνουν σε αντικείμενα-στόχους ώστε η αρίθμηση να μην διορθώνεται χειροκίνητα μετά από αλλαγές δομής.','Σχήματα, πίνακες και εξισώσεις είναι δομημένα επιστημονικά αντικείμενα και μεταφέρονται σε υποστηριζόμενες εξαγωγές.','Τα πολυμέσα συνδέονται ως assets· ένα πλήρες πακέτο OMI μπορεί να μεταφέρει αρχεία, χειρόγραφο και δεδομένα ακεραιότητας.','Κατά την εισαγωγή Word, το Studio επιχειρεί να μετατρέψει επικεφαλίδες, μορφοποίηση, σημειώσεις, πίνακες και άλλες αναγνωρίσιμες δομές σε στοιχεία OMI.','Σε συνεδρία που ξεκινά από OJS, χειρόγραφο και διαθέσιμα μεταδεδομένα ανταλλάσσονται σύμφωνα με scopes, assignment και δικαιώματα.','Το μοντέλο διαχωρίζει χειρόγραφο, assignment αξιολόγησης και εργασία αξιολογητή· η πρόσβαση μέσω OJS συνδέεται με το assignment.','Οι αλλαγές κατάστασης παρακολουθούνται ως αναθεωρήσεις και μπορούν να συνοδεύονται από digest ακεραιότητας και tombstone δεδομένα.','Το προφίλ διαχωρίζει το περιεχόμενο από τους εκδοτικούς κανόνες και μπορεί να ορίζει σελίδα, τυπογραφία, αρίθμηση, σημειώσεις, λεζάντες, μεταδεδομένα και εξόδους.','Μπορούν να δημιουργούνται και να εκδίδονται σε εκδόσεις προσαρμοσμένα προφίλ εκδότη· προστατευμένο προφίλ αλλάζει με νέα έκδοση.','Ένα προφίλ μπορεί να έχει γενικό Export CSS και ξεχωριστό Print/PDF CSS με @page, περιθώρια, αλλαγές σελίδας και άλλους κανόνες εκτύπωσης.','Διατίθενται OMI, OMI JSON, JATS XML, σημασιολογικό HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB και ροή PDF μέσω εκτύπωσης.','Το σημασιολογικό HTML είναι χωρίς scripts. Πριν την εξαγωγή, το Studio επικυρώνει το χειρόγραφο με το ενεργό προφίλ και εμφανίζει σφάλματα ή προειδοποιήσεις.','Υποστηρίζεται τοπική και ρυθμιζόμενη εξωτερική αποθήκευση· WebDAV/Nextcloud εξαρτάται από την εγκατάσταση και τις ρυθμίσεις.','Εντοπίστε αν το πρόβλημα αφορά περιεχόμενο, δομή, μεταδεδομένα, ενσωμάτωση ή εμφάνιση και ελέγξτε γλώσσες, προφίλ και διαγνωστικά.'
    ]),
  },
  es: {
    navigation: 'Ayuda', title: 'Ayuda de Open Manuscript Studio',
    description: 'Guía de las funciones actuales de manuscrito, revisión por pares, publicación y exportación de Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio edita un manuscrito semántico: títulos, secciones, notas, citas, figuras, tablas, ecuaciones y metadatos se conservan como objetos estructurados. Al abrir un manuscrito desde OJS, el documento y los datos de publicación disponibles se importan mediante la integración.',
    topics: topics([
      '1. Edición del manuscrito y formato semántico','2. Secciones, jerarquía y numeración','3. Datos del manuscrito, front matter e idiomas','4. Colaboradores, instituciones, ORCID y ROR','5. Notas y citas dentro de notas','6. Citas, bibliografía y estilo de citación','7. Referencias cruzadas','8. Figuras, tablas y ecuaciones','9. Archivos multimedia y paquete OMI','10. Importación DOCX','11. Integración con OJS','12. Revisión por pares','13. Revisiones, historial e integridad','14. Perfiles de publicación','15. Perfiles editoriales personalizados y protección','16. Export CSS y Print/PDF CSS','17. Formatos de exportación','18. HTML y validación de publicación','19. Almacenamiento en nube y archivos','20. Si algo no se ve correctamente'
    ],[
      'Edite el texto y la estructura en el editor principal. Studio conserva el significado de párrafos, encabezados y formato en línea compatible para futuras salidas.','Las secciones forman una jerarquía; los niveles y la numeración pueden estar controlados por el perfil de publicación activo.','Gestione título, subtítulo, lema, resumen, palabras clave, idioma del documento y variantes multilingües de metadatos.','Gestione autores y otros colaboradores, roles, afiliaciones, ORCID y, cuando esté disponible, ROR.','Las notas al pie y finales son objetos semánticos y pueden contener texto enriquecido y citas.','Las fuentes se almacenan como registros bibliográficos estructurados, pueden reutilizarse y mostrarse mediante CSL.','Las referencias internas apuntan a objetos de destino, por lo que la numeración no debe corregirse manualmente tras cambios estructurales.','Figuras, tablas y ecuaciones son objetos científicos estructurados que pueden pasar a los formatos de salida compatibles.','Los medios se adjuntan como recursos; un paquete OMI completo puede transportar archivos, manuscrito y datos de integridad.','Al importar Word, Studio intenta convertir encabezados, formato, notas, tablas y otras estructuras reconocibles en elementos OMI.','En una sesión iniciada desde OJS, manuscrito y metadatos disponibles se transfieren según scopes, assignment y permisos.','El modelo separa manuscrito, assignment de revisión y trabajo del revisor; el acceso desde OJS está ligado al assignment.','Los cambios de estado se siguen como revisiones y pueden llevar digest de integridad y datos tombstone para objetos eliminados.','El perfil separa el contenido de las reglas editoriales y puede definir página, tipografía, numeración, notas, leyendas, metadatos y salidas.','Se pueden crear y versionar perfiles editoriales personalizados; los perfiles protegidos se cambian mediante una nueva versión.','Un perfil puede incluir Export CSS general y Print/PDF CSS separado con @page, márgenes, saltos y otras reglas de impresión.','Están disponibles OMI, OMI JSON, JATS XML, HTML semántico, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB y flujo PDF mediante impresión.','El HTML semántico no incluye scripts. Antes de exportar, Studio valida el manuscrito frente al perfil activo y muestra errores o advertencias.','Se admite almacenamiento local y externo configurable; WebDAV/Nextcloud depende de la instalación y la configuración.','Determine si el problema es de contenido, estructura, metadatos, integración o presentación y revise idiomas, perfil y diagnósticos.'
    ]),
  },
  et: {
    navigation: 'Abi', title: 'Open Manuscript Studio abi',
    description: 'Juhend Studio 0.1.0-alpha.1 praeguste käsikirja-, eelretsenseerimise, avaldamise ja ekspordi funktsioonide kohta.',
    gettingStarted: 'Studio töötleb semantilist käsikirja: pealkirjad, jaotised, märkused, viited, joonised, tabelid, valemid ja metaandmed säilivad struktureeritud objektidena. OJS-ist avamisel imporditakse dokument ja saadaolevad avaldamisandmed integratsiooni kaudu.',
    topics: topics([
      '1. Käsikirja muutmine ja semantiline vormindus','2. Jaotised, hierarhia ja nummerdus','3. Käsikirjaandmed, front matter ja keeled','4. Kaastöötajad, asutused, ORCID ja ROR','5. Märkused ja viited märkustes','6. Viited, bibliograafia ja viitamisstiil','7. Ristviited','8. Joonised, tabelid ja valemid','9. Meediafailid ja OMI-pakett','10. DOCX-import','11. OJS-integratsioon','12. Eelretsenseerimine','13. Revisjonid, ajalugu ja terviklus','14. Avaldamisprofiilid','15. Kohandatud kirjastajaprofiilid ja kaitse','16. Export CSS ja Print/PDF CSS','17. Ekspordivormingud','18. HTML ja avaldamise kontroll','19. Pilve- ja failisalvestus','20. Kui miski ei näe õige välja'
    ],[
      'Muutke põhiredaktoris teksti ja struktuuri. Studio säilitab lõikude, pealkirjade ja toetatud sisemise vorminduse semantilise tähenduse.','Jaotised moodustavad hierarhia; tasemeid ja nummerdust võib juhtida aktiivne avaldamisprofiil.','Hallake pealkirja, alapealkirja, motot, kokkuvõtet, märksõnu, dokumendi keelt ja mitmekeelseid metaandmevariante.','Hallake autoreid ja teisi kaastöötajaid, rolle, asutusi, ORCID-i ja võimaluse korral ROR-i.','All- ja lõpumärkused on semantilised objektid ning võivad sisaldada vormindatud teksti ja viiteid.','Allikad on struktureeritud bibliograafiakirjed, mida saab taaskasutada ja CSL-i abil kuvada.','Sisemised viited osutavad sihtobjektidele, seega ei pea struktuurimuutuste järel nummerdust käsitsi parandama.','Joonised, tabelid ja valemid on struktureeritud teadusobjektid, mida saab toetatud väljunditesse kanda.','Meedia on seotud varadena; täielik OMI-pakett võib koos kanda faile, käsikirja ja tervikluse andmeid.','Wordi importimisel püüab Studio muuta pealkirjad, vorminduse, märkused, tabelid ja muud äratuntavad struktuurid OMI-elementideks.','OJS-ist käivitatud seansis liiguvad käsikiri ja metaandmed vastavalt lubatud scope’idele, assignment’ile ja õigustele.','Mudel eristab käsikirja, review assignment’i ja retsensendi tööd; OJS-i ligipääs on assignment’iga seotud.','Olekumuutusi jälgitakse revisjonidena; kasutada saab tervikluse digestit ja kustutatud objektide tombstone-andmeid.','Profiil eraldab sisu kirjastamisreeglitest ning võib määrata lehe, tüpograafia, nummerduse, märkused, pealdised, metaandmed ja väljundid.','Kohandatud kirjastajaprofiile saab luua ja versioonida; kaitstud profiili muudetakse uue versiooni loomisega.','Profiil võib sisaldada üldist Export CSS-i ja eraldi Print/PDF CSS-i @page-, veeriste, leheküljepiiride ja muude printimisreeglitega.','Saadaval on OMI, OMI JSON, JATS XML, semantiline HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB ja printimise kaudu PDF.','Semantiline HTML on skriptivaba. Enne eksporti valideerib Studio käsikirja aktiivse profiili järgi ja näitab vigu või hoiatusi.','Toetatud on kohalik ja seadistatav väline salvestus; WebDAV/Nextcloud sõltub paigaldusest ja seadetest.','Määrake, kas probleem puudutab sisu, struktuuri, metaandmeid, integratsiooni või esitust, ning kontrollige keeli, profiili ja diagnostikat.'
    ]),
  },
  fi: {
    navigation: 'Ohje', title: 'Open Manuscript Studio -ohje',
    description: 'Opas Studio 0.1.0-alpha.1:n nykyisiin käsikirja-, vertaisarviointi-, julkaisu- ja vientitoimintoihin.',
    gettingStarted: 'Studio muokkaa semanttista käsikirjoitusta: otsikot, osiot, huomautukset, viitteet, kuvat, taulukot, kaavat ja metatiedot säilyvät rakenteisina objekteina. OJS:stä avattaessa asiakirja ja saatavilla olevat julkaisutiedot tuodaan integraation kautta.',
    topics: topics([
      '1. Käsikirjoituksen muokkaus ja semanttinen muotoilu','2. Osiot, hierarkia ja numerointi','3. Käsikirjoituksen tiedot, front matter ja kielet','4. Tekijät, organisaatiot, ORCID ja ROR','5. Huomautukset ja viitteet huomautuksissa','6. Viitteet, lähdeluettelo ja viittaustyyli','7. Ristiviittaukset','8. Kuvat, taulukot ja kaavat','9. Mediatiedostot ja OMI-paketti','10. DOCX-tuonti','11. OJS-integraatio','12. Vertaisarviointi','13. Revisiot, historia ja eheys','14. Julkaisuprofiilit','15. Omat kustantajaprofiilit ja suojaus','16. Export CSS ja Print/PDF CSS','17. Vientimuodot','18. HTML ja julkaisun tarkistus','19. Pilvi- ja tiedostotallennus','20. Jos jokin ei näytä oikealta'
    ],[
      'Muokkaa tekstiä ja rakennetta pääeditorissa. Studio säilyttää kappaleiden, otsikoiden ja tuetun tekstimuotoilun semanttisen merkityksen myöhempiä vientimuotoja varten.','Osiot muodostavat hierarkian; tasoja ja numerointia voidaan ohjata aktiivisella julkaisuprofiililla.','Hallitse otsikkoa, alaotsikkoa, mottoa, tiivistelmää, avainsanoja, dokumentin kieltä ja monikielisiä metatietoversioita.','Hallitse kirjoittajia ja muita tekijöitä, rooleja, organisaatioita, ORCID-tunnuksia ja mahdollisuuksien mukaan ROR-tietoja.','Ala- ja loppuviitteet ovat semanttisia objekteja ja voivat sisältää muotoiltua tekstiä ja lähdeviitteitä.','Lähteet tallennetaan rakenteisina bibliografisina tietueina, niitä voidaan käyttää uudelleen ja esittää CSL:n avulla.','Sisäiset viittaukset osoittavat kohdeobjekteihin, joten numerointia ei tarvitse korjata käsin rakenteen muuttuessa.','Kuvat, taulukot ja kaavat käsitellään rakenteisina tieteellisinä objekteina ja voidaan siirtää tuettuihin vientimuotoihin.','Media liitetään aineistoina; täydellinen OMI-paketti voi sisältää tiedostot, käsikirjoituksen ja eheystiedot.','Word-tuonnissa Studio yrittää muuntaa otsikot, muotoilut, huomautukset, taulukot ja muut tunnistettavat rakenteet OMI-elementeiksi.','OJS:stä käynnistetyssä istunnossa käsikirjoitus ja metatiedot siirtyvät sallittujen scopejen, assignmentin ja oikeuksien mukaisesti.','Malli erottaa käsikirjoituksen, review assignmentin ja arvioijan työn; OJS-pääsy on sidottu assignmentiin.','Tilamuutoksia seurataan revisioina; eheysdigest ja tombstone-tiedot voivat tukea jäljitettävyyttä.','Profiili erottaa sisällön kustantajan säännöistä ja voi määrittää sivun, typografian, numeroinnin, viitteet, kuvatekstit, metatiedot ja tulosteet.','Omia kustantajaprofiileja voidaan luoda ja versioida; suojattu profiili muuttuu uuden version kautta.','Profiili voi sisältää yleisen Export CSS:n ja erillisen Print/PDF CSS:n @page-, marginaali-, sivunvaihto- ja muine tulostussääntöineen.','Saatavilla ovat OMI, OMI JSON, JATS XML, semanttinen HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB ja PDF tulostusnäkymän kautta.','Semanttinen HTML on skriptitön. Ennen vientiä Studio validoi käsikirjoituksen aktiivista profiilia vasten ja näyttää virheet tai varoitukset.','Paikallinen ja määritettävä ulkoinen tallennus on tuettu; WebDAV/Nextcloud riippuu asennuksesta ja asetuksista.','Selvitä koskeeko ongelma sisältöä, rakennetta, metatietoja, integraatiota vai esitystä ja tarkista kielet, profiili sekä diagnostiikka.'
    ]),
  },
  fr: {
    navigation: 'Aide', title: 'Aide Open Manuscript Studio',
    description: 'Guide des fonctions actuelles de manuscrit, d’évaluation par les pairs, de publication et d’export de Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio édite un manuscrit sémantique : titres, sections, notes, citations, figures, tableaux, équations et métadonnées restent des objets structurés. Lorsqu’un manuscrit est ouvert depuis OJS, le document et les données de publication disponibles sont importés par l’intégration.',
    topics: topics([
      '1. Édition du manuscrit et mise en forme sémantique','2. Sections, hiérarchie et numérotation','3. Données du manuscrit, front matter et langues','4. Contributeurs, institutions, ORCID et ROR','5. Notes et citations dans les notes','6. Citations, bibliographie et style bibliographique','7. Renvois internes','8. Figures, tableaux et équations','9. Fichiers multimédias et paquet OMI','10. Import DOCX','11. Intégration OJS','12. Évaluation par les pairs','13. Révisions, historique et intégrité','14. Profils de publication','15. Profils d’éditeur personnalisés et protection','16. Export CSS et Print/PDF CSS','17. Formats d’export','18. HTML et validation de publication','19. Stockage cloud et fichiers','20. Si quelque chose ne s’affiche pas correctement'
    ],[
      'Modifiez le texte et la structure dans l’éditeur principal. Studio conserve le sens des paragraphes, titres et mises en forme en ligne prises en charge pour les exports ultérieurs.','Les sections forment une hiérarchie ; les niveaux et la numérotation peuvent être pilotés par le profil de publication actif.','Gérez titre, sous-titre, devise, résumé, mots-clés, langue du document et variantes multilingues des métadonnées.','Gérez auteurs et autres contributeurs, rôles, affiliations, ORCID et, lorsque disponible, ROR.','Notes de bas de page et notes de fin sont des objets sémantiques pouvant contenir du texte riche et des citations.','Les sources sont stockées comme notices bibliographiques structurées, réutilisables et rendues avec CSL.','Les renvois internes pointent vers des objets cibles, ce qui évite de corriger manuellement la numérotation après une restructuration.','Figures, tableaux et équations sont des objets scientifiques structurés transmissibles aux exports pris en charge.','Les médias sont attachés comme ressources ; un paquet OMI complet peut transporter fichiers, manuscrit et données d’intégrité.','Lors d’un import Word, Studio tente de convertir titres, formats, notes, tableaux et autres structures reconnues en éléments OMI.','Dans une session lancée depuis OJS, manuscrit et métadonnées sont échangés selon les scopes, l’assignment et les droits accordés.','Le modèle sépare manuscrit, assignment d’évaluation et travail du reviewer ; l’accès OJS est lié à l’assignment.','Les changements d’état sont suivis comme révisions et peuvent utiliser un digest d’intégrité et des données tombstone.','Le profil sépare le contenu des règles éditoriales et peut définir page, typographie, numérotation, notes, légendes, métadonnées et sorties.','Des profils d’éditeur personnalisés peuvent être créés et versionnés ; un profil protégé évolue par nouvelle version.','Un profil peut inclure un Export CSS général et un Print/PDF CSS séparé avec @page, marges, sauts de page et autres règles d’impression.','Les sorties incluent OMI, OMI JSON, JATS XML, HTML sémantique, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB et PDF via l’impression.','L’HTML sémantique est sans script. Avant export, Studio valide le manuscrit avec le profil actif et signale erreurs et avertissements.','Le stockage local et externe configurable est pris en charge ; WebDAV/Nextcloud dépend de l’installation et des réglages.','Déterminez si le problème concerne contenu, structure, métadonnées, intégration ou présentation, puis vérifiez langues, profil et diagnostics.'
    ]),
  },
  ga: {
    navigation: 'Cabhair', title: 'Cabhair Open Manuscript Studio',
    description: 'Treoir do ghnéithe reatha lámhscríbhinne, piarmheasúnaithe, foilsithe agus easpórtála Studio 0.1.0-alpha.1.',
    gettingStarted: 'Cuireann Studio lámhscríbhinn shéimeantach in eagar: coimeádtar ceannteidil, rannóga, nótaí, lua, figiúirí, táblaí, cothromóidí agus meiteashonraí mar oibiachtaí struchtúrtha. Nuair a osclaítear ó OJS í, iompórtáiltear an doiciméad agus na sonraí foilseacháin atá ar fáil tríd an gcomhtháthú.',
    topics: topics([
      '1. Eagarthóireacht lámhscríbhinne agus formáidiú séimeantach','2. Rannóga, ordlathas agus uimhriú','3. Sonraí lámhscríbhinne, front matter agus teangacha','4. Rannpháirtithe, institiúidí, ORCID agus ROR','5. Nótaí agus lua i nótaí','6. Lua, leabharliosta agus stíl lua','7. Crostagairtí','8. Figiúirí, táblaí agus cothromóidí','9. Meáin agus pacáiste OMI','10. Iompórtáil DOCX','11. Comhtháthú OJS','12. Piarmheasúnú','13. Leasuithe, stair agus sláine','14. Próifílí foilseacháin','15. Próifílí foilsitheora saincheaptha agus cosaint','16. Export CSS agus Print/PDF CSS','17. Formáidí easpórtála','18. HTML agus bailíochtú foilseacháin','19. Stóráil scamall agus comhad','20. Mura bhfuil rud éigin le feiceáil i gceart'
    ],[
      'Cuir téacs agus struchtúr in eagar sa phríomheagarthóir. Coinníonn Studio brí shéimeantach na míreanna, na gceannteideal agus an fhormáidithe inline a dtacaítear leis.','Cruthaíonn rannóga ordlathas agus is féidir leis an bpróifíl foilseacháin ghníomhach leibhéil agus uimhriú a rialú.','Bainistigh teideal, fotheideal, mana, achoimre, eochairfhocail, teanga an doiciméid agus leaganacha ilteangacha meiteashonraí.','Bainistigh údair agus rannpháirtithe eile, róil, cleamhnachtaí, ORCID agus ROR nuair atá sé ar fáil.','Is oibiachtaí séimeantacha iad fonótaí agus iarnótaí agus is féidir leo téacs saibhir agus lua a bheith iontu.','Stóráiltear foinsí mar thaifid leabharliosta struchtúrtha, is féidir iad a athúsáid agus a rindreáil le CSL.','Díríonn crostagairtí inmheánacha ar sprioc-oibiachtaí, mar sin ní gá uimhriú a cheartú de láimh tar éis athstruchtúrú.','Is oibiachtaí eolaíochta struchtúrtha iad figiúirí, táblaí agus cothromóidí agus is féidir iad a iompar chuig easpórtálacha tacaithe.','Ceanglaítear meáin mar shócmhainní; is féidir le pacáiste iomlán OMI comhaid, an lámhscríbhinn agus sonraí sláine a iompar le chéile.','Agus Word á iompórtáil, déanann Studio iarracht ceannteidil, formáidiú, nótaí, táblaí agus struchtúir eile a aithnítear a thiontú go heilimintí OMI.','I seisiún a sheoltar ó OJS, aistrítear an lámhscríbhinn agus meiteashonraí de réir scopes, assignment agus ceadanna.','Scarann an tsamhail an lámhscríbhinn, an review assignment agus obair an athbhreithneora; tá rochtain OJS ceangailte leis an assignment.','Rianaítear athruithe stáit mar leasuithe agus is féidir digest sláine agus sonraí tombstone a úsáid.','Scarann an phróifíl ábhar ó rialacha foilsitheora agus féadann sí leathanach, clóghrafaíocht, uimhriú, nótaí, fotheidil, meiteashonraí agus aschuir a shainiú.','Is féidir próifílí foilsitheora saincheaptha a chruthú agus a leaganú; athraítear próifíl chosanta trí leagan nua.','Is féidir Export CSS ginearálta agus Print/PDF CSS ar leith a bheith i bpróifíl le @page, imill, sosanna leathanaigh agus rialacha priontála eile.','Tá OMI, OMI JSON, JATS XML, HTML séimeantach, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB agus PDF trí phriontáil ar fáil.','Tá HTML séimeantach saor ó scripteanna. Roimh easpórtáil bailíochtaíonn Studio an lámhscríbhinn i gcoinne na próifíle gníomhaí.','Tacaítear le stóráil áitiúil agus sheachtrach inchumraithe; braitheann WebDAV/Nextcloud ar an suiteáil agus ar na socruithe.','Aimsigh an mbaineann an fhadhb le hábhar, struchtúr, meiteashonraí, comhtháthú nó cur i láthair agus seiceáil teangacha, próifíl agus diagnóisic.'
    ]),
  },
  hr: {
    navigation: 'Pomoć', title: 'Pomoć za Open Manuscript Studio',
    description: 'Vodič za trenutačne funkcije rukopisa, recenziranja, objavljivanja i izvoza u Studiju 0.1.0-alpha.1.',
    gettingStarted: 'Studio uređuje semantički rukopis: naslovi, odjeljci, bilješke, citati, slike, tablice, jednadžbe i metapodaci čuvaju se kao strukturirani objekti. Kada se rukopis otvori iz OJS-a, dokument i dostupni publikacijski podaci uvoze se kroz integraciju.',
    topics: topics([
      '1. Uređivanje rukopisa i semantičko oblikovanje','2. Odjeljci, hijerarhija i numeriranje','3. Podaci rukopisa, front matter i jezici','4. Suradnici, ustanove, ORCID i ROR','5. Bilješke i citati u bilješkama','6. Citati, bibliografija i stil citiranja','7. Unakrsne poveznice','8. Slike, tablice i jednadžbe','9. Medijske datoteke i OMI paket','10. Uvoz DOCX-a','11. OJS integracija','12. Recenziranje','13. Revizije, povijest i integritet','14. Publikacijski profili','15. Vlastiti izdavački profili i zaštita','16. Export CSS i Print/PDF CSS','17. Izvozni formati','18. HTML i provjera publikacije','19. Pohrana u oblaku i datotekama','20. Ako nešto ne izgleda ispravno'
    ],[
      'U glavnom uređivaču mijenjajte tekst i strukturu. Studio čuva semantičko značenje odlomaka, naslova i podržanog oblikovanja za kasnije izvoze.','Odjeljci čine hijerarhiju; razine i numeriranje može kontrolirati aktivni publikacijski profil.','Upravljajte naslovom, podnaslovom, motom, sažetkom, ključnim riječima, jezikom dokumenta i višejezičnim metapodacima.','Upravljajte autorima i drugim suradnicima, ulogama, afilijacijama, ORCID-om i, gdje je dostupno, ROR-om.','Fusnote i završne bilješke semantički su objekti i mogu sadržavati oblikovani tekst i citate.','Izvori se čuvaju kao strukturirani bibliografski zapisi, mogu se ponovno koristiti i prikazivati putem CSL-a.','Unutarnje poveznice ciljaju objekte pa nije potrebno ručno popravljati numeriranje nakon promjene strukture.','Slike, tablice i jednadžbe strukturirani su znanstveni objekti koji se mogu prenijeti u podržane izvoze.','Mediji su priloženi kao resursi; puni OMI paket može zajedno prenijeti datoteke, rukopis i podatke o integritetu.','Pri uvozu Worda Studio pokušava pretvoriti naslove, oblikovanje, bilješke, tablice i druge prepoznatljive strukture u OMI elemente.','U sesiji pokrenutoj iz OJS-a rukopis i metapodaci prenose se prema dopuštenim scopeovima, assignmentu i pravima.','Model odvaja rukopis, review assignment i rad recenzenta; OJS pristup vezan je uz assignment.','Promjene stanja prate se kao revizije; mogu se koristiti integritetski digest i tombstone podaci.','Profil odvaja sadržaj od izdavačkih pravila i može definirati stranicu, tipografiju, numeriranje, bilješke, opise, metapodatke i izlaze.','Vlastiti izdavački profili mogu se stvarati i verzionirati; zaštićeni profil mijenja se novom verzijom.','Profil može sadržavati opći Export CSS i zasebni Print/PDF CSS s @page, marginama, prijelomima stranica i drugim pravilima ispisa.','Dostupni su OMI, OMI JSON, JATS XML, semantički HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB i PDF putem ispisa.','Semantički HTML je bez skripti. Prije izvoza Studio provjerava rukopis prema aktivnom profilu i prikazuje pogreške ili upozorenja.','Podržana je lokalna i konfigurabilna vanjska pohrana; WebDAV/Nextcloud ovisi o instalaciji i postavkama.','Utvrdite odnosi li se problem na sadržaj, strukturu, metapodatke, integraciju ili prikaz te provjerite jezike, profil i dijagnostiku.'
    ]),
  },
  it: {
    navigation: 'Aiuto', title: 'Guida di Open Manuscript Studio',
    description: 'Guida alle funzioni correnti di manoscritto, peer review, pubblicazione ed esportazione di Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio modifica un manoscritto semantico: titoli, sezioni, note, citazioni, figure, tabelle, equazioni e metadati restano oggetti strutturati. Quando un manoscritto viene aperto da OJS, il documento e i dati di pubblicazione disponibili vengono importati tramite l’integrazione.',
    topics: topics([
      '1. Modifica del manoscritto e formattazione semantica','2. Sezioni, gerarchia e numerazione','3. Dati del manoscritto, front matter e lingue','4. Contributori, istituzioni, ORCID e ROR','5. Note e citazioni nelle note','6. Citazioni, bibliografia e stile citazionale','7. Riferimenti incrociati','8. Figure, tabelle ed equazioni','9. File multimediali e pacchetto OMI','10. Importazione DOCX','11. Integrazione OJS','12. Peer review','13. Revisioni, cronologia e integrità','14. Profili di pubblicazione','15. Profili editore personalizzati e protezione','16. Export CSS e Print/PDF CSS','17. Formati di esportazione','18. HTML e convalida della pubblicazione','19. Archiviazione cloud e file','20. Se qualcosa non appare correttamente'
    ],[
      'Modifica testo e struttura nell’editor principale. Studio conserva il significato di paragrafi, titoli e formattazione inline supportata per gli output successivi.','Le sezioni formano una gerarchia; livelli e numerazione possono essere controllati dal profilo di pubblicazione attivo.','Gestisci titolo, sottotitolo, motto, abstract, parole chiave, lingua del documento e varianti multilingue dei metadati.','Gestisci autori e altri contributori, ruoli, affiliazioni, ORCID e, se disponibile, ROR.','Note a piè di pagina e note finali sono oggetti semantici e possono contenere testo formattato e citazioni.','Le fonti sono record bibliografici strutturati, riutilizzabili e visualizzabili tramite CSL.','I riferimenti interni puntano agli oggetti di destinazione, quindi la numerazione non va corretta manualmente dopo modifiche strutturali.','Figure, tabelle ed equazioni sono oggetti scientifici strutturati e possono essere trasferiti negli export supportati.','I media sono allegati come risorse; un pacchetto OMI completo può trasportare file, manoscritto e dati di integrità.','Durante l’importazione Word, Studio tenta di convertire titoli, formattazione, note, tabelle e altre strutture riconoscibili in elementi OMI.','In una sessione avviata da OJS, manoscritto e metadati vengono trasferiti in base a scope, assignment e permessi concessi.','Il modello separa manoscritto, review assignment e lavoro del revisore; l’accesso OJS è legato all’assignment.','I cambi di stato sono tracciati come revisioni e possono includere digest di integrità e dati tombstone.','Il profilo separa il contenuto dalle regole editoriali e può definire pagina, tipografia, numerazione, note, didascalie, metadati e output.','Si possono creare e versionare profili editore personalizzati; un profilo protetto si modifica creando una nuova versione.','Un profilo può contenere Export CSS generale e Print/PDF CSS separato con @page, margini, interruzioni e altre regole di stampa.','Sono disponibili OMI, OMI JSON, JATS XML, HTML semantico, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB e PDF tramite stampa.','L’HTML semantico è privo di script. Prima dell’export Studio valida il manoscritto rispetto al profilo attivo e segnala errori o avvisi.','Sono supportati archiviazione locale ed esterna configurabile; WebDAV/Nextcloud dipende dall’installazione e dalle impostazioni.','Determina se il problema riguarda contenuto, struttura, metadati, integrazione o presentazione e controlla lingue, profilo e diagnostica.'
    ]),
  },
  lt: {
    navigation: 'Žinynas', title: 'Open Manuscript Studio žinynas',
    description: 'Studio 0.1.0-alpha.1 dabartinių rankraščio, recenzavimo, publikavimo ir eksporto funkcijų vadovas.',
    gettingStarted: 'Studio redaguoja semantinį rankraštį: antraštės, skyriai, pastabos, citatos, paveikslai, lentelės, formulės ir metaduomenys išlieka struktūriniais objektais. Atidarius iš OJS, dokumentas ir turimi publikacijos duomenys importuojami per integraciją.',
    topics: topics([
      '1. Rankraščio redagavimas ir semantinis formatavimas','2. Skyriai, hierarchija ir numeravimas','3. Rankraščio duomenys, front matter ir kalbos','4. Autoriai, institucijos, ORCID ir ROR','5. Pastabos ir citatos pastabose','6. Citatos, bibliografija ir citavimo stilius','7. Kryžminės nuorodos','8. Paveikslai, lentelės ir formulės','9. Medijos failai ir OMI paketas','10. DOCX importas','11. OJS integracija','12. Recenzavimas','13. Revizijos, istorija ir vientisumas','14. Publikavimo profiliai','15. Individualūs leidėjo profiliai ir apsauga','16. Export CSS ir Print/PDF CSS','17. Eksporto formatai','18. HTML ir publikavimo patikra','19. Debesies ir failų saugykla','20. Jei kas nors rodoma neteisingai'
    ],[
      'Redaguokite tekstą ir struktūrą pagrindiniame redaktoriuje. Studio išsaugo pastraipų, antraščių ir palaikomo inline formatavimo semantiką.','Skyriai sudaro hierarchiją; lygius ir numeravimą gali valdyti aktyvus publikavimo profilis.','Tvarkykite pavadinimą, paantraštę, moto, santrauką, raktažodžius, dokumento kalbą ir daugiakalbius metaduomenis.','Tvarkykite autorius ir kitus bendraautorius, vaidmenis, institucijas, ORCID ir, kai įmanoma, ROR.','Išnašos ir galinės pastabos yra semantiniai objektai ir gali turėti formatuotą tekstą bei citatas.','Šaltiniai saugomi kaip struktūriniai bibliografiniai įrašai, gali būti pakartotinai naudojami ir atvaizduojami su CSL.','Vidinės nuorodos rodo į tikslinius objektus, todėl keičiant struktūrą numeravimo nereikia taisyti rankiniu būdu.','Paveikslai, lentelės ir formulės yra struktūriniai moksliniai objektai ir gali būti perduoti į palaikomus eksportus.','Medija pridedama kaip ištekliai; visas OMI paketas gali kartu perkelti failus, rankraštį ir vientisumo duomenis.','Importuojant Word Studio bando antraštes, formatavimą, pastabas, lenteles ir kitas atpažįstamas struktūras paversti OMI elementais.','Iš OJS paleistoje sesijoje rankraštis ir metaduomenys perduodami pagal suteiktus scope, assignment ir teises.','Modelis atskiria rankraštį, review assignment ir recenzento darbą; OJS prieiga susieta su assignment.','Būsenos pokyčiai sekami kaip revizijos; gali būti naudojamas vientisumo digest ir tombstone duomenys.','Profilis atskiria turinį nuo leidėjo taisyklių ir gali apibrėžti puslapį, tipografiją, numeravimą, pastabas, antraštes, metaduomenis ir išvestis.','Individualius leidėjo profilius galima kurti ir versijuoti; apsaugotas profilis keičiamas kuriant naują versiją.','Profilis gali turėti bendrą Export CSS ir atskirą Print/PDF CSS su @page, paraštėmis, puslapių lūžiais ir kitomis spausdinimo taisyklėmis.','Galimi OMI, OMI JSON, JATS XML, semantinis HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB ir PDF per spausdinimą.','Semantinis HTML yra be skriptų. Prieš eksportą Studio tikrina rankraštį pagal aktyvų profilį ir rodo klaidas ar įspėjimus.','Palaikoma vietinė ir konfigūruojama išorinė saugykla; WebDAV/Nextcloud priklauso nuo diegimo ir nustatymų.','Nustatykite, ar problema susijusi su turiniu, struktūra, metaduomenimis, integracija ar vaizdavimu, ir patikrinkite kalbas, profilį bei diagnostiką.'
    ]),
  },
  lv: {
    navigation: 'Palīdzība', title: 'Open Manuscript Studio palīdzība',
    description: 'Studio 0.1.0-alpha.1 pašreizējo manuskripta, recenzēšanas, publicēšanas un eksporta funkciju ceļvedis.',
    gettingStarted: 'Studio rediģē semantisku manuskriptu: virsraksti, sadaļas, piezīmes, citāti, attēli, tabulas, formulas un metadati tiek saglabāti kā strukturēti objekti. Atverot no OJS, dokuments un pieejamie publikācijas dati tiek importēti caur integrāciju.',
    topics: topics([
      '1. Manuskripta rediģēšana un semantiskā formatēšana','2. Sadaļas, hierarhija un numerācija','3. Manuskripta dati, front matter un valodas','4. Līdzautori, institūcijas, ORCID un ROR','5. Piezīmes un citāti piezīmēs','6. Citāti, bibliogrāfija un citēšanas stils','7. Iekšējās atsauces','8. Attēli, tabulas un formulas','9. Multivides faili un OMI pakotne','10. DOCX imports','11. OJS integrācija','12. Recenzēšana','13. Revīzijas, vēsture un integritāte','14. Publicēšanas profili','15. Pielāgoti izdevēja profili un aizsardzība','16. Export CSS un Print/PDF CSS','17. Eksporta formāti','18. HTML un publikācijas pārbaude','19. Mākoņa un failu glabāšana','20. Ja kaut kas netiek attēlots pareizi'
    ],[
      'Rediģējiet tekstu un struktūru galvenajā redaktorā. Studio saglabā rindkopu, virsrakstu un atbalstītā inline formatējuma semantiku.','Sadaļas veido hierarhiju; līmeņus un numerāciju var pārvaldīt aktīvais publicēšanas profils.','Pārvaldiet nosaukumu, apakšnosaukumu, moto, kopsavilkumu, atslēgvārdus, dokumenta valodu un daudzvalodu metadatus.','Pārvaldiet autorus un citus līdzautorus, lomas, institūcijas, ORCID un, ja pieejams, ROR.','Zemsvītras un beigu piezīmes ir semantiski objekti un var saturēt formatētu tekstu un citātus.','Avoti tiek glabāti kā strukturēti bibliogrāfiski ieraksti, tos var izmantot atkārtoti un attēlot ar CSL.','Iekšējās atsauces norāda uz mērķa objektiem, tāpēc pēc struktūras izmaiņām numerācija nav jālabo manuāli.','Attēli, tabulas un formulas ir strukturēti zinātniski objekti un var tikt pārnesti uz atbalstītiem eksporta formātiem.','Multivide tiek piesaistīta kā resursi; pilna OMI pakotne var kopā pārnest failus, manuskriptu un integritātes datus.','Importējot Word, Studio mēģina pārvērst virsrakstus, formatējumu, piezīmes, tabulas un citas atpazīstamas struktūras OMI elementos.','OJS palaistā sesijā manuskripts un metadati tiek pārsūtīti atbilstoši scopes, assignment un tiesībām.','Modelis atdala manuskriptu, review assignment un recenzenta darbu; OJS piekļuve ir piesaistīta assignment.','Stāvokļa izmaiņas tiek izsekotas kā revīzijas; var izmantot integritātes digest un tombstone datus.','Profils atdala saturu no izdevēja noteikumiem un var definēt lapu, tipogrāfiju, numerāciju, piezīmes, parakstus, metadatus un izvades.','Pielāgotus izdevēja profilus var veidot un versijot; aizsargāts profils tiek mainīts, izveidojot jaunu versiju.','Profilā var būt vispārējs Export CSS un atsevišķs Print/PDF CSS ar @page, malām, lapu pārtraukumiem un citiem drukas noteikumiem.','Pieejami OMI, OMI JSON, JATS XML, semantiskais HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB un PDF caur drukāšanu.','Semantiskais HTML ir bez skriptiem. Pirms eksporta Studio validē manuskriptu pret aktīvo profilu un rāda kļūdas vai brīdinājumus.','Atbalstīta lokāla un konfigurējama ārējā glabāšana; WebDAV/Nextcloud ir atkarīgs no instalācijas un iestatījumiem.','Nosakiet, vai problēma skar saturu, struktūru, metadatus, integrāciju vai attēlojumu, un pārbaudiet valodas, profilu un diagnostiku.'
    ]),
  },
  mt: {
    navigation: 'Għajnuna', title: 'Għajnuna ta’ Open Manuscript Studio',
    description: 'Gwida għall-funzjonijiet attwali tal-manuskritt, peer review, pubblikazzjoni u esportazzjoni fi Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio jeditja manuskritt semantiku: titli, sezzjonijiet, noti, ċitazzjonijiet, figuri, tabelli, ekwazzjonijiet u metadata jinżammu bħala oġġetti strutturati. Meta manuskritt jinfetaħ minn OJS, id-dokument u d-data tal-pubblikazzjoni disponibbli jiġu importati permezz tal-integrazzjoni.',
    topics: topics([
      '1. Editjar tal-manuskritt u format semantiku','2. Sezzjonijiet, ġerarkija u numerazzjoni','3. Data tal-manuskritt, front matter u lingwi','4. Kontributuri, istituzzjonijiet, ORCID u ROR','5. Noti u ċitazzjonijiet fin-noti','6. Ċitazzjonijiet, bibljografija u stil ta’ ċitazzjoni','7. Referenzi inkroċjati','8. Figuri, tabelli u ekwazzjonijiet','9. Fajls tal-midja u pakkett OMI','10. Importazzjoni DOCX','11. Integrazzjoni OJS','12. Peer review','13. Reviżjonijiet, storja u integrità','14. Profili ta’ pubblikazzjoni','15. Profili personalizzati tal-pubblikatur u protezzjoni','16. Export CSS u Print/PDF CSS','17. Formati ta’ esportazzjoni','18. HTML u validazzjoni tal-pubblikazzjoni','19. Ħażna cloud u fajls','20. Jekk xi ħaġa ma tidhirx sew'
    ],[
      'Editja t-test u l-istruttura fl-editur ewlieni. Studio jippreserva t-tifsira semantika tal-paragrafi, headings u format inline appoġġjat.','Is-sezzjonijiet jiffurmaw ġerarkija; il-livelli u n-numerazzjoni jistgħu jiġu kkontrollati mill-profil ta’ pubblikazzjoni attiv.','Immaniġġja titlu, sottotitlu, motto, abstract, keywords, lingwa tad-dokument u varjanti multilingwi tal-metadata.','Immaniġġja awturi u kontributuri oħra, rwoli, affiliations, ORCID u, fejn disponibbli, ROR.','Footnotes u endnotes huma oġġetti semantiċi u jistgħu jinkludu test ifformattjat u ċitazzjonijiet.','Is-sorsi jinżammu bħala rekords bibljografiċi strutturati, jistgħu jerġgħu jintużaw u jiġu murija permezz ta’ CSL.','Referenzi interni jindikaw oġġetti fil-mira, għalhekk in-numerazzjoni ma tridx tiġi kkoreġuta manwalment wara bidliet fl-istruttura.','Figuri, tabelli u ekwazzjonijiet huma oġġetti xjentifiċi strutturati u jistgħu jgħaddu għal esportazzjonijiet appoġġjati.','Il-midja tintrabat bħala assets; pakkett OMI sħiħ jista’ jġorr fajls, il-manuskritt u data ta’ integrità flimkien.','Meta timporta Word, Studio jipprova jikkonverti headings, format, noti, tabelli u strutturi oħra rikonoxxibbli f’elementi OMI.','F’sessjoni mnedija minn OJS, il-manuskritt u metadata jiġu trasferiti skont scopes, assignment u permessi mogħtija.','Il-mudell jifred il-manuskritt, review assignment u xogħol tar-reviewer; l-aċċess OJS huwa marbut mal-assignment.','Bidliet fl-istat jiġu segwiti bħala reviżjonijiet u jistgħu jużaw integrity digest u tombstone data.','Il-profil jifred il-kontenut mir-regoli tal-pubblikatur u jista’ jiddefinixxi paġna, tipografija, numerazzjoni, noti, captions, metadata u outputs.','Profili personalizzati jistgħu jinħolqu u jiġu versioned; profil protett jinbidel billi tinħoloq verżjoni ġdida.','Profil jista’ jinkludi Export CSS ġenerali u Print/PDF CSS separat b’@page, margins, page breaks u regoli oħra tal-istampar.','Hemm OMI, OMI JSON, JATS XML, HTML semantiku, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB u PDF permezz tal-istampar.','HTML semantiku huwa bla scripts. Qabel l-esportazzjoni Studio jivvalida l-manuskritt mal-profil attiv u juri żbalji jew twissijiet.','Ħażna lokali u esterna konfigurabbli hija appoġġjata; WebDAV/Nextcloud jiddependi fuq l-installazzjoni u s-settings.','Iddetermina jekk il-problema hijiex fil-kontenut, struttura, metadata, integrazzjoni jew preżentazzjoni u ċċekkja lingwi, profil u dijanjostiċi.'
    ]),
  },
  nl: {
    navigation: 'Help', title: 'Help voor Open Manuscript Studio',
    description: 'Gids voor de huidige functies voor manuscripten, peer review, publicatie en export in Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio bewerkt een semantisch manuscript: koppen, secties, noten, citaties, figuren, tabellen, vergelijkingen en metadata blijven gestructureerde objecten. Wanneer een manuscript vanuit OJS wordt geopend, worden het document en beschikbare publicatiegegevens via de integratie geïmporteerd.',
    topics: topics([
      '1. Manuscript bewerken en semantisch opmaken','2. Secties, hiërarchie en nummering','3. Manuscriptgegevens, front matter en talen','4. Bijdragers, instellingen, ORCID en ROR','5. Noten en citaties in noten','6. Citaties, bibliografie en citatiestijl','7. Kruisverwijzingen','8. Figuren, tabellen en vergelijkingen','9. Mediabestanden en OMI-pakket','10. DOCX-import','11. OJS-integratie','12. Peer review','13. Revisies, geschiedenis en integriteit','14. Publicatieprofielen','15. Aangepaste uitgeversprofielen en bescherming','16. Export CSS en Print/PDF CSS','17. Exportformaten','18. HTML en publicatievalidatie','19. Cloud- en bestandsopslag','20. Als iets niet goed wordt weergegeven'
    ],[
      'Bewerk tekst en structuur in de hoofdbewerker. Studio bewaart de semantische betekenis van alinea’s, koppen en ondersteunde inline-opmaak voor latere uitvoer.','Secties vormen een hiërarchie; niveaus en nummering kunnen door het actieve publicatieprofiel worden beheerd.','Beheer titel, subtitel, motto, samenvatting, trefwoorden, documenttaal en meertalige metadata.','Beheer auteurs en andere bijdragers, rollen, affiliaties, ORCID en, waar beschikbaar, ROR.','Voetnoten en eindnoten zijn semantische objecten en kunnen opgemaakte tekst en citaties bevatten.','Bronnen worden opgeslagen als gestructureerde bibliografische records, kunnen worden hergebruikt en via CSL worden weergegeven.','Interne verwijzingen wijzen naar doelobjecten, zodat nummering na structuurwijzigingen niet handmatig hoeft te worden aangepast.','Figuren, tabellen en vergelijkingen zijn gestructureerde wetenschappelijke objecten die naar ondersteunde uitvoer kunnen worden meegenomen.','Media worden als assets gekoppeld; een volledig OMI-pakket kan bestanden, manuscript en integriteitsgegevens samen vervoeren.','Bij Word-import probeert Studio koppen, opmaak, noten, tabellen en andere herkenbare structuren om te zetten naar OMI-elementen.','In een vanuit OJS gestarte sessie worden manuscript en metadata overgedragen volgens scopes, assignment en rechten.','Het model scheidt manuscript, review assignment en reviewerwerk; OJS-toegang is aan het assignment gekoppeld.','Statuswijzigingen worden als revisies gevolgd en kunnen een integriteitsdigest en tombstone-gegevens bevatten.','Het profiel scheidt inhoud van uitgeversregels en kan pagina, typografie, nummering, noten, bijschriften, metadata en uitvoer definiëren.','Aangepaste uitgeversprofielen kunnen worden gemaakt en geversioneerd; een beschermd profiel wordt gewijzigd via een nieuwe versie.','Een profiel kan algemene Export CSS en aparte Print/PDF CSS bevatten met @page, marges, pagina-einden en andere printregels.','Beschikbaar zijn OMI, OMI JSON, JATS XML, semantische HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB en PDF via afdrukken.','Semantische HTML is scriptvrij. Voor export valideert Studio het manuscript tegen het actieve profiel en toont fouten of waarschuwingen.','Lokale en configureerbare externe opslag wordt ondersteund; WebDAV/Nextcloud hangt af van installatie en instellingen.','Bepaal of het probleem inhoud, structuur, metadata, integratie of presentatie betreft en controleer talen, profiel en diagnostiek.'
    ]),
  },
  pl: {
    navigation: 'Pomoc', title: 'Pomoc Open Manuscript Studio',
    description: 'Przewodnik po bieżących funkcjach manuskryptu, recenzji, publikacji i eksportu w Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio edytuje manuskrypt semantyczny: nagłówki, sekcje, przypisy, cytowania, ryciny, tabele, równania i metadane są zachowywane jako obiekty strukturalne. Po otwarciu z OJS dokument i dostępne dane publikacyjne są importowane przez integrację.',
    topics: topics([
      '1. Edycja manuskryptu i formatowanie semantyczne','2. Sekcje, hierarchia i numeracja','3. Dane manuskryptu, front matter i języki','4. Współtwórcy, instytucje, ORCID i ROR','5. Przypisy i cytowania w przypisach','6. Cytowania, bibliografia i styl cytowań','7. Odsyłacze wewnętrzne','8. Ryciny, tabele i równania','9. Pliki multimedialne i pakiet OMI','10. Import DOCX','11. Integracja OJS','12. Recenzja naukowa','13. Rewizje, historia i integralność','14. Profile publikacyjne','15. Własne profile wydawcy i ochrona','16. Export CSS i Print/PDF CSS','17. Formaty eksportu','18. HTML i walidacja publikacji','19. Przechowywanie w chmurze i plikach','20. Gdy coś nie wygląda prawidłowo'
    ],[
      'Edytuj tekst i strukturę w głównym edytorze. Studio zachowuje semantyczne znaczenie akapitów, nagłówków i obsługiwanego formatowania inline.','Sekcje tworzą hierarchię; poziomy i numeracja mogą być sterowane przez aktywny profil publikacyjny.','Zarządzaj tytułem, podtytułem, mottem, abstraktem, słowami kluczowymi, językiem dokumentu i wielojęzycznymi metadanymi.','Zarządzaj autorami i innymi współtwórcami, rolami, afiliacjami, ORCID oraz, jeśli dostępne, ROR.','Przypisy dolne i końcowe są obiektami semantycznymi i mogą zawierać tekst formatowany oraz cytowania.','Źródła są przechowywane jako strukturalne rekordy bibliograficzne, mogą być używane ponownie i renderowane przez CSL.','Odsyłacze wewnętrzne wskazują na obiekty docelowe, więc po zmianie struktury numeracji nie trzeba poprawiać ręcznie.','Ryciny, tabele i równania są strukturalnymi obiektami naukowymi i mogą przechodzić do obsługiwanych eksportów.','Media są dołączane jako zasoby; pełny pakiet OMI może przenosić pliki, manuskrypt i dane integralności.','Podczas importu Word Studio próbuje przekształcić nagłówki, formatowanie, przypisy, tabele i inne rozpoznawalne struktury w elementy OMI.','W sesji uruchomionej z OJS manuskrypt i metadane są przekazywane zgodnie ze scopes, assignmentem i uprawnieniami.','Model oddziela manuskrypt, review assignment i pracę recenzenta; dostęp OJS jest powiązany z assignmentem.','Zmiany stanu są śledzone jako rewizje; można używać digestu integralności i danych tombstone.','Profil oddziela treść od reguł wydawniczych i może określać stronę, typografię, numerację, przypisy, podpisy, metadane i wyjścia.','Własne profile wydawcy można tworzyć i wersjonować; profil chroniony zmienia się przez utworzenie nowej wersji.','Profil może zawierać ogólny Export CSS i osobny Print/PDF CSS z @page, marginesami, podziałami stron i innymi regułami druku.','Dostępne są OMI, OMI JSON, JATS XML, semantyczny HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB i PDF przez drukowanie.','Semantyczny HTML jest bez skryptów. Przed eksportem Studio waliduje manuskrypt względem aktywnego profilu i pokazuje błędy lub ostrzeżenia.','Obsługiwane jest lokalne i konfigurowalne zewnętrzne przechowywanie; WebDAV/Nextcloud zależy od instalacji i ustawień.','Ustal, czy problem dotyczy treści, struktury, metadanych, integracji czy prezentacji, i sprawdź języki, profil oraz diagnostykę.'
    ]),
  },
  pt: {
    navigation: 'Ajuda', title: 'Ajuda do Open Manuscript Studio',
    description: 'Guia das funções atuais de manuscrito, revisão por pares, publicação e exportação no Studio 0.1.0-alpha.1.',
    gettingStarted: 'O Studio edita um manuscrito semântico: títulos, secções, notas, citações, figuras, tabelas, equações e metadados permanecem como objetos estruturados. Quando um manuscrito é aberto a partir do OJS, o documento e os dados de publicação disponíveis são importados através da integração.',
    topics: topics([
      '1. Edição do manuscrito e formatação semântica','2. Secções, hierarquia e numeração','3. Dados do manuscrito, front matter e idiomas','4. Colaboradores, instituições, ORCID e ROR','5. Notas e citações em notas','6. Citações, bibliografia e estilo de citação','7. Referências cruzadas','8. Figuras, tabelas e equações','9. Ficheiros multimédia e pacote OMI','10. Importação DOCX','11. Integração OJS','12. Revisão por pares','13. Revisões, histórico e integridade','14. Perfis de publicação','15. Perfis de editor personalizados e proteção','16. Export CSS e Print/PDF CSS','17. Formatos de exportação','18. HTML e validação da publicação','19. Armazenamento em cloud e ficheiros','20. Se algo não aparecer corretamente'
    ],[
      'Edite texto e estrutura no editor principal. O Studio preserva o significado de parágrafos, cabeçalhos e formatação inline suportada para saídas posteriores.','As secções formam uma hierarquia; níveis e numeração podem ser controlados pelo perfil de publicação ativo.','Gira título, subtítulo, lema, resumo, palavras-chave, idioma do documento e variantes multilingues de metadados.','Gira autores e outros colaboradores, funções, afiliações, ORCID e, quando disponível, ROR.','Notas de rodapé e finais são objetos semânticos e podem conter texto formatado e citações.','As fontes são guardadas como registos bibliográficos estruturados, reutilizáveis e renderizáveis com CSL.','Referências internas apontam para objetos de destino, evitando correções manuais de numeração após alterações estruturais.','Figuras, tabelas e equações são objetos científicos estruturados que podem ser levados para exportações suportadas.','Os media são anexados como recursos; um pacote OMI completo pode transportar ficheiros, manuscrito e dados de integridade.','Na importação de Word, o Studio tenta converter cabeçalhos, formatação, notas, tabelas e outras estruturas reconhecíveis em elementos OMI.','Numa sessão iniciada pelo OJS, manuscrito e metadados são transferidos de acordo com scopes, assignment e permissões.','O modelo separa manuscrito, review assignment e trabalho do revisor; o acesso OJS está ligado ao assignment.','Alterações de estado são acompanhadas como revisões e podem usar digest de integridade e dados tombstone.','O perfil separa o conteúdo das regras editoriais e pode definir página, tipografia, numeração, notas, legendas, metadados e saídas.','Perfis de editor personalizados podem ser criados e versionados; um perfil protegido é alterado criando uma nova versão.','Um perfil pode incluir Export CSS geral e Print/PDF CSS separado com @page, margens, quebras de página e outras regras de impressão.','Estão disponíveis OMI, OMI JSON, JATS XML, HTML semântico, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB e PDF através da impressão.','O HTML semântico não contém scripts. Antes da exportação, o Studio valida o manuscrito contra o perfil ativo e apresenta erros ou avisos.','É suportado armazenamento local e externo configurável; WebDAV/Nextcloud depende da instalação e das definições.','Determine se o problema é de conteúdo, estrutura, metadados, integração ou apresentação e verifique idiomas, perfil e diagnósticos.'
    ]),
  },
  ro: {
    navigation: 'Ajutor', title: 'Ajutor Open Manuscript Studio',
    description: 'Ghid pentru funcțiile curente de manuscris, peer review, publicare și export din Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio editează un manuscris semantic: titlurile, secțiunile, notele, citările, figurile, tabelele, ecuațiile și metadatele rămân obiecte structurate. La deschiderea din OJS, documentul și datele de publicare disponibile sunt importate prin integrare.',
    topics: topics([
      '1. Editarea manuscrisului și formatarea semantică','2. Secțiuni, ierarhie și numerotare','3. Datele manuscrisului, front matter și limbi','4. Contributori, instituții, ORCID și ROR','5. Note și citări în note','6. Citări, bibliografie și stil de citare','7. Referințe încrucișate','8. Figuri, tabele și ecuații','9. Fișiere media și pachet OMI','10. Import DOCX','11. Integrare OJS','12. Peer review','13. Revizii, istoric și integritate','14. Profiluri de publicare','15. Profiluri personalizate de editor și protecție','16. Export CSS și Print/PDF CSS','17. Formate de export','18. HTML și validarea publicării','19. Stocare cloud și fișiere','20. Dacă ceva nu se afișează corect'
    ],[
      'Editați textul și structura în editorul principal. Studio păstrează sensul semantic al paragrafelor, titlurilor și formatării inline suportate.','Secțiunile formează o ierarhie; nivelurile și numerotarea pot fi controlate de profilul de publicare activ.','Gestionați titlul, subtitlul, motto-ul, rezumatul, cuvintele-cheie, limba documentului și variantele multilingve de metadate.','Gestionați autori și alți contributori, roluri, afilieri, ORCID și, unde este disponibil, ROR.','Notele de subsol și de final sunt obiecte semantice și pot conține text formatat și citări.','Sursele sunt stocate ca înregistrări bibliografice structurate, reutilizabile și randabile prin CSL.','Referințele interne indică obiecte-țintă, astfel încât numerotarea nu trebuie corectată manual după schimbări structurale.','Figurile, tabelele și ecuațiile sunt obiecte științifice structurate și pot fi transferate în exporturile acceptate.','Media este atașată ca resurse; un pachet OMI complet poate transporta fișierele, manuscrisul și datele de integritate.','La importul Word, Studio încearcă să transforme titlurile, formatarea, notele, tabelele și alte structuri recognoscibile în elemente OMI.','Într-o sesiune lansată din OJS, manuscrisul și metadatele se transferă conform scopes, assignment și permisiunilor.','Modelul separă manuscrisul, review assignment și munca recenzorului; accesul OJS este legat de assignment.','Schimbările de stare sunt urmărite ca revizii și pot utiliza digest de integritate și date tombstone.','Profilul separă conținutul de regulile editoriale și poate defini pagina, tipografia, numerotarea, notele, legendele, metadatele și ieșirile.','Profilurile personalizate de editor pot fi create și versionate; un profil protejat se schimbă printr-o versiune nouă.','Un profil poate include Export CSS general și Print/PDF CSS separat cu @page, margini, întreruperi de pagină și alte reguli de tipărire.','Sunt disponibile OMI, OMI JSON, JATS XML, HTML semantic, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB și PDF prin tipărire.','HTML-ul semantic este fără scripturi. Înainte de export, Studio validează manuscrisul față de profilul activ și arată erori sau avertismente.','Este acceptată stocarea locală și externă configurabilă; WebDAV/Nextcloud depinde de instalare și setări.','Stabiliți dacă problema ține de conținut, structură, metadate, integrare sau prezentare și verificați limbile, profilul și diagnosticele.'
    ]),
  },
  sk: {
    navigation: 'Pomoc', title: 'Pomoc Open Manuscript Studio',
    description: 'Sprievodca aktuálnymi funkciami rukopisu, recenzného konania, publikovania a exportu v Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio upravuje sémantický rukopis: nadpisy, sekcie, poznámky, citácie, obrázky, tabuľky, rovnice a metadáta zostávajú štruktúrovanými objektmi. Pri otvorení z OJS sa dokument a dostupné publikačné údaje importujú prostredníctvom integrácie.',
    topics: topics([
      '1. Úprava rukopisu a sémantické formátovanie','2. Sekcie, hierarchia a číslovanie','3. Údaje rukopisu, front matter a jazyky','4. Prispievatelia, inštitúcie, ORCID a ROR','5. Poznámky a citácie v poznámkach','6. Citácie, bibliografia a citačný štýl','7. Krížové odkazy','8. Obrázky, tabuľky a rovnice','9. Mediálne súbory a balík OMI','10. Import DOCX','11. Integrácia OJS','12. Peer review','13. Revízie, história a integrita','14. Publikačné profily','15. Vlastné vydavateľské profily a ochrana','16. Export CSS a Print/PDF CSS','17. Exportné formáty','18. HTML a kontrola publikácie','19. Cloudové a súborové úložisko','20. Ak sa niečo nezobrazuje správne'
    ],[
      'Upravujte text a štruktúru v hlavnom editore. Studio zachováva sémantický význam odsekov, nadpisov a podporovaného inline formátovania.','Sekcie tvoria hierarchiu; úrovne a číslovanie môže riadiť aktívny publikačný profil.','Spravujte názov, podnázov, motto, abstrakt, kľúčové slová, jazyk dokumentu a viacjazyčné varianty metadát.','Spravujte autorov a ďalších prispievateľov, roly, afiliácie, ORCID a, ak je dostupné, ROR.','Poznámky pod čiarou a koncové poznámky sú sémantické objekty a môžu obsahovať formátovaný text a citácie.','Zdroje sú uložené ako štruktúrované bibliografické záznamy, možno ich opakovane používať a zobrazovať cez CSL.','Interné odkazy smerujú na cieľové objekty, takže po zmene štruktúry netreba ručne opravovať číslovanie.','Obrázky, tabuľky a rovnice sú štruktúrované vedecké objekty a možno ich prenášať do podporovaných exportov.','Médiá sú pripojené ako aktíva; úplný OMI balík môže prenášať súbory, rukopis a údaje integrity spolu.','Pri importe Wordu sa Studio pokúša previesť nadpisy, formátovanie, poznámky, tabuľky a ďalšie rozpoznateľné štruktúry na OMI prvky.','V relácii spustenej z OJS sa rukopis a metadáta prenášajú podľa povolených scopes, assignmentu a práv.','Model oddeľuje rukopis, review assignment a prácu recenzenta; prístup OJS je viazaný na assignment.','Zmeny stavu sa sledujú ako revízie; možno použiť integrity digest a tombstone údaje.','Profil oddeľuje obsah od vydavateľských pravidiel a môže definovať stránku, typografiu, číslovanie, poznámky, popisy, metadáta a výstupy.','Vlastné vydavateľské profily možno vytvárať a verzovať; chránený profil sa mení novou verziou.','Profil môže obsahovať všeobecný Export CSS a samostatný Print/PDF CSS s @page, okrajmi, zlomami strán a ďalšími pravidlami tlače.','Dostupné sú OMI, OMI JSON, JATS XML, sémantické HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB a PDF cez tlač.','Sémantické HTML je bez skriptov. Pred exportom Studio overuje rukopis oproti aktívnemu profilu a zobrazuje chyby alebo upozornenia.','Podporované je lokálne aj konfigurovateľné externé úložisko; WebDAV/Nextcloud závisí od inštalácie a nastavení.','Určte, či problém súvisí s obsahom, štruktúrou, metadátami, integráciou alebo vzhľadom, a skontrolujte jazyky, profil a diagnostiku.'
    ]),
  },
  sl: {
    navigation: 'Pomoč', title: 'Pomoč za Open Manuscript Studio',
    description: 'Vodnik po trenutnih funkcijah rokopisa, recenziranja, objave in izvoza v Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio ureja semantični rokopis: naslovi, razdelki, opombe, citati, slike, tabele, enačbe in metapodatki ostanejo strukturirani objekti. Ko je rokopis odprt iz OJS, se dokument in razpoložljivi publikacijski podatki uvozijo prek integracije.',
    topics: topics([
      '1. Urejanje rokopisa in semantično oblikovanje','2. Razdelki, hierarhija in številčenje','3. Podatki rokopisa, front matter in jeziki','4. Sodelavci, ustanove, ORCID in ROR','5. Opombe in citati v opombah','6. Citati, bibliografija in slog citiranja','7. Navzkrižne sklice','8. Slike, tabele in enačbe','9. Predstavnostne datoteke in paket OMI','10. Uvoz DOCX','11. Integracija OJS','12. Recenziranje','13. Revizije, zgodovina in integriteta','14. Publikacijski profili','15. Lastni založniški profili in zaščita','16. Export CSS in Print/PDF CSS','17. Izvozni formati','18. HTML in preverjanje publikacije','19. Oblak in shranjevanje datotek','20. Če nekaj ni prikazano pravilno'
    ],[
      'Urejajte besedilo in strukturo v glavnem urejevalniku. Studio ohranja semantični pomen odstavkov, naslovov in podprtega oblikovanja.','Razdelki tvorijo hierarhijo; ravni in številčenje lahko določa aktivni publikacijski profil.','Upravljajte naslov, podnaslov, moto, izvleček, ključne besede, jezik dokumenta in večjezične metapodatke.','Upravljajte avtorje in druge sodelavce, vloge, afiliacije, ORCID in, kjer je na voljo, ROR.','Sprotne in končne opombe so semantični objekti in lahko vsebujejo oblikovano besedilo ter citate.','Viri so shranjeni kot strukturirani bibliografski zapisi, jih je mogoče ponovno uporabiti in prikazati prek CSL.','Notranji sklici kažejo na ciljne objekte, zato številčenja po spremembah strukture ni treba ročno popravljati.','Slike, tabele in enačbe so strukturirani znanstveni objekti, ki se lahko prenesejo v podprte izvoze.','Mediji so priloženi kot sredstva; celoten paket OMI lahko prenese datoteke, rokopis in podatke o integriteti.','Pri uvozu Worda Studio poskuša naslove, oblikovanje, opombe, tabele in druge prepoznavne strukture pretvoriti v elemente OMI.','V seji, zagnani iz OJS, se rokopis in metapodatki prenašajo glede na scopes, assignment in dovoljenja.','Model ločuje rokopis, review assignment in delo recenzenta; dostop OJS je vezan na assignment.','Spremembe stanja se spremljajo kot revizije; uporabiti je mogoče integrity digest in tombstone podatke.','Profil ločuje vsebino od založniških pravil in lahko opredeli stran, tipografijo, številčenje, opombe, napise, metapodatke in izhode.','Lastne založniške profile je mogoče ustvarjati in različicati; zaščiten profil se spremeni z novo različico.','Profil lahko vsebuje splošni Export CSS in ločeni Print/PDF CSS z @page, robovi, prelomi strani in drugimi pravili tiskanja.','Na voljo so OMI, OMI JSON, JATS XML, semantični HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB in PDF prek tiskanja.','Semantični HTML je brez skriptov. Pred izvozom Studio preveri rokopis glede na aktivni profil in prikaže napake ali opozorila.','Podprto je lokalno in nastavljivo zunanje shranjevanje; WebDAV/Nextcloud je odvisen od namestitve in nastavitev.','Ugotovite, ali težava zadeva vsebino, strukturo, metapodatke, integracijo ali prikaz, ter preverite jezike, profil in diagnostiko.'
    ]),
  },
  sv: {
    navigation: 'Hjälp', title: 'Hjälp för Open Manuscript Studio',
    description: 'Guide till de aktuella manuskript-, peer review-, publicerings- och exportfunktionerna i Studio 0.1.0-alpha.1.',
    gettingStarted: 'Studio redigerar ett semantiskt manuskript: rubriker, avsnitt, noter, citat, figurer, tabeller, ekvationer och metadata bevaras som strukturerade objekt. När ett manuskript öppnas från OJS importeras dokumentet och tillgängliga publikationsdata via integrationen.',
    topics: topics([
      '1. Manuskriptredigering och semantisk formatering','2. Avsnitt, hierarki och numrering','3. Manuskriptdata, front matter och språk','4. Medverkande, institutioner, ORCID och ROR','5. Noter och citat i noter','6. Citat, bibliografi och citeringsstil','7. Korsreferenser','8. Figurer, tabeller och ekvationer','9. Mediefiler och OMI-paket','10. DOCX-import','11. OJS-integration','12. Peer review','13. Revisioner, historik och integritet','14. Publikationsprofiler','15. Egna förlagsprofiler och skydd','16. Export CSS och Print/PDF CSS','17. Exportformat','18. HTML och publiceringsvalidering','19. Moln- och fillagring','20. Om något inte visas korrekt'
    ],[
      'Redigera text och struktur i huvudredigeraren. Studio bevarar den semantiska betydelsen av stycken, rubriker och stödd inline-formatering.','Avsnitt bildar en hierarki; nivåer och numrering kan styras av den aktiva publikationsprofilen.','Hantera titel, undertitel, motto, sammanfattning, nyckelord, dokumentspråk och flerspråkiga metadata.','Hantera författare och andra medverkande, roller, affilieringar, ORCID och, där det finns tillgängligt, ROR.','Fotnoter och slutnoter är semantiska objekt och kan innehålla formaterad text och citat.','Källor lagras som strukturerade bibliografiska poster, kan återanvändas och renderas med CSL.','Interna referenser pekar på målobjekt, så numreringen behöver inte rättas manuellt när strukturen ändras.','Figurer, tabeller och ekvationer är strukturerade vetenskapliga objekt som kan följa med till stödda exportformat.','Media kopplas som tillgångar; ett komplett OMI-paket kan bära filer, manuskript och integritetsdata tillsammans.','Vid Word-import försöker Studio omvandla rubriker, formatering, noter, tabeller och andra igenkännbara strukturer till OMI-element.','I en session som startas från OJS överförs manuskript och metadata enligt beviljade scopes, assignment och rättigheter.','Modellen skiljer manuskript, review assignment och granskarens arbete; OJS-åtkomsten är knuten till assignmentet.','Tillståndsändringar spåras som revisioner och kan använda integritetsdigest och tombstone-data.','Profilen skiljer innehåll från förlagsregler och kan definiera sida, typografi, numrering, noter, bildtexter, metadata och utdata.','Egna förlagsprofiler kan skapas och versionshanteras; en skyddad profil ändras genom att skapa en ny version.','En profil kan innehålla generell Export CSS och separat Print/PDF CSS med @page, marginaler, sidbrytningar och andra utskriftsregler.','Tillgängligt är OMI, OMI JSON, JATS XML, semantisk HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB och PDF via utskrift.','Semantisk HTML är skriptfri. Före export validerar Studio manuskriptet mot den aktiva profilen och visar fel eller varningar.','Lokal och konfigurerbar extern lagring stöds; WebDAV/Nextcloud beror på installation och inställningar.','Avgör om problemet gäller innehåll, struktur, metadata, integration eller presentation och kontrollera språk, profil och diagnostik.'
    ]),
  },
};

export function getAdditionalHelpCopy(locale: string): HelpCopy | null {
  return Object.prototype.hasOwnProperty.call(extra, locale)
    ? extra[locale as ExtraHelpLocale]
    : null;
}
