import type { HelpCopy } from './help';

type Locale = 'et' | 'fi' | 'ga';
const common: Record<Locale, string[]> = {
 et:['Kasuta pealkirjatasemeid struktuuri, mitte ainult välimuse jaoks.','Kontrolli tulemust sihtvormingus.'],
 fi:['Käytä otsikkotasoja rakenteeseen, älä vain ulkoasuun.','Tarkista tulos kohdemuodossa.'],
 ga:['Úsáid leibhéil ceannteidil don struchtúr, ní don chuma amháin.','Seiceáil an toradh san fhormáid sprice.'],
};
const specific: Record<Locale,string[]> = {
 et:['Ära nummerda jaotisi käsitsi.','Täida metaandmed kõigis vajalikes keeltes.','Kasuta ORCIDi autoritele ja RORi asutustele.','Kasuta struktureeritud viiteid ka märkustes.','Paranda allikaandmed bibliograafiakirjes.','Viita sihtobjektile, mitte käsitsi numbrile.','Lisa joonistele pealkiri ja alternatiivtekst.','Säilita originaalsed meediafailid.','Kasuta enne DOCX-importi järjekindlalt Wordi laade.','Kontrolli enne tagasikirjutamist õiget OJS submissionit.','Testi double-blind anonüümsust tegeliku retsendikontoga.','Loo enne allkirjastamist selge revisjon ja kontrolli digestit.','Vali enne lõplikku eksporti õige avaldamisprofiil.','Versioonihalda ja kaitse kinnitatud kirjastajaprofiile.','Hoia Export CSS ja Print/PDF CSS rollid eraldi.','Arhiveeri OMI koos levitamisvorminguga.','Paranda valideerimisvead enne hoiatusi.','Hoia vähemalt üks sõltumatu varukoopia ja testi taastamist.','Kirjelda vea täpsed kordamise sammud.'],
 fi:['Älä numeroi osia käsin.','Täytä metatiedot kaikilla tarvittavilla kielillä.','Käytä ORCIDia tekijöille ja RORia organisaatioille.','Käytä rakenteisia lähdeviitteitä myös alaviitteissä.','Korjaa lähdetiedot bibliografisessa tietueessa.','Viittaa kohdeobjektiin, älä käsin kirjoitettuun numeroon.','Lisää kuvateksti ja vaihtoehtoinen teksti.','Säilytä alkuperäiset mediatiedostot.','Käytä Word-tyylejä johdonmukaisesti ennen DOCX-tuontia.','Tarkista oikea OJS submission ennen takaisin kirjoittamista.','Testaa double-blind-anonymisointi oikealla arvioijatilillä.','Luo selkeä revisio ennen allekirjoitusta ja tarkista digest.','Valitse oikea julkaisuprofiili ennen lopullista vientiä.','Versioi ja suojaa hyväksytyt kustantajaprofiilit.','Pidä Export CSS ja Print/PDF CSS erillisinä kerroksina.','Arkistoi OMI jakeluformaatin rinnalla.','Korjaa validointivirheet ennen varoituksia.','Pidä vähintään yksi riippumaton varmuuskopio ja testaa palautus.','Kirjaa ongelman tarkat toistovaiheet.'],
 ga:['Ná cuir uimhreacha rannán isteach de láimh.','Líon na meiteashonraí sna teangacha riachtanacha uile.','Úsáid ORCID d’údair agus ROR d’eagraíochtaí.','Úsáid tagairtí struchtúrtha sna nótaí freisin.','Ceartaigh sonraí na foinse sa taifead bibleagrafaíoch.','Déan tagairt don sprioc-réad, ní d’uimhir lámhscríofa.','Cuir fotheideal agus téacs malartach le figiúirí.','Coinnigh na bunchomhaid meán.','Úsáid stíleanna Word go comhsheasmhach roimh iompórtáil DOCX.','Deimhnigh an OJS submission ceart roimh scríobh ar ais.','Tástáil anaithnideacht double-blind le fíorchuntas athbhreithneora.','Cruthaigh revision shoiléir roimh shíniú agus seiceáil an digest.','Roghnaigh an phróifíl fhoilsitheoireachta cheart roimh an easpórtáil deiridh.','Leaganraigh agus cosain próifílí foilsitheora ceadaithe.','Coinnigh róil Export CSS agus Print/PDF CSS ar leith.','Cartlannaigh OMI in éineacht leis an bhformáid dáilte.','Ceartaigh earráidí bailíochtaithe roimh rabhaidh.','Coinnigh cúltaca neamhspleách amháin ar a laghad agus tástáil athchóiriú.','Taifead na céimeanna beachta chun an fhadhb a atáirgeadh.'],
};
export function applyEtFiGaHelpQuality(locale: Locale, copy: HelpCopy): HelpCopy {
 let s=0;
 return {...copy,topics:copy.topics.map((topic,index)=>index<20?{...topic,tips:index===0?[common[locale][0],common[locale][1]]:[specific[locale][s++] ?? common[locale][0], common[locale][1]]}:topic)};
}
