import type { HelpCopy } from './help';

type Topic = { title: string; body: string; tips?: string[] };
const make = (navigation: string, title: string, description: string, gettingStarted: string, rows: Array<[string,string,string,string]>): HelpCopy => ({ navigation, title, description, gettingStarted, topics: rows.map(([title,body,a,b]): Topic => ({title,body,tips:[a,b]})) });

export const danishHelp = make('Hjælp','Hjælp til Open Manuscript Studio','Detaljeret vejledning til manuskript, peer review, publicering, signaturer og eksport i Studio 0.1.0-alpha.1.','Studio behandler manuskriptet som strukturerede videnskabelige data. Brug semantiske elementer frem for visuel formatering, så indholdet kan genbruges på tværs af publiceringsformater.',[
['1. Manuskriptredigering og semantisk formatering','Redigér brødtekst, overskrifter og inline-formatering i hovededitoren. Strukturen bevares semantisk og kan derfor eksporteres konsistent.','Brug overskriftsniveauer til struktur, ikke kun til udseende.','Kontrollér strukturen før den endelige eksport.'],
['2. Afsnit, hierarki og nummerering','Afsnit danner et hierarki, og publikationsprofilen kan styre deres nummerering og visning.','Flyt afsnit som strukturelle enheder.','Undgå manuel nummerering i selve overskriftsteksten.'],
['3. Manuskriptdata, front matter og sprog','Titel, undertitel, resumé, nøgleord og flersprogede metadata administreres separat fra brødteksten.','Udfyld metadata på alle relevante sprog.','Kontrollér dokumentets primære sprog før publicering.'],
['4. Bidragydere, ORCID og ROR','Forfattere og andre bidragydere kan have roller, institutioner, ORCID og ROR-identifikatorer.','Brug ORCID til entydig forfatteridentifikation.','Brug ROR, når institutionen kan identificeres entydigt.'],
['5. Noter og citater i noter','Fodnoter og slutnoter er semantiske objekter og kan indeholde formateret tekst og bibliografiske citater.','Indsæt noter med noteværktøjet.','Brug strukturerede citater også inde i noter.'],
['6. Citater, bibliografi og citationsstil','Bibliografiske poster kan genbruges, og CSL styrer visningen. Egne navngivne citationsstile kan gemmes.','Ret kildedata i posten frem for den formaterede tekst.','Vælg eller gem citationsstil før slutkontrol.'],
['7. Krydshenvisninger','Krydshenvisninger peger på dokumentobjekter og følger derfor ændringer i nummerering.','Henvis til målobjektet, ikke et manuelt nummer.','Kontrollér brudte henvisninger efter større strukturændringer.'],
['8. Figurer, tabeller og ligninger','Figurer, tabeller og ligninger bevares som strukturerede videnskabelige objekter med tilhørende metadata.','Tilføj billedtekst og alternativ tekst til figurer.','Kontrollér tabeller og formler i målformatet.'],
['9. Mediefiler og OMI-pakke','Mediefiler er manuskriptaktiver. En fuld OMI-pakke kan transportere manuskript, aktiver og integritetsdata samlet.','Bevar originale mediefiler.','Brug OMI-pakken, når hele projektet skal flyttes.'],
['10. DOCX-import','DOCX-import forsøger at omsætte Word-overskrifter, formatering, noter, tabeller og andre genkendelige strukturer til OMI-elementer.','Brug Word-typografier konsekvent før import.','Gennemgå overskrifter og noter efter import.'],
['11. OJS-integration','Når Studio startes fra OJS, udveksles manuskript og tilladte metadata efter sessionens scopes, assignment og rettigheder.','Kontrollér den aktuelle OJS-submission før tilbageskrivning.','Rapportér integrationsfejl med submission- og assignment-kontekst.'],
['12. Peer review','Reviewer-adgang er knyttet til en konkret assignment, og review-visningen skal kun vise det materiale, som rollen må se.','Brug reviewer-kontoen til reel adgangstest.','Kontrollér anonymisering ved double-blind review.'],
['13. Revisioner, historik og integritet','Ændringer kan knyttes til revisioner og integritets-digests, så en bestemt dokumenttilstand kan identificeres præcist.','Opret en klar revision før signering.','Sammenlign digest, hvis dokumentintegriteten er tvivlsom.'],
['14. Publikationsprofiler','Publikationsprofiler adskiller indhold fra udgiverens regler for side, typografi, nummerering, noter, metadata og output.','Vælg profil før sluteksport.','Hold indholdskorrektioner adskilt fra layoutregler.'],
['15. Egne udgiverprofiler og beskyttelse','En udgiver kan gemme egne profiler med navn og logo. Beskyttede profiler ændres gennem en ny version efter passende identifikation.','Versionér ændringer i produktionsprofiler.','Beskyt godkendte profiler mod utilsigtet redigering.'],
['16. Export CSS og Print/PDF CSS','Profilen kan indeholde generel Export CSS og separat Print/PDF CSS med @page, marginer og sideskift.','Hold skærm- og printregler adskilt.','Test PDF-resultatet i den anvendte printmotor.'],
['17. Eksportformater','Studio understøtter OMI, OMI JSON, JATS XML, semantisk HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB og et printbaseret PDF-flow.','Vælg format efter næste led i arbejdsgangen.','Arkivér OMI sammen med distributionsformatet.'],
['18. HTML og publiceringskontrol','Semantisk HTML eksporteres uden scripts. Studio validerer dokumentet mod den aktive profil før publicering.','Ret fejl før advarsler.','Kontrollér HTML-strukturen, ikke kun udseendet.'],
['19. Lagring og sikkerhedskopiering','Lokale og konfigurerbare eksterne lagre kan anvendes; WebDAV/Nextcloud afhænger af installationens konfiguration.','Bevar mindst én uafhængig sikkerhedskopi.','Test gendannelse, ikke kun sikkerhedskopiering.'],
['20. Fejlfinding','Afgør først, om problemet vedrører indhold, struktur, metadata, integration, eksport eller visning.','Notér de præcise trin, der udløser fejlen.','Kontrollér aktivt sprog og publikationsprofil.'],
['21. Kryptografiske forfattersignaturer','En registreret forfatter kan efter sikker identifikation knytte en WebAuthn/passkey-nøgle til sin ORCID-identitet og signere en bestemt manuskriptrevision kryptografisk.','Signér først den revision, der faktisk skal godkendes.','Efter indholdsændringer skal den nye revision signeres igen.']
]);

export const swedishHelp = make('Hjälp','Hjälp för Open Manuscript Studio','Detaljerad vägledning för manuskript, peer review, publicering, signaturer och export i Studio 0.1.0-alpha.1.','Studio behandlar manuskriptet som strukturerade vetenskapliga data. Använd semantiska element i stället för enbart visuell formatering så att innehållet kan återanvändas i olika publiceringsformat.',[
['1. Manuskriptredigering och semantisk formatering','Redigera brödtext, rubriker och inline-formatering i huvudredigeraren. Den semantiska strukturen bevaras så att samma innehåll kan exporteras konsekvent till olika publiceringsformat.','Använd rubriknivåer för struktur, inte bara för utseende.','Kontrollera dokumentstrukturen före slutlig export.'],
['2. Avsnitt, hierarki och numrering','Avsnitten bildar en dokumenthierarki, och den aktiva publikationsprofilen kan styra både automatisk numrering och hur nivåerna presenteras i olika utdataformat.','Flytta avsnitt som kompletta strukturella enheter.','Undvik manuell numrering direkt i rubriktexten.'],
['3. Manuskriptdata, front matter och språk','Titel, undertitel, abstract, nyckelord och flerspråkiga metadata hanteras separat från brödtexten så att de kan återanvändas korrekt vid publicering och export.','Fyll i metadata på alla språk som publikationen kräver.','Kontrollera dokumentets huvudspråk före publicering.'],
['4. Medverkande, ORCID och ROR','Författare och andra medverkande kan registreras med roller, affilieringar samt beständiga ORCID- och ROR-identifierare, vilket skiljer person- och organisationsidentitet från visningsnamn.','Använd ORCID för entydig författaridentifikation.','Använd ROR när en institution kan identifieras entydigt.'],
['5. Noter och citeringar i noter','Fotnoter och slutnoter är semantiska dokumentobjekt som kan innehålla formaterad text, bibliografiska citeringar och andra strukturer utan att reduceras till vanlig brödtext.','Skapa noter med det särskilda notverktyget.','Använd strukturerade citeringar även inne i noter.'],
['6. Citeringar, bibliografi och citeringsstil','Bibliografiska poster lagras som återanvändbara källdata medan CSL styr presentationen. Egna namngivna citeringsstilar kan sparas och återanvändas utan att källposterna ändras.','Korrigera bibliografiska fakta i källposten, inte i den renderade texten.','Välj eller spara citeringsstil före den slutliga kontrollen.'],
['7. Korsreferenser','Korsreferenser pekar på stabila dokumentobjekt i stället för manuellt skrivna nummer och kan därför följa ändringar i avsnitts-, figur-, tabell- och annan härledd numrering.','Referera till målobjektet i stället för ett manuellt nummer.','Kontrollera brutna referenser efter större strukturändringar.'],
['8. Figurer, tabeller och ekvationer','Figurer, tabeller och ekvationer bevaras som strukturerade vetenskapliga objekt med egna metadata, vilket gör att de kan renderas och exporteras på ett formatspecifikt men semantiskt konsekvent sätt.','Lägg till bildtext och alternativtext till figurer.','Kontrollera tabeller och formler i det slutliga målformatet.'],
['9. Mediefiler och OMI-paket','Mediefiler hanteras som manuskripttillgångar. Ett komplett OMI-paket kan transportera manuskriptets strukturerade data, tillhörande filer och integritetsinformation tillsammans.','Bevara originalfilerna även när förhandsvisningar skapas.','Använd OMI-paketet när hela projektet ska flyttas eller arkiveras.'],
['10. DOCX-import','DOCX-importen försöker omvandla Word-rubriker, teckenformatering, noter, tabeller och andra igenkännbara strukturer till motsvarande OMI-element i stället för att platta ut dokumentet.','Använd Word-formatmallar konsekvent före import.','Granska särskilt rubriker, noter och tabeller efter import.'],
['11. OJS-integration','När Studio startas från OJS utbyts manuskript och tillåtna metadata enligt sessionens scopes, aktuell assignment och användarens rättigheter, så att integrationen respekterar det redaktionella sammanhanget.','Kontrollera aktuell OJS-submission innan data skrivs tillbaka.','Rapportera integrationsfel tillsammans med submission- och assignment-kontext.'],
['12. Peer review','Granskaråtkomst är bunden till en konkret review-assignment, och granskningsvyn ska endast exponera det material och de identitetsuppgifter som den aktuella rollen har rätt att se.','Testa arbetsflödet med ett verkligt granskar-konto.','Kontrollera anonymisering särskilt vid double-blind peer review.'],
['13. Revisioner, historik och integritet','Ändringar kan bindas till identifierbara revisioner och integritets-digests så att ett exakt dokumenttillstånd kan verifieras och senare skiljas från efterföljande redigeringar.','Skapa en tydlig revision innan dokumentet signeras.','Jämför digest-värden om dokumentets integritet behöver verifieras.'],
['14. Publikationsprofiler','Publikationsprofiler skiljer det vetenskapliga innehållet från utgivarens regler för sidformat, typografi, numrering, noter, metadata och utdata, vilket gör samma manuskript återanvändbart.','Välj rätt profil före slutexporten.','Håll innehållskorrigeringar åtskilda från layout- och presentationsregler.'],
['15. Egna utgivarprofiler och skydd','En utgivare kan spara egna namngivna profiler med logotyp och produktionsregler. En skyddad profilversion görs skrivskyddad och ändringar sker genom en ny version efter lämplig identifiering.','Versionshantera ändringar i profiler som används i produktion.','Skydda godkända profiler mot oavsiktlig redigering.'],
['16. Export CSS och Print/PDF CSS','En utgivarprofil kan innehålla generell Export CSS och separat Print/PDF CSS, inklusive regler för @page, marginaler, sidbrytningar och andra utskriftsspecifika presentationsegenskaper.','Separera generella exportregler från regler som bara gäller utskrift.','Testa PDF-resultatet i den printmotor som faktiskt används i produktion.'],
['17. Exportformat','Studio stöder OMI, OMI JSON, JATS XML, semantisk HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX och EPUB samt ett utskriftsbaserat PDF-flöde för publiceringsanpassad produktion.','Välj exportformat efter nästa steg i publiceringskedjan.','Arkivera OMI tillsammans med det format som distribueras.'],
['18. HTML och publiceringskontroll','Semantisk HTML exporteras utan aktiva skript. Före publicering kan Studio validera dokumentets struktur och krav mot den aktiva publikationsprofilen och rapportera fel och varningar.','Åtgärda valideringsfel innan mindre varningar behandlas.','Kontrollera HTML-strukturen och semantiken, inte bara det visuella resultatet.'],
['19. Lagring och säkerhetskopiering','Studio kan använda lokala och konfigurerbara externa lagringsmål; stöd för exempelvis WebDAV eller Nextcloud beror på installationens konfiguration och ersätter inte en oberoende backupstrategi.','Behåll minst en oberoende säkerhetskopia av viktiga manuskript.','Testa regelbundet att säkerhetskopior faktiskt går att återställa.'],
['20. Felsökning','Avgör först om problemet gäller innehåll, dokumentstruktur, metadata, integration, export eller presentation. En tydlig avgränsning gör loggar och reproduktionssteg betydligt mer användbara.','Dokumentera de exakta steg som utlöser felet.','Kontrollera aktivt språk, publikationsprofil och relevant användarroll.'],
['21. Kryptografiska författarsignaturer','En registrerad författare kan efter säker identifiering knyta en WebAuthn/passkey-nyckel till sin ORCID-identitet och kryptografiskt signera en bestämd manuskriptrevision, så att signaturen avser ett exakt dokumenttillstånd.','Signera endast den revision som faktiskt ska godkännas eller lämnas vidare.','Efter en innehållsändring måste den nya revisionen signeras på nytt.']
]);