import type { HelpCopy, HelpTopic } from './help';

const directSubmissionTopic: Record<string, HelpTopic> = {
  bg: { title: 'Директно изпращане към OJS и OMP', body: 'В изгледа Publication самостоятелно OMI изследване може да бъде изпратено директно към конфигурирано OJS списание или OMP издателство. Studio създава отдалечена чернова, прехвърля метаданните и изходните DOCX и OMI файлове и изпълнява проверката на PKP преди окончателното изпращане.', tips: ['Проверете целевата секция на OJS или серията на OMP преди подготовката.', 'При прекъсване повторете подготовката: Studio използва съществуващата чернова и избягва дублирането.', 'Отстранете всички грешки от отдалечената проверка преди окончателно изпращане.'] },
  cs: { title: 'Přímé odeslání do OJS a OMP', body: 'V zobrazení Publication lze samostatnou studii OMI odeslat přímo do nakonfigurovaného časopisu OJS nebo nakladatelství OMP. Studio vytvoří vzdálený koncept, přenese metadata a zdrojové soubory DOCX i OMI a před konečným odesláním spustí validaci systému PKP.', tips: ['Před přípravou zkontrolujte cílovou sekci OJS nebo sérii OMP.', 'Po přerušení přípravu zopakujte; Studio znovu použije existující koncept a zabrání duplicitám.', 'Před konečným odesláním opravte všechny chyby vzdálené validace.'] },
  da: { title: 'Direkte indsendelse til OJS og OMP', body: 'I visningen Publication kan et selvstændigt OMI-studie indsendes direkte til et konfigureret OJS-tidsskrift eller en OMP-presse. Studio opretter et eksternt kladdeindlæg, overfører metadata samt DOCX- og OMI-kildefiler og kører PKP-validering før den endelige indsendelse.', tips: ['Kontrollér OJS-sektionen eller OMP-serien før kladden forberedes.', 'Efter en afbrydelse kan forberedelsen gentages; den eksisterende kladde genbruges.', 'Ret alle eksterne valideringsfejl før den endelige indsendelse.'] },
  de: { title: 'Direkte Einreichung an OJS und OMP', body: 'In der Ansicht Publikation kann eine eigenständige OMI-Studie direkt an eine konfigurierte OJS-Zeitschrift oder OMP-Publikationsplattform übermittelt werden. Studio legt einen entfernten Entwurf an, überträgt Metadaten sowie DOCX- und OMI-Quelldateien und führt vor der endgültigen Einreichung die PKP-Validierung aus.', tips: ['Prüfen Sie vor der Vorbereitung die OJS-Rubrik bzw. die OMP-Reihe.', 'Nach einer Unterbrechung kann die Vorbereitung fortgesetzt werden; der vorhandene Entwurf wird wiederverwendet.', 'Beheben Sie alle entfernten Validierungsfehler vor der endgültigen Einreichung.'] },
  el: { title: 'Άμεση υποβολή σε OJS και OMP', body: 'Στην προβολή Publication μια αυτοτελής μελέτη OMI μπορεί να υποβληθεί απευθείας σε ρυθμισμένο περιοδικό OJS ή εκδοτική εγκατάσταση OMP. Το Studio δημιουργεί απομακρυσμένο προσχέδιο, μεταφέρει μεταδεδομένα και τα αρχεία προέλευσης DOCX και OMI και εκτελεί την επικύρωση PKP πριν από την τελική υποβολή.', tips: ['Ελέγξτε την ενότητα OJS ή τη σειρά OMP πριν από την προετοιμασία.', 'Μετά από διακοπή επαναλάβετε την προετοιμασία· το υπάρχον προσχέδιο επαναχρησιμοποιείται.', 'Διορθώστε όλα τα σφάλματα απομακρυσμένης επικύρωσης πριν από την τελική υποβολή.'] },
  en: { title: 'Direct submission to OJS and OMP', body: 'From Publication, an open standalone OMI study can be submitted directly to a configured OJS journal or OMP press. Studio creates a native remote draft, transfers the reviewed metadata plus DOCX and OMI source files, and asks the PKP destination to validate the draft before final submission.', tips: ['Check the target OJS section or OMP series before preparing the draft.', 'If preparation is interrupted, retry it: Studio reuses the existing remote draft and avoids duplicate submissions or files.', 'Resolve every remote validation error before final submission.'] },
  es: { title: 'Envío directo a OJS y OMP', body: 'Desde Publicación, un estudio OMI independiente puede enviarse directamente a una revista OJS o una editorial OMP configurada. Studio crea un borrador remoto nativo, transfiere los metadatos revisados y los archivos fuente DOCX y OMI, y solicita al destino PKP que valide el borrador antes del envío definitivo.', tips: ['Revise la sección OJS o la serie OMP de destino antes de preparar el borrador.', 'Si la preparación se interrumpe, repítala: Studio reutiliza el borrador existente y evita duplicados.', 'Corrija todos los errores de validación remota antes del envío definitivo.'] },
  et: { title: 'Otseedastus OJS-i ja OMP-sse', body: 'Publication-vaates saab avatud iseseisva OMI uurimuse saata otse seadistatud OJS-ajakirja või OMP kirjastusse. Studio loob kaugkeskkonnas mustandi, edastab kontrollitud metaandmed ning DOCX- ja OMI-lähtefailid ja käivitab enne lõplikku esitamist PKP valideerimise.', tips: ['Kontrollige enne ettevalmistamist OJS-i jaotist või OMP sarja.', 'Katkestuse järel korrake ettevalmistust; Studio kasutab olemasolevat mustandit ega loo duplikaate.', 'Parandage kõik kaugvalideerimise vead enne lõplikku esitamist.'] },
  fi: { title: 'Suora lähetys OJS:ään ja OMP:hen', body: 'Publication-näkymästä avoin itsenäinen OMI-tutkimus voidaan lähettää suoraan määritettyyn OJS-lehteen tai OMP-julkaisualustaan. Studio luo etäluonnoksen, siirtää tarkistetut metatiedot sekä DOCX- ja OMI-lähdetiedostot ja suorittaa PKP-validoinnin ennen lopullista lähetystä.', tips: ['Tarkista OJS-osasto tai OMP-sarja ennen luonnoksen valmistelua.', 'Jos valmistelu keskeytyy, yritä uudelleen; Studio käyttää olemassa olevaa luonnosta eikä tee kaksoiskappaleita.', 'Korjaa kaikki etävalidoinnin virheet ennen lopullista lähetystä.'] },
  fr: { title: 'Soumission directe vers OJS et OMP', body: 'Depuis Publication, une étude OMI autonome ouverte peut être soumise directement à une revue OJS ou à une presse OMP configurée. Studio crée un brouillon distant natif, transfère les métadonnées vérifiées ainsi que les fichiers source DOCX et OMI, puis demande au système PKP de valider le brouillon avant la soumission finale.', tips: ['Vérifiez la rubrique OJS ou la série OMP cible avant de préparer le brouillon.', 'Après une interruption, relancez la préparation : le brouillon existant est réutilisé et les doublons sont évités.', 'Corrigez toutes les erreurs de validation distante avant la soumission finale.'] },
  ga: { title: 'Aighneacht dhíreach chuig OJS agus OMP', body: 'Ó Publication is féidir staidéar OMI neamhspleách atá oscailte a chur go díreach chuig iris OJS nó preas OMP atá cumraithe. Cruthaíonn Studio dréacht cianda, aistríonn sé na meiteashonraí athbhreithnithe agus na comhaid fhoinse DOCX agus OMI, agus iarrann sé ar an gceann scríbe PKP an dréacht a bhailíochtú roimh an aighneacht deiridh.', tips: ['Seiceáil an rannán OJS nó an tsraith OMP sula n-ullmhaítear an dréacht.', 'Tar éis briseadh, déan an t-ullmhúchán arís; athúsáidtear an dréacht atá ann.', 'Ceartaigh gach earráid bhailíochtaithe cianda roimh an aighneacht deiridh.'] },
  hr: { title: 'Izravna predaja u OJS i OMP', body: 'U prikazu Publication otvorena samostalna OMI studija može se izravno predati konfiguriranom OJS časopisu ili OMP izdavaču. Studio stvara udaljenu radnu verziju, prenosi provjerene metapodatke te izvorne DOCX i OMI datoteke i pokreće PKP provjeru prije konačne predaje.', tips: ['Prije pripreme provjerite ciljnu OJS rubriku ili OMP seriju.', 'Ako se priprema prekine, ponovite je; Studio koristi postojeću radnu verziju i izbjegava duplikate.', 'Ispravite sve pogreške udaljene provjere prije konačne predaje.'] },
  hu: { title: 'Közvetlen beküldés OJS-be és OMP-be', body: 'A Publikáció nézetből a megnyitott önálló OMI-tanulmány közvetlenül beküldhető egy beállított OJS-folyóiratba vagy OMP-kiadói rendszerbe. A Studio natív távoli piszkozatot hoz létre, átadja az ellenőrzött metaadatokat, valamint a DOCX- és OMI-forrásfájlt, majd a végleges beküldés előtt lefuttatja a PKP-rendszer saját ellenőrzését.', tips: ['Előkészítés előtt ellenőrizze a cél OJS-rovatot vagy OMP-sorozatot.', 'Megszakadt előkészítés után ismételje meg a műveletet: a Studio a meglévő távoli piszkozatot használja tovább, és nem hoz létre duplikátumot.', 'A végleges beküldés előtt javítsa a távoli ellenőrzés minden hibáját.'] },
  it: { title: 'Invio diretto a OJS e OMP', body: 'Dalla vista Pubblicazione uno studio OMI autonomo aperto può essere inviato direttamente a una rivista OJS o a una piattaforma editoriale OMP configurata. Studio crea una bozza remota nativa, trasferisce i metadati verificati e i file sorgente DOCX e OMI, quindi esegue la validazione PKP prima dell’invio definitivo.', tips: ['Controllare la sezione OJS o la serie OMP di destinazione prima di preparare la bozza.', 'Se la preparazione viene interrotta, ripeterla: Studio riutilizza la bozza esistente ed evita duplicati.', 'Correggere tutti gli errori di validazione remota prima dell’invio definitivo.'] },
  lt: { title: 'Tiesioginis pateikimas į OJS ir OMP', body: 'Publication rodinyje atvirą savarankišką OMI studiją galima tiesiogiai pateikti sukonfigūruotam OJS žurnalui arba OMP leidyklai. Studio sukuria nuotolinį juodraštį, perduoda patikrintus metaduomenis bei DOCX ir OMI šaltinio failus ir prieš galutinį pateikimą paleidžia PKP patikrą.', tips: ['Prieš rengdami patikrinkite tikslinę OJS skiltį arba OMP seriją.', 'Po pertrūkio pakartokite rengimą; Studio naudoja esamą juodraštį ir išvengia dublikatų.', 'Prieš galutinį pateikimą ištaisykite visas nuotolinės patikros klaidas.'] },
  lv: { title: 'Tieša iesniegšana OJS un OMP', body: 'Publication skatā atvērtu patstāvīgu OMI pētījumu var tieši iesniegt konfigurētam OJS žurnālam vai OMP izdevniecībai. Studio izveido attālu melnrakstu, pārsūta pārbaudītos metadatus un DOCX un OMI avota failus un pirms galīgās iesniegšanas palaiž PKP validāciju.', tips: ['Pirms sagatavošanas pārbaudiet mērķa OJS sadaļu vai OMP sēriju.', 'Pēc pārtraukuma atkārtojiet sagatavošanu; Studio izmanto esošo melnrakstu un neveido dublikātus.', 'Pirms galīgās iesniegšanas izlabojiet visas attālās validācijas kļūdas.'] },
  mt: { title: 'Sottomissjoni diretta lejn OJS u OMP', body: 'Mill-veduta Publication studju OMI indipendenti miftuħ jista’ jintbagħat direttament lil ġurnal OJS jew press OMP ikkonfigurat. Studio joħloq abbozz remot, jittrasferixxi l-metadata riveduta u l-fajls sors DOCX u OMI, u jwettaq il-validazzjoni PKP qabel is-sottomissjoni finali.', tips: ['Iċċekkja s-sezzjoni OJS jew is-serje OMP fil-mira qabel il-preparazzjoni.', 'Wara interruzzjoni erġa’ agħmel il-preparazzjoni; l-abbozz eżistenti jerġa’ jintuża.', 'Ikkoreġi l-iżbalji kollha tal-validazzjoni remota qabel is-sottomissjoni finali.'] },
  nl: { title: 'Direct indienen bij OJS en OMP', body: 'Vanuit Publicatie kan een geopende zelfstandige OMI-studie rechtstreeks worden ingediend bij een geconfigureerd OJS-tijdschrift of OMP-uitgever. Studio maakt een externe conceptinzending, draagt de gecontroleerde metadata en de DOCX- en OMI-bronbestanden over en laat de PKP-bestemming het concept valideren vóór de definitieve indiening.', tips: ['Controleer vooraf de OJS-sectie of OMP-serie.', 'Na een onderbreking kunt u de voorbereiding herhalen; Studio hergebruikt het bestaande concept en voorkomt duplicaten.', 'Los alle externe validatiefouten op vóór de definitieve indiening.'] },
  pl: { title: 'Bezpośrednie zgłoszenie do OJS i OMP', body: 'W widoku Publication otwarte samodzielne opracowanie OMI można wysłać bezpośrednio do skonfigurowanego czasopisma OJS lub wydawnictwa OMP. Studio tworzy zdalną wersję roboczą, przekazuje sprawdzone metadane oraz pliki źródłowe DOCX i OMI, a przed ostatecznym zgłoszeniem uruchamia walidację PKP.', tips: ['Przed przygotowaniem sprawdź docelową sekcję OJS lub serię OMP.', 'Po przerwaniu ponów przygotowanie; Studio wykorzysta istniejącą wersję roboczą i uniknie duplikatów.', 'Przed ostatecznym zgłoszeniem popraw wszystkie błędy zdalnej walidacji.'] },
  pt: { title: 'Submissão direta para OJS e OMP', body: 'Na vista Publicação, um estudo OMI autónomo aberto pode ser submetido diretamente a uma revista OJS ou editora OMP configurada. O Studio cria um rascunho remoto nativo, transfere os metadados revistos e os ficheiros fonte DOCX e OMI e solicita a validação PKP antes da submissão final.', tips: ['Confirme a secção OJS ou a série OMP de destino antes de preparar o rascunho.', 'Após uma interrupção, repita a preparação; o Studio reutiliza o rascunho existente e evita duplicados.', 'Corrija todos os erros de validação remota antes da submissão final.'] },
  ro: { title: 'Trimitere directă către OJS și OMP', body: 'Din vizualizarea Publication, un studiu OMI autonom deschis poate fi trimis direct către o revistă OJS sau o editură OMP configurată. Studio creează o ciornă la distanță, transferă metadatele verificate și fișierele sursă DOCX și OMI și rulează validarea PKP înainte de trimiterea finală.', tips: ['Verificați secțiunea OJS sau seria OMP înainte de pregătire.', 'După o întrerupere repetați pregătirea; Studio reutilizează ciorna existentă și evită duplicatele.', 'Corectați toate erorile de validare la distanță înainte de trimiterea finală.'] },
  sk: { title: 'Priame odoslanie do OJS a OMP', body: 'V zobrazení Publication možno otvorenú samostatnú štúdiu OMI odoslať priamo do nakonfigurovaného časopisu OJS alebo vydavateľstva OMP. Studio vytvorí vzdialený koncept, prenesie skontrolované metadáta a zdrojové súbory DOCX a OMI a pred konečným odoslaním spustí validáciu PKP.', tips: ['Pred prípravou skontrolujte cieľovú sekciu OJS alebo sériu OMP.', 'Po prerušení prípravu zopakujte; Studio použije existujúci koncept a zabráni duplikátom.', 'Pred konečným odoslaním opravte všetky chyby vzdialenej validácie.'] },
  sl: { title: 'Neposredna oddaja v OJS in OMP', body: 'V pogledu Publication je mogoče odprto samostojno študijo OMI neposredno oddati konfigurirani reviji OJS ali založbi OMP. Studio ustvari oddaljeni osnutek, prenese preverjene metapodatke ter izvorni datoteki DOCX in OMI in pred končno oddajo zažene preverjanje PKP.', tips: ['Pred pripravo preverite ciljni razdelek OJS ali serijo OMP.', 'Po prekinitvi pripravo ponovite; Studio uporabi obstoječi osnutek in prepreči dvojnike.', 'Pred končno oddajo odpravite vse napake oddaljenega preverjanja.'] },
  sv: { title: 'Direkt inskickning till OJS och OMP', body: 'Från vyn Publication kan en öppen fristående OMI-studie skickas direkt till en konfigurerad OJS-tidskrift eller OMP-utgivare. Studio skapar ett fjärrutkast, överför granskade metadata samt DOCX- och OMI-källfiler och kör PKP-validering före den slutliga inskickningen.', tips: ['Kontrollera OJS-sektionen eller OMP-serien innan utkastet förbereds.', 'Efter ett avbrott kan förberedelsen upprepas; Studio återanvänder det befintliga utkastet och undviker dubbletter.', 'Åtgärda alla fjärrvalideringsfel före den slutliga inskickningen.'] },
};

export function appendDirectSubmissionHelp(locale: string, copy: HelpCopy): HelpCopy {
  const topic = directSubmissionTopic[locale];
  if (!topic) return copy;
  return {
    ...copy,
    topics: [...copy.topics, topic],
  };
}
