import type { HelpCopy } from './help';

/** Adds practical guidance and current manuscript workflows to localized help. */
const practicalGuidance: Record<string, { label: string; suffix: string }> = {
  bg: { label: 'Практически съвет', suffix: 'Проверете настройките и резултата преди окончателния експорт.' }, cs: { label: 'Praktický tip', suffix: 'Před konečným exportem zkontrolujte nastavení a výsledný výstup.' }, da: { label: 'Praktisk tip', suffix: 'Kontrollér indstillingerne og resultatet før den endelige eksport.' }, de: { label: 'Praktischer Hinweis', suffix: 'Prüfen Sie Einstellungen und Ergebnis vor dem endgültigen Export.' }, el: { label: 'Πρακτική συμβουλή', suffix: 'Ελέγξτε τις ρυθμίσεις και το αποτέλεσμα πριν από την τελική εξαγωγή.' }, en: { label: 'Practical tip', suffix: 'Check the settings and result before the final export.' }, es: { label: 'Consejo práctico', suffix: 'Compruebe la configuración y el resultado antes de la exportación definitiva.' }, et: { label: 'Praktiline soovitus', suffix: 'Kontrollige seadeid ja tulemust enne lõplikku eksporti.' }, fi: { label: 'Käytännön vinkki', suffix: 'Tarkista asetukset ja lopputulos ennen lopullista vientiä.' }, fr: { label: 'Conseil pratique', suffix: 'Vérifiez les réglages et le résultat avant l’exportation définitive.' }, ga: { label: 'Leid phraiticiúil', suffix: 'Seiceáil na socruithe agus an toradh roimh an easpórtáil deiridh.' }, hr: { label: 'Praktični savjet', suffix: 'Provjerite postavke i rezultat prije konačnog izvoza.' }, hu: { label: 'Gyakorlati tipp', suffix: 'A végleges export előtt ellenőrizze a beállításokat és az eredményt.' }, lt: { label: 'Praktinis patarimas', suffix: 'Prieš galutinį eksportą patikrinkite nustatymus ir rezultatą.' }, lv: { label: 'Praktisks padoms', suffix: 'Pirms galīgā eksporta pārbaudiet iestatījumus un rezultātu.' }, mt: { label: 'Parir prattiku', suffix: 'Iċċekkja s-settings u r-riżultat qabel l-esportazzjoni finali.' }, nl: { label: 'Praktische tip', suffix: 'Controleer de instellingen en het resultaat vóór de definitieve export.' }, pl: { label: 'Praktyczna wskazówka', suffix: 'Przed końcowym eksportem sprawdź ustawienia i wynik.' }, pt: { label: 'Sugestão prática', suffix: 'Verifique as definições e o resultado antes da exportação final.' }, ro: { label: 'Sfat practic', suffix: 'Verificați setările și rezultatul înainte de exportul final.' }, sk: { label: 'Praktický tip', suffix: 'Pred konečným exportom skontrolujte nastavenia a výsledok.' }, sl: { label: 'Praktični nasvet', suffix: 'Pred končnim izvozom preverite nastavitve in rezultat.' }, sv: { label: 'Praktiskt tips', suffix: 'Kontrollera inställningarna och resultatet före den slutliga exporten.' },
};

const signatureTopic: Record<string, { title: string; body: string; tips: string[] }> = {
  hu: { title: 'Kriptográfiai szerzői aláírás', body: 'A regisztrált szerzők egy konkrét kéziratrevíziót WebAuthn/passkey hitelesítő adattal írhatnak alá, amely biztonságosan ellenőrzött személyazonossághoz, például ORCID-hoz kapcsolódik. Az aláírás pontosan az adott revízió kriptográfiai lenyomatához kötődik.', tips: ['A metaadatok közé kézzel beírt ORCID nem azonos a hitelesített ORCID-identitással.', 'A kézirat módosítása után az új revíziót újra alá kell írni.', 'Többszerzős kéziratnál minden szerző külön aláírhatja ugyanazt a revíziót.'] },
  en: { title: 'Cryptographic author signatures', body: 'Registered authors can sign a specific manuscript revision with a WebAuthn/passkey credential linked to a securely verified identity such as ORCID. The signature is bound to the cryptographic digest of that exact revision.', tips: ['A manually entered ORCID is not the same as an authenticated ORCID identity.', 'After manuscript changes, the new revision must be signed again.', 'Each co-author can sign the same revision independently.'] },
  de: { title: 'Kryptografische Autorensignatur', body: 'Registrierte Autorinnen und Autoren können eine konkrete Revision mit einer WebAuthn/passkey-Anmeldeinformation signieren, die mit einer sicher verifizierten Identität wie ORCID verbunden ist. Die Signatur ist an den kryptografischen Digest genau dieser Revision gebunden.', tips: ['Eine manuell eingetragene ORCID ist nicht gleichbedeutend mit einer authentifizierten ORCID-Identität.', 'Nach einer Manuskriptänderung muss die neue Revision erneut signiert werden.'] },
};

const navigationTopic: Record<string, { title: string; body: string; tips: string[] }> = {
  hu: { title: 'Tartalomjegyzék és mutatók', body: 'A Studio a tartalomjegyzéket és a mutatókat szemantikus navigációként kezeli. Wordből importált tartalomjegyzék esetén a címsorhierarchiából élő, a dokumentumba ágyazott tartalomjegyzék készül: a bejegyzésekre kattintva közvetlenül a megfelelő fejezethez lehet ugrani. A Word statikus oldalszámai nem kerülnek megőrzésre, mert a Studio folyamatos, reszponzív dokumentummodellt használ. A dokumentumban több, szabadon elnevezhető mutató is létrehozható – például névmutató, helységmutató vagy képek jegyzéke – és a mutató előfordulásai a megjelölt szöveghelyhez navigálnak.', tips: ['A tartalomjegyzék alapja a címsorhierarchia, ezért a fejezetekhez valódi címsorszinteket használjon.', 'Import után ne javítsa kézzel a tartalomjegyzék oldalszámait: a Studio nem statikus oldalszámokra építi a navigációt.', 'Mutatóbejegyzésnél a konkrét előfordulásra kattintva a dokumentum megfelelő helyére ugorhat.'] },
  en: { title: 'Table of contents and indexes', body: 'Studio treats tables of contents and indexes as semantic navigation. When a Word table of contents is imported, Studio builds a live in-document table of contents from the heading hierarchy; selecting an entry navigates directly to its section. Static Word page numbers are not preserved because Studio uses a continuous responsive document model. A manuscript can also contain multiple freely named indexes, such as a name index, place index, or list of figures, with occurrences navigating to their marked location.', tips: ['Use real heading levels because the table of contents is generated from the heading hierarchy.', 'Do not manually repair imported TOC page numbers; Studio navigation does not depend on static pagination.', 'Select an index occurrence to navigate to the corresponding place in the manuscript.'] },
  de: { title: 'Inhaltsverzeichnis und Register', body: 'Studio behandelt Inhaltsverzeichnisse und Register als semantische Navigation. Beim Import eines Word-Inhaltsverzeichnisses erzeugt Studio aus der Überschriftenhierarchie ein dynamisches Inhaltsverzeichnis im Dokument; ein Klick auf einen Eintrag führt direkt zum entsprechenden Abschnitt. Statische Word-Seitenzahlen werden nicht übernommen, da Studio ein fortlaufendes responsives Dokumentmodell verwendet. Ein Manuskript kann außerdem mehrere frei benannte Register enthalten, etwa Personenregister, Ortsregister oder Abbildungsverzeichnis; die Fundstellen führen zur markierten Stelle im Dokument.', tips: ['Verwenden Sie echte Überschriftenebenen, da daraus das Inhaltsverzeichnis erzeugt wird.', 'Korrigieren Sie importierte Seitenzahlen nicht manuell; die Studio-Navigation beruht nicht auf statischer Paginierung.', 'Klicken Sie auf eine Registerfundstelle, um zur entsprechenden Stelle im Manuskript zu springen.'] },
};

export function enrichAdditionalHelp(locale: string, copy: HelpCopy): HelpCopy {
  const guidance = practicalGuidance[locale];
  if (!guidance) return copy;
  const topics = copy.topics.map((topic) => ({ ...topic, tips: topic.tips?.length ? topic.tips : [`${guidance.label}: ${guidance.suffix}`] }));
  const navigation = navigationTopic[locale] ?? navigationTopic.en;
  if (!topics.some((topic) => topic.title === navigation.title)) topics.push(navigation);
  const signature = signatureTopic[locale];
  if (signature && !topics.some((topic) => topic.title === signature.title)) topics.push(signature);
  return { ...copy, topics };
}
