// Generated by scripts/translate-help-with-deepl.mjs.
// Keep this file committed so generated translations are reproducible in every build.
// Manual corrections are allowed; the translator does not overwrite existing locales unless --force is used.

export const generatedDetailedHelpLabels: Record<string, {
  location: string;
  steps: string;
  checks: string;
}> = {};

export const generatedDetailedHelpByLocale: Record<string, Record<number, {
  location: string;
  steps: string[];
  checks: string[];
}>> = {};
