import type { HelpCopy } from './help';

type Topic = { title: string; body: string; tips?: string[] };
const make = (navigation: string, title: string, description: string, gettingStarted: string, rows: Array<[string,string,string,string]>): HelpCopy => ({ navigation, title, description, gettingStarted, topics: rows.map(([title,body,a,b]): Topic => ({title,body,tips:[a,b]})) });

export const danishHelp = make('Hjælp','Hjælp til Open Manuscript Studio','Detaljeret vejledning til manuskript, peer review, publicering, signaturer og eksport i Studio 0.1.0-alpha.1.','Studio behandler manuskriptet som strukturerede videnskabelige data. Brug semantiske elementer frem for visuel formatering, så indholdet kan genbruges på tværs af publiceringsformater.',[
['1. Manuskriptredigering og semantisk formatering','Redigér brødtekst, overskrifter og inline-formatering i hovededitoren. Strukturen bevares semantisk og kan derfor eksporteres konsistent.','Brug overskriftsniveauer til struktur, ikke kun til udseende.','Kontrollér strukturen før den endelige eksport.'],
['2. Afsnit, hierarki og nummerering','Afsnit danner et hierarki, og publikationsprofilen kan styre deres nummerering og visning.','Flyt afsnit som strukturelle enheder.','Undgå manuel nummerering i selve overskriftsteksten.'],
['3. Manuskriptdata, front matter og sprog','Titel, undertitel, resumé, nøgleord og flersprogede metadata administreres separat fra brødteksten.','Udfyld metadata på alle relevante sprog.','Kontrollér dokumentets primære sprog før publicering.'],
['4. Bidragydere, ORCID og ROR','Forfattere og andre bidragydere kan have roller, institutioner, ORCID og ROR-identifikatorer.','Brug ORCID til entydig forfatteridentifikation.','Brug ROR, når institutionen kan identificeres entydigt.'],
['5. Noter og citater i noter','Fodnoter og slutnoter er semantiske objekter og kan indeholde formateret tekst og bibliografiske citater.','Indsæt noter med noteværktøjet.','Brug strukturerede citater også inde i noter.'],
['6. Citater, bibliografi og citationsstil','Bibliografiske poster kan genbruges, og CSL styrer visningen. Egne navngivne citationsstile kan gemmes.','Ret kildedata i posten frem for den formaterede tekst.','Vælg eller gem citationsstil før slutkontrol.'],
['7. Krydshenvisninger','Krydshenvisninger peger på dokumentobjekter og følger derfor ændringer i nummerering.','Henvis til målobjektet, ikke et manuelt nummer.','Kontrollér brudte henvisninger efter større strukturændringer.'],
['8. Figurer, tabeller og ligninger','Figurer, tabeller og ligninger bevares som strukturerede videnskabelige objekter med tilhørende metadata.','Tilføj billedtekst og alternativ tekst til figurer.','Kontrollér tabeller og formler i målformatet.'],
['9. Mediefiler og OMI-pakke','Mediefiler er manuskriptaktiver. En fuld OMI-pakke kan transportere manuskript, aktiver og integritetsdata samlet.','Bevar originale mediefiler.','Brug OMI-pakken, når hele projektet skal flyttes.'],
['10. DOCX-import','DOCX-import forsøger at omsætte Word-overskrifter, formatering, noter, tabeller og andre genkendelige strukturer til OMI-elementer.','Brug Word-typografier konsekvent før import.','Gennemgå overskrifter og noter efter import.'],
['11. OJS-integration','Når Studio startes fra OJS, udveksles manuskript og tilladte metadata efter sessionens scopes, assignment og rettigheder.','Kontrollér den aktuelle OJS-submission før tilbageskrivning.','Rapportér integrationsfejl med submission- og assignment-kontekst.'],
['12. Peer review','Reviewer-adgang er knyttet til en konkret assignment, og review-visningen skal kun vise det materiale, som rollen må se.','Brug reviewer-kontoen til reel adgangstest.','Kontrollér anonymisering ved double-blind review.'],
['13. Revisioner, historik og integritet','Ændringer kan knyttes til revisioner og integritets-digests, så en bestemt dokumenttilstand kan identificeres præcist.','Opret en klar revision før signering.','Sammenlign digest, hvis dokumentintegriteten er tvivlsom.'],
['14. Publikationsprofiler','Publikationsprofiler adskiller indhold fra udgiverens regler for side, typografi, nummerering, noter, metadata og output.','Vælg profil før sluteksport.','Hold indholdskorrektioner adskilt fra layoutregler.'],
['15. Egne udgiverprofiler og beskyttelse','En udgiver kan gemme egne profiler med navn og logo. Beskyttede profiler ændres gennem en ny version efter passende identifikation.','Versionér ændringer i produktionsprofiler.','Beskyt godkendte profiler mod utilsigtet redigering.'],
['16. Export CSS og Print/PDF CSS','Profilen kan indeholde generel Export CSS og separat Print/PDF CSS med @page, marginer og sideskift.','Hold skærm- og printregler adskilt.','Test PDF-resultatet i den anvendte printmotor.'],
['17. Eksportformater','Studio understøtter OMI, OMI JSON, JATS XML, semantisk HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB og et printbaseret PDF-flow.','Vælg format efter næste led i arbejdsgangen.','Arkivér OMI sammen med distributionsformatet.'],
['18. HTML og publiceringskontrol','Semantisk HTML eksporteres uden scripts. Studio validerer dokumentet mod den aktive profil før publicering.','Ret fejl før advarsler.','Kontrollér HTML-strukturen, ikke kun udseendet.'],
['19. Lagring og sikkerhedskopiering','Lokale og konfigurerbare eksterne lagre kan anvendes; WebDAV/Nextcloud afhænger af installationens konfiguration.','Bevar mindst én uafhængig sikkerhedskopi.','Test gendannelse, ikke kun sikkerhedskopiering.'],
['20. Fejlfinding','Afgør først, om problemet vedrører indhold, struktur, metadata, integration, eksport eller visning.','Notér de præcise trin, der udløser fejlen.','Kontrollér aktivt sprog og publikationsprofil.'],
['21. Kryptografiske forfattersignaturer','En registreret forfatter kan efter sikker identifikation knytte en WebAuthn/passkey-nøgle til sin ORCID-identitet og signere en bestemt manuskriptrevision kryptografisk.','Signér først den revision, der faktisk skal godkendes.','Efter indholdsændringer skal den nye revision signeres igen.']
]);

export const swedishHelp = make('Hjälp','Hjälp för Open Manuscript Studio','Detaljerad vägledning för manuskript, peer review, publicering, signaturer och export i Studio 0.1.0-alpha.1.','Studio behandlar manuskriptet som strukturerade vetenskapliga data. Använd semantiska element i stället för enbart visuell formatering så att innehållet kan återanvändas i olika publiceringsformat.',[
['1. Manuskriptredigering och semantisk formatering','Redigera brödtext, rubriker och inline-formatering i huvudredigeraren. Strukturen bevaras semantiskt för konsekvent export.','Använd rubriknivåer för struktur.','Kontrollera strukturen före slutlig export.'],
['2. Avsnitt, hierarki och numrering','Avsnitt bildar en hierarki och publikationsprofilen kan styra numrering och visning.','Flytta avsnitt som strukturella enheter.','Undvik manuell numrering i rubriktexten.'],
['3. Manuskriptdata, front matter och språk','Titel, undertitel, abstract, nyckelord och flerspråkiga metadata hanteras separat från brödtexten.','Fyll i metadata på relevanta språk.','Kontrollera dokumentets huvudspråk.'],
['4. Medverkande, ORCID och ROR','Författare och andra medverkande kan ha roller, affilieringar, ORCID och ROR.','Använd ORCID för entydig författaridentitet.','Använd ROR för identifierbara institutioner.'],
['5. Noter och citeringar i noter','Fotnoter och slutnoter är semantiska objekt och kan innehålla formaterad text och bibliografiska citeringar.','Skapa noter med notverktyget.','Använd strukturerade citeringar även i noter.'],
['6. Citeringar, bibliografi och citeringsstil','Bibliografiska poster kan återanvändas och CSL styr presentationen. Egna namngivna stilar kan sparas.','Korrigera källdata i posten.','Välj citeringsstil före slutkontroll.'],
['7. Korsreferenser','Korsreferenser pekar på dokumentobjekt och följer ändringar i numreringen.','Referera till målobjektet, inte ett manuellt nummer.','Kontrollera brutna referenser efter strukturändringar.'],
['8. Figurer, tabeller och ekvationer','Figurer, tabeller och ekvationer bevaras som strukturerade vetenskapliga objekt med metadata.','Lägg till bildtext och alternativtext.','Kontrollera tabeller och formler i målformatet.'],
['9. Mediefiler och OMI-paket','Mediefiler är manuskripttillgångar. Ett komplett OMI-paket kan bära manuskript, filer och integritetsdata tillsammans.','Bevara originalfilerna.','Använd OMI-paketet när hela projektet ska flyttas.'],
['10. DOCX-import','DOCX-import försöker omvandla Word-rubriker, formatering, noter, tabeller och andra igenkända strukturer till OMI-element.','Använd Word-formatmallar konsekvent.','Granska rubriker och noter efter import.'],
['11. OJS-integration','När Studio startas från OJS utbyts manuskript och tillåtna metadata enligt sessionens scopes, assignment och behörigheter.','Kontrollera aktuell OJS-submission före återföring.','Rapportera integrationsfel med submission- och assignment-kontext.'],
['12. Peer review','Granskaråtkomst är bunden till en konkret assignment och granskningsvyn ska endast visa material som rollen får se.','Testa med ett verkligt granskar-konto.','Kontrollera anonymisering vid double-blind review.'],
['13. Revisioner, historik och integritet','Ändringar kan bindas till revisioner och integritets-digests så att ett exakt dokumenttillstånd kan identifieras.','Skapa en tydlig revision före signering.','Jämför digest vid misstänkt förändring.'],
['14. Publikationsprofiler','Publikationsprofiler skiljer innehåll från utgivarens regler för sida, typografi, numrering, noter, metadata och output.','Välj profil före slutexport.','Håll innehållskorrigeringar skilda från layoutregler.'],
['15. Egna utgivarprofiler och skydd','En utgivare kan spara egna profiler med namn och logotyp. Skyddade profiler ändras genom en ny version efter lämplig identifiering.','Versionshantera produktionsprofiler.','Skydda godkända profiler från oavsiktlig redigering.'],
['16. Export CSS och Print/PDF CSS','Profilen kan innehålla generell Export CSS och separat Print/PDF CSS med @page, marginaler och sidbrytningar.','Separera skärm- och utskriftsregler.','Testa PDF-resultatet i aktuell utskriftsmotor.'],
['17. Exportformat','Studio stöder OMI, OMI JSON, JATS XML, semantisk HTML, DOCX, IDML, XTG, MIF, SLA, LaTeX, EPUB och ett utskriftsbaserat PDF-flöde.','Välj format efter nästa arbetssteg.','Arkivera OMI tillsammans med distributionsformatet.'],
['18. HTML och publiceringskontroll','Semantisk HTML exporteras utan skript. Studio validerar dokumentet mot aktiv profil före publicering.','Åtgärda fel före varningar.','Kontrollera HTML-strukturen, inte bara utseendet.'],
['19. Lagring och säkerhetskopiering','Lokala och konfigurerbara externa lagringsmål kan användas; WebDAV/Nextcloud beror på installationens konfiguration.','Behåll minst en oberoende säkerhetskopia.','Testa återställning regelbundet.'],
['20. Felsökning','Avgör först om problemet gäller innehåll, struktur, metadata, integration, export eller visning.','Dokumentera exakta steg som utlöser felet.','Kontrollera aktivt språk och publikationsprofil.'],
['21. Kryptografiska författarsignaturer','En registrerad författare kan efter säker identifiering knyta en WebAuthn/passkey-nyckel till sin ORCID-identitet och kryptografiskt signera en bestämd manuskriptrevision.','Signera den revision som faktiskt ska godkännas.','Efter innehållsändringar måste den nya revisionen signeras igen.']
]);