import type { HelpCopy, HelpTopic } from './help';

const collaborationTopic: Record<string, HelpTopic> = {
  bg: { title: '21. Покана за съвместно редактиране', body: 'Съвместното редактиране е достъпно само когато администраторът е включил функцията за тази инсталация. В отворения ръкопис авторът намира панела Live collaboration, избира Start shared editing, въвежда имейл адреса на профила в Studio на поканения автор и избира Send invitation. Добавянето на име в списъка с автори само по себе си не предоставя достъп.', tips: ['Поканеният влиза в Studio със същия имейл адрес и приема или отхвърля поканата в горния десен ъгъл.', 'Имейл връзката е алтернативен начин за отваряне на поканата; приемането пак изисква съвпадащ профил.', 'След приемане отворете същия OMI ръкопис в Studio. Без чакаща покана или при изключена функция панелът за покани не се показва.'] },
  cs: { title: '21. Pozvání ke společné úpravě', body: 'Společné úpravy jsou dostupné jen tehdy, když je správce pro tuto instalaci zapne. U otevřeného rukopisu otevře autor panel Live collaboration, zvolí Start shared editing, zadá e-mail účtu pozvaného autora ve Studiu a zvolí Send invitation. Přidání jména do seznamu autorů samo o sobě přístup neuděluje.', tips: ['Pozvaný se přihlásí do Studia stejnou e-mailovou adresou a v pravém horním rohu pozvánku přijme nebo odmítne.', 'E-mailový odkaz je další způsob, jak pozvánku otevřít; přijetí stále vyžaduje shodný účet.', 'Po přijetí otevřete ve Studiu tentýž rukopis OMI. Bez čekající pozvánky nebo při vypnuté funkci se schránka pozvánek nezobrazí.'] },
  da: { title: '21. Invitation til fælles redigering', body: 'Fælles redigering er kun tilgængelig, når administratoren har aktiveret funktionen for installationen. I det åbne manuskript vælger forfatteren Live collaboration, derefter Start shared editing, indtaster den inviterede forfatters Studio-kontomail og vælger Send invitation. At tilføje et navn til forfatterlisten giver ikke i sig selv adgang.', tips: ['Den inviterede logger ind i Studio med samme mailadresse og accepterer eller afviser invitationen øverst til højre.', 'Mail-linket er en alternativ måde at åbne invitationen på; accept kræver stadig den matchende konto.', 'Efter accept skal den samme OMI-fil åbnes i Studio. Uden en afventende invitation eller når funktionen er slået fra, vises indbakken ikke.'] },
  de: { title: '21. Einladung zur gemeinsamen Bearbeitung', body: 'Die gemeinsame Bearbeitung ist nur verfügbar, wenn die Administration die Funktion für diese Installation aktiviert hat. Im geöffneten Manuskript wählt die einladende Person im Bereich Live collaboration die Option Start shared editing, gibt die Studio-Konto-E-Mail der eingeladenen Person ein und wählt Send invitation. Ein Name in der Autorenliste allein gewährt keinen Zugriff.', tips: ['Die eingeladene Person meldet sich mit derselben E-Mail-Adresse in Studio an und nimmt die Einladung oben rechts an oder lehnt sie ab.', 'Der E-Mail-Link ist ein alternativer Weg zur Einladung; die Annahme erfordert weiterhin das passende Konto.', 'Nach der Annahme muss dieselbe OMI-Datei in Studio geöffnet werden. Ohne offene Einladung oder bei deaktivierter Funktion wird der Einladungseingang nicht angezeigt.'] },
  el: { title: '21. Πρόσκληση για συνεργατική επεξεργασία', body: 'Η συνεργατική επεξεργασία είναι διαθέσιμη μόνο όταν ο διαχειριστής έχει ενεργοποιήσει τη λειτουργία για αυτήν την εγκατάσταση. Στο ανοιχτό χειρόγραφο, ο συγγραφέας επιλέγει Live collaboration και Start shared editing, εισάγει το email του λογαριασμού Studio του προσκεκλημένου και επιλέγει Send invitation. Η προσθήκη ονόματος στους συντελεστές δεν δίνει από μόνη της πρόσβαση.', tips: ['Ο προσκεκλημένος συνδέεται στο Studio με το ίδιο email και αποδέχεται ή απορρίπτει την πρόσκληση επάνω δεξιά.', 'Ο σύνδεσμος email είναι εναλλακτικός τρόπος ανοίγματος της πρόσκλησης· η αποδοχή απαιτεί τον ίδιο λογαριασμό.', 'Μετά την αποδοχή, ανοίξτε στο Studio το ίδιο χειρόγραφο OMI. Χωρίς εκκρεμή πρόσκληση ή με απενεργοποιημένη λειτουργία, τα εισερχόμενα δεν εμφανίζονται.'] },
  en: { title: '21. Inviting an author to collaborate', body: 'Live collaboration is available only when an administrator has enabled it for the installation. In the open manuscript, the inviting author uses the Live collaboration panel, selects Start shared editing, enters the invited author’s Studio account email, and selects Send invitation. Adding someone to the manuscript’s author list does not grant access.', tips: ['The invitee signs in to Studio with that same email address and accepts or declines the invitation in the upper-right corner.', 'The email link is an alternative way to open the invitation; acceptance still requires the matching account.', 'After accepting, open the same OMI manuscript in Studio. The inbox is hidden when there is no pending invitation or the feature is disabled.'] },
  es: { title: '21. Invitar a un autor a colaborar', body: 'La colaboración en directo solo está disponible cuando la administración activa la función para esta instalación. En el manuscrito abierto, quien invita abre el panel Live collaboration, elige Start shared editing, introduce el correo de la cuenta de Studio del autor invitado y pulsa Send invitation. Añadir a alguien a la lista de autores no le concede acceso.', tips: ['La persona invitada inicia sesión en Studio con ese mismo correo y acepta o rechaza la invitación en la esquina superior derecha.', 'El enlace del correo es otra forma de abrir la invitación; para aceptarla sigue siendo necesaria la cuenta correspondiente.', 'Tras aceptar, abre en Studio el mismo manuscrito OMI. La bandeja no aparece si no hay invitaciones pendientes o la función está desactivada.'] },
  et: { title: '21. Autori kutsumine koostööd tegema', body: 'Reaalajas koostöö on saadaval ainult siis, kui administraator on selle paigalduse jaoks funktsiooni lubanud. Avatud käsikirjas valib kutsuja paneeli Live collaboration, seejärel Start shared editing, sisestab kutsutava autori Studio konto e-posti aadressi ja valib Send invitation. Autori lisamine käsikirja autorite loendisse ei anna iseenesest ligipääsu.', tips: ['Kutsutu logib Studiose sisse sama e-posti aadressiga ning võtab kutse paremas ülanurgas vastu või lükkab tagasi.', 'E-kirja link on kutse avamiseks alternatiivne viis; vastuvõtmiseks peab konto siiski kattuma.', 'Pärast vastuvõtmist ava Studios sama OMI käsikiri. Kutsete postkast on peidetud, kui kutset pole ootel või funktsioon on välja lülitatud.'] },
  fi: { title: '21. Kirjoittajan kutsuminen yhteismuokkaukseen', body: 'Reaaliaikainen yhteistyö on käytettävissä vain, jos ylläpitäjä on ottanut ominaisuuden käyttöön tässä asennuksessa. Avoimessa käsikirjoituksessa kutsuja avaa Live collaboration -paneelin, valitsee Start shared editing, kirjoittaa kutsutun Studio-tilin sähköpostiosoitteen ja valitsee Send invitation. Nimen lisääminen tekijäluetteloon ei yksin anna käyttöoikeutta.', tips: ['Kutsuttu kirjautuu Studioon samalla sähköpostiosoitteella ja hyväksyy tai hylkää kutsun oikeassa yläkulmassa.', 'Sähköpostilinkki on vaihtoehtoinen tapa avata kutsu; hyväksyminen edellyttää silti vastaavaa tiliä.', 'Hyväksymisen jälkeen avaa sama OMI-käsikirjoitus Studiossa. Saapuneet kutsut eivät näy, jos kutsua ei ole tai ominaisuus on poissa käytöstä.'] },
  fr: { title: '21. Inviter un auteur à collaborer', body: 'La collaboration en direct est disponible uniquement si l’administration a activé cette fonction pour l’installation. Dans le manuscrit ouvert, la personne qui invite ouvre le panneau Live collaboration, choisit Start shared editing, saisit l’adresse e-mail du compte Studio de l’auteur invité et choisit Send invitation. Ajouter un nom à la liste des auteurs ne donne pas accès au manuscrit.', tips: ['La personne invitée se connecte à Studio avec cette même adresse et accepte ou refuse l’invitation en haut à droite.', 'Le lien reçu par e-mail permet aussi d’ouvrir l’invitation ; son acceptation exige toujours le compte correspondant.', 'Après acceptation, ouvrez le même manuscrit OMI dans Studio. La boîte de réception reste masquée sans invitation en attente ou si la fonction est désactivée.'] },
  ga: { title: '21. Údar a thabhairt isteach le haghaidh comhoibrithe', body: 'Ní bhíonn comhoibriú beo ar fáil ach amháin má tá an ghné cumasaithe ag an riarthóir don suiteáil seo. Sa lámhscríbhinn oscailte, osclaíonn an t-údar a thugann an cuireadh an painéal Live collaboration, roghnaíonn Start shared editing, cuireann sé ríomhphost chuntas Studio an údair eile isteach agus roghnaíonn Send invitation. Ní thugann ainm a chur ar liosta na n-údar rochtain leis féin.', tips: ['Síníonn an cuireadh isteach i Studio leis an seoladh ríomhphoist céanna agus glacann nó diúltaíonn sé don chuireadh sa chúinne uachtarach ar dheis.', 'Is bealach eile é an nasc ríomhphoist chun an cuireadh a oscailt; teastaíonn an cuntas meaitseála fós chun glacadh leis.', 'Tar éis glactha, oscail an lámhscríbhinn OMI chéanna in Studio. Ní thaispeántar an bosca isteach mura bhfuil cuireadh ar feitheamh nó má tá an ghné múchta.'] },
  hr: { title: '21. Pozivanje autora na suradnju', body: 'Suradnja uživo dostupna je samo ako je administrator uključio tu funkciju za ovu instalaciju. U otvorenom rukopisu osoba koja poziva otvara panel Live collaboration, odabire Start shared editing, upisuje e-mail adresu Studio računa pozvanog autora i odabire Send invitation. Dodavanje osobe na popis autora samo po sebi ne daje pristup.', tips: ['Pozvana osoba prijavljuje se u Studio istom e-mail adresom te prihvaća ili odbija poziv u gornjem desnom kutu.', 'Poveznica iz e-pošte alternativni je način otvaranja poziva; za prihvaćanje je i dalje potreban odgovarajući račun.', 'Nakon prihvaćanja otvorite isti OMI rukopis u Studiju. Ulazni sandučić nije prikazan ako nema poziva na čekanju ili je funkcija isključena.'] },
  hu: { title: '21. Szerző meghívása közös szerkesztésre', body: 'Az élő együttműködés csak akkor érhető el, ha a rendszergazda bekapcsolta ezt a funkciót a telepítésen. A meghíváshoz nyissa meg a kézirat tetején lévő Live collaboration panelt, válassza a Start shared editing lehetőséget, írja be a meghívott Studio-fiókjának email-címét, majd válassza a Send invitation gombot. A szerző nevének felvétele a kézirat közreműködői közé önmagában nem ad hozzáférést.', tips: ['A meghívott ugyanazzal az email-címmel lépjen be a Studioba, majd a jobb felső sarokban fogadja el vagy utasítsa el a meghívást.', 'Az emailben kapott link is megnyitja a meghívást; az elfogadáshoz akkor is a meghívott email-című fiók kell.', 'Elfogadás után nyissa meg ugyanazt az OMI-kéziratot a Studioban. Függő meghívás nélkül vagy kikapcsolt funkciónál a meghívásinbox nem látható.'] },
  it: { title: '21. Invitare un autore alla collaborazione', body: 'La collaborazione in tempo reale è disponibile solo se l’amministratore ha attivato la funzione per questa installazione. Nel manoscritto aperto, chi invita apre il pannello Live collaboration, seleziona Start shared editing, inserisce l’indirizzo email dell’account Studio dell’autore invitato e seleziona Send invitation. Aggiungere un nome all’elenco degli autori non concede accesso.', tips: ['L’invitato accede a Studio con lo stesso indirizzo email e accetta o rifiuta l’invito nell’angolo in alto a destra.', 'Il collegamento email è un modo alternativo per aprire l’invito; per accettarlo serve comunque l’account corrispondente.', 'Dopo l’accettazione, aprire in Studio lo stesso manoscritto OMI. La posta in arrivo non appare se non ci sono inviti in attesa o la funzione è disattivata.'] },
  lt: { title: '21. Autoriaus pakvietimas bendradarbiauti', body: 'Tiesioginis bendradarbiavimas galimas tik tada, kai administratorius įjungė šią funkciją šioje instaliacijoje. Atvirame rankraštyje kviečiantis asmuo pasirenka Live collaboration skydelį, tada Start shared editing, įveda kviečiamo autoriaus Studio paskyros el. pašto adresą ir pasirenka Send invitation. Vien autoriaus įtraukimas į rankraščio autorių sąrašą prieigos nesuteikia.', tips: ['Pakviestas asmuo prisijungia prie Studio tuo pačiu el. pašto adresu ir kvietimą priima arba atmeta viršutiniame dešiniajame kampe.', 'El. laiško nuoroda yra alternatyvus būdas atidaryti kvietimą; priimant vis tiek būtina atitinkama paskyra.', 'Priėmę atidarykite tą patį OMI rankraštį Studio. Gautieji nerodomi, jei nėra laukiančio kvietimo arba funkcija išjungta.'] },
  lv: { title: '21. Autora uzaicināšana kopīgam darbam', body: 'Tiešsaistes sadarbība ir pieejama tikai tad, ja administrators ir iespējojis šo funkciju šajā instalācijā. Atvērtajā manuskriptā uzaicinātājs atver Live collaboration paneli, izvēlas Start shared editing, ievada uzaicinātā autora Studio konta e-pasta adresi un izvēlas Send invitation. Vārda pievienošana autoru sarakstam pati par sevi nepiešķir piekļuvi.', tips: ['Uzaicinātais piesakās Studio ar to pašu e-pasta adresi un augšējā labajā stūrī pieņem vai noraida uzaicinājumu.', 'E-pastā saņemtā saite ir alternatīvs veids, kā atvērt uzaicinājumu; pieņemšanai tik un tā vajadzīgs atbilstošais konts.', 'Pēc pieņemšanas Studio atveriet to pašu OMI manuskriptu. Iesūtne nav redzama, ja nav gaidoša uzaicinājuma vai funkcija ir izslēgta.'] },
  mt: { title: '21. Stieden ta’ awtur biex jikkollabora', body: 'Il-kollaborazzjoni diretta tkun disponibbli biss jekk l-amministratur ikun attiva din il-karatteristika għal din l-installazzjoni. Fil-manuskritt miftuħ, min jistieden jiftaħ il-panel Live collaboration, jagħżel Start shared editing, idaħħal l-email tal-kont Studio tal-awtur mistieden u jagħżel Send invitation. Iż-żieda ta’ isem fil-lista tal-awturi waħedha ma tagħtix aċċess.', tips: ['Il-mistieden jidħol fi Studio bl-istess email u jaċċetta jew jirrifjuta l-istedina fir-rokna ta’ fuq tal-lemin.', 'Il-link bl-email huwa mod alternattiv biex tinfetaħ l-istedina; xorta hemm bżonn il-kont li jaqbel biex tiġi aċċettata.', 'Wara li taċċetta, iftaħ l-istess manuskritt OMI fi Studio. L-inbox ma tidhirx jekk ma jkunx hemm stedina pendenti jew jekk il-karatteristika tkun mitfija.'] },
  nl: { title: '21. Een auteur uitnodigen om samen te werken', body: 'Live samenwerking is alleen beschikbaar wanneer de beheerder de functie voor deze installatie heeft ingeschakeld. In het geopende manuscript kiest de uitnodiger in het paneel Live collaboration voor Start shared editing, voert het Studio-account-e-mailadres van de genodigde auteur in en kiest Send invitation. Iemand aan de auteurslijst toevoegen geeft op zichzelf geen toegang.', tips: ['De genodigde meldt zich met hetzelfde e-mailadres aan bij Studio en accepteert of weigert de uitnodiging rechtsboven.', 'De e-maillink is een alternatieve manier om de uitnodiging te openen; acceptatie vereist nog steeds het overeenkomende account.', 'Open na acceptatie hetzelfde OMI-manuscript in Studio. De inbox wordt niet getoond zonder openstaande uitnodiging of wanneer de functie uitstaat.'] },
  pl: { title: '21. Zapraszanie autora do wspólnej pracy', body: 'Współpraca na żywo jest dostępna tylko wtedy, gdy administrator włączył tę funkcję w tej instalacji. W otwartym manuskrypcie osoba zapraszająca otwiera panel Live collaboration, wybiera Start shared editing, wpisuje adres e-mail konta Studio zapraszanego autora i wybiera Send invitation. Dodanie osoby do listy autorów samo w sobie nie przyznaje dostępu.', tips: ['Zaproszona osoba loguje się do Studio tym samym adresem e-mail i przyjmuje lub odrzuca zaproszenie w prawym górnym rogu.', 'Link z wiadomości e-mail to alternatywny sposób otwarcia zaproszenia; do jego przyjęcia nadal wymagane jest właściwe konto.', 'Po przyjęciu otwórz w Studio ten sam manuskrypt OMI. Skrzynka zaproszeń jest ukryta, gdy nie ma oczekującego zaproszenia lub funkcja jest wyłączona.'] },
  pt: { title: '21. Convidar um autor para colaborar', body: 'A colaboração em direto só está disponível quando a administração ativa a funcionalidade nesta instalação. No manuscrito aberto, quem convida abre o painel Live collaboration, escolhe Start shared editing, introduz o email da conta Studio do autor convidado e escolhe Send invitation. Adicionar alguém à lista de autores não concede acesso por si só.', tips: ['A pessoa convidada inicia sessão no Studio com o mesmo email e aceita ou recusa o convite no canto superior direito.', 'A ligação recebida por email é uma forma alternativa de abrir o convite; a aceitação continua a exigir a conta correspondente.', 'Depois de aceitar, abra no Studio o mesmo manuscrito OMI. A caixa de entrada não aparece sem convite pendente ou quando a funcionalidade está desativada.'] },
  ro: { title: '21. Invitarea unui autor la colaborare', body: 'Colaborarea în timp real este disponibilă numai dacă administratorul a activat funcția pentru această instalare. În manuscrisul deschis, persoana care invită deschide panoul Live collaboration, selectează Start shared editing, introduce adresa de e-mail a contului Studio al autorului invitat și selectează Send invitation. Adăugarea unui nume în lista autorilor nu oferă acces.', tips: ['Invitatul se conectează la Studio cu aceeași adresă de e-mail și acceptă sau refuză invitația în colțul din dreapta sus.', 'Linkul din e-mail este o modalitate alternativă de a deschide invitația; acceptarea necesită tot contul corespunzător.', 'După acceptare, deschideți în Studio același manuscris OMI. Căsuța de invitații nu apare fără o invitație în așteptare sau când funcția este dezactivată.'] },
  sk: { title: '21. Pozvanie autora na spoluprácu', body: 'Spolupráca naživo je dostupná iba vtedy, keď správca zapol túto funkciu pre danú inštaláciu. V otvorenom rukopise pozývajúci otvorí panel Live collaboration, vyberie Start shared editing, zadá e-mail účtu Studio pozývaného autora a vyberie Send invitation. Pridanie mena do zoznamu autorov samo osebe prístup neudeľuje.', tips: ['Pozvaný sa prihlási do Studia rovnakým e-mailom a pozvánku prijme alebo odmietne v pravom hornom rohu.', 'E-mailový odkaz je alternatívny spôsob otvorenia pozvánky; na prijatie je stále potrebný zhodný účet.', 'Po prijatí otvorte v Studiu ten istý rukopis OMI. Doručená pošta sa nezobrazí bez čakajúcej pozvánky alebo pri vypnutej funkcii.'] },
  sl: { title: '21. Povabilo avtorju k sodelovanju', body: 'Sodelovanje v živo je na voljo samo, če je skrbnik omogočil to funkcijo za to namestitev. V odprtem rokopisu povabitelj odpre ploščo Live collaboration, izbere Start shared editing, vnese e-poštni naslov računa Studio povabljenega avtorja in izbere Send invitation. Dodajanje imena na seznam avtorjev samo po sebi ne omogoči dostopa.', tips: ['Povabljeni se prijavi v Studio z istim e-poštnim naslovom ter povabilo sprejme ali zavrne v zgornjem desnem kotu.', 'Povezava v e-poštnem sporočilu je druga možnost za odprtje povabila; za sprejem je še vedno potreben ustrezen račun.', 'Po sprejemu v Studiu odprite isti rokopis OMI. Prejeta povabila niso prikazana, če ni čakajočega povabila ali je funkcija izklopljena.'] },
  sv: { title: '21. Bjud in en författare till samarbete', body: 'Livesamarbete är bara tillgängligt när administratören har aktiverat funktionen för installationen. I det öppna manuskriptet öppnar den som bjuder in panelen Live collaboration, väljer Start shared editing, anger den inbjudna författarens e-postadress för Studio-kontot och väljer Send invitation. Att lägga till någon i författarlistan ger inte åtkomst i sig.', tips: ['Den inbjudna loggar in i Studio med samma e-postadress och accepterar eller avböjer inbjudan uppe till höger.', 'E-postlänken är ett alternativt sätt att öppna inbjudan; godkännandet kräver fortfarande rätt konto.', 'Öppna samma OMI-manuskript i Studio efter godkännandet. Inkorgen visas inte utan en väntande inbjudan eller när funktionen är avstängd.'] },
};

const collaborationAdminEnablementTip: Record<string, string> = {
  bg: 'Съвместната работа е включена по подразбиране в продукционната среда. Ако не е налична, администраторът трябва да провери дали API работи в продукционен режим, MANUSCRIPT_COLLABORATION_ENABLED не е false, миграциите на базата данни са приложени и /collaboration/ws се препраща към порт 3022. След промяна на средата рестартирайте API.',
  cs: 'Spolupráce je v produkčním prostředí ve výchozím nastavení zapnutá. Pokud není dostupná, správce má ověřit, že API běží v produkčním režimu, MANUSCRIPT_COLLABORATION_ENABLED není nastaveno na false, databázové migrace jsou aktuální a /collaboration/ws se předává na port 3022. Po změně prostředí restartujte API.',
  da: 'Samarbejde er som standard aktiveret i produktionsmiljøet. Hvis det ikke er tilgængeligt, skal serveradministratoren kontrollere, at API’et kører i produktion, at MANUSCRIPT_COLLABORATION_ENABLED ikke er false, at databasemigreringerne er gennemført, og at /collaboration/ws videresendes til port 3022. Genstart API’et efter ændringer i miljøet.',
  de: 'Die Zusammenarbeit ist in der Produktionsumgebung standardmäßig aktiviert. Falls sie nicht verfügbar ist, sollte die Serveradministration prüfen, ob die API im Produktionsmodus läuft, MANUSCRIPT_COLLABORATION_ENABLED nicht auf false steht, die Datenbankmigrationen aktuell sind und /collaboration/ws an Port 3022 weitergeleitet wird. Starten Sie die API nach Änderungen an der Umgebung neu.',
  el: 'Η συνεργασία είναι ενεργοποιημένη από προεπιλογή στο παραγωγικό περιβάλλον. Αν δεν είναι διαθέσιμη, ο διαχειριστής πρέπει να ελέγξει ότι το API εκτελείται σε παραγωγική λειτουργία, το MANUSCRIPT_COLLABORATION_ENABLED δεν είναι false, οι μεταναστεύσεις της βάσης έχουν εφαρμοστεί και η διαδρομή /collaboration/ws προωθείται στη θύρα 3022. Μετά από αλλαγή περιβάλλοντος, επανεκκινήστε το API.',
  en: 'Production Studio enables live collaboration by default. If it is unavailable, the server operator should confirm the API is running in production, MANUSCRIPT_COLLABORATION_ENABLED is not set to false, the database migrations are current, and /collaboration/ws is proxied to the API listener on port 3022. Restart the API after changing its environment.',
  es: 'La colaboración está activada de forma predeterminada en producción. Si no está disponible, el administrador debe comprobar que la API se ejecuta en producción, que MANUSCRIPT_COLLABORATION_ENABLED no está en false, que las migraciones de la base de datos están aplicadas y que /collaboration/ws se dirige al puerto 3022. Reinicia la API después de cambiar su entorno.',
  et: 'Koostöö on tootmiskeskkonnas vaikimisi lubatud. Kui see pole saadaval, kontrolligu serveri haldur, et API töötab tootmisrežiimis, MANUSCRIPT_COLLABORATION_ENABLED pole false, andmebaasi migratsioonid on rakendatud ja /collaboration/ws suunatakse porti 3022. Pärast keskkonna muutmist käivita API uuesti.',
  fi: 'Yhteistyö on tuotantoympäristössä oletusarvoisesti käytössä. Jos se ei ole saatavilla, palvelimen ylläpitäjän tulee tarkistaa, että API toimii tuotantotilassa, MANUSCRIPT_COLLABORATION_ENABLED ei ole false, tietokantamigraatiot on tehty ja /collaboration/ws välitetään porttiin 3022. Käynnistä API uudelleen ympäristömuutosten jälkeen.',
  fr: 'La collaboration est activée par défaut en production. Si elle est indisponible, l’administrateur doit vérifier que l’API fonctionne en mode production, que MANUSCRIPT_COLLABORATION_ENABLED n’est pas défini sur false, que les migrations de la base sont appliquées et que /collaboration/ws est redirigé vers le port 3022. Redémarrez l’API après toute modification de son environnement.',
  ga: 'Tá an comhoibriú cumasaithe de réir réamhshocraithe i dtáirgeadh. Mura bhfuil sé ar fáil, ba cheart d’oibreoir an fhreastalaí a dheimhniú go bhfuil an API ag rith i mód táirgthe, nach bhfuil MANUSCRIPT_COLLABORATION_ENABLED socraithe mar false, go bhfuil na himirceachtaí bunachair sonraí curtha i bhfeidhm agus go gcuirtear /collaboration/ws ar aghaidh chuig port 3022. Atosaigh an API tar éis athrú timpeallachta.',
  hr: 'Suradnja je prema zadanim postavkama uključena u produkciji. Ako nije dostupna, administrator treba provjeriti radi li API u produkcijskom načinu, nije li MANUSCRIPT_COLLABORATION_ENABLED postavljen na false, jesu li migracije baze podataka primijenjene i prosljeđuje li se /collaboration/ws na port 3022. Nakon promjene okruženja ponovno pokrenite API.',
  hu: 'Éles környezetben a valós idejű együttműködés alapértelmezés szerint be van kapcsolva. Ha nem érhető el, a szerver üzemeltetője ellenőrizze, hogy az API production módban fut-e, a MANUSCRIPT_COLLABORATION_ENABLED nincs-e false értékre állítva, lefutottak-e az adatbázis-migrációk, és a /collaboration/ws útvonal az API 3022-es portjára van-e irányítva. Környezeti beállítás módosítása után újra kell indítani az API-t.',
  it: 'La collaborazione è attiva per impostazione predefinita in produzione. Se non è disponibile, l’amministratore deve verificare che l’API sia in modalità production, che MANUSCRIPT_COLLABORATION_ENABLED non sia false, che le migrazioni del database siano state applicate e che /collaboration/ws venga inoltrato alla porta 3022. Riavvia l’API dopo aver modificato l’ambiente.',
  lt: 'Gamybinėje aplinkoje bendradarbiavimas įjungtas pagal numatytuosius nustatymus. Jei jis nepasiekiamas, serverio administratorius turėtų patikrinti, ar API veikia gamybiniu režimu, MANUSCRIPT_COLLABORATION_ENABLED nėra false, duomenų bazės migracijos pritaikytos ir /collaboration/ws nukreipiamas į 3022 prievadą. Pakeitę aplinką iš naujo paleiskite API.',
  lv: 'Produkcijas vidē sadarbība pēc noklusējuma ir ieslēgta. Ja tā nav pieejama, servera operatoram jāpārbauda, vai API darbojas produkcijas režīmā, MANUSCRIPT_COLLABORATION_ENABLED nav false, datubāzes migrācijas ir izpildītas un /collaboration/ws tiek novirzīts uz 3022. portu. Pēc vides maiņas restartējiet API.',
  mt: 'Il-kollaborazzjoni hija attivata awtomatikament fil-produzzjoni. Jekk ma tkunx disponibbli, l-operatur tas-server għandu jiċċekkja li l-API qed taħdem fil-modalità tal-produzzjoni, li MANUSCRIPT_COLLABORATION_ENABLED mhuwiex false, li l-migrations tad-database ġew applikati u li /collaboration/ws jgħaddi għall-port 3022. Erġa’ ibda l-API wara bidliet fl-ambjent.',
  nl: 'Samenwerking staat standaard aan in productie. Als deze niet beschikbaar is, controleert de serverbeheerder of de API in productiemodus draait, MANUSCRIPT_COLLABORATION_ENABLED niet op false staat, de databasemigraties zijn uitgevoerd en /collaboration/ws naar poort 3022 wordt doorgestuurd. Herstart de API na wijzigingen in de omgeving.',
  pl: 'Współpraca jest domyślnie włączona w środowisku produkcyjnym. Jeśli jest niedostępna, administrator powinien sprawdzić, czy API działa w trybie produkcyjnym, MANUSCRIPT_COLLABORATION_ENABLED nie ma wartości false, migracje bazy danych zostały zastosowane, a /collaboration/ws jest przekazywane na port 3022. Po zmianie środowiska uruchom ponownie API.',
  pt: 'A colaboração está ativada por predefinição em produção. Se não estiver disponível, o administrador deve confirmar que a API está em modo de produção, que MANUSCRIPT_COLLABORATION_ENABLED não está como false, que as migrações da base de dados foram aplicadas e que /collaboration/ws é encaminhado para a porta 3022. Reinicie a API após alterar o ambiente.',
  ro: 'Colaborarea este activată implicit în producție. Dacă nu este disponibilă, administratorul trebuie să verifice dacă API-ul rulează în modul de producție, MANUSCRIPT_COLLABORATION_ENABLED nu este false, migrările bazei de date sunt aplicate și /collaboration/ws este direcționat către portul 3022. Reporniți API-ul după modificarea mediului.',
  sk: 'Spolupráca je v produkcii predvolene zapnutá. Ak nie je dostupná, správca má overiť, či API beží v produkčnom režime, MANUSCRIPT_COLLABORATION_ENABLED nie je nastavené na false, databázové migrácie sú použité a /collaboration/ws smeruje na port 3022. Po zmene prostredia reštartujte API.',
  sl: 'Sodelovanje je v produkciji privzeto omogočeno. Če ni na voljo, naj skrbnik preveri, ali API deluje v produkcijskem načinu, MANUSCRIPT_COLLABORATION_ENABLED ni nastavljen na false, so migracije zbirke podatkov izvedene in je /collaboration/ws preusmerjen na vrata 3022. Po spremembi okolja znova zaženite API.',
  sv: 'Samarbete är aktiverat som standard i produktion. Om det inte är tillgängligt bör serveroperatören kontrollera att API:t körs i produktionsläge, att MANUSCRIPT_COLLABORATION_ENABLED inte är false, att databasmigreringarna är genomförda och att /collaboration/ws vidarebefordras till port 3022. Starta om API:t efter ändringar i miljön.',
};

export function collaborationInvitationHelpTitle(locale: string): string | undefined {
  return collaborationTopic[locale]?.title;
}

export function appendCollaborationHelp(locale: string, copy: HelpCopy): HelpCopy {
  const topic = collaborationTopic[locale];
  if (!topic || copy.topics.some((existing) => existing.title === topic.title)) return copy;
  const fileTransferTip: Record<string, string> = {
    bg: 'Поканата не изпраща самия файл OMI; уверете се, че поканеният може да отвори същия ръкопис в Studio.',
    cs: 'Pozvánka nepřenáší samotný soubor OMI; zajistěte, aby pozvaný mohl ve Studiu otevřít tentýž rukopis.',
    da: 'Invitationen overfører ikke selve OMI-filen; sørg for, at den inviterede kan åbne det samme manuskript i Studio.',
    de: 'Die Einladung überträgt nicht die OMI-Datei selbst; stellen Sie sicher, dass die eingeladene Person dasselbe Manuskript in Studio öffnen kann.',
    el: 'Η πρόσκληση δεν μεταφέρει το ίδιο το αρχείο OMI· βεβαιωθείτε ότι ο προσκεκλημένος μπορεί να ανοίξει το ίδιο χειρόγραφο στο Studio.',
    en: 'The invitation does not transfer the OMI file; make sure the invitee can open that same manuscript in Studio.',
    es: 'La invitación no transfiere el archivo OMI; asegúrate de que la persona invitada pueda abrir ese mismo manuscrito en Studio.',
    et: 'Kutse ei edasta OMI-faili; veendu, et kutsutu saab Studio kaudu avada sama käsikirja.',
    fi: 'Kutsu ei siirrä OMI-tiedostoa; varmista, että kutsuttu voi avata saman käsikirjoituksen Studiossa.',
    fr: 'L’invitation ne transmet pas le fichier OMI ; assurez-vous que la personne invitée peut ouvrir ce même manuscrit dans Studio.',
    ga: 'Ní aistríonn an cuireadh an comhad OMI; cinntigh gur féidir leis an gcuireadh an lámhscríbhinn chéanna a oscailt in Studio.',
    hr: 'Poziv ne prenosi samu datoteku OMI; pobrinite se da pozvana osoba može otvoriti isti rukopis u Studiju.',
    hu: 'A meghívó nem küldi át az OMI-fájlt; gondoskodjon róla, hogy a meghívott meg tudja nyitni ugyanazt a kéziratot a Studioban.',
    it: 'L’invito non trasferisce il file OMI; assicurati che l’invitato possa aprire lo stesso manoscritto in Studio.',
    lt: 'Kvietimas neperduoda OMI failo; pasirūpinkite, kad pakviestas asmuo galėtų Studio atidaryti tą patį rankraštį.',
    lv: 'Uzaicinājums nenosūta OMI failu; pārliecinieties, ka uzaicinātais Studio var atvērt to pašu manuskriptu.',
    mt: 'L-istedina ma tittrasferix il-fajl OMI; kun żgur li l-mistieden jista’ jiftaħ l-istess manuskritt fi Studio.',
    nl: 'De uitnodiging verstuurt het OMI-bestand niet; zorg ervoor dat de genodigde hetzelfde manuscript in Studio kan openen.',
    pl: 'Zaproszenie nie przesyła pliku OMI; upewnij się, że zaproszona osoba może otworzyć ten sam manuskrypt w Studio.',
    pt: 'O convite não transfere o ficheiro OMI; certifique-se de que a pessoa convidada consegue abrir o mesmo manuscrito no Studio.',
    ro: 'Invitația nu transferă fișierul OMI; asigurați-vă că persoana invitată poate deschide același manuscris în Studio.',
    sk: 'Pozvánka neprenáša samotný súbor OMI; uistite sa, že pozvaný môže v Studiu otvoriť ten istý rukopis.',
    sl: 'Povabilo ne prenese datoteke OMI; poskrbite, da lahko povabljeni v Studiu odpre isti rokopis.',
    sv: 'Inbjudan överför inte OMI-filen; se till att den inbjudna kan öppna samma manuskript i Studio.',
  };
  return { ...copy, topics: [...copy.topics, { ...topic, tips: [...(topic.tips ?? []), fileTransferTip[locale], collaborationAdminEnablementTip[locale]] }] };
}
