export interface LinkedIdentitiesCopy {
  title: string;
  description: string;
  local: string;
  available: string;
  notSet: string;
  passwordAction: string;
  passwordSent: string;
  linked: string;
  connect: string;
  disconnect: string;
  connectedAt: string;
  lastUsed: string;
  issuer: string;
  cannotDisconnect: string;
  confirmDisconnect: string;
  providers: string;
  none: string;
  refresh: string;
  loading: string;
  error: string;
  providerError: string;
}

export const linkedIdentitiesTranslations: Record<string, LinkedIdentitiesCopy> = {
  bg: {
    title: 'Свързани идентичности', description: 'Управлявайте идентификационните данни и външните идентичности, с които може да се влиза в този Studio профил.', local: 'Имейл и парола', available: 'Налично', notSet: 'Не е зададено', passwordAction: 'Задаване / смяна на парола', passwordSent: 'Изпратена е връзка за задаване на парола, ако този имейл адрес може да получава писма от Studio.', linked: 'Свързано', connect: 'Свързване', disconnect: 'Прекъсване', connectedAt: 'Свързано', lastUsed: 'Последно използвано', issuer: 'Издател', cannotDisconnect: 'Добавете друг начин за вход или задайте парола, преди да прекъснете тази идентичност.', confirmDisconnect: 'Да се прекъсне ли тази идентичност от Studio профила?', providers: 'Налични доставчици за вход', none: 'В момента няма допълнителен доставчик.', refresh: 'Обновяване', loading: 'Зареждане на свързаните идентичности…', error: 'Настройките на свързаните идентичности не можаха да се заредят.', providerError: 'Външният доставчик за вход не можа да бъде отворен.',
  },
  cs: {
    title: 'Propojené identity', description: 'Spravujte přihlašovací údaje a externí identity, kterými se lze přihlásit k tomuto účtu Studio.', local: 'E-mail a heslo', available: 'Dostupné', notSet: 'Nenastaveno', passwordAction: 'Nastavit / změnit heslo', passwordSent: 'Odkaz pro nastavení hesla byl odeslán, pokud tato e-mailová adresa může přijímat zprávy ze Studia.', linked: 'Propojeno', connect: 'Propojit', disconnect: 'Odpojit', connectedAt: 'Propojeno', lastUsed: 'Naposledy použito', issuer: 'Vydavatel', cannotDisconnect: 'Před odpojením této identity přidejte jiný způsob přihlášení nebo nastavte heslo.', confirmDisconnect: 'Odpojit tuto identitu od účtu Studio?', providers: 'Dostupní poskytovatelé přihlášení', none: 'Aktuálně není k dispozici žádný další poskytovatel.', refresh: 'Obnovit', loading: 'Načítání propojených identit…', error: 'Nastavení propojených identit se nepodařilo načíst.', providerError: 'Externího poskytovatele přihlášení se nepodařilo otevřít.',
  },
  da: {
    title: 'Tilknyttede identiteter', description: 'Administrer legitimationsoplysninger og eksterne identiteter, der kan bruges til at logge ind på denne Studio-konto.', local: 'E-mail og adgangskode', available: 'Tilgængelig', notSet: 'Ikke angivet', passwordAction: 'Angiv / skift adgangskode', passwordSent: 'Et link til opsætning af adgangskode er sendt, hvis denne e-mailadresse kan modtage Studio-mail.', linked: 'Tilknyttet', connect: 'Tilknyt', disconnect: 'Fjern tilknytning', connectedAt: 'Tilknyttet', lastUsed: 'Sidst brugt', issuer: 'Udsteder', cannotDisconnect: 'Tilføj en anden loginmetode eller angiv en adgangskode, før denne identitet fjernes.', confirmDisconnect: 'Fjern denne identitet fra din Studio-konto?', providers: 'Tilgængelige loginudbydere', none: 'Der er ingen yderligere udbyder tilgængelig i øjeblikket.', refresh: 'Opdater', loading: 'Indlæser tilknyttede identiteter…', error: 'Indstillingerne for tilknyttede identiteter kunne ikke indlæses.', providerError: 'Den eksterne loginudbyder kunne ikke åbnes.',
  },
  de: {
    title: 'Verknüpfte Identitäten', description: 'Verwalten Sie die Anmeldemethoden und externen Identitäten, mit denen dieses Studio-Konto verwendet werden kann.', local: 'E-Mail-Adresse und Passwort', available: 'Verfügbar', notSet: 'Nicht eingerichtet', passwordAction: 'Passwort einrichten / ändern', passwordSent: 'Ein Link zum Einrichten des Passworts wurde gesendet, sofern Studio E-Mails an diese Adresse zustellen kann.', linked: 'Verbunden', connect: 'Verbinden', disconnect: 'Trennen', connectedAt: 'Verbunden', lastUsed: 'Zuletzt verwendet', issuer: 'Aussteller', cannotDisconnect: 'Richten Sie zuerst eine weitere Anmeldemethode oder ein Passwort ein.', confirmDisconnect: 'Diese Identität vom Studio-Konto trennen?', providers: 'Verfügbare Anmeldeanbieter', none: 'Derzeit ist kein weiterer Anbieter verfügbar.', refresh: 'Aktualisieren', loading: 'Verknüpfte Identitäten werden geladen…', error: 'Die Einstellungen für verknüpfte Identitäten konnten nicht geladen werden.', providerError: 'Der externe Anmeldeanbieter konnte nicht geöffnet werden.',
  },
  el: {
    title: 'Συνδεδεμένες ταυτότητες', description: 'Διαχειριστείτε τα διαπιστευτήρια και τις εξωτερικές ταυτότητες που μπορούν να συνδεθούν σε αυτόν τον λογαριασμό Studio.', local: 'E-mail και κωδικός πρόσβασης', available: 'Διαθέσιμο', notSet: 'Δεν έχει οριστεί', passwordAction: 'Ορισμός / αλλαγή κωδικού', passwordSent: 'Στάλθηκε σύνδεσμος ρύθμισης κωδικού, εφόσον αυτή η διεύθυνση μπορεί να λαμβάνει μηνύματα από το Studio.', linked: 'Συνδεδεμένη', connect: 'Σύνδεση', disconnect: 'Αποσύνδεση', connectedAt: 'Συνδεδεμένη', lastUsed: 'Τελευταία χρήση', issuer: 'Εκδότης', cannotDisconnect: 'Προσθέστε άλλη μέθοδο σύνδεσης ή ορίστε κωδικό πριν αποσυνδέσετε αυτή την ταυτότητα.', confirmDisconnect: 'Να αποσυνδεθεί αυτή η ταυτότητα από τον λογαριασμό Studio;', providers: 'Διαθέσιμοι πάροχοι σύνδεσης', none: 'Δεν υπάρχει άλλος διαθέσιμος πάροχος αυτή τη στιγμή.', refresh: 'Ανανέωση', loading: 'Φόρτωση συνδεδεμένων ταυτοτήτων…', error: 'Δεν ήταν δυνατή η φόρτωση των ρυθμίσεων συνδεδεμένων ταυτοτήτων.', providerError: 'Δεν ήταν δυνατό το άνοιγμα του εξωτερικού παρόχου σύνδεσης.',
  },
  en: {
    title: 'Connected identities', description: 'Manage the credentials and external identities that can sign in to this Studio account.', local: 'E-mail and password', available: 'Available', notSet: 'Not set', passwordAction: 'Set / change password', passwordSent: 'A password setup link was sent if this e-mail address can receive Studio mail.', linked: 'Connected', connect: 'Connect', disconnect: 'Disconnect', connectedAt: 'Connected', lastUsed: 'Last used', issuer: 'Issuer', cannotDisconnect: 'Add another sign-in method or set a password before disconnecting this identity.', confirmDisconnect: 'Disconnect this identity from your Studio account?', providers: 'Available sign-in providers', none: 'No additional provider is currently available.', refresh: 'Refresh', loading: 'Loading connected identities…', error: 'The linked identity settings could not be loaded.', providerError: 'The external sign-in provider could not be opened.',
  },
  es: {
    title: 'Identidades conectadas', description: 'Gestione las credenciales e identidades externas que pueden iniciar sesión en esta cuenta de Studio.', local: 'Correo y contraseña', available: 'Disponible', notSet: 'No configurado', passwordAction: 'Establecer / cambiar contraseña', passwordSent: 'Se envió un enlace para configurar la contraseña si esta dirección puede recibir correo de Studio.', linked: 'Conectada', connect: 'Conectar', disconnect: 'Desconectar', connectedAt: 'Conectada', lastUsed: 'Último uso', issuer: 'Emisor', cannotDisconnect: 'Añada otro método de inicio de sesión o establezca una contraseña antes de desconectar esta identidad.', confirmDisconnect: '¿Desconectar esta identidad de su cuenta de Studio?', providers: 'Proveedores de inicio de sesión disponibles', none: 'No hay ningún proveedor adicional disponible actualmente.', refresh: 'Actualizar', loading: 'Cargando identidades conectadas…', error: 'No se pudieron cargar los ajustes de identidades conectadas.', providerError: 'No se pudo abrir el proveedor externo de inicio de sesión.',
  },
  et: {
    title: 'Seotud identiteedid', description: 'Hallake sisselogimisandmeid ja väliseid identiteete, millega saab sellele Studio kontole sisse logida.', local: 'E-post ja parool', available: 'Saadaval', notSet: 'Määramata', passwordAction: 'Määra / muuda parooli', passwordSent: 'Parooli seadistamise link saadeti, kui see e-posti aadress saab Studio kirju vastu võtta.', linked: 'Seotud', connect: 'Ühenda', disconnect: 'Katkesta ühendus', connectedAt: 'Seotud', lastUsed: 'Viimati kasutatud', issuer: 'Väljastaja', cannotDisconnect: 'Enne selle identiteedi eemaldamist lisage teine sisselogimisviis või määrake parool.', confirmDisconnect: 'Kas eemaldada see identiteet Studio kontolt?', providers: 'Saadaolevad sisselogimisteenused', none: 'Praegu ei ole ühtegi täiendavat teenust saadaval.', refresh: 'Värskenda', loading: 'Seotud identiteetide laadimine…', error: 'Seotud identiteetide seadeid ei saanud laadida.', providerError: 'Välist sisselogimisteenust ei saanud avada.',
  },
  fi: {
    title: 'Yhdistetyt identiteetit', description: 'Hallitse tunnuksia ja ulkoisia identiteettejä, joilla tähän Studio-tiliin voi kirjautua.', local: 'Sähköposti ja salasana', available: 'Käytettävissä', notSet: 'Ei asetettu', passwordAction: 'Aseta / vaihda salasana', passwordSent: 'Salasanan määrityslinkki lähetettiin, jos tämä sähköpostiosoite voi vastaanottaa Studio-viestejä.', linked: 'Yhdistetty', connect: 'Yhdistä', disconnect: 'Katkaise yhteys', connectedAt: 'Yhdistetty', lastUsed: 'Viimeksi käytetty', issuer: 'Myöntäjä', cannotDisconnect: 'Lisää toinen kirjautumistapa tai aseta salasana ennen tämän identiteetin irrottamista.', confirmDisconnect: 'Irrotetaanko tämä identiteetti Studio-tilistä?', providers: 'Käytettävissä olevat kirjautumispalvelut', none: 'Muita palveluntarjoajia ei ole tällä hetkellä käytettävissä.', refresh: 'Päivitä', loading: 'Ladataan yhdistettyjä identiteettejä…', error: 'Yhdistettyjen identiteettien asetuksia ei voitu ladata.', providerError: 'Ulkoista kirjautumispalvelua ei voitu avata.',
  },
  fr: {
    title: 'Identités connectées', description: 'Gérez les identifiants et les identités externes permettant de se connecter à ce compte Studio.', local: 'E-mail et mot de passe', available: 'Disponible', notSet: 'Non défini', passwordAction: 'Définir / modifier le mot de passe', passwordSent: 'Un lien de configuration du mot de passe a été envoyé si cette adresse peut recevoir les e-mails de Studio.', linked: 'Connectée', connect: 'Connecter', disconnect: 'Déconnecter', connectedAt: 'Connectée', lastUsed: 'Dernière utilisation', issuer: 'Émetteur', cannotDisconnect: 'Ajoutez une autre méthode de connexion ou définissez un mot de passe avant de déconnecter cette identité.', confirmDisconnect: 'Déconnecter cette identité de votre compte Studio ?', providers: 'Fournisseurs de connexion disponibles', none: 'Aucun fournisseur supplémentaire n’est actuellement disponible.', refresh: 'Actualiser', loading: 'Chargement des identités connectées…', error: 'Impossible de charger les paramètres des identités connectées.', providerError: 'Impossible d’ouvrir le fournisseur externe de connexion.',
  },
  ga: {
    title: 'Aitheantais nasctha', description: 'Bainistigh na dintiúir agus na haitheantais sheachtracha ar féidir leo síniú isteach sa chuntas Studio seo.', local: 'Ríomhphost agus pasfhocal', available: 'Ar fáil', notSet: 'Gan socrú', passwordAction: 'Socraigh / athraigh pasfhocal', passwordSent: 'Seoladh nasc socraithe pasfhocail más féidir leis an seoladh ríomhphoist seo post Studio a fháil.', linked: 'Nasctha', connect: 'Nasc', disconnect: 'Dínasc', connectedAt: 'Nasctha', lastUsed: 'Úsáid dheireanach', issuer: 'Eisitheoir', cannotDisconnect: 'Cuir modh sínithe isteach eile leis nó socraigh pasfhocal sula ndínascann tú an t-aitheantas seo.', confirmDisconnect: 'An t-aitheantas seo a dhínascadh ó do chuntas Studio?', providers: 'Soláthraithe sínithe isteach atá ar fáil', none: 'Níl aon soláthraí breise ar fáil faoi láthair.', refresh: 'Athnuaigh', loading: 'Aitheantais nasctha á lódáil…', error: 'Níorbh fhéidir socruithe na n-aitheantas nasctha a lódáil.', providerError: 'Níorbh fhéidir an soláthraí seachtrach sínithe isteach a oscailt.',
  },
  hr: {
    title: 'Povezani identiteti', description: 'Upravljajte vjerodajnicama i vanjskim identitetima kojima se može prijaviti na ovaj Studio račun.', local: 'E-pošta i lozinka', available: 'Dostupno', notSet: 'Nije postavljeno', passwordAction: 'Postavi / promijeni lozinku', passwordSent: 'Poveznica za postavljanje lozinke poslana je ako ova adresa može primati Studio poruke.', linked: 'Povezano', connect: 'Poveži', disconnect: 'Odspoji', connectedAt: 'Povezano', lastUsed: 'Posljednje korištenje', issuer: 'Izdavatelj', cannotDisconnect: 'Dodajte drugi način prijave ili postavite lozinku prije odspajanja ovog identiteta.', confirmDisconnect: 'Odspojiti ovaj identitet sa Studio računa?', providers: 'Dostupni pružatelji prijave', none: 'Trenutačno nema dodatnog dostupnog pružatelja.', refresh: 'Osvježi', loading: 'Učitavanje povezanih identiteta…', error: 'Postavke povezanih identiteta nije moguće učitati.', providerError: 'Vanjski pružatelj prijave nije moguće otvoriti.',
  },
  hu: {
    title: 'Kapcsolt azonosítók', description: 'Itt kezelhetők azok a hitelesítési módok és külső azonosítók, amelyekkel ebbe a Studio-fiókba be lehet jelentkezni.', local: 'E-mail-cím és jelszó', available: 'Elérhető', notSet: 'Nincs beállítva', passwordAction: 'Jelszó beállítása / módosítása', passwordSent: 'A rendszer elküldte a jelszóbeállító hivatkozást, ha erre az e-mail-címre a Studio levelet tud kézbesíteni.', linked: 'Kapcsolva', connect: 'Kapcsolás', disconnect: 'Leválasztás', connectedAt: 'Kapcsolva', lastUsed: 'Utoljára használva', issuer: 'Kibocsátó', cannotDisconnect: 'Előbb kapcsolj egy másik bejelentkezési módot vagy állíts be jelszót.', confirmDisconnect: 'Leválasztod ezt az azonosítót a Studio-fiókról?', providers: 'Elérhető bejelentkezési szolgáltatók', none: 'Jelenleg nincs további elérhető szolgáltató.', refresh: 'Frissítés', loading: 'A kapcsolt azonosítók betöltése…', error: 'A kapcsolt azonosítók beállításai nem tölthetők be.', providerError: 'A külső bejelentkezési szolgáltató nem nyitható meg.',
  },
  it: {
    title: 'Identità collegate', description: 'Gestisci le credenziali e le identità esterne che possono accedere a questo account Studio.', local: 'E-mail e password', available: 'Disponibile', notSet: 'Non impostata', passwordAction: 'Imposta / cambia password', passwordSent: 'È stato inviato un link per impostare la password se questo indirizzo può ricevere messaggi da Studio.', linked: 'Collegata', connect: 'Collega', disconnect: 'Scollega', connectedAt: 'Collegata', lastUsed: 'Ultimo utilizzo', issuer: 'Emittente', cannotDisconnect: 'Aggiungi un altro metodo di accesso o imposta una password prima di scollegare questa identità.', confirmDisconnect: 'Scollegare questa identità dall’account Studio?', providers: 'Provider di accesso disponibili', none: 'Al momento non è disponibile alcun provider aggiuntivo.', refresh: 'Aggiorna', loading: 'Caricamento delle identità collegate…', error: 'Impossibile caricare le impostazioni delle identità collegate.', providerError: 'Impossibile aprire il provider di accesso esterno.',
  },
  lt: {
    title: 'Susietos tapatybės', description: 'Tvarkykite prisijungimo duomenis ir išorines tapatybes, kuriomis galima prisijungti prie šios Studio paskyros.', local: 'El. paštas ir slaptažodis', available: 'Pasiekiama', notSet: 'Nenustatyta', passwordAction: 'Nustatyti / keisti slaptažodį', passwordSent: 'Slaptažodžio nustatymo nuoroda išsiųsta, jei šis el. pašto adresas gali gauti Studio laiškus.', linked: 'Susieta', connect: 'Susieti', disconnect: 'Atsieti', connectedAt: 'Susieta', lastUsed: 'Paskutinį kartą naudota', issuer: 'Išdavėjas', cannotDisconnect: 'Prieš atsiedami šią tapatybę pridėkite kitą prisijungimo būdą arba nustatykite slaptažodį.', confirmDisconnect: 'Atsieti šią tapatybę nuo Studio paskyros?', providers: 'Galimi prisijungimo teikėjai', none: 'Šiuo metu nėra papildomo teikėjo.', refresh: 'Atnaujinti', loading: 'Įkeliamos susietos tapatybės…', error: 'Nepavyko įkelti susietų tapatybių nustatymų.', providerError: 'Nepavyko atidaryti išorinio prisijungimo teikėjo.',
  },
  lv: {
    title: 'Saistītās identitātes', description: 'Pārvaldiet akreditācijas datus un ārējās identitātes, ar kurām var pierakstīties šajā Studio kontā.', local: 'E-pasts un parole', available: 'Pieejams', notSet: 'Nav iestatīts', passwordAction: 'Iestatīt / mainīt paroli', passwordSent: 'Paroles iestatīšanas saite tika nosūtīta, ja šī e-pasta adrese var saņemt Studio pastu.', linked: 'Saistīta', connect: 'Saistīt', disconnect: 'Atsaistīt', connectedAt: 'Saistīta', lastUsed: 'Pēdējoreiz izmantota', issuer: 'Izdevējs', cannotDisconnect: 'Pirms šīs identitātes atsaistīšanas pievienojiet citu pierakstīšanās veidu vai iestatiet paroli.', confirmDisconnect: 'Atsaistīt šo identitāti no Studio konta?', providers: 'Pieejamie pierakstīšanās pakalpojumi', none: 'Pašlaik nav pieejams neviens papildu pakalpojums.', refresh: 'Atsvaidzināt', loading: 'Notiek saistīto identitāšu ielāde…', error: 'Neizdevās ielādēt saistīto identitāšu iestatījumus.', providerError: 'Neizdevās atvērt ārējo pierakstīšanās pakalpojumu.',
  },
  mt: {
    title: 'Identitajiet konnessi', description: 'Immaniġġja l-kredenzjali u l-identitajiet esterni li jistgħu jidħlu f’dan il-kont Studio.', local: 'E-mail u password', available: 'Disponibbli', notSet: 'Mhux issettjat', passwordAction: 'Issettja / ibdel il-password', passwordSent: 'Intbagħtet link biex tiġi ssettjata l-password jekk dan l-indirizz jista’ jirċievi posta minn Studio.', linked: 'Konnessa', connect: 'Qabbad', disconnect: 'Skonnettja', connectedAt: 'Konnessa', lastUsed: 'L-aħħar użu', issuer: 'Emittent', cannotDisconnect: 'Żid metodu ieħor ta’ dħul jew issettja password qabel tiskonnettja din l-identità.', confirmDisconnect: 'Tiskonnettja din l-identità mill-kont Studio?', providers: 'Fornituri ta’ dħul disponibbli', none: 'Bħalissa m’hemm l-ebda fornitur addizzjonali disponibbli.', refresh: 'Aġġorna', loading: 'Qed jitgħabbew l-identitajiet konnessi…', error: 'Ma setgħux jitgħabbew is-settings tal-identitajiet konnessi.', providerError: 'Ma setax jinfetaħ il-fornitur estern tad-dħul.',
  },
  nl: {
    title: 'Gekoppelde identiteiten', description: 'Beheer de aanmeldgegevens en externe identiteiten waarmee op dit Studio-account kan worden ingelogd.', local: 'E-mail en wachtwoord', available: 'Beschikbaar', notSet: 'Niet ingesteld', passwordAction: 'Wachtwoord instellen / wijzigen', passwordSent: 'Er is een link voor het instellen van een wachtwoord verzonden als dit e-mailadres Studio-mail kan ontvangen.', linked: 'Gekoppeld', connect: 'Koppelen', disconnect: 'Ontkoppelen', connectedAt: 'Gekoppeld', lastUsed: 'Laatst gebruikt', issuer: 'Uitgever', cannotDisconnect: 'Voeg eerst een andere aanmeldmethode toe of stel een wachtwoord in voordat je deze identiteit ontkoppelt.', confirmDisconnect: 'Deze identiteit van je Studio-account ontkoppelen?', providers: 'Beschikbare aanmeldproviders', none: 'Er is momenteel geen extra provider beschikbaar.', refresh: 'Vernieuwen', loading: 'Gekoppelde identiteiten laden…', error: 'De instellingen voor gekoppelde identiteiten konden niet worden geladen.', providerError: 'De externe aanmeldprovider kon niet worden geopend.',
  },
  pl: {
    title: 'Połączone tożsamości', description: 'Zarządzaj poświadczeniami i zewnętrznymi tożsamościami umożliwiającymi logowanie do tego konta Studio.', local: 'E-mail i hasło', available: 'Dostępne', notSet: 'Nie ustawiono', passwordAction: 'Ustaw / zmień hasło', passwordSent: 'Link do ustawienia hasła został wysłany, jeśli ten adres może odbierać wiadomości Studio.', linked: 'Połączona', connect: 'Połącz', disconnect: 'Odłącz', connectedAt: 'Połączona', lastUsed: 'Ostatnio używana', issuer: 'Wystawca', cannotDisconnect: 'Przed odłączeniem tej tożsamości dodaj inną metodę logowania lub ustaw hasło.', confirmDisconnect: 'Odłączyć tę tożsamość od konta Studio?', providers: 'Dostępni dostawcy logowania', none: 'Obecnie nie ma dodatkowego dostępnego dostawcy.', refresh: 'Odśwież', loading: 'Ładowanie połączonych tożsamości…', error: 'Nie udało się załadować ustawień połączonych tożsamości.', providerError: 'Nie udało się otworzyć zewnętrznego dostawcy logowania.',
  },
  pt: {
    title: 'Identidades associadas', description: 'Gira as credenciais e identidades externas que podem iniciar sessão nesta conta do Studio.', local: 'E-mail e palavra-passe', available: 'Disponível', notSet: 'Não definida', passwordAction: 'Definir / alterar palavra-passe', passwordSent: 'Foi enviada uma ligação para definir a palavra-passe se este endereço puder receber correio do Studio.', linked: 'Associada', connect: 'Associar', disconnect: 'Desassociar', connectedAt: 'Associada', lastUsed: 'Última utilização', issuer: 'Emissor', cannotDisconnect: 'Adicione outro método de início de sessão ou defina uma palavra-passe antes de desassociar esta identidade.', confirmDisconnect: 'Desassociar esta identidade da sua conta Studio?', providers: 'Fornecedores de início de sessão disponíveis', none: 'Não existe atualmente nenhum fornecedor adicional disponível.', refresh: 'Atualizar', loading: 'A carregar identidades associadas…', error: 'Não foi possível carregar as definições das identidades associadas.', providerError: 'Não foi possível abrir o fornecedor externo de início de sessão.',
  },
  ro: {
    title: 'Identități conectate', description: 'Gestionați acreditările și identitățile externe care se pot autentifica în acest cont Studio.', local: 'E-mail și parolă', available: 'Disponibil', notSet: 'Nesetat', passwordAction: 'Setează / schimbă parola', passwordSent: 'A fost trimis un link pentru setarea parolei dacă această adresă poate primi mesaje Studio.', linked: 'Conectată', connect: 'Conectează', disconnect: 'Deconectează', connectedAt: 'Conectată', lastUsed: 'Ultima utilizare', issuer: 'Emitent', cannotDisconnect: 'Adăugați o altă metodă de autentificare sau setați o parolă înainte de a deconecta această identitate.', confirmDisconnect: 'Deconectați această identitate de la contul Studio?', providers: 'Furnizori de autentificare disponibili', none: 'Nu există momentan niciun furnizor suplimentar disponibil.', refresh: 'Reîmprospătează', loading: 'Se încarcă identitățile conectate…', error: 'Setările identităților conectate nu au putut fi încărcate.', providerError: 'Furnizorul extern de autentificare nu a putut fi deschis.',
  },
  sk: {
    title: 'Prepojené identity', description: 'Spravujte prihlasovacie údaje a externé identity, ktorými sa možno prihlásiť do tohto účtu Studio.', local: 'E-mail a heslo', available: 'Dostupné', notSet: 'Nenastavené', passwordAction: 'Nastaviť / zmeniť heslo', passwordSent: 'Odkaz na nastavenie hesla bol odoslaný, ak táto e-mailová adresa môže prijímať správy zo Studia.', linked: 'Prepojená', connect: 'Prepojiť', disconnect: 'Odpojiť', connectedAt: 'Prepojená', lastUsed: 'Naposledy použitá', issuer: 'Vydavateľ', cannotDisconnect: 'Pred odpojením tejto identity pridajte iný spôsob prihlásenia alebo nastavte heslo.', confirmDisconnect: 'Odpojiť túto identitu od účtu Studio?', providers: 'Dostupní poskytovatelia prihlásenia', none: 'Momentálne nie je k dispozícii žiadny ďalší poskytovateľ.', refresh: 'Obnoviť', loading: 'Načítavajú sa prepojené identity…', error: 'Nastavenia prepojených identít sa nepodarilo načítať.', providerError: 'Externého poskytovateľa prihlásenia sa nepodarilo otvoriť.',
  },
  sl: {
    title: 'Povezane identitete', description: 'Upravljajte poverilnice in zunanje identitete, s katerimi se je mogoče prijaviti v ta račun Studio.', local: 'E-pošta in geslo', available: 'Na voljo', notSet: 'Ni nastavljeno', passwordAction: 'Nastavi / spremeni geslo', passwordSent: 'Povezava za nastavitev gesla je bila poslana, če ta naslov lahko prejema sporočila Studia.', linked: 'Povezana', connect: 'Poveži', disconnect: 'Prekini povezavo', connectedAt: 'Povezana', lastUsed: 'Nazadnje uporabljena', issuer: 'Izdajatelj', cannotDisconnect: 'Pred prekinitvijo te identitete dodajte drug način prijave ali nastavite geslo.', confirmDisconnect: 'Prekiniti povezavo te identitete z računom Studio?', providers: 'Razpoložljivi ponudniki prijave', none: 'Trenutno ni na voljo dodatnega ponudnika.', refresh: 'Osveži', loading: 'Nalaganje povezanih identitet…', error: 'Nastavitev povezanih identitet ni bilo mogoče naložiti.', providerError: 'Zunanjega ponudnika prijave ni bilo mogoče odpreti.',
  },
  sv: {
    title: 'Anslutna identiteter', description: 'Hantera inloggningsuppgifter och externa identiteter som kan logga in på detta Studio-konto.', local: 'E-post och lösenord', available: 'Tillgängligt', notSet: 'Inte inställt', passwordAction: 'Ange / ändra lösenord', passwordSent: 'En länk för att ange lösenord skickades om den här e-postadressen kan ta emot Studio-post.', linked: 'Ansluten', connect: 'Anslut', disconnect: 'Koppla från', connectedAt: 'Ansluten', lastUsed: 'Senast använd', issuer: 'Utfärdare', cannotDisconnect: 'Lägg till en annan inloggningsmetod eller ange ett lösenord innan du kopplar från denna identitet.', confirmDisconnect: 'Koppla från denna identitet från ditt Studio-konto?', providers: 'Tillgängliga inloggningsleverantörer', none: 'Ingen ytterligare leverantör är tillgänglig just nu.', refresh: 'Uppdatera', loading: 'Läser in anslutna identiteter…', error: 'Inställningarna för anslutna identiteter kunde inte läsas in.', providerError: 'Den externa inloggningsleverantören kunde inte öppnas.',
  },
};

export function getLinkedIdentitiesCopy(locale: string): LinkedIdentitiesCopy {
  return linkedIdentitiesTranslations[locale] ?? linkedIdentitiesTranslations.en;
}
