export interface PersonalPublishingCredentialsCopy {
  title: string;
  description: string;
  savedConnections: string;
  none: string;
  addTitle: string;
  provider: string;
  label: string;
  labelPlaceholder: string;
  baseUrl: string;
  apiKey: string;
  apiKeyPlaceholder: string;
  save: string;
  saved: string;
  remove: string;
  security: string;
  replaceHint: string;
  ojs: string;
  omp: string;
  removeConfirmation: (name: string) => string;
}

const en: PersonalPublishingCredentialsCopy = {
  title: 'OJS / OMP API keys',
  description: 'Save a separate personal API key for each OJS or OMP installation you use.',
  savedConnections: 'Saved installations',
  none: 'No personal publishing API key has been saved yet.',
  addTitle: 'Add or replace an API key',
  provider: 'Publishing system',
  label: 'Name',
  labelPlaceholder: 'Optional name, for example Journal editorial site',
  baseUrl: 'Installation URL',
  apiKey: 'Personal API key',
  apiKeyPlaceholder: 'API key',
  save: 'Save API key',
  saved: 'The API key was saved.',
  remove: 'Remove',
  security: 'Keys are encrypted in the separate personal profile database and are never displayed again.',
  replaceHint: 'Saving the same system and URL again replaces only that installation’s key.',
  ojs: 'OJS',
  omp: 'OMP',
  removeConfirmation: (name) => `Remove the saved API key for ${name}?`,
};

const translations: Record<string, PersonalPublishingCredentialsCopy> = {
  bg: { ...en, title: 'OJS / OMP API ключове', description: 'Запазете отделен личен API ключ за всяка OJS или OMP инсталация.', savedConnections: 'Запазени инсталации', none: 'Все още няма запазен личен API ключ.', addTitle: 'Добавяне или замяна на API ключ', provider: 'Система за публикуване', label: 'Име', labelPlaceholder: 'Незадължително име', baseUrl: 'URL на инсталацията', apiKey: 'Личен API ключ', apiKeyPlaceholder: 'API ключ', save: 'Запази API ключа', saved: 'API ключът е запазен.', remove: 'Премахни', security: 'Ключовете се съхраняват криптирано в отделната база данни на личния профил и никога не се показват отново.', replaceHint: 'Повторното запазване на същата система и URL заменя само ключа за тази инсталация.', removeConfirmation: (name) => `Премахване на запазения API ключ за ${name}?` },
  cs: { ...en, title: 'API klíče OJS / OMP', description: 'Uložte samostatný osobní API klíč pro každou instalaci OJS nebo OMP.', savedConnections: 'Uložené instalace', none: 'Zatím není uložen žádný osobní publikační API klíč.', addTitle: 'Přidat nebo nahradit API klíč', provider: 'Publikační systém', label: 'Název', labelPlaceholder: 'Volitelný název', baseUrl: 'URL instalace', apiKey: 'Osobní API klíč', apiKeyPlaceholder: 'API klíč', save: 'Uložit API klíč', saved: 'API klíč byl uložen.', remove: 'Odebrat', security: 'Klíče jsou šifrovány v oddělené databázi osobního profilu a nikdy se znovu nezobrazují.', replaceHint: 'Opětovné uložení stejného systému a URL nahradí pouze klíč této instalace.', removeConfirmation: (name) => `Odebrat uložený API klíč pro ${name}?` },
  da: { ...en, title: 'OJS / OMP API-nøgler', description: 'Gem en separat personlig API-nøgle for hver OJS- eller OMP-installation.', savedConnections: 'Gemte installationer', none: 'Der er endnu ikke gemt en personlig publicerings-API-nøgle.', addTitle: 'Tilføj eller erstat en API-nøgle', provider: 'Publiceringssystem', label: 'Navn', labelPlaceholder: 'Valgfrit navn', baseUrl: 'Installations-URL', apiKey: 'Personlig API-nøgle', apiKeyPlaceholder: 'API-nøgle', save: 'Gem API-nøgle', saved: 'API-nøglen er gemt.', remove: 'Fjern', security: 'Nøgler krypteres i den separate personlige profildatabase og vises aldrig igen.', replaceHint: 'Hvis samme system og URL gemmes igen, erstattes kun nøglen for den installation.', removeConfirmation: (name) => `Fjern den gemte API-nøgle for ${name}?` },
  de: { ...en, title: 'OJS-/OMP-API-Schlüssel', description: 'Speichern Sie für jede verwendete OJS- oder OMP-Installation einen eigenen persönlichen API-Schlüssel.', savedConnections: 'Gespeicherte Installationen', none: 'Noch kein persönlicher Publikations-API-Schlüssel gespeichert.', addTitle: 'API-Schlüssel hinzufügen oder ersetzen', provider: 'Publikationssystem', label: 'Name', labelPlaceholder: 'Optionaler Name', baseUrl: 'Installations-URL', apiKey: 'Persönlicher API-Schlüssel', apiKeyPlaceholder: 'API-Schlüssel', save: 'API-Schlüssel speichern', saved: 'Der API-Schlüssel wurde gespeichert.', remove: 'Entfernen', security: 'Die Schlüssel werden verschlüsselt in der getrennten persönlichen Profildatenbank gespeichert und nie wieder angezeigt.', replaceHint: 'Erneutes Speichern desselben Systems und derselben URL ersetzt nur den Schlüssel dieser Installation.', removeConfirmation: (name) => `Gespeicherten API-Schlüssel für ${name} entfernen?` },
  el: { ...en, title: 'Κλειδιά API OJS / OMP', description: 'Αποθηκεύστε ξεχωριστό προσωπικό κλειδί API για κάθε εγκατάσταση OJS ή OMP.', savedConnections: 'Αποθηκευμένες εγκαταστάσεις', none: 'Δεν έχει αποθηκευτεί ακόμη προσωπικό κλειδί API δημοσίευσης.', addTitle: 'Προσθήκη ή αντικατάσταση κλειδιού API', provider: 'Σύστημα δημοσίευσης', label: 'Όνομα', labelPlaceholder: 'Προαιρετικό όνομα', baseUrl: 'URL εγκατάστασης', apiKey: 'Προσωπικό κλειδί API', apiKeyPlaceholder: 'Κλειδί API', save: 'Αποθήκευση κλειδιού API', saved: 'Το κλειδί API αποθηκεύτηκε.', remove: 'Κατάργηση', security: 'Τα κλειδιά αποθηκεύονται κρυπτογραφημένα στην ξεχωριστή βάση προσωπικού προφίλ και δεν εμφανίζονται ξανά.', replaceHint: 'Η εκ νέου αποθήκευση του ίδιου συστήματος και URL αντικαθιστά μόνο το κλειδί αυτής της εγκατάστασης.', removeConfirmation: (name) => `Να αφαιρεθεί το αποθηκευμένο κλειδί API για ${name};` },
  en,
  es: { ...en, title: 'Claves API de OJS / OMP', description: 'Guarde una clave API personal distinta para cada instalación de OJS u OMP que utilice.', savedConnections: 'Instalaciones guardadas', none: 'Todavía no se ha guardado ninguna clave API personal de publicación.', addTitle: 'Añadir o sustituir una clave API', provider: 'Sistema de publicación', label: 'Nombre', labelPlaceholder: 'Nombre opcional', baseUrl: 'URL de la instalación', apiKey: 'Clave API personal', apiKeyPlaceholder: 'Clave API', save: 'Guardar clave API', saved: 'La clave API se ha guardado.', remove: 'Eliminar', security: 'Las claves se almacenan cifradas en la base de datos separada del perfil personal y nunca se vuelven a mostrar.', replaceHint: 'Guardar de nuevo el mismo sistema y URL solo sustituye la clave de esa instalación.', removeConfirmation: (name) => `¿Eliminar la clave API guardada para ${name}?` },
  et: { ...en, title: 'OJS / OMP API võtmed', description: 'Salvesta iga OJS-i või OMP installatsiooni jaoks eraldi isiklik API võti.', savedConnections: 'Salvestatud installatsioonid', none: 'Isiklikku avaldamise API võtit pole veel salvestatud.', addTitle: 'Lisa või asenda API võti', provider: 'Avaldamissüsteem', label: 'Nimi', labelPlaceholder: 'Valikuline nimi', baseUrl: 'Installatsiooni URL', apiKey: 'Isiklik API võti', apiKeyPlaceholder: 'API võti', save: 'Salvesta API võti', saved: 'API võti salvestati.', remove: 'Eemalda', security: 'Võtmed salvestatakse krüptitult eraldi isikliku profiili andmebaasi ja neid ei kuvata enam.', replaceHint: 'Sama süsteemi ja URL-i uuesti salvestamine asendab ainult selle installatsiooni võtme.', removeConfirmation: (name) => `Kas eemaldada ${name} salvestatud API võti?` },
  fi: { ...en, title: 'OJS / OMP API-avaimet', description: 'Tallenna erillinen henkilökohtainen API-avain jokaiselle käyttämällesi OJS- tai OMP-asennukselle.', savedConnections: 'Tallennetut asennukset', none: 'Henkilökohtaista julkaisu-API-avainta ei ole vielä tallennettu.', addTitle: 'Lisää tai korvaa API-avain', provider: 'Julkaisujärjestelmä', label: 'Nimi', labelPlaceholder: 'Valinnainen nimi', baseUrl: 'Asennuksen URL', apiKey: 'Henkilökohtainen API-avain', apiKeyPlaceholder: 'API-avain', save: 'Tallenna API-avain', saved: 'API-avain tallennettiin.', remove: 'Poista', security: 'Avaimet tallennetaan salattuina erilliseen henkilökohtaisen profiilin tietokantaan eikä niitä näytetä uudelleen.', replaceHint: 'Saman järjestelmän ja URL-osoitteen tallentaminen uudelleen korvaa vain kyseisen asennuksen avaimen.', removeConfirmation: (name) => `Poistetaanko tallennettu API-avain kohteelle ${name}?` },
  fr: { ...en, title: 'Clés API OJS / OMP', description: 'Enregistrez une clé API personnelle distincte pour chaque installation OJS ou OMP utilisée.', savedConnections: 'Installations enregistrées', none: 'Aucune clé API personnelle de publication n’est encore enregistrée.', addTitle: 'Ajouter ou remplacer une clé API', provider: 'Système de publication', label: 'Nom', labelPlaceholder: 'Nom facultatif', baseUrl: 'URL de l’installation', apiKey: 'Clé API personnelle', apiKeyPlaceholder: 'Clé API', save: 'Enregistrer la clé API', saved: 'La clé API a été enregistrée.', remove: 'Supprimer', security: 'Les clés sont chiffrées dans la base distincte du profil personnel et ne sont jamais réaffichées.', replaceHint: 'Réenregistrer le même système et la même URL remplace uniquement la clé de cette installation.', removeConfirmation: (name) => `Supprimer la clé API enregistrée pour ${name} ?` },
  ga: { ...en, title: 'Eochracha API OJS / OMP', description: 'Sábháil eochair API phearsanta ar leith do gach suiteáil OJS nó OMP.', savedConnections: 'Suiteálacha sábháilte', none: 'Níl eochair API foilsitheoireachta phearsanta sábháilte fós.', addTitle: 'Cuir eochair API leis nó cuir ina hionad í', provider: 'Córas foilsitheoireachta', label: 'Ainm', labelPlaceholder: 'Ainm roghnach', baseUrl: 'URL na suiteála', apiKey: 'Eochair API phearsanta', apiKeyPlaceholder: 'Eochair API', save: 'Sábháil eochair API', saved: 'Sábháladh an eochair API.', remove: 'Bain', security: 'Stóráiltear na heochracha criptithe sa bhunachar próifíle pearsanta ar leith agus ní thaispeántar arís iad.', replaceHint: 'Má shábháiltear an córas agus an URL céanna arís, ní chuirtear ach eochair na suiteála sin ina hionad.', removeConfirmation: (name) => `Bain an eochair API shábháilte do ${name}?` },
  hr: { ...en, title: 'OJS / OMP API ključevi', description: 'Spremite zaseban osobni API ključ za svaku OJS ili OMP instalaciju.', savedConnections: 'Spremljene instalacije', none: 'Još nije spremljen osobni API ključ za objavljivanje.', addTitle: 'Dodaj ili zamijeni API ključ', provider: 'Sustav za objavljivanje', label: 'Naziv', labelPlaceholder: 'Neobavezni naziv', baseUrl: 'URL instalacije', apiKey: 'Osobni API ključ', apiKeyPlaceholder: 'API ključ', save: 'Spremi API ključ', saved: 'API ključ je spremljen.', remove: 'Ukloni', security: 'Ključevi se šifrirano čuvaju u zasebnoj bazi osobnog profila i više se ne prikazuju.', replaceHint: 'Ponovno spremanje istog sustava i URL-a zamjenjuje samo ključ te instalacije.', removeConfirmation: (name) => `Ukloniti spremljeni API ključ za ${name}?` },
  hu: { ...en, title: 'OJS / OMP API-kulcsok', description: 'Minden használt OJS- vagy OMP-telepítéshez külön személyes API-kulcs menthető.', savedConnections: 'Mentett telepítések', none: 'Még nincs elmentett személyes publikációs API-kulcs.', addTitle: 'API-kulcs hozzáadása vagy cseréje', provider: 'Publikációs rendszer', label: 'Név', labelPlaceholder: 'Opcionális név, például Egyháztörténeti Szemle', baseUrl: 'Telepítés URL-je', apiKey: 'Személyes API-kulcs', apiKeyPlaceholder: 'API-kulcs', save: 'API-kulcs mentése', saved: 'Az API-kulcs elmentve.', remove: 'Törlés', security: 'A kulcsok a különálló személyes profiladatbázisban titkosítva tárolódnak, és később sem jelenítjük meg őket.', replaceHint: 'Ugyanazt a rendszert és URL-t újra mentve csak az adott telepítés kulcsa cserélődik.', removeConfirmation: (name) => `Törlöd a(z) ${name} telepítés mentett API-kulcsát?` },
  it: { ...en, title: 'Chiavi API OJS / OMP', description: 'Salva una chiave API personale separata per ogni installazione OJS o OMP utilizzata.', savedConnections: 'Installazioni salvate', none: 'Non è ancora stata salvata alcuna chiave API personale di pubblicazione.', addTitle: 'Aggiungi o sostituisci una chiave API', provider: 'Sistema di pubblicazione', label: 'Nome', labelPlaceholder: 'Nome facoltativo', baseUrl: 'URL installazione', apiKey: 'Chiave API personale', apiKeyPlaceholder: 'Chiave API', save: 'Salva chiave API', saved: 'La chiave API è stata salvata.', remove: 'Rimuovi', security: 'Le chiavi sono cifrate nel database separato del profilo personale e non vengono mai mostrate di nuovo.', replaceHint: 'Salvare di nuovo lo stesso sistema e URL sostituisce solo la chiave di quella installazione.', removeConfirmation: (name) => `Rimuovere la chiave API salvata per ${name}?` },
  lt: { ...en, title: 'OJS / OMP API raktai', description: 'Kiekvienai naudojamai OJS ar OMP diegčiai išsaugokite atskirą asmeninį API raktą.', savedConnections: 'Išsaugotos diegtys', none: 'Asmeninis publikavimo API raktas dar neišsaugotas.', addTitle: 'Pridėti arba pakeisti API raktą', provider: 'Publikavimo sistema', label: 'Pavadinimas', labelPlaceholder: 'Pasirenkamas pavadinimas', baseUrl: 'Diegties URL', apiKey: 'Asmeninis API raktas', apiKeyPlaceholder: 'API raktas', save: 'Išsaugoti API raktą', saved: 'API raktas išsaugotas.', remove: 'Pašalinti', security: 'Raktai šifruojami atskiroje asmeninio profilio duomenų bazėje ir daugiau nerodomi.', replaceHint: 'Pakartotinai išsaugojus tą pačią sistemą ir URL pakeičiamas tik tos diegties raktas.', removeConfirmation: (name) => `Pašalinti išsaugotą ${name} API raktą?` },
  lv: { ...en, title: 'OJS / OMP API atslēgas', description: 'Saglabājiet atsevišķu personīgo API atslēgu katrai OJS vai OMP instalācijai.', savedConnections: 'Saglabātās instalācijas', none: 'Vēl nav saglabāta personīgā publicēšanas API atslēga.', addTitle: 'Pievienot vai aizstāt API atslēgu', provider: 'Publicēšanas sistēma', label: 'Nosaukums', labelPlaceholder: 'Neobligāts nosaukums', baseUrl: 'Instalācijas URL', apiKey: 'Personīgā API atslēga', apiKeyPlaceholder: 'API atslēga', save: 'Saglabāt API atslēgu', saved: 'API atslēga saglabāta.', remove: 'Noņemt', security: 'Atslēgas tiek glabātas šifrēti atsevišķajā personīgā profila datubāzē un vairs netiek rādītas.', replaceHint: 'Atkārtoti saglabājot to pašu sistēmu un URL, tiek aizstāta tikai šīs instalācijas atslēga.', removeConfirmation: (name) => `Noņemt saglabāto API atslēgu ${name}?` },
  mt: { ...en, title: 'Ċwievet API OJS / OMP', description: 'Issejvja ċavetta API personali separata għal kull installazzjoni OJS jew OMP.', savedConnections: 'Installazzjonijiet issejvjati', none: 'Għadha ma ġietx issejvjata ċavetta API personali tal-pubblikazzjoni.', addTitle: 'Żid jew ibdel ċavetta API', provider: 'Sistema ta’ pubblikazzjoni', label: 'Isem', labelPlaceholder: 'Isem fakultattiv', baseUrl: 'URL tal-installazzjoni', apiKey: 'Ċavetta API personali', apiKeyPlaceholder: 'Ċavetta API', save: 'Issejvja ċ-ċavetta API', saved: 'Iċ-ċavetta API ġiet issejvjata.', remove: 'Neħħi', security: 'Iċ-ċwievet jinżammu kriptati fid-database separata tal-profil personali u qatt ma jerġgħu jintwerew.', replaceHint: 'Jekk terġa’ ssalva l-istess sistema u URL, tinbidel biss iċ-ċavetta ta’ dik l-installazzjoni.', removeConfirmation: (name) => `Tneħħi ċ-ċavetta API issejvjata għal ${name}?` },
  nl: { ...en, title: 'OJS / OMP API-sleutels', description: 'Sla voor elke gebruikte OJS- of OMP-installatie een aparte persoonlijke API-sleutel op.', savedConnections: 'Opgeslagen installaties', none: 'Er is nog geen persoonlijke publicatie-API-sleutel opgeslagen.', addTitle: 'API-sleutel toevoegen of vervangen', provider: 'Publicatiesysteem', label: 'Naam', labelPlaceholder: 'Optionele naam', baseUrl: 'Installatie-URL', apiKey: 'Persoonlijke API-sleutel', apiKeyPlaceholder: 'API-sleutel', save: 'API-sleutel opslaan', saved: 'De API-sleutel is opgeslagen.', remove: 'Verwijderen', security: 'Sleutels worden versleuteld opgeslagen in de aparte persoonlijke profieldatabase en nooit opnieuw weergegeven.', replaceHint: 'Hetzelfde systeem en dezelfde URL opnieuw opslaan vervangt alleen de sleutel van die installatie.', removeConfirmation: (name) => `Opgeslagen API-sleutel voor ${name} verwijderen?` },
  pl: { ...en, title: 'Klucze API OJS / OMP', description: 'Zapisz osobny osobisty klucz API dla każdej używanej instalacji OJS lub OMP.', savedConnections: 'Zapisane instalacje', none: 'Nie zapisano jeszcze osobistego klucza API publikowania.', addTitle: 'Dodaj lub zastąp klucz API', provider: 'System publikacyjny', label: 'Nazwa', labelPlaceholder: 'Opcjonalna nazwa', baseUrl: 'URL instalacji', apiKey: 'Osobisty klucz API', apiKeyPlaceholder: 'Klucz API', save: 'Zapisz klucz API', saved: 'Klucz API został zapisany.', remove: 'Usuń', security: 'Klucze są szyfrowane w oddzielnej bazie profilu osobistego i nigdy nie są ponownie wyświetlane.', replaceHint: 'Ponowne zapisanie tego samego systemu i URL zastępuje tylko klucz tej instalacji.', removeConfirmation: (name) => `Usunąć zapisany klucz API dla ${name}?` },
  pt: { ...en, title: 'Chaves API OJS / OMP', description: 'Guarde uma chave API pessoal separada para cada instalação OJS ou OMP utilizada.', savedConnections: 'Instalações guardadas', none: 'Ainda não foi guardada nenhuma chave API pessoal de publicação.', addTitle: 'Adicionar ou substituir uma chave API', provider: 'Sistema de publicação', label: 'Nome', labelPlaceholder: 'Nome opcional', baseUrl: 'URL da instalação', apiKey: 'Chave API pessoal', apiKeyPlaceholder: 'Chave API', save: 'Guardar chave API', saved: 'A chave API foi guardada.', remove: 'Remover', security: 'As chaves são guardadas cifradas na base de dados separada do perfil pessoal e nunca voltam a ser apresentadas.', replaceHint: 'Guardar novamente o mesmo sistema e URL substitui apenas a chave dessa instalação.', removeConfirmation: (name) => `Remover a chave API guardada para ${name}?` },
  ro: { ...en, title: 'Chei API OJS / OMP', description: 'Salvați o cheie API personală separată pentru fiecare instalare OJS sau OMP utilizată.', savedConnections: 'Instalări salvate', none: 'Nu a fost salvată încă nicio cheie API personală pentru publicare.', addTitle: 'Adăugați sau înlocuiți o cheie API', provider: 'Sistem de publicare', label: 'Nume', labelPlaceholder: 'Nume opțional', baseUrl: 'URL instalare', apiKey: 'Cheie API personală', apiKeyPlaceholder: 'Cheie API', save: 'Salvați cheia API', saved: 'Cheia API a fost salvată.', remove: 'Elimină', security: 'Cheile sunt stocate criptat în baza de date separată a profilului personal și nu sunt afișate din nou.', replaceHint: 'Salvarea din nou a aceluiași sistem și URL înlocuiește doar cheia acelei instalări.', removeConfirmation: (name) => `Eliminați cheia API salvată pentru ${name}?` },
  sk: { ...en, title: 'API kľúče OJS / OMP', description: 'Uložte samostatný osobný API kľúč pre každú inštaláciu OJS alebo OMP.', savedConnections: 'Uložené inštalácie', none: 'Zatiaľ nie je uložený žiadny osobný publikačný API kľúč.', addTitle: 'Pridať alebo nahradiť API kľúč', provider: 'Publikačný systém', label: 'Názov', labelPlaceholder: 'Voliteľný názov', baseUrl: 'URL inštalácie', apiKey: 'Osobný API kľúč', apiKeyPlaceholder: 'API kľúč', save: 'Uložiť API kľúč', saved: 'API kľúč bol uložený.', remove: 'Odstrániť', security: 'Kľúče sa ukladajú šifrovane v oddelenej databáze osobného profilu a nikdy sa znova nezobrazia.', replaceHint: 'Opätovné uloženie rovnakého systému a URL nahradí iba kľúč tejto inštalácie.', removeConfirmation: (name) => `Odstrániť uložený API kľúč pre ${name}?` },
  sl: { ...en, title: 'API-ključi OJS / OMP', description: 'Za vsako namestitev OJS ali OMP shranite ločen osebni API-ključ.', savedConnections: 'Shranjene namestitve', none: 'Osebni API-ključ za objavljanje še ni shranjen.', addTitle: 'Dodaj ali zamenjaj API-ključ', provider: 'Sistem za objavljanje', label: 'Ime', labelPlaceholder: 'Izbirno ime', baseUrl: 'URL namestitve', apiKey: 'Osebni API-ključ', apiKeyPlaceholder: 'API-ključ', save: 'Shrani API-ključ', saved: 'API-ključ je shranjen.', remove: 'Odstrani', security: 'Ključi so šifrirano shranjeni v ločeni podatkovni zbirki osebnega profila in se nikoli več ne prikažejo.', replaceHint: 'Ponovno shranjevanje istega sistema in URL-ja zamenja samo ključ te namestitve.', removeConfirmation: (name) => `Odstranim shranjeni API-ključ za ${name}?` },
  sv: { ...en, title: 'OJS / OMP API-nycklar', description: 'Spara en separat personlig API-nyckel för varje OJS- eller OMP-installation du använder.', savedConnections: 'Sparade installationer', none: 'Ingen personlig publicerings-API-nyckel har sparats ännu.', addTitle: 'Lägg till eller ersätt en API-nyckel', provider: 'Publiceringssystem', label: 'Namn', labelPlaceholder: 'Valfritt namn', baseUrl: 'Installations-URL', apiKey: 'Personlig API-nyckel', apiKeyPlaceholder: 'API-nyckel', save: 'Spara API-nyckel', saved: 'API-nyckeln har sparats.', remove: 'Ta bort', security: 'Nycklar lagras krypterade i den separata personliga profildatabasen och visas aldrig igen.', replaceHint: 'Om samma system och URL sparas igen ersätts bara nyckeln för den installationen.', removeConfirmation: (name) => `Ta bort den sparade API-nyckeln för ${name}?` },
};

export function getPersonalPublishingCredentialsCopy(locale: string): PersonalPublishingCredentialsCopy {
  return translations[locale] ?? en;
}
