import { buildPublicationRenderingContext } from '../model/publicationRendering';
import { resolvePublicationProfile } from '../model/publicationProfile';
import type { OmiManuscript } from '../types/omi';
import { blockPlainText, exportFileStem, localizedPublicationLabel } from './exportTextUtils';

export interface MifExportResult {
  text: string;
  blob: Blob;
  fileName: string;
}

/** Minimal editable Maker Interchange Format document for FrameMaker. */
export function buildMifExport(manuscript: OmiManuscript): MifExportResult {
  const context = buildPublicationRenderingContext(manuscript, resolvePublicationProfile(manuscript));
  const paragraphs: string[] = [];

  paragraphs.push(mifParagraph('OMI Title', context.title));
  if (context.subtitle) paragraphs.push(mifParagraph('OMI Subtitle', context.subtitle));
  if (context.contributors.length) {
    paragraphs.push(mifParagraph('OMI Authors', context.contributors.map((item) => item.displayName).join(', ')));
  }
  if (context.abstract) {
    paragraphs.push(mifParagraph('OMI Heading 1', localizedPublicationLabel(context.locale, 'abstract')));
    paragraphs.push(mifParagraph('OMI Body', context.abstract));
  }
  if (context.keywords.length) {
    paragraphs.push(mifParagraph('OMI Metadata', `${localizedPublicationLabel(context.locale, 'keywords')}: ${context.keywords.join('; ')}`));
  }

  const renderSections = (sections: typeof context.sections) => {
    for (const section of sections) {
      const level = Math.min(6, section.depth + 1);
      paragraphs.push(mifParagraph(`OMI Heading ${level}`, section.number ? `${section.number} ${section.title}` : section.title));
      for (const block of section.blocks) {
        const text = blockPlainText(block);
        if (text) paragraphs.push(mifParagraph('OMI Body', text));
      }
      renderSections(section.children);
    }
  };
  renderSections(context.sections);

  if (manuscript.annotations.length) {
    paragraphs.push(mifParagraph('OMI Heading 1', localizedPublicationLabel(context.locale, 'notes')));
    manuscript.annotations.forEach((note, index) => paragraphs.push(mifParagraph('OMI Note', `${index + 1}. ${note.body}`)));
  }

  const catalog = [
    pgf('OMI Body', 11, 'Regular'),
    pgf('OMI Title', 24, 'Bold'),
    pgf('OMI Subtitle', 16, 'Regular'),
    pgf('OMI Authors', 11, 'Regular'),
    pgf('OMI Metadata', 10, 'Regular'),
    pgf('OMI Note', 9, 'Regular'),
    ...[1,2,3,4,5,6].map((level) => pgf(`OMI Heading ${level}`, Math.max(11, 18 - level), 'Bold')),
  ].join('\n');

  const text = `<MIFFile 16.0> # Generated by Open Manuscript Studio\n<Units Ucm>\n<PgfCatalog\n${indent(catalog, 1)}\n> # end PgfCatalog\n<TextFlow\n <TFTag \`A'>\n <TFAutoConnect Yes>\n${indent(paragraphs.join('\n'), 1)}\n> # end TextFlow\n# End of MIFFile\n`;

  return {
    text,
    blob: new Blob([text], { type: 'text/plain;charset=utf-8' }),
    fileName: `${exportFileStem(manuscript)}.mif`,
  };
}

function pgf(name: string, size: number, weight: 'Regular' | 'Bold'): string {
  return `<Pgf\n <PgfTag \`${mif(name)}'>\n <PgfFTag \`${weight === 'Bold' ? 'Bold' : ''}'>\n <PgfFont\n  <FTag \`'>\n  <FPlatformName \`Times New Roman'>\n  <FSize ${size}.0 pt>\n  <FWeight ${weight}>\n >\n>`;
}

function mifParagraph(style: string, value: string): string {
  return `<Para\n <PgfTag \`${mif(style)}'>\n <ParaLine\n  <String \`${mif(value)}'>\n >\n>`;
}

function mif(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/>/g, '\\>')
    .replace(/\r?\n/g, '\\n');
}

function indent(value: string, depth: number): string {
  const prefix = ' '.repeat(depth);
  return value.split('\n').map((line) => `${prefix}${line}`).join('\n');
}
