import {
  extractOmiInlineRuns,
  type OmiInlineRun,
  type OmiInlineSemanticKind,
} from '../model/inlineSemantics';
import { buildPublicationRenderingContext } from '../model/publicationRendering';
import { resolvePublicationProfile } from '../model/publicationProfile';
import type { OmiManuscript } from '../types/omi';
import { blockPlainText, exportFileStem, localizedPublicationLabel } from './exportTextUtils';
import { escapeLatexText, escapeLatexUrl } from './latexEscaping';

export interface LatexExportResult {
  text: string;
  blob: Blob;
  fileName: string;
}

export function buildLatexExport(manuscript: OmiManuscript): LatexExportResult {
  const context = buildPublicationRenderingContext(manuscript, resolvePublicationProfile(manuscript));
  const body: string[] = [];

  if (context.abstract) {
    body.push('\\begin{abstract}', escapeLatexText(context.abstract), '\\end{abstract}', '');
  }
  if (context.keywords.length) {
    body.push(`\\noindent\\textbf{${escapeLatexText(localizedPublicationLabel(context.locale, 'keywords'))}:} ${context.keywords.map(escapeLatexText).join('; ')}`, '');
  }

  const renderSections = (sections: typeof context.sections) => {
    for (const section of sections) {
      const command = sectionCommand(section.depth);
      body.push(`\\${command}{${escapeLatexText(section.title)}}`);
      for (const block of section.blocks) {
        const runs = block.visual ? [] : extractOmiInlineRuns(block.content);
        if (runs.length) body.push(renderLatexRuns(runs), '');
        else {
          const text = blockPlainText(block);
          if (text) body.push(escapeLatexText(text), '');
        }
      }
      renderSections(section.children);
    }
  };
  renderSections(context.sections);

  if (manuscript.annotations.length) {
    body.push(`\\section*{${escapeLatexText(localizedPublicationLabel(context.locale, 'notes'))}}`);
    body.push('\\begin{enumerate}');
    manuscript.annotations.forEach((note) => body.push(`\\item ${escapeLatexText(note.body)}`));
    body.push('\\end{enumerate}', '');
  }

  const authors = context.contributors.map((item) => escapeLatexText(item.displayName)).join(' \\and ');
  const title = context.subtitle ? `${escapeLatexText(context.title)}\\\\{\\large ${escapeLatexText(context.subtitle)}}` : escapeLatexText(context.title);
  const language = context.locale.toLowerCase().split(/[-_]/)[0];
  const babel = language === 'hu' ? 'magyar' : language === 'de' ? 'ngerman' : 'english';

  const text = [
    '% Generated by Open Manuscript Studio',
    '\\documentclass[11pt,a4paper]{article}',
    '\\usepackage[utf8]{inputenc}',
    '\\usepackage[T1]{fontenc}',
    `\\usepackage[${babel}]{babel}`,
    '\\usepackage{microtype}',
    '\\usepackage{hyperref}',
    '\\usepackage{graphicx}',
    '\\usepackage{amsmath}',
    '\\usepackage[normalem]{ulem}',
    '\\usepackage{relsize}',
    `\\title{${title}}`,
    authors ? `\\author{${authors}}` : '\\author{}',
    '\\date{}',
    '\\begin{document}',
    '\\maketitle',
    '',
    ...body,
    '\\end{document}',
    '',
  ].join('\n');

  return {
    text,
    blob: new Blob([text], { type: 'application/x-tex;charset=utf-8' }),
    fileName: `${exportFileStem(manuscript)}.tex`,
  };
}

function renderLatexRuns(runs: readonly OmiInlineRun[]): string {
  return runs.map((run) => {
    if (run.text === '\n') return '\\\\ ';
    let value = escapeLatexText(run.text);
    for (const semantic of run.semantics) {
      value = wrapSemantic(value, semantic);
    }
    if (run.link) value = `\\href{${escapeLatexUrl(run.link)}}{${value}}`;
    return value;
  }).join('');
}

function wrapSemantic(value: string, semantic: OmiInlineSemanticKind): string {
  switch (semantic) {
    case 'strong': return `\\textbf{${value}}`;
    case 'emphasis': return `\\emph{${value}}`;
    case 'strike': return `\\sout{${value}}`;
    case 'underline': return `\\uline{${value}}`;
    case 'small-caps': return `\\textsc{${value}}`;
    case 'superscript': return `\\textsuperscript{${value}}`;
    case 'subscript': return `\\textsubscript{${value}}`;
    case 'code': return `\\texttt{${value}}`;
  }
}

function sectionCommand(depth: number): string {
  if (depth <= 0) return 'section';
  if (depth === 1) return 'subsection';
  if (depth === 2) return 'subsubsection';
  return 'paragraph';
}