import { ensureManuscriptRevisionStateDigests } from '../src/model/revisionIntegrity.ts';
import type { OmiManuscript, OmiManuscriptState } from '../src/types/omi.ts';

export const REFERENCE_TIMESTAMP_ROOT = '2026-09-19T12:00:00.000Z';
export const REFERENCE_TIMESTAMP_HEAD = '2026-09-19T12:30:00.000Z';

export const REFERENCE_MANUSCRIPT_FEATURES = [
  'canonical OMI-SPEC-320@0.2.0 manuscript envelope',
  'complete revision history with state digests and tombstone evidence',
  'edited-volume structure with two studies and nested sections',
  'multilingual title-adjacent metadata, abstracts and keywords',
  'complete scholarly metadata and OJS open-science extension',
  'title matter, subtitle and motto',
  'person, organization, consortium, project, service and unidentified agents',
  'ORCID, ROR, multiple name forms, biographies and contribution roles',
  'CRediT roles and competing-interest declarations',
  'all inline semantic text marks, language spans and external links',
  'headings, paragraphs, block quotes, lists and code blocks',
  'footnote, endnote, author note, comment, editorial and semantic annotations',
  'rich-text note body with embedded note citation',
  'bibliographic records, citation modes, locators and citation clusters',
  'section, figure, table, chart and equation cross-references',
  'image, table, chart, equation and MusicXML/MIDI score blocks',
  'semantic captions and document/section caption numbering',
  'portable asset metadata for all asset roles',
  'tracked changes in pending, accepted and rejected states',
  'all publication-correction kinds',
  'named anchors/bookmarks',
  'semantic fields covering text, rich-text, date, boolean and choice values',
  'computed fields covering every computed-field kind',
  'table of contents, generated lists and categorized reference lists',
  'name/subject indexes, hierarchical entries, see/see-also and text ranges',
  'publication profile, branding, accessibility requirements and publisher CSS',
  'section numbering, citation style and object-numbering preferences',
  'paragraph-style assignments',
  'localized front matter',
] as const;

export const REFERENCE_MANUSCRIPT_NON_PORTABLE_SETTINGS = [
  'account authentication and linked identities',
  'institutional and central-admin grants',
  'cloud-storage credentials and device trust',
  'integration API secrets and provider credentials',
  'interface language and other per-account UI preferences',
  'saved custom-export templates and publication-style editor presets',
] as const;

type JsonNode = Record<string, unknown>;

function documentNode(...content: JsonNode[]): string {
  return JSON.stringify({ type: 'doc', content });
}

function heading(level: number, text: string): JsonNode {
  return {
    type: 'heading',
    attrs: { level },
    content: [{ type: 'text', text }],
  };
}

function paragraph(...content: JsonNode[]): JsonNode {
  return { type: 'paragraph', content };
}

function text(value: string, marks?: JsonNode[]): JsonNode {
  return {
    type: 'text',
    text: value,
    ...(marks?.length ? { marks } : {}),
  };
}

function mark(type: string, attrs?: Record<string, unknown>): JsonNode {
  return { type, ...(attrs ? { attrs } : {}) };
}

function simpleAgent(
  id: string,
  type: 'organization' | 'consortium' | 'project' | 'service' | 'unidentified',
  name: string,
  visibility: 'public' | 'restricted' | 'private' | 'withheld' = 'public',
) {
  return {
    id,
    type,
    names: [{
      id: `name-${id}`,
      value: name,
      preferred: true,
      visibility,
    }],
    identifiers: [],
    affiliations: [],
    createdAt: REFERENCE_TIMESTAMP_ROOT,
    updatedAt: REFERENCE_TIMESTAMP_HEAD,
  };
}

function buildCurrentState(): OmiManuscriptState {
  const richBlockContent = documentNode(
    paragraph(
      text('Strong', [mark('bold')]),
      text(' · emphasis', [mark('italic')]),
      text(' · strike', [mark('strike')]),
      text(' · underline', [mark('omiUnderline')]),
      text(' · small caps', [mark('omiSmallCaps')]),
      text(' · superscript', [mark('omiSuperscript')]),
      text(' · subscript', [mark('omiSubscript')]),
      text(' · code', [mark('code')]),
      text(' · latin', [mark('omiLanguage', { lang: 'la' })]),
      text(' · external link', [mark('omiLink', { href: 'https://openmanuscript.org/' })]),
      { type: 'hardBreak' },
      text('Semantic objects: '),
      {
        type: 'omiCitation',
        attrs: {
          citationId: 'citation-journal',
          citationIds: ['citation-journal', 'citation-book'],
          clusterId: 'cluster-primary',
          anchorId: 'anchor-citation-primary',
          label: '(Scholar, 2026; Editor, 2024)',
        },
      },
      text(' · '),
      {
        type: 'omiCrossReference',
        attrs: {
          crossReferenceId: 'xref-table',
          anchorId: 'anchor-xref-table',
          label: 'Table 1',
        },
      },
      text(' · '),
      {
        type: 'omiNote',
        attrs: {
          noteId: 'note-footnote',
          anchorId: 'anchor-note-footnote',
          label: '1',
          noteType: 'footnote',
        },
      },
    ),
    {
      type: 'bulletList',
      content: [{
        type: 'listItem',
        content: [paragraph(text('Bullet-list item in the reference manuscript.'))],
      }],
    },
    {
      type: 'orderedList',
      content: [{
        type: 'listItem',
        content: [paragraph(text('Numbered-list item in the reference manuscript.'))],
      }],
    },
    {
      type: 'codeBlock',
      attrs: { language: 'typescript' },
      content: [text('const portable = true;')],
    },
  );

  const state = {
    schema: 'https://openmanuscript.org/schemas/omi-manuscript-0.2.schema.json',
    id: 'reference-manuscript-all-features',
    version: '0.1.0-alpha.1',
    identityModelVersion: 'OMI-SPEC-150@0.1.0',
    locale: 'en',
    title: 'OMI Reference Manuscript: Complete Feature and Lifecycle Corpus',
    subtitle: 'A synthetic manuscript exercising portable scholarly structure and publication settings',
    motto: 'Write naturally. Structure once. Publish everywhere.',
    abstract: 'This synthetic reference manuscript exercises the portable document features implemented by Open Manuscript Studio for lifecycle and interoperability testing.',
    abstracts: {
      en: 'This synthetic reference manuscript exercises the portable document features implemented by Open Manuscript Studio for lifecycle and interoperability testing.',
      hu: 'Ez a szintetikus referenciakézirat az Open Manuscript Studio hordozható dokumentumfunkcióit teszteli.',
      de: 'Dieses synthetische Referenzmanuskript testet die portablen Dokumentfunktionen von Open Manuscript Studio.',
    },
    keywords: ['open manuscript', 'structured publishing', 'interoperability', 'reference corpus'],
    keywordsByLocale: {
      en: ['open manuscript', 'structured publishing', 'interoperability', 'reference corpus'],
      hu: ['nyílt kézirat', 'strukturált publikálás', 'interoperabilitás', 'referenciakorpusz'],
      de: ['offenes Manuskript', 'strukturiertes Publizieren', 'Interoperabilität', 'Referenzkorpus'],
    },
    localizedFrontMatter: {
      en: {
        abstract: 'This synthetic reference manuscript exercises the portable document features implemented by Open Manuscript Studio for lifecycle and interoperability testing.',
        keywords: ['open manuscript', 'structured publishing', 'interoperability', 'reference corpus'],
      },
      hu: {
        abstract: 'Ez a szintetikus referenciakézirat az Open Manuscript Studio hordozható dokumentumfunkcióit teszteli.',
        keywords: ['nyílt kézirat', 'strukturált publikálás', 'interoperabilitás', 'referenciakorpusz'],
      },
      de: {
        abstract: 'Dieses synthetische Referenzmanuskript testet die portablen Dokumentfunktionen von Open Manuscript Studio.',
        keywords: ['offenes Manuskript', 'strukturiertes Publizieren', 'Interoperabilität', 'Referenzkorpus'],
      },
    },
    sectionNumberingStyle: 'upper-roman',
    citationStyle: 'chicago-notes-bibliography',
    crossReferenceNumbering: 'section',
    documentStructure: {
      modelVersion: '0.1.0-alpha.1',
      kind: 'volume',
      volumeKind: 'edited-volume',
      noteNumberingScope: 'study',
      referencesPlacement: 'study-end',
      listsPlacement: 'volume-end',
    },
    titleMatter: {
      halfTitle: 'OMI Reference Manuscript',
      responsibilityStatement: 'Prepared by the Open Manuscript Initiative as synthetic test data',
      editionStatement: 'Reference corpus edition 1',
      publisherName: 'Open Manuscript Initiative',
      publicationPlace: 'Open scholarly infrastructure',
      publicationYear: '2026',
      isbn: '978-0-000000-00-0',
      copyrightStatement: 'Synthetic test content — reusable for OMI conformance testing.',
      colophon: 'Generated deterministically from the Studio reference-manuscript fixture.',
    },
    metadata: {
      subjects: {
        en: ['scholarly communication', 'digital publishing'],
        hu: ['tudományos kommunikáció', 'digitális publikálás'],
      },
      disciplines: {
        en: ['digital humanities', 'information science'],
        de: ['Digital Humanities', 'Informationswissenschaft'],
      },
      supportingAgencies: {
        en: ['Open Manuscript Initiative'],
        hu: ['Open Manuscript Initiative'],
      },
      coverage: {
        en: 'International; synthetic reference corpus',
        hu: 'Nemzetközi; szintetikus referenciakorpusz',
      },
      rights: {
        en: 'Synthetic test data for open-source conformance and interoperability testing.',
      },
      source: {
        en: 'Open Manuscript Studio reference fixture',
      },
      type: {
        en: 'Reference manuscript',
      },
      dataAvailability: {
        en: 'All data in this manuscript are synthetic and stored in the repository fixture.',
      },
      languages: {
        en: 'English; localized metadata also in Hungarian and German',
      },
      publicationVenue: {
        id: 'venue-reference-journal',
        type: 'JOURNAL',
        name: 'OMI Reference Journal',
        website: 'https://openmanuscript.org/',
        issn: '0000-0000',
        integrationProvider: 'OJS',
        integrationStatus: 'VERIFIED',
      },
      publisherId: 'publisher-open-manuscript-initiative',
      licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
      copyrightHolder: {
        en: 'Open Manuscript Initiative',
      },
      copyrightYear: 2026,
    },
    extensions: {
      'org.pkp.ojs': {
        openScience: {
          openData: { en: 'Synthetic data are included in the reference corpus.' },
          openMaterials: { en: 'All test materials are repository fixtures.' },
          preregistered: { en: 'Not applicable to this synthetic reference manuscript.' },
          preregisteredPlus: { en: 'Not applicable to this synthetic reference manuscript.' },
        },
        referenceFixture: true,
      },
    },
    agents: [
      {
        id: 'agent-author',
        type: 'person',
        names: [
          {
            id: 'name-author-en',
            value: 'Ada Scholar',
            givenName: 'Ada',
            familyName: 'Scholar',
            language: 'en',
            script: 'Latn',
            preferred: true,
            visibility: 'public',
            validFrom: '2020-01-01',
          },
          {
            id: 'name-author-hu',
            value: 'Scholar Ada',
            givenName: 'Ada',
            familyName: 'Scholar',
            language: 'hu',
            script: 'Latn',
            visibility: 'public',
          },
        ],
        identifiers: [{
          id: 'identifier-author-orcid',
          scheme: 'orcid',
          value: '0000-0002-1825-0097',
          normalizedValue: '0000-0002-1825-0097',
          verificationStatus: 'verified',
          source: 'https://orcid.org/',
          assertedAt: REFERENCE_TIMESTAMP_ROOT,
          visibility: 'public',
        }],
        affiliations: [{
          id: 'affiliation-author',
          organizationName: 'Open Manuscript Institute',
          organizationIdentifier: {
            id: 'identifier-affiliation-ror',
            scheme: 'ror',
            value: 'https://ror.org/00tjv0s33',
            normalizedValue: 'https://ror.org/00tjv0s33',
            verificationStatus: 'self-asserted',
            source: 'https://api.ror.org/v2/organizations',
            assertedAt: REFERENCE_TIMESTAMP_ROOT,
            visibility: 'public',
          },
          department: 'Structured Scholarly Communication',
          position: 'Research author',
          validFrom: '2024-01-01',
          source: 'reference-fixture',
          visibility: 'public',
        }],
        email: 'ada.scholar@example.test',
        country: 'GB',
        url: 'https://example.test/ada-scholar',
        biography: {
          en: 'Synthetic reference author used only for automated tests.',
          hu: 'Kizárólag automatikus tesztekhez használt szintetikus referenciaszerző.',
        },
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        updatedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'agent-editor',
        type: 'person',
        names: [{
          id: 'name-editor',
          value: 'Erik Editor',
          givenName: 'Erik',
          familyName: 'Editor',
          preferred: true,
          visibility: 'restricted',
        }],
        identifiers: [{
          id: 'identifier-editor-local',
          scheme: 'local',
          value: 'editor-reference',
          normalizedValue: 'editor-reference',
          verificationStatus: 'self-asserted',
          visibility: 'restricted',
        }],
        affiliations: [],
        email: 'editor@example.test',
        country: 'DE',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        updatedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      simpleAgent('agent-organization', 'organization', 'Open Manuscript Initiative'),
      simpleAgent('agent-consortium', 'consortium', 'OMI Reference Consortium', 'restricted'),
      simpleAgent('agent-project', 'project', 'Reference Corpus Project', 'private'),
      simpleAgent('agent-service', 'service', 'Automated Reference Service', 'public'),
      simpleAgent('agent-unidentified', 'unidentified', 'Anonymous reviewer', 'withheld'),
    ],
    contributions: [
      {
        id: 'contribution-author',
        agentId: 'agent-author',
        targetId: 'reference-manuscript-all-features',
        roles: ['author', 'data-curator', 'methodology', 'visualization', 'software'],
        order: 1,
        corresponding: true,
        attributionName: 'Ada Scholar',
        includeInPublicationList: true,
        creditRoles: [
          'conceptualization',
          'data-curation',
          'formal-analysis',
          'funding-acquisition',
          'investigation',
          'methodology',
          'project-administration',
          'resources',
          'software',
          'supervision',
          'validation',
          'visualization',
          'writing-original-draft',
          'writing-review-editing',
        ],
        competingInterests: {
          status: 'none',
          statements: {
            en: 'The author declares no competing interests.',
            hu: 'A szerző nem jelent összeférhetetlenséget.',
          },
        },
        visibility: 'public',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        updatedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'contribution-editor',
        agentId: 'agent-editor',
        targetId: 'study-one',
        roles: ['editor', 'translator'],
        order: 2,
        corresponding: false,
        includeInPublicationList: true,
        competingInterests: {
          status: 'declared',
          statements: {
            en: 'Synthetic declared interest used to exercise the metadata field.',
          },
        },
        visibility: 'restricted',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        updatedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'contribution-reviewer',
        agentId: 'agent-unidentified',
        targetId: 'study-two',
        roles: ['reviewer', 'other'],
        includeInPublicationList: false,
        competingInterests: {
          status: 'unclassified',
          statements: {},
        },
        visibility: 'withheld',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        updatedAt: REFERENCE_TIMESTAMP_HEAD,
      },
    ],
    tombstones: [{
      objectId: 'block-deleted-reference',
      objectType: 'block',
      deletionRevisionId: 'revision-reference-head',
      deletingChangeEventId: 'event-reference-delete',
      deletedAt: REFERENCE_TIMESTAMP_HEAD,
      deletedByAgentId: 'agent-author',
      reason: 'Synthetic deletion retained to exercise tombstone preservation.',
      formerContainerId: 'section-introduction',
      visibility: 'restricted',
      retention: 'retain',
    }],
    sections: [
      {
        id: 'study-one',
        title: 'Study One — Structured Authoring',
        studyMetadata: {
          modelVersion: '0.1.0-alpha.1',
          title: 'Study One — Structured Authoring',
          subtitle: 'Imported-study metadata projection',
          abstract: 'Study-level abstract retained independently inside an edited volume.',
          keywords: ['study metadata', 'edited volume'],
          locale: 'en',
          abstracts: {
            hu: 'Tanulmányszintű összefoglaló szerkesztett kötetben.',
          },
          keywordsByLocale: {
            hu: ['tanulmány metaadat', 'szerkesztett kötet'],
          },
          scholarlyMetadata: {
            subjects: { en: ['structured authoring'] },
            rights: { en: 'Synthetic reference content.' },
          },
          source: {
            format: 'omi',
            manuscriptId: 'source-study-one',
            fileName: 'source-study-one.omi.json',
            importedAt: REFERENCE_TIMESTAMP_ROOT,
          },
        },
        blocks: [{
          id: 'block-study-one-heading',
          type: 'heading',
          content: documentNode(heading(1, 'Study One — Structured Authoring')),
        }],
      },
      {
        id: 'section-introduction',
        parentSectionId: 'study-one',
        title: 'Introduction',
        blocks: [
          {
            id: 'block-introduction-heading',
            type: 'heading',
            content: documentNode(heading(2, 'Introduction')),
          },
          {
            id: 'block-rich-inline',
            type: 'paragraph',
            paragraphStyleId: 'body-reference',
            content: richBlockContent,
          },
          {
            id: 'block-quote',
            type: 'quote',
            paragraphStyleId: 'quotation-reference',
            content: documentNode({
              type: 'blockquote',
              content: [paragraph(text('Structured meaning should survive changes in presentation.'))],
            }),
          },
        ],
      },
      {
        id: 'section-objects',
        parentSectionId: 'study-one',
        title: 'Structured Objects',
        blocks: [
          {
            id: 'block-objects-heading',
            type: 'heading',
            content: documentNode(heading(2, 'Structured Objects')),
          },
          {
            id: 'block-image',
            type: 'image',
            content: '',
            visual: {
              kind: 'image',
              assetId: 'asset-image',
              src: '',
              mediaType: 'image/png',
              fileName: 'reference-figure.png',
              alt: 'Synthetic diagram showing a structured manuscript lifecycle.',
              caption: 'Structured manuscript lifecycle',
              width: 1200,
              height: 800,
              semanticCaption: {
                id: 'caption-image',
                label: 'Figure',
                sequenceKey: 'figure',
                title: 'Structured manuscript lifecycle',
                scope: 'document',
                source: {
                  format: 'manual',
                  instruction: 'Reference caption',
                },
              },
              provenance: {
                sourceFormat: 'image',
                fileName: 'reference-figure.png',
                importedAt: REFERENCE_TIMESTAMP_ROOT,
              },
            },
          },
          {
            id: 'block-table',
            type: 'table',
            content: '',
            visual: {
              kind: 'table',
              cells: [
                ['Feature', 'Expected result'],
                ['Round-trip', 'Preserved'],
                ['Export', 'Deterministic semantics'],
              ],
              headerRows: 1,
              caption: 'Lifecycle invariants',
              semanticCaption: {
                id: 'caption-table',
                label: 'Table',
                sequenceKey: 'table',
                title: 'Lifecycle invariants',
                scope: 'section',
                source: {
                  format: 'docx',
                  instruction: 'SEQ Table',
                },
              },
              provenance: {
                sourceFormat: 'xlsx',
                fileName: 'reference-table.xlsx',
                importedAt: REFERENCE_TIMESTAMP_ROOT,
                sourcePart: 'Sheet1!A1:B3',
              },
            },
          },
          {
            id: 'block-chart',
            type: 'chart',
            content: '',
            visual: {
              kind: 'chart',
              chartType: 'line',
              cells: [
                ['Version', 'Coverage'],
                ['0.1', '65'],
                ['0.2', '100'],
              ],
              title: 'Reference coverage',
              caption: 'Synthetic feature-coverage series',
              semanticCaption: {
                id: 'caption-chart',
                label: 'Figure',
                sequenceKey: 'figure',
                title: 'Synthetic feature-coverage series',
                scope: 'document',
              },
              provenance: {
                sourceFormat: 'xlsx',
                fileName: 'reference-chart.xlsx',
                importedAt: REFERENCE_TIMESTAMP_ROOT,
              },
            },
          },
          {
            id: 'block-equation',
            type: 'equation',
            content: '',
            visual: {
              kind: 'equation',
              notation: 'latex',
              source: 'E = mc^2',
              latex: 'E = mc^2',
              label: 'eq:reference',
              caption: 'Reference equation',
              semanticCaption: {
                id: 'caption-equation',
                label: 'Equation',
                sequenceKey: 'equation',
                title: 'Reference equation',
                scope: 'section',
              },
              provenance: {
                sourceFormat: 'docx',
                importedAt: REFERENCE_TIMESTAMP_ROOT,
                sourcePart: 'word/document.xml',
              },
            },
          },
          {
            id: 'block-musicxml',
            type: 'music-score',
            content: '',
            visual: {
              kind: 'music-score',
              format: 'musicxml',
              source: '<score-partwise version="4.0"></score-partwise>',
              title: 'Reference MusicXML score',
              composer: 'Synthetic Composer',
              divisions: 4,
              beats: 4,
              beatType: 4,
              notes: [
                { step: 'C', octave: 4, duration: 4, type: 'quarter' },
                { step: 'D', octave: 4, alter: 1, duration: 4, type: 'quarter' },
                { step: 'E', octave: 4, duration: 4, type: 'quarter', rest: false },
              ],
              caption: 'Reference MusicXML excerpt',
              semanticCaption: {
                id: 'caption-musicxml',
                label: 'Music',
                sequenceKey: 'music',
                title: 'Reference MusicXML excerpt',
                scope: 'document',
              },
              provenance: {
                sourceFormat: 'musicxml',
                fileName: 'reference.musicxml',
                importedAt: REFERENCE_TIMESTAMP_ROOT,
              },
            },
          },
          {
            id: 'block-midi',
            type: 'music-score',
            content: '',
            visual: {
              kind: 'music-score',
              format: 'midi',
              source: 'TVRoZAAAAAYAAQABAGBNVHJr',
              title: 'Reference MIDI score',
              composer: 'Synthetic Composer',
              beats: 3,
              beatType: 4,
              notes: [
                { step: 'G', octave: 3, duration: 2, type: 'half' },
                { step: 'A', octave: 3, duration: 1, type: 'quarter' },
              ],
              caption: 'Reference MIDI excerpt',
              semanticCaption: {
                id: 'caption-midi',
                label: 'Music',
                sequenceKey: 'music',
                title: 'Reference MIDI excerpt',
                scope: 'document',
              },
              provenance: {
                sourceFormat: 'midi',
                fileName: 'reference.mid',
                importedAt: REFERENCE_TIMESTAMP_ROOT,
              },
            },
          },
        ],
      },
      {
        id: 'study-two',
        title: 'Study Two — Interoperability',
        studyMetadata: {
          modelVersion: '0.1.0-alpha.1',
          title: 'Study Two — Interoperability',
          abstract: 'Second synthetic study to exercise edited-volume boundaries.',
          keywords: ['interoperability', 'publishing systems'],
          locale: 'en',
          source: {
            format: 'omi',
            manuscriptId: 'source-study-two',
            importedAt: REFERENCE_TIMESTAMP_ROOT,
          },
        },
        blocks: [{
          id: 'block-study-two-heading',
          type: 'heading',
          content: documentNode(heading(1, 'Study Two — Interoperability')),
        }],
      },
      {
        id: 'section-conclusion',
        parentSectionId: 'study-two',
        title: 'Conclusion',
        blocks: [
          {
            id: 'block-conclusion-heading',
            type: 'heading',
            content: documentNode(heading(2, 'Conclusion')),
          },
          {
            id: 'block-conclusion',
            type: 'paragraph',
            paragraphStyleId: 'body-reference',
            content: documentNode(
              paragraph(
                text('A portable manuscript should preserve scholarly meaning through save, reopen and export.'),
              ),
            ),
          },
        ],
      },
    ],
    annotations: [
      {
        id: 'note-footnote',
        type: 'note',
        noteKind: 'footnote',
        anchorId: 'anchor-note-footnote',
        targetBlockId: 'block-rich-inline',
        targetText: 'Semantic objects',
        body: 'Reference footnote with a bibliographic citation.',
        bodyContent: documentNode(
          paragraph(
            text('Reference footnote with an embedded citation '),
            {
              type: 'omiCitation',
              attrs: {
                citationId: 'note-citation-journal',
                citationIds: ['note-citation-journal'],
                anchorId: 'note-citation-anchor-note-citation-journal',
                label: 'Scholar 2026, 42',
              },
            },
          ),
        ),
        noteCitations: [{
          id: 'note-citation-journal',
          target: 'record-journal',
          locator: { type: 'page', value: '42' },
          prefix: 'see',
          suffix: 'for comparison',
          createdAt: REFERENCE_TIMESTAMP_ROOT,
          modifiedAt: REFERENCE_TIMESTAMP_HEAD,
        }],
        renderingHint: 'footnote',
        creatorAgentId: 'agent-author',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'note-endnote',
        type: 'note',
        noteKind: 'endnote',
        anchorId: 'anchor-note-endnote',
        targetBlockId: 'block-conclusion',
        body: 'Reference endnote.',
        renderingHint: 'endnote',
        creatorAgentId: 'agent-author',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'note-author',
        type: 'note',
        noteKind: 'author-note',
        anchorId: 'anchor-note-author',
        targetBlockId: 'block-conclusion',
        body: 'Reference author note.',
        renderingHint: 'margin',
        creatorAgentId: 'agent-author',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'comment-open',
        type: 'comment',
        targetBlockId: 'block-rich-inline',
        targetText: 'external link',
        targetRange: { from: 0, to: 12 },
        body: 'Synthetic open comment visible to author and editor.',
        renderingHint: 'popup',
        status: 'open',
        visibility: 'author_and_editor',
        creatorAgentId: 'agent-editor',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'editorial-resolved',
        type: 'editorial',
        targetBlockId: 'block-conclusion',
        body: 'Synthetic resolved editor-only comment.',
        renderingHint: 'popup',
        status: 'resolved',
        visibility: 'editor_only',
        creatorAgentId: 'agent-editor',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
        resolvedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'annotation-semantic-hidden',
        type: 'semantic',
        targetBlockId: 'block-table',
        body: 'Hidden semantic annotation used for round-trip coverage.',
        renderingHint: 'hidden',
        creatorAgentId: 'agent-service',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
    ],
    proofing: {
      trackChanges: true,
      changes: [
        {
          id: 'proofing-pending',
          targetBlockId: 'block-rich-inline',
          before: documentNode(paragraph(text('Original pending text.'))),
          after: richBlockContent,
          status: 'pending',
          actorAgentId: 'agent-editor',
          createdAt: REFERENCE_TIMESTAMP_ROOT,
          modifiedAt: REFERENCE_TIMESTAMP_HEAD,
        },
        {
          id: 'proofing-accepted',
          targetBlockId: 'block-conclusion',
          before: documentNode(paragraph(text('Earlier conclusion.'))),
          after: documentNode(paragraph(text('Accepted conclusion revision.'))),
          status: 'accepted',
          actorAgentId: 'agent-author',
          createdAt: REFERENCE_TIMESTAMP_ROOT,
          modifiedAt: REFERENCE_TIMESTAMP_HEAD,
        },
        {
          id: 'proofing-rejected',
          targetBlockId: 'block-quote',
          before: documentNode({ type: 'blockquote', content: [paragraph(text('Original quotation.'))] }),
          after: documentNode({ type: 'blockquote', content: [paragraph(text('Rejected quotation revision.'))] }),
          status: 'rejected',
          actorAgentId: 'agent-editor',
          createdAt: REFERENCE_TIMESTAMP_ROOT,
          modifiedAt: REFERENCE_TIMESTAMP_HEAD,
        },
      ],
    },
    publicationCorrections: [
      {
        id: 'correction-hyphen',
        targetBlockId: 'block-rich-inline',
        kind: 'discretionary-hyphen',
        from: 6,
        to: 6,
        sourceText: '',
        creatorAgentId: 'agent-editor',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'correction-nonbreaking',
        targetBlockId: 'block-rich-inline',
        kind: 'nonbreaking',
        from: 0,
        to: 6,
        sourceText: 'Strong',
        creatorAgentId: 'agent-editor',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'correction-line-break',
        targetBlockId: 'block-conclusion',
        kind: 'forced-line-break',
        from: 12,
        to: 12,
        creatorAgentId: 'agent-editor',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'correction-page-break',
        targetBlockId: 'block-conclusion',
        kind: 'page-break-before',
        creatorAgentId: 'agent-editor',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'correction-keep-together',
        targetBlockId: 'block-quote',
        kind: 'keep-together',
        creatorAgentId: 'agent-editor',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'correction-keep-next',
        targetBlockId: 'block-introduction-heading',
        kind: 'keep-with-next',
        creatorAgentId: 'agent-editor',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
    ],
    bibliographicRecords: [
      {
        id: 'record-journal',
        type: 'journal-article',
        title: 'Structured manuscripts as portable scholarly objects',
        subtitle: 'A reference article',
        contributors: [{
          id: 'bib-contributor-journal',
          role: 'author',
          givenName: 'Ada',
          familyName: 'Scholar',
        }],
        containerTitle: 'Journal of Synthetic Scholarly Infrastructure',
        issued: '2026',
        publisher: 'Open Example Press',
        place: 'London',
        volume: '12',
        issue: '3',
        pages: '40-58',
        language: 'en',
        identifiers: [
          { scheme: 'doi', value: '10.0000/reference.2026.1' },
          { scheme: 'issn', value: '0000-0000' },
        ],
        url: 'https://example.test/reference-article',
        accessed: '2026-09-19',
        status: 'verified',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'record-book',
        type: 'book',
        title: 'Open Scholarly Publishing',
        contributors: [{
          id: 'bib-contributor-book',
          role: 'editor',
          givenName: 'Erik',
          familyName: 'Editor',
        }],
        issued: '2024',
        publisher: 'Example University Press',
        place: 'Berlin',
        identifiers: [{ scheme: 'isbn', value: '978-0-000000-01-7' }],
        status: 'resolved',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'record-archive',
        type: 'archival-source',
        title: 'Synthetic archive collection',
        contributors: [{
          id: 'bib-contributor-archive',
          role: 'compiler',
          literalName: 'Reference Archive',
        }],
        issued: '1901',
        identifiers: [{ scheme: 'uri', value: 'https://example.test/archive/1' }],
        status: 'provisional',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'record-dataset',
        type: 'dataset',
        title: 'Synthetic interoperability dataset',
        contributors: [{
          id: 'bib-contributor-dataset',
          role: 'contributor',
          literalName: 'OMI Reference Project',
        }],
        issued: '2026',
        identifiers: [{ scheme: 'doi', value: '10.0000/reference.dataset.1' }],
        url: 'https://example.test/dataset/1',
        status: 'verified',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'record-standard',
        type: 'standard',
        title: 'Synthetic interoperability standard',
        contributors: [],
        issued: '2025',
        identifiers: [{ scheme: 'url', value: 'https://example.test/standard' }],
        status: 'verified',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
    ],
    citations: [
      {
        id: 'citation-journal',
        target: 'record-journal',
        anchorId: 'anchor-citation-primary',
        targetBlockId: 'block-rich-inline',
        clusterId: 'cluster-primary',
        locator: { type: 'page', value: '42' },
        prefix: 'see',
        suffix: 'for the model',
        mode: 'parenthetical',
        intent: 'background',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'citation-book',
        target: 'record-book',
        anchorId: 'anchor-citation-primary',
        targetBlockId: 'block-rich-inline',
        clusterId: 'cluster-primary',
        locator: { type: 'chapter', value: '3' },
        mode: 'narrative',
        intent: 'methodology',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'citation-dataset',
        target: 'record-dataset',
        anchorId: 'anchor-citation-dataset',
        targetBlockId: 'block-conclusion',
        locator: { type: 'section', value: 'Methods' },
        mode: 'bibliography-only',
        intent: 'data',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'citation-standard',
        target: 'record-standard',
        anchorId: 'anchor-citation-standard',
        targetBlockId: 'block-conclusion',
        locator: { type: 'paragraph', value: '7' },
        mode: 'note',
        intent: 'legislation',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
    ],
    citationClusters: [{
      id: 'cluster-primary',
      anchorId: 'anchor-citation-primary',
      targetBlockId: 'block-rich-inline',
      citationIds: ['citation-journal', 'citation-book'],
      createdAt: REFERENCE_TIMESTAMP_ROOT,
      modifiedAt: REFERENCE_TIMESTAMP_HEAD,
    }],
    crossReferences: [
      {
        id: 'xref-section',
        anchorId: 'anchor-xref-section',
        sourceBlockId: 'block-conclusion',
        targetId: 'section-introduction',
        targetKind: 'section',
        displayStyle: 'label-number-title',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'xref-figure',
        anchorId: 'anchor-xref-figure',
        sourceBlockId: 'block-conclusion',
        targetId: 'block-image',
        targetKind: 'figure',
        displayStyle: 'number',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'xref-table',
        anchorId: 'anchor-xref-table',
        sourceBlockId: 'block-rich-inline',
        targetId: 'block-table',
        targetKind: 'table',
        displayStyle: 'label-number',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'xref-chart',
        anchorId: 'anchor-xref-chart',
        sourceBlockId: 'block-conclusion',
        targetId: 'block-chart',
        targetKind: 'chart',
        displayStyle: 'title',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'xref-equation',
        anchorId: 'anchor-xref-equation',
        sourceBlockId: 'block-conclusion',
        targetId: 'block-equation',
        targetKind: 'equation',
        displayStyle: 'label-number-title',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
    ],
    assets: [
      {
        id: 'asset-image',
        modelVersion: '0.1.0-alpha.1',
        fileName: 'reference-figure.png',
        originalFileName: 'reference figure.png',
        mediaType: 'image/png',
        size: 68,
        role: 'figure',
        checksum: {
          algorithm: 'sha256',
          value: '0000000000000000000000000000000000000000000000000000000000000001',
          scope: 'raw-bytes',
        },
        provenance: {
          sourceFormat: 'image',
          fileName: 'reference figure.png',
          importedAt: REFERENCE_TIMESTAMP_ROOT,
        },
        createdAt: REFERENCE_TIMESTAMP_ROOT,
      },
      {
        id: 'asset-supplement',
        modelVersion: '0.1.0-alpha.1',
        fileName: 'supplement.pdf',
        mediaType: 'application/pdf',
        size: 128,
        role: 'supplementary-material',
        checksum: {
          algorithm: 'sha256',
          value: '0000000000000000000000000000000000000000000000000000000000000002',
          scope: 'raw-bytes',
        },
        createdAt: REFERENCE_TIMESTAMP_ROOT,
      },
      {
        id: 'asset-source-data',
        modelVersion: '0.1.0-alpha.1',
        fileName: 'source-data.csv',
        mediaType: 'text/csv',
        size: 96,
        role: 'source-data',
        checksum: {
          algorithm: 'sha256',
          value: '0000000000000000000000000000000000000000000000000000000000000003',
          scope: 'raw-bytes',
        },
        createdAt: REFERENCE_TIMESTAMP_ROOT,
      },
      {
        id: 'asset-attachment',
        modelVersion: '0.1.0-alpha.1',
        fileName: 'attachment.txt',
        mediaType: 'text/plain',
        size: 32,
        role: 'attachment',
        checksum: {
          algorithm: 'sha256',
          value: '0000000000000000000000000000000000000000000000000000000000000004',
          scope: 'raw-bytes',
        },
        createdAt: REFERENCE_TIMESTAMP_ROOT,
      },
    ],
    namedAnchors: [
      {
        id: 'bookmark-introduction',
        name: 'Introduction start',
        exportName: 'Introduction_start',
        targetId: 'section-introduction',
        targetKind: 'section',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
        source: { format: 'manual', originalName: 'Introduction start' },
      },
      {
        id: 'bookmark-table',
        name: 'Lifecycle table',
        exportName: 'Lifecycle_table',
        targetId: 'block-table',
        targetKind: 'block',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
        source: { format: 'docx', originalName: 'Lifecycle_table' },
      },
    ],
    semanticFields: [
      {
        id: 'field-funding',
        role: 'funding-statement',
        label: 'Funding statement',
        valueType: 'rich-text',
        value: 'No external funding; synthetic reference field.',
        required: true,
        scope: 'manuscript',
        locked: false,
        source: { format: 'manual', tag: 'funding', alias: 'Funding' },
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'field-short-title',
        role: 'short-title',
        label: 'Short title',
        valueType: 'text',
        value: 'OMI Reference Manuscript',
        scope: 'manuscript',
        locked: false,
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'field-publication-date',
        role: 'publication-date',
        label: 'Publication date',
        valueType: 'date',
        value: '2026-09-19',
        scope: 'manuscript',
        locked: true,
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'field-open-data',
        role: 'open-data',
        label: 'Open data',
        valueType: 'boolean',
        value: true,
        scope: 'manuscript',
        locked: false,
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'field-article-type',
        role: 'article-type',
        label: 'Article type',
        valueType: 'choice',
        value: 'research-article',
        required: true,
        options: ['research-article', 'review', 'data-paper'],
        scope: 'section',
        sectionId: 'study-one',
        locked: false,
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
    ],
    computedFields: [
      {
        id: 'computed-title',
        label: 'Document title',
        kind: 'document-property',
        property: 'title',
        fallback: 'Untitled',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'computed-subtitle',
        label: 'Document subtitle',
        kind: 'document-property',
        property: 'subtitle',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'computed-locale',
        label: 'Document language',
        kind: 'document-property',
        property: 'locale',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'computed-created',
        label: 'Created date',
        kind: 'document-property',
        property: 'created-at',
        dateStyle: 'medium',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'computed-updated',
        label: 'Updated date',
        kind: 'document-property',
        property: 'updated-at',
        dateStyle: 'long',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'computed-semantic',
        label: 'Funding statement field',
        kind: 'semantic-field',
        semanticFieldId: 'field-funding',
        fallback: 'No funding statement',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'computed-xref',
        label: 'Lifecycle table reference',
        kind: 'cross-reference',
        crossReferenceTargetId: 'block-table',
        crossReferenceDisplayStyle: 'label-number-title',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'computed-date',
        label: 'Current date',
        kind: 'current-date',
        dateStyle: 'iso',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'computed-section-count',
        label: 'Section count',
        kind: 'section-count',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
      {
        id: 'computed-word-count',
        label: 'Word count',
        kind: 'word-count',
        createdAt: REFERENCE_TIMESTAMP_ROOT,
        modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      },
    ],
    tableOfContents: {
      id: 'toc-reference',
      title: 'Contents',
      minLevel: 1,
      maxLevel: 4,
      hyperlinks: true,
      useOutlineLevels: true,
      source: {
        format: 'manual',
        instruction: 'TOC \\o "1-4" \\h \\z \\u',
      },
    },
    indexDefinitions: [
      { id: 'index-names', title: 'Name index', kind: 'name' },
      { id: 'index-subjects', title: 'Subject index', kind: 'subject' },
    ],
    indexEntries: [
      {
        id: 'index-entry-ada',
        indexId: 'index-names',
        kind: 'name',
        terms: ['Scholar, Ada'],
        sortKey: 'Scholar, Ada',
        relation: 'location',
        targetBlockId: 'block-rich-inline',
        anchorId: 'index-anchor-ada',
        targetText: 'Strong',
        targetTextOffset: 0,
        range: {
          startBlockId: 'block-rich-inline',
          startOffset: 0,
          endBlockId: 'block-rich-inline',
          endOffset: 6,
          text: 'Strong',
        },
        source: {
          format: 'docx-xe',
          instruction: 'XE "Scholar, Ada"',
        },
      },
      {
        id: 'index-entry-omi',
        indexId: 'index-subjects',
        kind: 'subject',
        terms: ['Open Manuscript Initiative'],
        relation: 'location',
        targetBlockId: 'block-conclusion',
        anchorId: 'index-anchor-omi',
        targetText: 'portable manuscript',
        targetTextOffset: 2,
        source: {
          format: 'manual',
        },
      },
      {
        id: 'index-entry-portable',
        indexId: 'index-subjects',
        kind: 'subject',
        terms: ['Publishing', 'Portable manuscript'],
        parentEntryId: 'index-entry-omi',
        relation: 'see-also',
        relatedEntryId: 'index-entry-omi',
        source: {
          format: 'ai-suggestion',
          instruction: 'Synthetic suggestion retained for semantic coverage',
        },
      },
      {
        id: 'index-entry-alias',
        indexId: 'index-subjects',
        kind: 'subject',
        terms: ['Structured document'],
        relation: 'see',
        relatedTerm: 'Open Manuscript Initiative',
        source: {
          format: 'manual',
        },
      },
    ],
    generatedIndexes: [
      {
        id: 'generated-index-names',
        kind: 'name',
        title: 'Name index',
        source: {
          format: 'docx-index',
          instruction: 'INDEX \\c "1"',
        },
      },
      {
        id: 'generated-index-subjects',
        kind: 'subject',
        title: 'Subject index',
        source: {
          format: 'manual',
        },
      },
    ],
    categorizedReferenceLists: [{
      id: 'reference-list-primary',
      title: 'Sources and references',
      includeUncited: true,
      createdAt: REFERENCE_TIMESTAMP_ROOT,
      modifiedAt: REFERENCE_TIMESTAMP_HEAD,
      categories: [
        {
          id: 'reference-category-archive',
          title: 'Archival sources',
          kind: 'archival-sources',
          resourceTypes: ['archival-source', 'manuscript'],
          recordIds: ['record-archive'],
          sort: 'title',
        },
        {
          id: 'reference-category-law',
          title: 'Standards and legislation',
          kind: 'legislation',
          resourceTypes: ['standard'],
          citationIntents: ['legislation', 'law', 'legal-authority'],
          sort: 'title',
        },
        {
          id: 'reference-category-primary',
          title: 'Primary sources',
          kind: 'primary-sources',
          resourceTypes: ['dataset'],
          citationIntents: ['data', 'primary-source'],
          sort: 'issued-title',
        },
        {
          id: 'reference-category-custom',
          title: 'Books and articles',
          kind: 'custom',
          resourceTypes: ['journal-article', 'book'],
          sort: 'author-title',
        },
      ],
    }],
    generatedListDefinitions: [
      { id: 'generated-list-toc', kind: 'toc', title: 'Table of contents', source: { format: 'manual' } },
      { id: 'generated-list-figures', kind: 'figures', title: 'List of figures', source: { captionLabel: 'Figure' } },
      { id: 'generated-list-tables', kind: 'tables', title: 'List of tables', source: { captionLabel: 'Table' } },
      { id: 'generated-list-index', kind: 'index', title: 'Name index', source: { indexId: 'index-names' } },
      { id: 'generated-list-references', kind: 'references', title: 'Sources and references', source: { categorizedReferenceListId: 'reference-list-primary' } },
      { id: 'generated-list-custom', kind: 'custom', title: 'Custom generated list', source: { format: 'manual', instruction: 'Reference custom list' } },
    ],
    publicationProfile: {
      id: 'omi-reference-complete',
      version: '1.0.0-reference',
    },
    embeddedPublicationProfile: {
      model: 'omi-publication-profile-alpha-0.1',
      id: 'omi-reference-complete',
      version: '1.0.0-reference',
      name: 'OMI Complete Reference Profile',
      description: 'Synthetic profile that exercises all currently portable publication-profile settings.',
      publisher: 'Open Manuscript Initiative',
      branding: {
        logoDataUrl: 'data:image/svg+xml;base64,PHN2Zy8+',
        logoAlt: 'Open Manuscript Initiative reference mark',
        primaryColor: '#6d2130',
        accentColor: '#275d70',
        website: 'https://openmanuscript.org/',
      },
      rules: {
        layout: {
          pageSize: 'Letter',
          columns: 2,
          marginMm: { top: 18, right: 19, bottom: 20, left: 21 },
          fontFamily: 'sans-serif',
          baseFontSizePt: 10.5,
          lineHeight: 1.42,
          textAlign: 'justified',
        },
        sections: {
          numberingStyle: 'upper-roman',
          maxNumberedDepth: 4,
        },
        citations: {
          style: 'chicago-notes-bibliography',
          bibliographyHeading: true,
        },
        notes: {
          placement: 'interactive',
          restartNumbering: 'section',
        },
        objects: {
          numbering: 'section',
          figureCaptionPosition: 'above',
          tableCaptionPosition: 'below',
          equationNumbering: 'section',
        },
        contributors: {
          showAffiliations: true,
          affiliationMode: 'inline',
          showOrcid: true,
          showCorrespondingMarker: true,
        },
        metadata: {
          requireTitle: true,
          requireAbstract: true,
          minimumKeywords: 3,
          requireContributor: true,
          affiliation: 'required',
          orcid: 'recommended',
        },
        accessibility: {
          figureAltText: 'required',
          tableHeaders: 'required',
          semanticHeadings: 'required',
        },
        outputs: ['html', 'jats', 'docx', 'pdf', 'epub'],
      },
      exportStylesheet: {
        model: 'OMI-PUBLISHER-EXPORT-STYLESHEET',
        version: '0.1.0',
        fileName: 'reference-publication.css',
        mediaType: 'text/css',
        cssText: '.omi-scholarly-article { max-width: 72rem; }\n.article-motto { font-style: italic; }',
        scope: 'publication-export',
        addedAt: REFERENCE_TIMESTAMP_ROOT,
      },
      printStylesheet: {
        model: 'OMI-PUBLISHER-PRINT-STYLESHEET',
        version: '0.1.0',
        fileName: 'reference-print.css',
        mediaType: 'text/css',
        cssText: '@page { @bottom-center { content: counter(page); } }',
        scope: 'print-pdf',
        addedAt: REFERENCE_TIMESTAMP_ROOT,
      },
    },
    createdAt: REFERENCE_TIMESTAMP_ROOT,
    updatedAt: REFERENCE_TIMESTAMP_HEAD,
  } as unknown as OmiManuscriptState;

  return state;
}

function rootStateWithDeletedBlock(current: OmiManuscriptState): OmiManuscriptState {
  const root = JSON.parse(JSON.stringify(current)) as OmiManuscriptState;
  root.updatedAt = REFERENCE_TIMESTAMP_ROOT;
  root.tombstones = [];
  const introduction = root.sections.find((section) => section.id === 'section-introduction');
  introduction?.blocks.push({
    id: 'block-deleted-reference',
    type: 'paragraph',
    content: documentNode(paragraph(text('This block exists only in the root revision and is deleted in the current state.'))),
  });
  return root;
}

export function createReferenceManuscript(): OmiManuscript {
  const current = buildCurrentState();
  const root = rootStateWithDeletedBlock(current);

  const manuscript = {
    ...current,
    versioningModelVersion: 'OMI-SPEC-160@0.1.0',
    headRevisionId: 'revision-reference-head',
    revisionHistory: {
      profile: 'core-revision-history',
      completeness: 'complete',
      rootRevisionId: 'revision-reference-root',
      headRevisionId: 'revision-reference-head',
      revisions: [
        {
          id: 'revision-reference-root',
          parentRevisionIds: [],
          createdAt: REFERENCE_TIMESTAMP_ROOT,
          actorAgentId: 'agent-author',
          summary: 'Created complete synthetic reference manuscript',
          changeSet: {
            id: 'changeset-reference-root',
            summary: 'Created complete synthetic reference manuscript',
            actorAgentId: 'agent-author',
            createdAt: REFERENCE_TIMESTAMP_ROOT,
            events: [{
              id: 'event-reference-root',
              operation: 'manuscript.snapshot.create',
              targetId: current.id,
              path: '/',
              nextValue: {
                manuscriptId: current.id,
                title: current.title,
              },
              createdAt: REFERENCE_TIMESTAMP_ROOT,
            }],
          },
          snapshot: {
            manuscriptId: current.id,
            state: root,
          },
        },
        {
          id: 'revision-reference-head',
          parentRevisionIds: ['revision-reference-root'],
          createdAt: REFERENCE_TIMESTAMP_HEAD,
          actorAgentId: 'agent-author',
          summary: 'Deleted synthetic historical block',
          changeSet: {
            id: 'changeset-reference-head',
            summary: 'Deleted synthetic historical block',
            actorAgentId: 'agent-author',
            createdAt: REFERENCE_TIMESTAMP_HEAD,
            events: [{
              id: 'event-reference-delete',
              operation: 'block.remove',
              targetId: 'block-deleted-reference',
              path: '/sections/section-introduction/blocks/block-deleted-reference',
              previousValue: {
                id: 'block-deleted-reference',
                type: 'paragraph',
              },
              createdAt: REFERENCE_TIMESTAMP_HEAD,
            }],
          },
          snapshot: {
            manuscriptId: current.id,
            state: current,
          },
        },
      ],
    },
  } as unknown as OmiManuscript;

  return ensureManuscriptRevisionStateDigests(manuscript);
}
