ALTER TYPE "CloudProviderType" ADD VALUE IF NOT EXISTS 'GOOGLE_DRIVE';
ALTER TYPE "CloudProviderType" ADD VALUE IF NOT EXISTS 'ONEDRIVE';
ALTER TYPE "CloudProviderType" ADD VALUE IF NOT EXISTS 'DROPBOX';
