import type {
  IntegrationAuthenticationMode,
  IntegrationPermission,
  IntegrationProviderDescriptor,
  IntegrationProviderKind,
} from './contracts';

export interface IntegrationCatalogEntry extends IntegrationProviderDescriptor {
  categoryLabel: string;
  status: 'available' | 'planned' | 'connected';
  configurable?: boolean;
}

const permissions = (...items: IntegrationPermission[]) => items;
const auth = (...items: IntegrationAuthenticationMode[]) => items;

export const integrationCatalog: IntegrationCatalogEntry[] = [
  {
    id: 'deepl',
    kind: 'translation',
    displayName: 'DeepL',
    description: 'Machine translation provider for selections, blocks, sections, and manuscript language variants.',
    categoryLabel: 'Translation',
    permissions: permissions('document.read', 'document.suggest'),
    authenticationModes: auth('server_secret', 'user_api_key'),
    preferredAuthenticationMode: 'server_secret',
    requiresServerSecret: true,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: false,
    configurable: true,
    status: 'available',
  },
  {
    id: 'ai-provider',
    kind: 'ai',
    displayName: 'AI provider',
    description: 'Provider-neutral OpenAI-compatible AI endpoint used by OMI Agents. Endpoint, model and encrypted API key are configured inside the OMI Agents settings.',
    categoryLabel: 'AI',
    permissions: permissions('document.read', 'document.suggest', 'metadata.read'),
    authenticationModes: auth('server_secret', 'user_api_key'),
    preferredAuthenticationMode: 'server_secret',
    requiresServerSecret: true,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: true,
    configurable: false,
    status: 'available',
  },
  {
    id: 'omi-agents',
    kind: 'agent',
    displayName: 'OMI agents',
    description: 'Scoped assistants for language editing, metadata generation, summarisation and citation checks. Agents produce reviewable suggestions by default.',
    categoryLabel: 'AI agents',
    permissions: permissions(
      'document.read',
      'document.suggest',
      'document.write',
      'metadata.read',
      'metadata.write',
      'references.read',
    ),
    authenticationModes: auth('none'),
    preferredAuthenticationMode: 'none',
    requiresServerSecret: false,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: false,
    configurable: true,
    status: 'available',
  },
  {
    id: 'ojs',
    kind: 'publishing',
    displayName: 'Open Journal Systems (OJS)',
    description: 'Journal publishing integration for manuscript exchange, peer review, assignments and editorial workflow. Multiple OJS installations or journals can be registered independently.',
    categoryLabel: 'Publishing · Journals',
    permissions: permissions(
      'document.read',
      'document.write',
      'metadata.read',
      'metadata.write',
      'review.read',
      'files.read',
      'files.write',
    ),
    authenticationModes: auth('integration_token'),
    preferredAuthenticationMode: 'integration_token',
    requiresServerSecret: false,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: true,
    configurable: true,
    status: 'available',
  },
  {
    id: 'omp',
    kind: 'publishing',
    displayName: 'Open Monograph Press (OMP)',
    description: 'Monograph publishing integration for presses, books, chapters, contributors, files and editorial workflow. Multiple OMP installations or presses can be registered independently.',
    categoryLabel: 'Publishing · Monographs',
    permissions: permissions('metadata.read', 'files.read'),
    authenticationModes: auth('integration_token'),
    preferredAuthenticationMode: 'integration_token',
    requiresServerSecret: false,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: true,
    configurable: true,
    status: 'available',
  },
  {
    id: 'wordpress',
    kind: 'publishing',
    displayName: 'WordPress',
    description: 'Deliver committed semantic HTML5 artifacts with an explicit peer-review assurance seal through the WordPress REST API. Credentials use a WordPress application password, never the normal account password.',
    categoryLabel: 'Publishing · Websites',
    permissions: permissions('document.read', 'metadata.read', 'files.read', 'files.write', 'publication.deliver'),
    authenticationModes: auth('user_api_key'),
    preferredAuthenticationMode: 'user_api_key',
    requiresServerSecret: false,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: true,
    configurable: true,
    status: 'available',
  },
  {
    id: 'web-publishing',
    kind: 'publishing',
    displayName: 'Generic web publishing endpoint',
    description: 'Deliver committed semantic HTML5 artifacts with explicit peer-review assurance through the omi-web-publication/1 contract using Bearer, X-API-Key, Basic, or no authentication.',
    categoryLabel: 'Publishing · Websites',
    permissions: permissions('document.read', 'metadata.read', 'files.read', 'files.write', 'publication.deliver'),
    authenticationModes: auth('none', 'user_api_key'),
    preferredAuthenticationMode: 'user_api_key',
    requiresServerSecret: false,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: true,
    configurable: true,
    status: 'available',
  },
  {
    id: 'zotero',
    kind: 'scholarly-service',
    displayName: 'Zotero',
    description: 'Personal Zotero reference-library integration. Search your private library and import normalized references into the current OMI manuscript.',
    categoryLabel: 'Reference managers',
    permissions: permissions('references.read'),
    authenticationModes: auth('user_api_key'),
    preferredAuthenticationMode: 'user_api_key',
    requiresServerSecret: false,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: false,
    configurable: true,
    status: 'available',
  },
  {
    id: 'mendeley',
    kind: 'scholarly-service',
    displayName: 'Mendeley',
    description: 'Personal Mendeley reference-library integration using OAuth 2.0. Search your library and import normalized references into the current OMI manuscript.',
    categoryLabel: 'Reference managers',
    permissions: permissions('references.read'),
    authenticationModes: auth('oauth2'),
    preferredAuthenticationMode: 'oauth2',
    requiresServerSecret: true,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: false,
    configurable: true,
    status: 'available',
  },
  {
    id: 'orcid',
    kind: 'identity',
    displayName: 'ORCID',
    description: 'Researcher identity and profile linking using ORCID authentication and identifiers.',
    categoryLabel: 'Identity',
    permissions: permissions('metadata.read', 'metadata.write'),
    authenticationModes: auth('oauth2'),
    preferredAuthenticationMode: 'oauth2',
    requiresServerSecret: true,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: false,
    configurable: true,
    status: 'available',
  },
  {
    id: 'cloud-storage',
    kind: 'storage',
    displayName: 'Cloud storage',
    description: 'Provider-aware storage for portable OMI manuscript backups. Choose the provider, account type and connection method, including desktop-synchronized folders, direct WebDAV and future OAuth connections.',
    categoryLabel: 'Storage',
    permissions: permissions('files.read', 'files.write'),
    authenticationModes: auth('none', 'server_secret', 'oauth2'),
    preferredAuthenticationMode: 'none',
    requiresServerSecret: false,
    supportsPerUserAuthentication: true,
    supportsMultipleConnections: true,
    configurable: true,
    status: 'available',
  },
];

export function getIntegrationsByKind(kind: IntegrationProviderKind): IntegrationCatalogEntry[] {
  return integrationCatalog.filter((entry) => entry.kind === kind);
}
