import { useState } from 'react';
import { CheckCircle2, Clock3, LogOut, Menu, Search, UserRound, X } from 'lucide-react';
import { useStudioStore } from '../app/useStudioStore';
import { useTranslation } from '../i18n';
import { useAuthStore } from '../store/authStore';
import { AccountPanel } from './AccountPanel';
import { HeaderInsertMenu } from './HeaderInsertMenu';
import { LanguageSwitcher } from './LanguageSwitcher';
interface HeaderProps{onOpenMenu:()=>void}
const searchLabels:Record<string,string>={de:'Suchen',en:'Search',hu:'Keresés'};const accountLabels:Record<string,string>={en:'Account',hu:'Fiók',de:'Konto'};
export function Header({onOpenMenu}:HeaderProps){const {t,locale}=useTranslation();const [accountOpen,setAccountOpen]=useState(false);const manuscript=useStudioStore(s=>s.manuscript);const pending=useStudioStore(s=>s.pendingChangeSet);const selectedId=useStudioStore(s=>s.selectedSectionId);const logout=useAuthStore(s=>s.logout);const loading=useAuthStore(s=>s.isLoading);const section=manuscript.sections.find(s=>s.id===selectedId);const searchLabel=searchLabels[locale]??searchLabels.en;const accountLabel=accountLabels[locale]??accountLabels.en;const search=()=>window.dispatchEvent(new KeyboardEvent('keydown',{key:'f',ctrlKey:true,bubbles:true}));return <><header className="app-header focus-header"><div className="focus-header-identity"><button type="button" className="focus-menu-button" onClick={onOpenMenu} aria-label={t('studio.menu')}><Menu size={19}/></button><button type="button" className="focus-menu-button focus-search-button" onClick={search} aria-label={searchLabel}><Search size={18}/></button><div className="focus-brand-lockup"><img className="focus-brand-mark" src="/studio-icon.svg" width="34" height="34" alt=""/><span className="focus-brand-copy"><span className="focus-brand-initiative">Open Manuscript Initiative</span><strong>Studio</strong></span></div></div><div className="focus-header-context" title={section?.title??manuscript.title}><span className="focus-header-context-label">Manuscript</span><span className="focus-header-manuscript-title">{manuscript.title}</span>{section?.title&&section.title!==manuscript.title?<><span className="focus-header-context-divider">/</span><span className="focus-header-section">{section.title}</span></>:null}</div><div className="focus-header-primary-action"><HeaderInsertMenu/></div><div className="focus-header-actions"><div className={`focus-save-state${pending?' focus-save-state--pending':''}`}>{pending?<Clock3 size={15}/>:<CheckCircle2 size={15}/>}<span>{pending?t('studio.pending'):t('studio.saved')}</span></div><LanguageSwitcher/><button type="button" className="focus-menu-button" onClick={()=>setAccountOpen(true)} aria-label={accountLabel} title={accountLabel}><UserRound size={18}/><span className="focus-logout-label">{accountLabel}</span></button><button type="button" className="focus-menu-button focus-logout-button" onClick={()=>void logout().catch(()=>{})} disabled={loading} aria-label={t('auth.logout')}><LogOut size={18}/><span className="focus-logout-label">{t('auth.logout')}</span></button></div></header>{accountOpen?<div className="account-overlay" role="dialog" aria-modal="true" aria-label={accountLabel}><div className="account-overlay-backdrop" onClick={()=>setAccountOpen(false)}/><div className="account-drawer"><button type="button" className="account-close" onClick={()=>setAccountOpen(false)} aria-label="Close"><X size={22}/></button><AccountPanel/></div></div>:null}</>}
