import { useState, type ReactNode } from 'react';
import { FileText, LogOut, Menu, Pencil, Search, SlidersHorizontal, User } from 'lucide-react';
import { AccountPanel } from '../../components/AccountPanel';
import { Footer } from '../../components/Footer';
import { HeaderInsertMenu } from '../../components/HeaderInsertMenu';
import { LanguageSwitcher } from '../../components/LanguageSwitcher';
import { useTranslation } from '../../i18n';
import { useAuthStore } from '../../store/authStore';
import '../styles/mobile.css';
interface MobileLayoutProps { children:ReactNode; onOpenMenu:()=>void; }
const searchLabels:Record<string,string>={de:'Suchen',en:'Search',hu:'Keresés'};
const navLabels:Record<string,{document:string;editor:string;details:string;account:string}>={en:{document:'Document',editor:'Editor',details:'Details',account:'Account'},hu:{document:'Dokumentum',editor:'Szerkesztő',details:'Részletek',account:'Fiók'},de:{document:'Dokument',editor:'Editor',details:'Details',account:'Konto'}};
export function MobileLayout({children,onOpenMenu}:MobileLayoutProps){const {t,locale}=useTranslation();const logout=useAuthStore(s=>s.logout);const isAuthLoading=useAuthStore(s=>s.isLoading);const [view,setView]=useState<'editor'|'account'>('editor');const searchLabel=searchLabels[locale]??searchLabels.en;const nav=navLabels[locale]??navLabels.en;const handleSearch=()=>window.dispatchEvent(new KeyboardEvent('keydown',{key:'f',ctrlKey:true,bubbles:true}));return <div className="mobile-shell"><header className="mobile-header"><button type="button" className="mobile-icon-button" onClick={onOpenMenu} aria-label={t('studio.menu')}><Menu size={22}/></button><div className="mobile-header-title"><img src="/studio-icon.svg" width="28" height="28" alt=""/><span>Open Manuscript Studio</span></div><button type="button" className="mobile-icon-button" onClick={()=>void logout().catch(()=>{})} aria-label={t('auth.logout')} disabled={isAuthLoading}><LogOut size={20}/></button></header>{view==='editor'?<div className="mobile-action-bar"><button type="button" className="mobile-action-button" onClick={handleSearch} aria-label={searchLabel}><Search size={18}/><span>{searchLabel}</span></button><div className="mobile-insert-action"><HeaderInsertMenu/></div><LanguageSwitcher/></div>:<div className="mobile-account-bar"><strong>{nav.account}</strong><LanguageSwitcher/></div>}<main className="mobile-workspace">{view==='account'?<AccountPanel/>:children}<Footer/></main><nav className="mobile-bottom-nav"><button type="button" className="mobile-nav-item" disabled><FileText size={20}/><span>{nav.document}</span></button><button type="button" className={`mobile-nav-item${view==='editor'?' mobile-nav-item--active':''}`} onClick={()=>setView('editor')}><Pencil size={20}/><span>{nav.editor}</span></button><button type="button" className="mobile-nav-item" disabled><SlidersHorizontal size={20}/><span>{nav.details}</span></button><button type="button" className={`mobile-nav-item${view==='account'?' mobile-nav-item--active':''}`} onClick={()=>setView('account')}><User size={20}/><span>{nav.account}</span></button></nav></div>}
