import type { TranslationDictionary } from '../types';

export const bg: TranslationDictionary = {
  common: {
    save: 'Запазване', cancel: 'Отказ', close: 'Затваряне', delete: 'Изтриване', edit: 'Редактиране', add: 'Добавяне', loading: 'Зареждане…', language: 'Език'
  },
  navigation: {
    documents: 'Документи', editor: 'Редактор', metadata: 'Метаданни', preview: 'Преглед', settings: 'Настройки'
  },
  studio: {
    menu: 'Меню на ръкописа', closeMenu: 'Затваряне на менюто на ръкописа', languageSwitcher: 'Език на интерфейса', saved: 'Запазено', pending: 'Запазване…', editorAria: 'Редактор на ръкопис', titlePlaceholder: 'Въведете заглавието на ръкописа', noSection: 'Няма избран раздел.',
    navigation: { document: 'Документ', manuscript: 'Данни за ръкописа', notes: 'Бележки', references: 'Източници', contributors: 'Сътрудници', history: 'История', tools: 'Експорт и инструменти', settings: 'Настройки' },
    document: { title: 'Структура на документа', description: 'Изберете раздела, по който искате да работите. Структурната информация и данните за обектите остават извън полето за писане, докато не са ви необходими.', addSection: 'Добавяне на раздел', sections: 'Раздели', objects: 'Обекти', annotations: 'Анотации', citations: 'Цитирания' },
    manuscript: { title: 'Данни за ръкописа', description: 'Редактирайте информацията на ниво ръкопис отделно от полето за писане.' },
    tools: { title: 'Експорт и инструменти', description: 'Вторичните, техническите и потенциално разрушителните действия са отделени от полето за писане.', export: 'Експорт .omi.json', exportDescription: 'Създайте каноничен преносим OMI файл на ръкописа след записване на текущите промени като контролна точка.', reset: 'Нулиране на примера', resetDescription: 'Заменете текущия алфа пример с нов чист примерен ръкопис.', confirmReset: 'Да се нулира ли текущият примерен ръкопис? Незапазените и текущите примерни данни ще бъдат заменени.', technicalData: 'Технически данни', technicalDescription: 'Преглеждайте семантичното представяне само когато са необходими технически подробности.', liveJson: 'JSON на текущия раздел', synced: 'Синхронизирано' },
    settings: { title: 'Настройки на интерфейса', description: 'Изберете кои езици на интерфейса да бъдат достъпни по време на работа. Предпочитанията се съхраняват на това устройство.', interfaceLanguages: 'Достъпни езици на интерфейса', interfaceLanguagesDescription: 'Активираните езици се показват в бързия превключвател в заглавната лента на редактора.', currentLanguage: 'Текущ език на интерфейса', currentLanguageHint: 'Текущо използваният език трябва да остане активиран. Превключете към друг език, преди да го изключите.', enabledLanguage: 'Достъпен в бързия превключвател', disabledLanguage: 'Скрит от бързия превключвател', futureLanguages: 'Езиковият регистър е разширяем. Нови речници за превод могат да се добавят без преработване на този екран.' }
  },
  manuscript: { newDocument: 'Нов ръкопис', documentTitle: 'Заглавие на документа', abstract: 'Резюме', keywords: 'Ключови думи', contributors: 'Сътрудници', sections: 'Раздели', annotations: 'Бележки', citations: 'Цитирания', bibliography: 'Библиография', documentLanguage: 'Език на документа', originalLanguage: 'Оригинален език' },
  notes: { title: 'Бележки', description: 'Управлявайте семантичните бележки към ръкописа. Текстът на бележките остава независим обект за анотация, а вградените котви остават в текста.', empty: 'Този ръкопис все още няма бележки.', emptyHint: 'Поставете курсора в текста и използвайте бутона Бележка или Ctrl/Cmd+Alt+N.', note: 'Бележка', type: 'Тип бележка', body: 'Текст на бележката', bodyPlaceholder: 'Напишете бележката…', footnote: 'Бележка под линия', endnote: 'Бележка в края', authorNote: 'Авторска бележка', delete: 'Изтриване на бележката', confirmDelete: 'Да се изтрие ли тази бележка и вградената ѝ котва от ръкописа?', closeEditor: 'Затваряне на редактора на бележки', goToNote: 'Към бележката', autoSave: 'Запазва се с ревизиите на ръкописа' },
  citations: {
    referencesTitle: 'Източници', referencesDescription: 'Добавете даден труд веднъж в библиотеката с източници на ръкописа и след това го използвайте в толкова цитирания, колкото е необходимо.', addReference: 'Добавяне на източник', editReference: 'Редактиране на източник', referenceEditorDescription: 'Съхранявайте структурирани библиографски метаданни независимо от конкретно цитиране или стил на изхода.', emptyLibrary: 'Библиотеката с източници на ръкописа е празна.', emptyLibraryHint: 'Добавете книга, статия, архивен източник, уеб ресурс или друг цитиран труд, преди да вмъквате цитирания в текста.', searchReferences: 'Търсене в източниците', searchPlaceholder: 'Търсене по заглавие, автор, година, DOI…', untitledReference: 'Източник без заглавие', occurrences: 'цитирания', bibliographyPreviewDescription: 'Неутрален преглед на записите, които в момента са цитирани в ръкописа. Окончателното форматиране се определя от профила за публикуване.', resourceType: 'Тип ресурс', title: 'Заглавие', titlePlaceholder: 'Заглавие на цитирания труд', subtitle: 'Подзаглавие', creators: 'Автори и сътрудници', creatorsDescription: 'Съхранявайте имената структурирано, за да могат стиловете за цитиране и експортите да ги визуализират правилно.', addCreator: 'Добавяне на автор/сътрудник', removeCreator: 'Премахване на автор/сътрудник', noCreators: 'Не е добавен автор или сътрудник.', creatorRole: 'Роля', givenName: 'Собствено име', familyName: 'Фамилия', containerTitle: 'Заглавие на списание, книга или контейнер', issued: 'Дата / година на публикация', volume: 'Том', issue: 'Брой', pages: 'Страници / обем', publisher: 'Издател', place: 'Място на издаване', duplicateReference: 'Вероятен дубликат вече съществува в библиотеката с източници:', insertTitle: 'Вмъкване на цитиране', insertDescription: 'Изберете труд от библиотеката с източници и по желание посочете конкретното цитирано място.', noReferences: 'Все още няма наличен източник.', noReferencesHint: 'Добавете труда чрез Меню на ръкописа → Източници и след това се върнете тук, за да го цитирате.', insert: 'Вмъкване на цитиране', citation: 'Цитиране', reference: 'Цитиран труд', locatorType: 'Тип локатор', locator: 'Локатор', locatorPlaceholder: 'напр. 45–47, 12r–13v, глава 4', prefix: 'Префикс', prefixPlaceholder: 'напр. виж също', suffix: 'Суфикс', suffixPlaceholder: 'напр. курсивът е добавен', openSource: 'Отваряне на източника', closeEditor: 'Затваряне на редактора за цитирания', deleteCitation: 'Изтриване на цитиране', confirmDeleteCitation: 'Да се изтрие ли това конкретно цитиране от ръкописа? Библиографският запис ще остане в библиотеката.', unresolvedReference: 'Цитираният библиографски запис не може да бъде разрешен или липсва.',
    roles: { author: 'Автор', editor: 'Редактор', translator: 'Преводач', compiler: 'Съставител', contributor: 'Сътрудник' },
    resourceTypes: { 'journal-article': 'Статия в списание', book: 'Книга', 'book-chapter': 'Глава от книга', 'conference-paper': 'Доклад от конференция', thesis: 'Дипломна работа', dissertation: 'Дисертация', report: 'Доклад', preprint: 'Препринт', dataset: 'Набор от данни', software: 'Софтуер', standard: 'Стандарт', 'archival-source': 'Архивен източник', manuscript: 'Ръкопис', 'web-page': 'Уеб страница' },
    locators: { page: 'Страница', 'page-range': 'Диапазон от страници', chapter: 'Глава', section: 'Раздел', paragraph: 'Абзац', figure: 'Фигура', table: 'Таблица', folio: 'Фолио', line: 'Ред', timestamp: 'Времева отметка' }
  },
  contributors: { description: 'Управлявайте преносими научни идентичности и специфичните им роли в ръкописа.', add: 'Добавяне на сътрудник', empty: 'Към този ръкопис не са добавени сътрудници.', remove: 'Премахване на сътрудник', moveUp: 'Преместване нагоре', moveDown: 'Преместване надолу', givenName: 'Собствено име', familyName: 'Фамилия', affiliation: 'Институционална принадлежност', orcid: 'ORCID', invalidOrcid: 'Контролната сума или форматът на ORCID е невалиден.', role: 'Роля на приноса', corresponding: 'Кореспондиращ сътрудник', roles: { author: 'Автор', editor: 'Редактор', translator: 'Преводач', reviewer: 'Рецензент', dataCurator: 'Куратор на данни', software: 'Софтуер', methodology: 'Методология', visualization: 'Визуализация', other: 'Друго' } },
  history: { title: 'История на ревизиите', description: 'Неизменяеми ревизии OMI-SPEC-160, записани за този ръкопис.', empty: 'Няма записани ревизии.', current: 'Текуща', revision: 'Ревизия', events: 'събития', groupedChanges: 'групирани промени', unknownActor: 'Неизвестен участник', completeHistory: 'Пълна история', shallowHistory: 'Съкратена история', pendingTitle: 'Непотвърдено работно състояние', pendingDescription: 'Последните редакции се групират и ще станат една неизменяема ревизия на контролна точка.', pendingBadge: 'Чакащо', checkpoint: 'Запазване на контролна точка', discard: 'Отхвърляне на промените', confirmDiscard: 'Да се отхвърлят ли всички непотвърдени промени и да се възстанови последната записана ревизия?', revert: 'Връщане', confirmRevert: 'Да се създаде ли нова ревизия, която възстановява това по-ранно състояние на ръкописа?', revertBlocked: 'Запазете или отхвърлете текущото работно състояние, преди да върнете записана ревизия.', tombstonesTitle: 'Записи за изтрити обекти', tombstonesDescription: 'Постоянните OMI-SPEC-160 tombstone записи съхраняват идентификаторите на изтритите обекти и доказателствата за възстановяване.', tombstoneActive: 'Изтрито', tombstoneRestored: 'Възстановено', operations: { snapshotCreated: 'Създадена е снимка на ръкописа', titleChanged: 'Заглавието на ръкописа е променено', abstractChanged: 'Резюмето на ръкописа е променено', sectionCreated: 'Добавен е раздел', blockChanged: 'Съдържанието на блока е променено', contributorAdded: 'Добавен е сътрудник', contributorChanged: 'Идентичността на сътрудника е променена', contributorRemoved: 'Сътрудникът е премахнат', contributionChanged: 'Ролята на приноса е променена', contributorsReordered: 'Сътрудниците са пренаредени', reverted: 'Възстановена е по-ранна ревизия' } },
  editor: { addSection: 'Добавяне на раздел', addParagraph: 'Добавяне на абзац', addNote: 'Бележка', addCitation: 'Цитиране', untitledSection: 'Раздел без заглавие', emptyParagraph: 'Започнете да пишете…', paragraph: 'Абзац', heading: 'Заглавие', quote: 'Цитат', insertNote: 'Вмъкване на семантична бележка към ръкописа', insertCitation: 'Вмъкване на семантично цитиране', loading: 'Зареждане на редактора…' },
  status: { draft: 'Чернова', submitted: 'Подадено', accepted: 'Прието', published: 'Публикувано' },
  validation: { requiredField: 'Това поле е задължително.', invalidDocument: 'Структурата на документа е невалидна.', unsupportedSchema: 'Версията на схемата на документа не се поддържа.' },
  languages: { en: 'Английски', hu: 'Унгарски', de: 'Немски' },
  auth: {
    brand: { name: 'Open Manuscript Studio', description: 'Съвместно научно писане' },
    login: { title: 'Вход', description: 'Влезте, за да продължите.', submit: 'Вход', submitting: 'Влизане…', noAccount: 'Все още нямате акаунт?', registerLink: 'Регистрация' },
    register: { title: 'Създаване на акаунт', description: 'Създайте своя акаунт.', submit: 'Регистрация', hasAccount: 'Вече имате акаунт?', loginLink: 'Вход' },
    fields: { name: { label: 'Пълно име', placeholder: 'Вашето пълно име' }, email: { label: 'Имейл', placeholder: 'name@example.com' }, password: { label: 'Парола', placeholder: 'Въведете паролата си' } },
    errors: { invalidEmail: 'Невалиден имейл адрес.', invalidCredentials: 'Неправилен имейл адрес или парола.', userNotFound: 'Потребителският акаунт не беше намерен.', accountNotActive: 'Потребителският акаунт не е активен.', authenticationRequired: 'Необходимо е удостоверяване.' },
    alphaNotice: 'Алфа версия – удостоверяването в момента е предназначено за тестови цели.'
  }
};
