import type { TranslationDictionary } from '../types';

export const cs: TranslationDictionary = {
  common: { save: 'Uložit', cancel: 'Zrušit', close: 'Zavřít', delete: 'Smazat', edit: 'Upravit', add: 'Přidat', loading: 'Načítání…', language: 'Jazyk' },
  navigation: { documents: 'Dokumenty', editor: 'Editor', metadata: 'Metadata', preview: 'Náhled', settings: 'Nastavení' },
  studio: {
    menu: 'Nabídka rukopisu', closeMenu: 'Zavřít nabídku rukopisu', languageSwitcher: 'Jazyk rozhraní', saved: 'Uloženo', pending: 'Ukládání…', editorAria: 'Editor rukopisu', titlePlaceholder: 'Zadejte název rukopisu', noSection: 'Není vybrána žádná sekce.',
    navigation: { document: 'Dokument', manuscript: 'Údaje rukopisu', notes: 'Poznámky', references: 'Reference', contributors: 'Přispěvatelé', history: 'Historie', tools: 'Export a nástroje', settings: 'Nastavení' },
    document: { title: 'Struktura dokumentu', description: 'Vyberte sekci, na které chcete pracovat. Strukturální informace a informace o objektech zůstávají mimo plochu pro psaní, dokud je nepotřebujete.', addSection: 'Přidat sekci', sections: 'Sekce', objects: 'Objekty', annotations: 'Anotace', citations: 'Citace' },
    manuscript: { title: 'Údaje rukopisu', description: 'Upravujte informace na úrovni rukopisu odděleně od plochy pro psaní.' },
    tools: { title: 'Export a nástroje', description: 'Sekundární, technické a potenciálně destruktivní akce jsou odděleny od plochy pro psaní.', export: 'Exportovat .omi.json', exportDescription: 'Po uložení nevyřízených změn do kontrolního bodu vytvořte kanonický přenositelný soubor rukopisu OMI.', reset: 'Obnovit ukázku', resetDescription: 'Nahraďte současný alfa vzorek novým čistým ukázkovým rukopisem.', confirmReset: 'Obnovit aktuální ukázkový rukopis? Neuložená a aktuální ukázková data budou nahrazena.', technicalData: 'Technická data', technicalDescription: 'Sémantickou reprezentaci kontrolujte pouze tehdy, když potřebujete technické podrobnosti.', liveJson: 'JSON aktuální sekce', synced: 'Synchronizováno' },
    settings: { title: 'Nastavení rozhraní', description: 'Vyberte jazyky rozhraní, které chcete mít při práci k dispozici. Předvolby se ukládají na tomto zařízení.', interfaceLanguages: 'Dostupné jazyky rozhraní', interfaceLanguagesDescription: 'Povolené jazyky se zobrazují v rychlém přepínači jazyků v záhlaví editoru.', currentLanguage: 'Aktuální jazyk rozhraní', currentLanguageHint: 'Aktuálně používaný jazyk musí zůstat povolen. Před jeho zakázáním přepněte na jiný jazyk.', enabledLanguage: 'Dostupný v rychlém přepínači', disabledLanguage: 'Skrytý v rychlém přepínači', futureLanguages: 'Registr jazyků je rozšiřitelný. Další překladové slovníky lze přidávat bez změny této obrazovky.' }
  },
  manuscript: { newDocument: 'Nový rukopis', documentTitle: 'Název dokumentu', abstract: 'Abstrakt', keywords: 'Klíčová slova', contributors: 'Přispěvatelé', sections: 'Sekce', annotations: 'Poznámky', citations: 'Citace', bibliography: 'Bibliografie', documentLanguage: 'Jazyk dokumentu', originalLanguage: 'Původní jazyk' },
  notes: { title: 'Poznámky', description: 'Spravujte sémantické poznámky rukopisu. Text poznámky zůstává samostatným anotačním objektem, zatímco její vložené kotvy zůstávají v textu.', empty: 'Tento rukopis zatím neobsahuje žádné poznámky.', emptyHint: 'Umístěte kurzor do textu a použijte tlačítko Poznámka nebo Ctrl/Cmd+Alt+N.', note: 'Poznámka', type: 'Typ poznámky', body: 'Text poznámky', bodyPlaceholder: 'Napište poznámku…', footnote: 'Poznámka pod čarou', endnote: 'Koncová poznámka', authorNote: 'Poznámka autora', delete: 'Smazat poznámku', confirmDelete: 'Smazat tuto poznámku a její vloženou kotvu z rukopisu?', closeEditor: 'Zavřít editor poznámek', goToNote: 'Přejít na poznámku', autoSave: 'Ukládá se spolu s revizemi rukopisu' },
  citations: {
    referencesTitle: 'Reference', referencesDescription: 'Přidejte dílo jednou do knihovny referencí rukopisu a poté je znovu použijte v libovolném počtu citačních výskytů.', addReference: 'Přidat referenci', editReference: 'Upravit referenci', referenceEditorDescription: 'Ukládejte strukturovaná bibliografická metadata nezávisle na konkrétní citaci nebo výstupním stylu.', emptyLibrary: 'Knihovna referencí rukopisu je prázdná.', emptyLibraryHint: 'Před vložením citací do textu přidejte knihu, článek, archivní pramen, webový zdroj nebo jiné citované dílo.', searchReferences: 'Hledat v referencích', searchPlaceholder: 'Hledat podle názvu, autora, roku, DOI…', untitledReference: 'Reference bez názvu', occurrences: 'citací', bibliographyPreviewDescription: 'Neutrální náhled záznamů aktuálně citovaných v rukopisu. Konečné formátování určuje publikační profil.', resourceType: 'Typ zdroje', title: 'Název', titlePlaceholder: 'Název citovaného díla', subtitle: 'Podnázev', creators: 'Autoři a přispěvatelé', creatorsDescription: 'Udržujte jména přispěvatelů strukturovaná, aby je citační styly a exporty mohly správně vykreslit.', addCreator: 'Přidat autora/přispěvatele', removeCreator: 'Odebrat autora/přispěvatele', noCreators: 'Nebyl přidán žádný autor ani přispěvatel.', creatorRole: 'Role', givenName: 'Jméno', familyName: 'Příjmení', containerTitle: 'Název časopisu, knihy nebo nadřazeného díla', issued: 'Datum / rok vydání', volume: 'Ročník / svazek', issue: 'Číslo', pages: 'Strany / rozsah', publisher: 'Vydavatel', place: 'Místo vydání', duplicateReference: 'V knihovně referencí již pravděpodobně existuje duplicitní záznam:', insertTitle: 'Vložit citaci', insertDescription: 'Vyberte dílo z knihovny referencí rukopisu a volitelně zadejte citované místo.', noReferences: 'Zatím není k dispozici žádná reference.', noReferencesHint: 'Přidejte dílo přes Nabídka rukopisu → Reference a poté se sem vraťte a citujte je.', insert: 'Vložit citaci', citation: 'Citace', reference: 'Citované dílo', locatorType: 'Typ lokátoru', locator: 'Lokátor', locatorPlaceholder: 'např. 45–47, 12r–13v, kapitola 4', prefix: 'Prefix', prefixPlaceholder: 'např. viz také', suffix: 'Sufix', suffixPlaceholder: 'např. zvýraznění doplněno', openSource: 'Otevřít zdroj', closeEditor: 'Zavřít editor citací', deleteCitation: 'Smazat citaci', confirmDeleteCitation: 'Smazat tento výskyt citace z rukopisu? Bibliografický záznam zůstane v knihovně referencí.', unresolvedReference: 'Citovaný bibliografický záznam nelze vyřešit nebo chybí.',
    roles: { author: 'Autor', editor: 'Editor', translator: 'Překladatel', compiler: 'Sestavovatel', contributor: 'Přispěvatel' },
    resourceTypes: { 'journal-article': 'Článek v časopise', book: 'Kniha', 'book-chapter': 'Kapitola v knize', 'conference-paper': 'Konferenční příspěvek', thesis: 'Závěrečná práce', dissertation: 'Disertace', report: 'Zpráva', preprint: 'Preprint', dataset: 'Datová sada', software: 'Software', standard: 'Norma', 'archival-source': 'Archivní pramen', manuscript: 'Rukopis', 'web-page': 'Webová stránka' },
    locators: { page: 'Strana', 'page-range': 'Rozsah stran', chapter: 'Kapitola', section: 'Sekce', paragraph: 'Odstavec', figure: 'Obrázek', table: 'Tabulka', folio: 'Folio', line: 'Řádek', timestamp: 'Časová značka' }
  },
  contributors: { description: 'Spravujte přenositelné vědecké identity a jejich role přispění specifické pro rukopis.', add: 'Přidat přispěvatele', empty: 'K tomuto rukopisu nebyli přidáni žádní přispěvatelé.', remove: 'Odebrat přispěvatele', moveUp: 'Posunout přispěvatele nahoru', moveDown: 'Posunout přispěvatele dolů', givenName: 'Jméno', familyName: 'Příjmení', affiliation: 'Afiliace', orcid: 'ORCID', invalidOrcid: 'Kontrolní součet nebo formát ORCID je neplatný.', role: 'Role přispění', corresponding: 'Korespondující přispěvatel', roles: { author: 'Autor', editor: 'Editor', translator: 'Překladatel', reviewer: 'Recenzent', dataCurator: 'Kurátor dat', software: 'Software', methodology: 'Metodologie', visualization: 'Vizualizace', other: 'Jiné' } },
  history: { title: 'Historie revizí', description: 'Neměnné revize OMI-SPEC-160 zaznamenané pro tento rukopis.', empty: 'Nebyly zaznamenány žádné revize.', current: 'Aktuální', revision: 'Revize', events: 'událostí', groupedChanges: 'seskupených změn', unknownActor: 'Neznámý účastník', completeHistory: 'Úplná historie', shallowHistory: 'Zkrácená historie', pendingTitle: 'Nepotvrzený pracovní stav', pendingDescription: 'Nedávné úpravy se seskupují a stanou se jednou neměnnou revizí kontrolního bodu.', pendingBadge: 'Čeká', checkpoint: 'Uložit kontrolní bod', discard: 'Zahodit změny', confirmDiscard: 'Zahodit všechny nepotvrzené změny a obnovit poslední potvrzenou revizi?', revert: 'Vrátit', confirmRevert: 'Vytvořit novou revizi, která obnoví tento dřívější stav rukopisu?', revertBlocked: 'Před návratem k potvrzené revizi uložte nebo zahoďte čekající pracovní stav.', tombstonesTitle: 'Záznamy smazaných objektů', tombstonesDescription: 'Trvalé záznamy OMI-SPEC-160 tombstone uchovávají identifikátory smazaných objektů a doklady o obnovení.', tombstoneActive: 'Smazáno', tombstoneRestored: 'Obnoveno', operations: { snapshotCreated: 'Vytvořen snímek rukopisu', titleChanged: 'Název rukopisu změněn', abstractChanged: 'Abstrakt rukopisu změněn', sectionCreated: 'Sekce přidána', blockChanged: 'Obsah bloku změněn', contributorAdded: 'Přispěvatel přidán', contributorChanged: 'Identita přispěvatele změněna', contributorRemoved: 'Přispěvatel odebrán', contributionChanged: 'Role přispění změněna', contributorsReordered: 'Přispěvatelé přeuspořádáni', reverted: 'Obnovena dřívější revize' } },
  editor: { addSection: 'Přidat sekci', addParagraph: 'Přidat odstavec', addNote: 'Poznámka', addCitation: 'Citace', untitledSection: 'Sekce bez názvu', emptyParagraph: 'Začněte psát…', paragraph: 'Odstavec', heading: 'Nadpis', quote: 'Citace', insertNote: 'Vložit sémantickou poznámku rukopisu', insertCitation: 'Vložit sémantickou citaci', loading: 'Načítání editoru…' },
  status: { draft: 'Koncept', submitted: 'Odesláno', accepted: 'Přijato', published: 'Publikováno' },
  validation: { requiredField: 'Toto pole je povinné.', invalidDocument: 'Struktura dokumentu je neplatná.', unsupportedSchema: 'Verze schématu dokumentu není podporována.' },
  languages: { en: 'Angličtina', hu: 'Maďarština', de: 'Němčina' },
  auth: { brand: { name: 'Open Manuscript Studio', description: 'Spolupráce při vědeckém psaní' }, login: { title: 'Přihlášení', description: 'Pro pokračování se přihlaste.', submit: 'Přihlásit se', submitting: 'Přihlašování…', noAccount: 'Ještě nemáte účet?', registerLink: 'Registrovat' }, register: { title: 'Vytvořit účet', description: 'Vytvořte si účet.', submit: 'Registrovat', hasAccount: 'Už máte účet?', loginLink: 'Přihlásit se' }, fields: { name: { label: 'Celé jméno', placeholder: 'Vaše celé jméno' }, email: { label: 'E-mail', placeholder: 'jmeno@example.cz' }, password: { label: 'Heslo', placeholder: 'Zadejte heslo' } }, errors: { invalidEmail: 'Neplatná e-mailová adresa.', invalidCredentials: 'Nesprávná e-mailová adresa nebo heslo.', userNotFound: 'Uživatelský účet nebyl nalezen.', accountNotActive: 'Uživatelský účet není aktivní.', authenticationRequired: 'Je vyžadováno ověření.' }, alphaNotice: 'Alfa verze – ověřování je nyní určeno pro testovací účely.' }
};
