import type { TranslationDictionary } from '../types';

export const et: TranslationDictionary = {
  common: { save: 'Salvesta', cancel: 'Loobu', close: 'Sulge', delete: 'Kustuta', edit: 'Muuda', add: 'Lisa', loading: 'Laadimine…', language: 'Keel' },
  navigation: { documents: 'Dokumendid', editor: 'Redaktor', metadata: 'Metaandmed', preview: 'Eelvaade', settings: 'Seaded' },
  studio: {
    menu: 'Käsikirja menüü', closeMenu: 'Sulge käsikirja menüü', languageSwitcher: 'Kasutajaliidese keel', saved: 'Salvestatud', pending: 'Salvestamine…', editorAria: 'Käsikirja redaktor', titlePlaceholder: 'Sisestage käsikirja pealkiri', noSection: 'Ühtegi jaotist pole valitud.',
    navigation: { document: 'Dokument', manuscript: 'Käsikirja andmed', notes: 'Märkused', references: 'Viited', contributors: 'Kaasautorid', history: 'Ajalugu', tools: 'Eksport ja tööriistad', settings: 'Seaded' },
    document: { title: 'Dokumendi struktuur', description: 'Valige jaotis, millega soovite töötada. Struktuuri- ja objektiandmed jäävad kirjutamisalast välja seni, kuni neid vajate.', addSection: 'Lisa jaotis', sections: 'Jaotised', objects: 'Objektid', annotations: 'Annotatsioonid', citations: 'Tsitaadid' },
    manuscript: { title: 'Käsikirja andmed', description: 'Muutke käsikirja taseme teavet kirjutamisalast eraldi.' },
    tools: { title: 'Eksport ja tööriistad', description: 'Teiseseid, tehnilisi ja potentsiaalselt hävitavaid toiminguid hoitakse kirjutamisalast eraldi.', export: 'Ekspordi .omi.json', exportDescription: 'Looge kanooniline kaasaskantav OMI käsikirjafail pärast ootel muudatuste salvestamist kontrollpunktina.', reset: 'Lähtesta näidis', resetDescription: 'Asendage praegune alfa-näidis uue puhta näidiskäsikirjaga.', confirmReset: 'Kas lähtestada praegune näidiskäsikiri? Salvestamata ja praegused näidisandmed asendatakse.', technicalData: 'Tehnilised andmed', technicalDescription: 'Vaadake semantilist esitust ainult siis, kui vajate tehnilisi üksikasju.', liveJson: 'Praeguse jaotise JSON', synced: 'Sünkroonitud' },
    settings: { title: 'Kasutajaliidese seaded', description: 'Valige kasutajaliidese keeled, mida soovite töötamise ajal kasutada. Eelistused salvestatakse sellesse seadmesse.', interfaceLanguages: 'Saadaolevad kasutajaliidese keeled', interfaceLanguagesDescription: 'Lubatud keeled kuvatakse redaktori päise kiirkeelevalikus.', currentLanguage: 'Praegune kasutajaliidese keel', currentLanguageHint: 'Praegu kasutatav keel peab jääma lubatuks. Enne selle keelamist lülituge teisele keelele.', enabledLanguage: 'Saadaval kiirvalikus', disabledLanguage: 'Kiirvalikus peidetud', futureLanguages: 'Keeleregister on laiendatav. Uusi tõlkesõnastikke saab lisada seda seadete vaadet ümber kujundamata.' }
  },
  manuscript: { newDocument: 'Uus käsikiri', documentTitle: 'Dokumendi pealkiri', abstract: 'Abstrakt', keywords: 'Märksõnad', contributors: 'Kaasautorid', sections: 'Jaotised', annotations: 'Märkused', citations: 'Tsitaadid', bibliography: 'Bibliograafia', documentLanguage: 'Dokumendi keel', originalLanguage: 'Algkeel' },
  notes: { title: 'Märkused', description: 'Hallake käsikirja semantilisi märkusi. Märkuse sisu jääb iseseisvaks annotatsiooniobjektiks, samal ajal kui tekstisisesed ankrud jäävad teksti.', empty: 'Selles käsikirjas pole veel märkusi.', emptyHint: 'Asetage kursor teksti ja kasutage nuppu Märkus või Ctrl/Cmd+Alt+N.', note: 'Märkus', type: 'Märkuse tüüp', body: 'Märkuse tekst', bodyPlaceholder: 'Kirjutage märkus…', footnote: 'Joonealune märkus', endnote: 'Lõpumärkus', authorNote: 'Autori märkus', delete: 'Kustuta märkus', confirmDelete: 'Kas kustutada see märkus ja selle tekstisisene ankur käsikirjast?', closeEditor: 'Sulge märkuste redaktor', goToNote: 'Mine märkuse juurde', autoSave: 'Salvestatakse koos käsikirja revisjonidega' },
  citations: {
    referencesTitle: 'Viited', referencesDescription: 'Lisage teos üks kord käsikirja viitekogusse ja kasutage seda seejärel nii paljudes viitamisjuhtudes kui vaja.', addReference: 'Lisa viide', editReference: 'Muuda viidet', referenceEditorDescription: 'Hoidke struktureeritud bibliograafilisi metaandmeid sõltumatult üksikust viitest või väljundstiilist.', emptyLibrary: 'Käsikirja viitekogu on tühi.', emptyLibraryHint: 'Lisage raamat, artikkel, arhiiviallikas, veebiallikas või muu tsiteeritud teos enne tekstisiseste viidete lisamist.', searchReferences: 'Otsi viiteid', searchPlaceholder: 'Otsi pealkirja, autori, aasta, DOI järgi…', untitledReference: 'Pealkirjata viide', occurrences: 'viitamist', bibliographyPreviewDescription: 'Neutraalne eelvaade kirjetest, millele käsikirjas praegu viidatakse. Lõplik vormindus kuulub avaldamisprofiili juurde.', resourceType: 'Allika tüüp', title: 'Pealkiri', titlePlaceholder: 'Tsiteeritud teose pealkiri', subtitle: 'Alapealkiri', creators: 'Autorid ja kaasautorid', creatorsDescription: 'Hoidke nimed struktureerituna, et viitamisstiilid ja ekspordid saaksid neid õigesti kuvada.', addCreator: 'Lisa autor/kaasautor', removeCreator: 'Eemalda autor/kaasautor', noCreators: 'Ühtegi autorit ega kaasautorit pole lisatud.', creatorRole: 'Roll', givenName: 'Eesnimi', familyName: 'Perekonnanimi', containerTitle: 'Ajakirja, raamatu või kogumiku pealkiri', issued: 'Avaldamiskuupäev / aasta', volume: 'Köide', issue: 'Number', pages: 'Leheküljed / ulatus', publisher: 'Kirjastaja', place: 'Avaldamiskoht', duplicateReference: 'Viitekogus on tõenäoliselt juba duplikaat:', insertTitle: 'Lisa viide', insertDescription: 'Valige käsikirja viitekogust teos ja määrake soovi korral tsiteeritud koht.', noReferences: 'Ühtegi viidet pole veel saadaval.', noReferencesHint: 'Lisage teos menüüst Käsikirja menüü → Viited ja tulge seejärel siia tagasi, et sellele viidata.', insert: 'Lisa viide', citation: 'Viide', reference: 'Tsiteeritud teos', locatorType: 'Asukohamääraja tüüp', locator: 'Asukohamääraja', locatorPlaceholder: 'nt 45–47, 12r–13v, peatükk 4', prefix: 'Eesliide', prefixPlaceholder: 'nt vt ka', suffix: 'Järelliide', suffixPlaceholder: 'nt rõhutus lisatud', openSource: 'Ava allikas', closeEditor: 'Sulge viidete redaktor', deleteCitation: 'Kustuta viide', confirmDeleteCitation: 'Kas kustutada see viitamisjuht käsikirjast? Bibliograafiline kirje jääb viitekogusse.', unresolvedReference: 'Tsiteeritud bibliograafilist kirjet ei leitud või see puudub.',
    roles: { author: 'Autor', editor: 'Toimetaja', translator: 'Tõlkija', compiler: 'Koostaja', contributor: 'Kaasautor' },
    resourceTypes: { 'journal-article': 'Ajakirjaartikkel', book: 'Raamat', 'book-chapter': 'Raamatupeatükk', 'conference-paper': 'Konverentsiettekanne', thesis: 'Lõputöö', dissertation: 'Doktoritöö', report: 'Aruanne', preprint: 'Eeltrükk', dataset: 'Andmestik', software: 'Tarkvara', standard: 'Standard', 'archival-source': 'Arhiiviallikas', manuscript: 'Käsikiri', 'web-page': 'Veebileht' },
    locators: { page: 'Lehekülg', 'page-range': 'Leheküljevahemik', chapter: 'Peatükk', section: 'Jaotis', paragraph: 'Lõik', figure: 'Joonis', table: 'Tabel', folio: 'Foolio', line: 'Rida', timestamp: 'Ajatempel' }
  },
  contributors: { description: 'Hallake kaasaskantavaid teadusidentiteete ja nende käsikirjapõhiseid panuserolle.', add: 'Lisa kaasautor', empty: 'Sellele käsikirjale pole kaasautoreid lisatud.', remove: 'Eemalda kaasautor', moveUp: 'Liiguta kaasautor üles', moveDown: 'Liiguta kaasautor alla', givenName: 'Eesnimi', familyName: 'Perekonnanimi', affiliation: 'Institutsionaalne kuuluvus', orcid: 'ORCID', invalidOrcid: 'ORCID-i kontrollsumma või vorming on vigane.', role: 'Panuseroll', corresponding: 'Kontaktisikust kaasautor', roles: { author: 'Autor', editor: 'Toimetaja', translator: 'Tõlkija', reviewer: 'Retsensent', dataCurator: 'Andmekuraator', software: 'Tarkvara', methodology: 'Metoodika', visualization: 'Visualiseerimine', other: 'Muu' } },
  history: { title: 'Revisjonide ajalugu', description: 'Selle käsikirja jaoks salvestatud muutumatud OMI-SPEC-160 revisjonid.', empty: 'Revisjone pole salvestatud.', current: 'Praegune', revision: 'Revisjon', events: 'sündmust', groupedChanges: 'rühmitatud muudatused', unknownActor: 'Tundmatu osapool', completeHistory: 'Täielik ajalugu', shallowHistory: 'Lühike ajalugu', pendingTitle: 'Kinnitamata tööolek', pendingDescription: 'Hiljutised muudatused rühmitatakse ja neist saab üks muutumatu kontrollpunkti revisjon.', pendingBadge: 'Ootel', checkpoint: 'Salvesta kontrollpunkt', discard: 'Loobu muudatustest', confirmDiscard: 'Kas loobuda kõigist kinnitamata muudatustest ja taastada viimane kinnitatud revisjon?', revert: 'Taasta', confirmRevert: 'Kas luua uus revisjon, mis taastab käsikirja selle varasema oleku?', revertBlocked: 'Enne kinnitatud revisjoni taastamist salvestage või tühistage ootel tööolek.', tombstonesTitle: 'Kustutatud objektide kirjed', tombstonesDescription: 'Püsivad OMI-SPEC-160 tombstone-kirjed säilitavad kustutatud objektide identifikaatorid ja taastamise tõendid.', tombstoneActive: 'Kustutatud', tombstoneRestored: 'Taastatud', operations: { snapshotCreated: 'Käsikirja hetktõmmis loodud', titleChanged: 'Käsikirja pealkiri muudetud', abstractChanged: 'Käsikirja abstrakt muudetud', sectionCreated: 'Jaotis lisatud', blockChanged: 'Ploki sisu muudetud', contributorAdded: 'Kaasautor lisatud', contributorChanged: 'Kaasautori identiteet muudetud', contributorRemoved: 'Kaasautor eemaldatud', contributionChanged: 'Panuseroll muudetud', contributorsReordered: 'Kaasautorid ümber järjestatud', reverted: 'Varasem revisjon taastatud' } },
  editor: { addSection: 'Lisa jaotis', addParagraph: 'Lisa lõik', addNote: 'Märkus', addCitation: 'Viide', untitledSection: 'Pealkirjata jaotis', emptyParagraph: 'Alustage kirjutamist…', paragraph: 'Lõik', heading: 'Pealkiri', quote: 'Tsitaat', insertNote: 'Lisa semantiline käsikirjamärkus', insertCitation: 'Lisa semantiline viide', loading: 'Redaktori laadimine…' },
  status: { draft: 'Mustand', submitted: 'Esitatud', accepted: 'Vastu võetud', published: 'Avaldatud' },
  validation: { requiredField: 'See väli on kohustuslik.', invalidDocument: 'Dokumendi struktuur on vigane.', unsupportedSchema: 'Dokumendiskeemi versiooni ei toetata.' },
  languages: { en: 'Inglise', hu: 'Ungari', de: 'Saksa' },
  auth: { brand: { name: 'Open Manuscript Studio', description: 'Koostööpõhine teadusteksti kirjutamine' }, login: { title: 'Logi sisse', description: 'Jätkamiseks logige sisse.', submit: 'Logi sisse', submitting: 'Sisselogimine…', noAccount: 'Kontot veel pole?', registerLink: 'Registreeru' }, register: { title: 'Loo konto', description: 'Looge oma konto.', submit: 'Registreeru', hasAccount: 'Kas teil on juba konto?', loginLink: 'Logi sisse' }, fields: { name: { label: 'Täisnimi', placeholder: 'Teie täisnimi' }, email: { label: 'E-post', placeholder: 'nimi@example.ee' }, password: { label: 'Parool', placeholder: 'Sisestage parool' } }, errors: { invalidEmail: 'Vigane e-posti aadress.', invalidCredentials: 'Vale e-posti aadress või parool.', userNotFound: 'Kasutajakontot ei leitud.', accountNotActive: 'Kasutajakonto pole aktiivne.', authenticationRequired: 'Autentimine on nõutav.' }, alphaNotice: 'Alfaversioon – autentimine on praegu mõeldud testimiseks.' }
};
