import type { TranslationDictionary } from '../types';

export const fi: TranslationDictionary = {
  common: { save: 'Tallenna', cancel: 'Peruuta', close: 'Sulje', delete: 'Poista', edit: 'Muokkaa', add: 'Lisää', loading: 'Ladataan…', language: 'Kieli' },
  navigation: { documents: 'Asiakirjat', editor: 'Muokkain', metadata: 'Metatiedot', preview: 'Esikatselu', settings: 'Asetukset' },
  studio: {
    menu: 'Käsikirjoitusvalikko', closeMenu: 'Sulje käsikirjoitusvalikko', languageSwitcher: 'Käyttöliittymän kieli', saved: 'Tallennettu', pending: 'Tallennetaan…', editorAria: 'Käsikirjoitusmuokkain', titlePlaceholder: 'Syötä käsikirjoituksen otsikko', noSection: 'Osaa ei ole valittu.',
    navigation: { document: 'Asiakirja', manuscript: 'Käsikirjoituksen tiedot', notes: 'Viitteet ja huomautukset', references: 'Lähteet', contributors: 'Tekijät', history: 'Historia', tools: 'Vienti ja työkalut', settings: 'Asetukset' },
    document: { title: 'Asiakirjan rakenne', description: 'Valitse osa, jota haluat käsitellä. Rakenteelliset ja objektitiedot pysyvät kirjoitusalueen ulkopuolella, kunnes tarvitset niitä.', addSection: 'Lisää osa', sections: 'Osat', objects: 'Objektit', annotations: 'Annotaatiot', citations: 'Lähdeviittaukset' },
    manuscript: { title: 'Käsikirjoituksen tiedot', description: 'Muokkaa käsikirjoitustason tietoja erillään kirjoitusalueesta.' },
    tools: { title: 'Vienti ja työkalut', description: 'Toissijaiset, tekniset ja mahdollisesti tuhoavat toiminnot pidetään kirjoitusalueen ulkopuolella.', export: 'Vie .omi.json', exportDescription: 'Luo kanoninen siirrettävä OMI-käsikirjoitustiedosto, kun odottavat muutokset on tallennettu tarkistuspisteeksi.', reset: 'Palauta esimerkki', resetDescription: 'Korvaa nykyinen alfaesimerkki uudella puhtaalla esimerkkikäsikirjoituksella.', confirmReset: 'Palautetaanko nykyinen esimerkkikäsikirjoitus? Tallentamattomat ja nykyiset esimerkkitiedot korvataan.', technicalData: 'Tekniset tiedot', technicalDescription: 'Tarkastele semanttista esitystä vain, kun teknisiä yksityiskohtia tarvitaan.', liveJson: 'Nykyisen osan JSON', synced: 'Synkronoitu' },
    settings: { title: 'Käyttöliittymän asetukset', description: 'Valitse käyttöliittymän kielet, jotka haluat pitää käytettävissä työskentelyn aikana. Asetukset tallennetaan tälle laitteelle.', interfaceLanguages: 'Käytettävissä olevat käyttöliittymäkielet', interfaceLanguagesDescription: 'Käytössä olevat kielet näkyvät muokkaimen otsikon pikakielenvaihtimessa.', currentLanguage: 'Nykyinen käyttöliittymän kieli', currentLanguageHint: 'Nykyisen kielen on pysyttävä käytössä. Vaihda toiseen kieleen ennen sen poistamista käytöstä.', enabledLanguage: 'Käytettävissä pikavaihtimessa', disabledLanguage: 'Piilotettu pikavaihtimesta', futureLanguages: 'Kielirekisteriä voidaan laajentaa. Uusia käännössanakirjoja voidaan lisätä ilman tämän asetussivun uudelleensuunnittelua.' }
  },
  manuscript: { newDocument: 'Uusi käsikirjoitus', documentTitle: 'Asiakirjan otsikko', abstract: 'Tiivistelmä', keywords: 'Avainsanat', contributors: 'Tekijät', sections: 'Osat', annotations: 'Huomautukset', citations: 'Lähdeviittaukset', bibliography: 'Lähdeluettelo', documentLanguage: 'Asiakirjan kieli', originalLanguage: 'Alkuperäinen kieli' },
  notes: { title: 'Huomautukset', description: 'Hallitse käsikirjoituksen semanttisia huomautuksia. Huomautuksen sisältö säilyy itsenäisenä annotaatio-objektina, kun taas tekstinsisäiset ankkurit pysyvät tekstissä.', empty: 'Tässä käsikirjoituksessa ei ole vielä huomautuksia.', emptyHint: 'Aseta kohdistin tekstiin ja käytä Huomautus-painiketta tai Ctrl/Cmd+Alt+N.', note: 'Huomautus', type: 'Huomautuksen tyyppi', body: 'Huomautuksen teksti', bodyPlaceholder: 'Kirjoita huomautus…', footnote: 'Alaviite', endnote: 'Loppuviite', authorNote: 'Tekijän huomautus', delete: 'Poista huomautus', confirmDelete: 'Poistetaanko tämä huomautus ja sen tekstinsisäinen ankkuri käsikirjoituksesta?', closeEditor: 'Sulje huomautusmuokkain', goToNote: 'Siirry huomautukseen', autoSave: 'Tallennetaan käsikirjoitusversioiden mukana' },
  citations: {
    referencesTitle: 'Lähteet', referencesDescription: 'Lisää teos kerran käsikirjoituksen lähdekirjastoon ja käytä sitä sen jälkeen niin monessa viittauksessa kuin tarvitaan.', addReference: 'Lisää lähde', editReference: 'Muokkaa lähdettä', referenceEditorDescription: 'Tallenna rakenteiset bibliografiset metatiedot riippumatta yksittäisestä viittauksesta tai tulostyylistä.', emptyLibrary: 'Käsikirjoituksen lähdekirjasto on tyhjä.', emptyLibraryHint: 'Lisää kirja, artikkeli, arkistolähde, verkkolähde tai muu viitattu teos ennen viittausten lisäämistä tekstiin.', searchReferences: 'Hae lähteistä', searchPlaceholder: 'Hae otsikolla, tekijällä, vuodella, DOI:lla…', untitledReference: 'Nimetön lähde', occurrences: 'viittausta', bibliographyPreviewDescription: 'Neutraali esikatselu käsikirjoituksessa tällä hetkellä viitatuista tietueista. Lopullinen muotoilu kuuluu julkaisuprofiiliin.', resourceType: 'Lähdetyyppi', title: 'Otsikko', titlePlaceholder: 'Viitatun teoksen otsikko', subtitle: 'Alaotsikko', creators: 'Tekijät ja muut osallistujat', creatorsDescription: 'Pidä nimet rakenteisina, jotta viittaustyylit ja viennit voivat esittää ne oikein.', addCreator: 'Lisää tekijä/osallistuja', removeCreator: 'Poista tekijä/osallistuja', noCreators: 'Tekijöitä tai osallistujia ei ole lisätty.', creatorRole: 'Rooli', givenName: 'Etunimi', familyName: 'Sukunimi', containerTitle: 'Lehden, kirjan tai emojulkaisun nimi', issued: 'Julkaisupäivä / vuosi', volume: 'Vuosikerta / nide', issue: 'Numero', pages: 'Sivut / laajuus', publisher: 'Kustantaja', place: 'Julkaisupaikka', duplicateReference: 'Lähdekirjastossa on todennäköisesti jo kaksoiskappale:', insertTitle: 'Lisää lähdeviittaus', insertDescription: 'Valitse teos käsikirjoituksen lähdekirjastosta ja määritä halutessasi viitattu kohta.', noReferences: 'Lähteitä ei ole vielä käytettävissä.', noReferencesHint: 'Lisää teos kohdasta Käsikirjoitusvalikko → Lähteet ja palaa sitten tänne viittaamaan siihen.', insert: 'Lisää lähdeviittaus', citation: 'Lähdeviittaus', reference: 'Viitattu teos', locatorType: 'Paikantimen tyyppi', locator: 'Paikannin', locatorPlaceholder: 'esim. 45–47, 12r–13v, luku 4', prefix: 'Etuliite', prefixPlaceholder: 'esim. ks. myös', suffix: 'Jälkiliite', suffixPlaceholder: 'esim. korostus lisätty', openSource: 'Avaa lähde', closeEditor: 'Sulje viittausmuokkain', deleteCitation: 'Poista lähdeviittaus', confirmDeleteCitation: 'Poistetaanko tämä viittaus käsikirjoituksesta? Bibliografinen tietue säilyy lähdekirjastossa.', unresolvedReference: 'Viitattua bibliografista tietuetta ei voida ratkaista tai se puuttuu.',
    roles: { author: 'Tekijä', editor: 'Toimittaja', translator: 'Kääntäjä', compiler: 'Kokoaja', contributor: 'Osallistuja' },
    resourceTypes: { 'journal-article': 'Aikakauslehtiartikkeli', book: 'Kirja', 'book-chapter': 'Kirjan luku', 'conference-paper': 'Konferenssijulkaisu', thesis: 'Opinnäyte', dissertation: 'Väitöskirja', report: 'Raportti', preprint: 'Esipainos', dataset: 'Aineisto', software: 'Ohjelmisto', standard: 'Standardi', 'archival-source': 'Arkistolähde', manuscript: 'Käsikirjoitus', 'web-page': 'Verkkosivu' },
    locators: { page: 'Sivu', 'page-range': 'Sivuväli', chapter: 'Luku', section: 'Osa', paragraph: 'Kappale', figure: 'Kuva', table: 'Taulukko', folio: 'Folio', line: 'Rivi', timestamp: 'Aikaleima' }
  },
  contributors: { description: 'Hallitse siirrettäviä tieteellisiä identiteettejä ja niiden käsikirjoituskohtaisia osallistumisrooleja.', add: 'Lisää osallistuja', empty: 'Tähän käsikirjoitukseen ei ole lisätty osallistujia.', remove: 'Poista osallistuja', moveUp: 'Siirrä osallistujaa ylöspäin', moveDown: 'Siirrä osallistujaa alaspäin', givenName: 'Etunimi', familyName: 'Sukunimi', affiliation: 'Organisaatio', orcid: 'ORCID', invalidOrcid: 'ORCID-tarkistussumma tai muoto on virheellinen.', role: 'Osallistumisrooli', corresponding: 'Vastaava osallistuja', roles: { author: 'Tekijä', editor: 'Toimittaja', translator: 'Kääntäjä', reviewer: 'Arvioija', dataCurator: 'Aineistokuraattori', software: 'Ohjelmisto', methodology: 'Metodologia', visualization: 'Visualisointi', other: 'Muu' } },
  history: { title: 'Versiohistoria', description: 'Tälle käsikirjoitukselle tallennetut muuttumattomat OMI-SPEC-160-versiot.', empty: 'Versioita ei ole tallennettu.', current: 'Nykyinen', revision: 'Versio', events: 'tapahtumaa', groupedChanges: 'ryhmiteltyä muutosta', unknownActor: 'Tuntematon toimija', completeHistory: 'Täydellinen historia', shallowHistory: 'Lyhyt historia', pendingTitle: 'Vahvistamaton työtila', pendingDescription: 'Viimeisimmät muutokset ryhmitellään ja niistä muodostuu yksi muuttumaton tarkistuspisteversio.', pendingBadge: 'Odottaa', checkpoint: 'Tallenna tarkistuspiste', discard: 'Hylkää muutokset', confirmDiscard: 'Hylätäänkö kaikki vahvistamattomat muutokset ja palautetaanko viimeisin vahvistettu versio?', revert: 'Palauta', confirmRevert: 'Luodaanko uusi versio, joka palauttaa tämän aiemman käsikirjoituksen tilan?', revertBlocked: 'Tallenna tai hylkää odottava työtila ennen vahvistetun version palauttamista.', tombstonesTitle: 'Poistettujen objektien tietueet', tombstonesDescription: 'Pysyvät OMI-SPEC-160-tombstone-tietueet säilyttävät poistettujen objektien tunnisteet ja palautustodisteet.', tombstoneActive: 'Poistettu', tombstoneRestored: 'Palautettu', operations: { snapshotCreated: 'Käsikirjoituksen tilannekuva luotu', titleChanged: 'Käsikirjoituksen otsikko muutettu', abstractChanged: 'Käsikirjoituksen tiivistelmä muutettu', sectionCreated: 'Osa lisätty', blockChanged: 'Lohkon sisältö muutettu', contributorAdded: 'Osallistuja lisätty', contributorChanged: 'Osallistujan identiteetti muutettu', contributorRemoved: 'Osallistuja poistettu', contributionChanged: 'Osallistumisrooli muutettu', contributorsReordered: 'Osallistujat järjestetty uudelleen', reverted: 'Aiempi versio palautettu' } },
  editor: { addSection: 'Lisää osa', addParagraph: 'Lisää kappale', addNote: 'Huomautus', addCitation: 'Lähdeviittaus', untitledSection: 'Nimetön osa', emptyParagraph: 'Aloita kirjoittaminen…', paragraph: 'Kappale', heading: 'Otsikko', quote: 'Lainaus', insertNote: 'Lisää semanttinen käsikirjoitushuomautus', insertCitation: 'Lisää semanttinen lähdeviittaus', loading: 'Muokkainta ladataan…' },
  status: { draft: 'Luonnos', submitted: 'Lähetetty', accepted: 'Hyväksytty', published: 'Julkaistu' },
  validation: { requiredField: 'Tämä kenttä on pakollinen.', invalidDocument: 'Asiakirjan rakenne on virheellinen.', unsupportedSchema: 'Asiakirjaskeeman versiota ei tueta.' },
  languages: { en: 'Englanti', hu: 'Unkari', de: 'Saksa' },
  auth: { brand: { name: 'Open Manuscript Studio', description: 'Yhteisöllinen tieteellinen kirjoittaminen' }, login: { title: 'Kirjaudu sisään', description: 'Kirjaudu sisään jatkaaksesi.', submit: 'Kirjaudu sisään', submitting: 'Kirjaudutaan…', noAccount: 'Eikö sinulla ole vielä tiliä?', registerLink: 'Rekisteröidy' }, register: { title: 'Luo tili', description: 'Luo käyttäjätilisi.', submit: 'Rekisteröidy', hasAccount: 'Onko sinulla jo tili?', loginLink: 'Kirjaudu sisään' }, fields: { name: { label: 'Koko nimi', placeholder: 'Koko nimesi' }, email: { label: 'Sähköposti', placeholder: 'nimi@example.fi' }, password: { label: 'Salasana', placeholder: 'Syötä salasanasi' } }, errors: { invalidEmail: 'Virheellinen sähköpostiosoite.', invalidCredentials: 'Väärä sähköpostiosoite tai salasana.', userNotFound: 'Käyttäjätiliä ei löytynyt.', accountNotActive: 'Käyttäjätili ei ole aktiivinen.', authenticationRequired: 'Tunnistautuminen vaaditaan.' }, alphaNotice: 'Alfaversio – tunnistautuminen on tällä hetkellä tarkoitettu testaukseen.' }
};
