import type { TranslationDictionary } from '../types';

export const mt: TranslationDictionary = {
  common: { save: 'Issejvja', cancel: 'Ikkanċella', close: 'Agħlaq', delete: 'Ħassar', edit: 'Editja', add: 'Żid', loading: 'Qed jitgħabba…', language: 'Lingwa' },
  navigation: { documents: 'Dokumenti', editor: 'Editur', metadata: 'Metadejta', preview: 'Previżjoni', settings: 'Settings' },
  studio: {
    menu: 'Menu tal-manuskritt', closeMenu: 'Agħlaq il-menu tal-manuskritt', languageSwitcher: 'Lingwa tal-interfaċċa', saved: 'Issejvjat', pending: 'Qed jiġi ssejvjat…', editorAria: 'Editur tal-manuskritt', titlePlaceholder: 'Daħħal it-titlu tal-manuskritt', noSection: 'Ma ntgħażlet l-ebda sezzjoni.',
    navigation: { document: 'Dokument', manuscript: 'Dejta tal-manuskritt', notes: 'Noti', references: 'Referenzi', contributors: 'Kontributuri', history: 'Storja', tools: 'Esportazzjoni u għodod', settings: 'Settings' },
    document: { title: 'Struttura tad-dokument', description: 'Agħżel is-sezzjoni li trid taħdem fuqha. L-informazzjoni strutturali u tal-oġġetti tibqa’ barra miż-żona tal-kitba sakemm ikollok bżonnha.', addSection: 'Żid sezzjoni', sections: 'Sezzjonijiet', objects: 'Oġġetti', annotations: 'Annotazzjonijiet', citations: 'Ċitazzjonijiet' },
    manuscript: { title: 'Dejta tal-manuskritt', description: 'Editja l-informazzjoni fil-livell tal-manuskritt separatament miż-żona tal-kitba.' },
    tools: { title: 'Esportazzjoni u għodod', description: 'Azzjonijiet sekondarji, tekniċi u potenzjalment distruttivi jinżammu barra miż-żona tal-kitba.', export: 'Esporta .omi.json', exportDescription: 'Oħloq fajl tal-manuskritt OMI kanoniku u portabbli wara li tissejvja l-bidliet pendenti bħala punt ta’ kontroll.', reset: 'Irrisettja l-kampjun', resetDescription: 'Ibdel il-kampjun alpha attwali b’manuskritt ta’ kampjun ġdid u nadif.', confirmReset: 'Tirrisettja l-manuskritt tal-kampjun attwali? Id-dejta mhux issejvjata u dik tal-kampjun attwali se tinbidel.', technicalData: 'Dejta teknika', technicalDescription: 'Iċċekkja r-rappreżentazzjoni semantika biss meta jkunu meħtieġa dettalji tekniċi.', liveJson: 'JSON tas-sezzjoni attwali', synced: 'Sinkronizzat' },
    settings: { title: 'Settings tal-interfaċċa', description: 'Agħżel liema lingwi tal-interfaċċa trid ikunu disponibbli waqt ix-xogħol. Dawn il-preferenzi jinħażnu fuq dan l-apparat.', interfaceLanguages: 'Lingwi tal-interfaċċa disponibbli', interfaceLanguagesDescription: 'Il-lingwi attivati jidhru fis-selettur rapidu tal-lingwa fl-intestatura tal-editur.', currentLanguage: 'Lingwa attwali tal-interfaċċa', currentLanguageHint: 'Il-lingwa li qed tintuża bħalissa trid tibqa’ attivata. Aqleb għal lingwa oħra qabel tiddiżattivaha.', enabledLanguage: 'Disponibbli fis-selettur rapidu', disabledLanguage: 'Moħbija mis-selettur rapidu', futureLanguages: 'Ir-reġistru tal-lingwi jista’ jitwessa’. Dizzjunarji ġodda tat-traduzzjoni jistgħu jiżdiedu mingħajr ma jerġa’ jiġi ddisinjat dan l-iskrin.' }
  },
  manuscript: { newDocument: 'Manuskritt ġdid', documentTitle: 'Titlu tad-dokument', abstract: 'Astratt', keywords: 'Kliem ewlieni', contributors: 'Kontributuri', sections: 'Sezzjonijiet', annotations: 'Noti', citations: 'Ċitazzjonijiet', bibliography: 'Biblijografija', documentLanguage: 'Lingwa tad-dokument', originalLanguage: 'Lingwa oriġinali' },
  notes: { title: 'Noti', description: 'Immaniġġja n-noti semantiċi tal-manuskritt. Il-kontenut tan-nota jibqa’ oġġett ta’ annotazzjoni indipendenti filwaqt li l-ankri inline tagħha jibqgħu fit-test.', empty: 'Dan il-manuskritt għad m’għandux noti.', emptyHint: 'Poġġi l-kursur fit-test u uża l-buttuna Nota jew Ctrl/Cmd+Alt+N.', note: 'Nota', type: 'Tip ta’ nota', body: 'Test tan-nota', bodyPlaceholder: 'Ikteb in-nota…', footnote: 'Nota f’qiegħ il-paġna', endnote: 'Nota finali', authorNote: 'Nota tal-awtur', delete: 'Ħassar in-nota', confirmDelete: 'Tħassar din in-nota u l-ankra inline tagħha mill-manuskritt?', closeEditor: 'Agħlaq l-editur tan-noti', goToNote: 'Mur għan-nota', autoSave: 'Tiġi ssejvjata mar-reviżjonijiet tal-manuskritt' },
  citations: {
    referencesTitle: 'Referenzi', referencesDescription: 'Żid xogħol darba fil-librerija tar-referenzi tal-manuskritt u mbagħad użah mill-ġdid f’kemm-il ċitazzjoni jkun meħtieġ.', addReference: 'Żid referenza', editReference: 'Editja referenza', referenceEditorDescription: 'Aħżen metadejta biblijografika strutturata indipendentement minn ċitazzjoni waħda jew stil ta’ output.', emptyLibrary: 'Il-librerija tar-referenzi tal-manuskritt hija vojta.', emptyLibraryHint: 'Żid ktieb, artiklu, sors arkivistiku, riżorsa web jew xogħol ieħor iċċitat qabel ma ddaħħal ċitazzjonijiet fit-test.', searchReferences: 'Fittex fir-referenzi', searchPlaceholder: 'Fittex bit-titlu, awtur, sena, DOI…', untitledReference: 'Referenza mingħajr titlu', occurrences: 'ċitazzjonijiet', bibliographyPreviewDescription: 'Previżjoni newtrali tar-rekords li bħalissa huma ċċitati fil-manuskritt. Il-format finali jiddependi mill-profil tal-pubblikazzjoni.', resourceType: 'Tip ta’ riżorsa', title: 'Titlu', titlePlaceholder: 'Titlu tax-xogħol iċċitat', subtitle: 'Sottotitlu', creators: 'Awturi u kontributuri', creatorsDescription: 'Żomm l-ismijiet strutturati sabiex l-istili taċ-ċitazzjoni u l-esportazzjonijiet ikunu jistgħu juruhom b’mod korrett.', addCreator: 'Żid awtur/kontributur', removeCreator: 'Neħħi awtur/kontributur', noCreators: 'Ma ġie miżjud l-ebda awtur jew kontributur.', creatorRole: 'Rwol', givenName: 'Isem', familyName: 'Kunjom', containerTitle: 'Titlu tal-ġurnal, ktieb jew pubblikazzjoni ospitanti', issued: 'Data / sena tal-pubblikazzjoni', volume: 'Volum', issue: 'Ħarġa', pages: 'Paġni / firxa', publisher: 'Pubblikatur', place: 'Post tal-pubblikazzjoni', duplicateReference: 'Probabbilment diġà teżisti referenza duplikata fil-librerija:', insertTitle: 'Daħħal ċitazzjoni', insertDescription: 'Agħżel xogħol mil-librerija tar-referenzi u, jekk trid, speċifika l-post iċċitat.', noReferences: 'Għad m’hemm l-ebda referenza disponibbli.', noReferencesHint: 'Żid ix-xogħol minn Menu tal-manuskritt → Referenzi u mbagħad erġa’ lura hawn biex tiċċitah.', insert: 'Daħħal ċitazzjoni', citation: 'Ċitazzjoni', reference: 'Xogħol iċċitat', locatorType: 'Tip ta’ lokalizzatur', locator: 'Lokalizzatur', locatorPlaceholder: 'eż. 45–47, 12r–13v, kapitlu 4', prefix: 'Prefiss', prefixPlaceholder: 'eż. ara wkoll', suffix: 'Suffiss', suffixPlaceholder: 'eż. enfasi miżjuda', openSource: 'Iftaħ is-sors', closeEditor: 'Agħlaq l-editur taċ-ċitazzjonijiet', deleteCitation: 'Ħassar iċ-ċitazzjoni', confirmDeleteCitation: 'Tħassar din iċ-ċitazzjoni mill-manuskritt? Ir-rekord biblijografiku jibqa’ fil-librerija tar-referenzi.', unresolvedReference: 'Ir-rekord biblijografiku ċċitat ma jistax jinstab jew huwa nieqes.',
    roles: { author: 'Awtur', editor: 'Editur', translator: 'Traduttur', compiler: 'Kompilatur', contributor: 'Kontributur' },
    resourceTypes: { 'journal-article': 'Artiklu f’ġurnal', book: 'Ktieb', 'book-chapter': 'Kapitlu ta’ ktieb', 'conference-paper': 'Dokument ta’ konferenza', thesis: 'Teżi', dissertation: 'Dissertazzjoni', report: 'Rapport', preprint: 'Preprint', dataset: 'Sett ta’ dejta', software: 'Software', standard: 'Standard', 'archival-source': 'Sors arkivistiku', manuscript: 'Manuskritt', 'web-page': 'Paġna web' },
    locators: { page: 'Paġna', 'page-range': 'Firxa ta’ paġni', chapter: 'Kapitlu', section: 'Sezzjoni', paragraph: 'Paragrafu', figure: 'Figura', table: 'Tabella', folio: 'Folio', line: 'Linja', timestamp: 'Marka tal-ħin' }
  },
  contributors: { description: 'Immaniġġja identitajiet akkademiċi portabbli u r-rwoli ta’ kontribut tagħhom speċifiċi għall-manuskritt.', add: 'Żid kontributur', empty: 'Ma ġew miżjuda l-ebda kontributuri ma’ dan il-manuskritt.', remove: 'Neħħi kontributur', moveUp: 'Mexxi kontributur ’il fuq', moveDown: 'Mexxi kontributur ’l isfel', givenName: 'Isem', familyName: 'Kunjom', affiliation: 'Affiljazzjoni', orcid: 'ORCID', invalidOrcid: 'Il-checksum jew il-format ORCID mhuwiex validu.', role: 'Rwol ta’ kontribut', corresponding: 'Kontributur korrispondenti', roles: { author: 'Awtur', editor: 'Editur', translator: 'Traduttur', reviewer: 'Reviżur', dataCurator: 'Kuratur tad-dejta', software: 'Software', methodology: 'Metodoloġija', visualization: 'Viżwalizzazzjoni', other: 'Ieħor' } },
  history: { title: 'Storja tar-reviżjonijiet', description: 'Reviżjonijiet OMI-SPEC-160 immutabbli rreġistrati għal dan il-manuskritt.', empty: 'Ma ġew irreġistrati l-ebda reviżjonijiet.', current: 'Attwali', revision: 'Reviżjoni', events: 'avvenimenti', groupedChanges: 'bidliet miġbura', unknownActor: 'Attur mhux magħruf', completeHistory: 'Storja sħiħa', shallowHistory: 'Storja mqassra', pendingTitle: 'Stat ta’ xogħol mhux ikkonfermat', pendingDescription: 'L-editjar reċenti qed jinġabar u se jsir reviżjoni waħda immutabbli ta’ punt ta’ kontroll.', pendingBadge: 'Pendenti', checkpoint: 'Issejvja punt ta’ kontroll', discard: 'Armi l-bidliet', confirmDiscard: 'Tarmi l-bidliet kollha mhux ikkonfermati u tirrestawra l-aħħar reviżjoni kkonfermata?', revert: 'Irrestawra', confirmRevert: 'Toħloq reviżjoni ġdida li tirrestawra dan l-istat preċedenti tal-manuskritt?', revertBlocked: 'Issejvja jew armi l-istat ta’ xogħol pendenti qabel tirrestawra reviżjoni kkonfermata.', tombstonesTitle: 'Rekords ta’ oġġetti mħassra', tombstonesDescription: 'Ir-rekords permanenti OMI-SPEC-160 tombstone jippreservaw l-identifikaturi tal-oġġetti mħassra u l-evidenza tar-restawr.', tombstoneActive: 'Imħassar', tombstoneRestored: 'Irrestawrat', operations: { snapshotCreated: 'Inħoloq snapshot tal-manuskritt', titleChanged: 'Inbidel it-titlu tal-manuskritt', abstractChanged: 'Inbidel l-astratt tal-manuskritt', sectionCreated: 'Żdiedet sezzjoni', blockChanged: 'Inbidel il-kontenut tal-blokka', contributorAdded: 'Żdied kontributur', contributorChanged: 'Inbidlet l-identità tal-kontributur', contributorRemoved: 'Tneħħa kontributur', contributionChanged: 'Inbidel ir-rwol ta’ kontribut', contributorsReordered: 'Il-kontributuri ġew irranġati mill-ġdid', reverted: 'Ġiet irrestawrata reviżjoni preċedenti' } },
  editor: { addSection: 'Żid sezzjoni', addParagraph: 'Żid paragrafu', addNote: 'Nota', addCitation: 'Ċitazzjoni', untitledSection: 'Sezzjoni mingħajr titlu', emptyParagraph: 'Ibda ikteb…', paragraph: 'Paragrafu', heading: 'Intestatura', quote: 'Kwotazzjoni', insertNote: 'Daħħal nota semantika tal-manuskritt', insertCitation: 'Daħħal ċitazzjoni semantika', loading: 'Qed jitgħabba l-editur…' },
  status: { draft: 'Abbozz', submitted: 'Sottomess', accepted: 'Aċċettat', published: 'Ippubblikat' },
  validation: { requiredField: 'Dan il-qasam huwa obbligatorju.', invalidDocument: 'L-istruttura tad-dokument mhijiex valida.', unsupportedSchema: 'Il-verżjoni tal-iskema tad-dokument mhijiex appoġġjata.' },
  languages: { en: 'Ingliż', hu: 'Ungeriż', de: 'Ġermaniż' },
  auth: { brand: { name: 'Open Manuscript Studio', description: 'Kitba akkademika kollaborattiva' }, login: { title: 'Idħol', description: 'Idħol biex tkompli.', submit: 'Idħol', submitting: 'Qed tidħol…', noAccount: 'Għad m’għandekx kont?', registerLink: 'Irreġistra' }, register: { title: 'Oħloq kont', description: 'Oħloq il-kont tiegħek.', submit: 'Irreġistra', hasAccount: 'Diġà għandek kont?', loginLink: 'Idħol' }, fields: { name: { label: 'Isem sħiħ', placeholder: 'L-isem sħiħ tiegħek' }, email: { label: 'Email', placeholder: 'isem@example.mt' }, password: { label: 'Password', placeholder: 'Daħħal il-password tiegħek' } }, errors: { invalidEmail: 'Indirizz tal-email mhux validu.', invalidCredentials: 'Indirizz tal-email jew password mhux korretti.', userNotFound: 'Il-kont tal-utent ma nstabx.', accountNotActive: 'Il-kont tal-utent mhuwiex attiv.', authenticationRequired: 'Hija meħtieġa awtentikazzjoni.' }, alphaNotice: 'Verżjoni alpha – l-awtentikazzjoni bħalissa hija għal skopijiet ta’ ttestjar.' }
};
