import type { TranslationDictionary } from '../types';

export const ro: TranslationDictionary = {
  common: { save: 'Salvează', cancel: 'Anulează', close: 'Închide', delete: 'Șterge', edit: 'Editează', add: 'Adaugă', loading: 'Se încarcă…', language: 'Limbă' },
  navigation: { documents: 'Documente', editor: 'Editor', metadata: 'Metadate', preview: 'Previzualizare', settings: 'Setări' },
  studio: {
    menu: 'Meniul manuscrisului', closeMenu: 'Închide meniul manuscrisului', languageSwitcher: 'Limba interfeței', saved: 'Salvat', pending: 'Se salvează…', editorAria: 'Editor de manuscris', titlePlaceholder: 'Introduceți titlul manuscrisului', noSection: 'Nu este selectată nicio secțiune.',
    navigation: { document: 'Document', manuscript: 'Datele manuscrisului', notes: 'Note', references: 'Referințe', contributors: 'Contributori', history: 'Istoric', tools: 'Export și instrumente', settings: 'Setări' },
    document: { title: 'Structura documentului', description: 'Alegeți secțiunea la care doriți să lucrați. Informațiile structurale și despre obiecte rămân în afara suprafeței de redactare până când sunt necesare.', addSection: 'Adaugă secțiune', sections: 'Secțiuni', objects: 'Obiecte', annotations: 'Adnotări', citations: 'Citări' },
    manuscript: { title: 'Datele manuscrisului', description: 'Editați informațiile la nivel de manuscris separat de suprafața de redactare.' },
    tools: { title: 'Export și instrumente', description: 'Acțiunile secundare, tehnice și potențial distructive sunt păstrate în afara suprafeței de redactare.', export: 'Exportă .omi.json', exportDescription: 'Creați un fișier de manuscris OMI canonic și portabil după salvarea modificărilor în așteptare ca punct de control.', reset: 'Resetează exemplul', resetDescription: 'Înlocuiți exemplul alfa curent cu un manuscris exemplu nou și curat.', confirmReset: 'Resetați manuscrisul exemplu curent? Datele nesalvate și datele exemplului curent vor fi înlocuite.', technicalData: 'Date tehnice', technicalDescription: 'Inspectați reprezentarea semantică numai când sunt necesare detalii tehnice.', liveJson: 'JSON-ul secțiunii curente', synced: 'Sincronizat' },
    settings: { title: 'Setările interfeței', description: 'Alegeți limbile interfeței pe care doriți să le aveți disponibile în timpul lucrului. Preferințele sunt stocate pe acest dispozitiv.', interfaceLanguages: 'Limbi de interfață disponibile', interfaceLanguagesDescription: 'Limbile activate apar în selectorul rapid de limbă din antetul editorului.', currentLanguage: 'Limba curentă a interfeței', currentLanguageHint: 'Limba utilizată în prezent trebuie să rămână activată. Comutați la altă limbă înainte de a o dezactiva.', enabledLanguage: 'Disponibilă în selectorul rapid', disabledLanguage: 'Ascunsă din selectorul rapid', futureLanguages: 'Registrul limbilor este extensibil. Pot fi adăugate noi dicționare de traducere fără reproiectarea acestui ecran de setări.' }
  },
  manuscript: { newDocument: 'Manuscris nou', documentTitle: 'Titlul documentului', abstract: 'Rezumat', keywords: 'Cuvinte-cheie', contributors: 'Contributori', sections: 'Secțiuni', annotations: 'Note', citations: 'Citări', bibliography: 'Bibliografie', documentLanguage: 'Limba documentului', originalLanguage: 'Limba originală' },
  notes: { title: 'Note', description: 'Gestionați notele semantice ale manuscrisului. Conținutul notei rămâne un obiect de adnotare independent, iar ancorele sale în linie rămân în text.', empty: 'Acest manuscris nu are încă note.', emptyHint: 'Plasați cursorul în text și utilizați butonul Notă sau Ctrl/Cmd+Alt+N.', note: 'Notă', type: 'Tip de notă', body: 'Textul notei', bodyPlaceholder: 'Scrieți nota…', footnote: 'Notă de subsol', endnote: 'Notă de final', authorNote: 'Nota autorului', delete: 'Șterge nota', confirmDelete: 'Ștergeți această notă și ancora sa în linie din manuscris?', closeEditor: 'Închide editorul de note', goToNote: 'Mergi la notă', autoSave: 'Se salvează împreună cu reviziile manuscrisului' },
  citations: {
    referencesTitle: 'Referințe', referencesDescription: 'Adăugați o lucrare o singură dată în biblioteca de referințe a manuscrisului, apoi reutilizați-o în oricâte apariții de citare sunt necesare.', addReference: 'Adaugă referință', editReference: 'Editează referința', referenceEditorDescription: 'Stocați metadate bibliografice structurate independent de o citare individuală sau de un stil de ieșire.', emptyLibrary: 'Biblioteca de referințe a manuscrisului este goală.', emptyLibraryHint: 'Adăugați o carte, un articol, o sursă de arhivă, o resursă web sau altă lucrare citată înainte de a introduce citări în text.', searchReferences: 'Caută în referințe', searchPlaceholder: 'Caută după titlu, autor, an, DOI…', untitledReference: 'Referință fără titlu', occurrences: 'citări', bibliographyPreviewDescription: 'Previzualizare neutră a înregistrărilor citate în prezent în manuscris. Formatarea finală aparține profilului de publicare.', resourceType: 'Tip de resursă', title: 'Titlu', titlePlaceholder: 'Titlul lucrării citate', subtitle: 'Subtitlu', creators: 'Autori și contributori', creatorsDescription: 'Păstrați numele contributorilor structurate astfel încât stilurile de citare și exporturile să le poată reda corect.', addCreator: 'Adaugă autor/contributor', removeCreator: 'Elimină autor/contributor', noCreators: 'Nu a fost adăugat niciun autor sau contributor.', creatorRole: 'Rol', givenName: 'Prenume', familyName: 'Nume de familie', containerTitle: 'Titlul revistei, cărții sau publicației gazdă', issued: 'Data / anul publicării', volume: 'Volum', issue: 'Număr', pages: 'Pagini / întindere', publisher: 'Editură', place: 'Locul publicării', duplicateReference: 'În biblioteca de referințe există deja un duplicat probabil:', insertTitle: 'Inserează citare', insertDescription: 'Alegeți o lucrare din biblioteca de referințe a manuscrisului și, opțional, specificați locul citat.', noReferences: 'Nu este încă disponibilă nicio referință.', noReferencesHint: 'Adăugați lucrarea din Meniul manuscrisului → Referințe, apoi reveniți aici pentru a o cita.', insert: 'Inserează citare', citation: 'Citare', reference: 'Lucrare citată', locatorType: 'Tip de localizator', locator: 'Localizator', locatorPlaceholder: 'de ex. 45–47, 12r–13v, capitolul 4', prefix: 'Prefix', prefixPlaceholder: 'de ex. vezi și', suffix: 'Sufix', suffixPlaceholder: 'de ex. evidențiere adăugată', openSource: 'Deschide sursa', closeEditor: 'Închide editorul de citări', deleteCitation: 'Șterge citarea', confirmDeleteCitation: 'Ștergeți această apariție de citare din manuscris? Înregistrarea bibliografică va rămâne în biblioteca de referințe.', unresolvedReference: 'Înregistrarea bibliografică citată nu poate fi rezolvată sau lipsește.',
    roles: { author: 'Autor', editor: 'Editor', translator: 'Traducător', compiler: 'Compilator', contributor: 'Contributor' },
    resourceTypes: { 'journal-article': 'Articol de revistă', book: 'Carte', 'book-chapter': 'Capitol de carte', 'conference-paper': 'Lucrare de conferință', thesis: 'Lucrare de absolvire', dissertation: 'Teză de doctorat', report: 'Raport', preprint: 'Preprint', dataset: 'Set de date', software: 'Software', standard: 'Standard', 'archival-source': 'Sursă de arhivă', manuscript: 'Manuscris', 'web-page': 'Pagină web' },
    locators: { page: 'Pagină', 'page-range': 'Interval de pagini', chapter: 'Capitol', section: 'Secțiune', paragraph: 'Paragraf', figure: 'Figură', table: 'Tabel', folio: 'Folio', line: 'Linie', timestamp: 'Marcaj temporal' }
  },
  contributors: { description: 'Gestionați identități academice portabile și rolurile lor de contribuție specifice manuscrisului.', add: 'Adaugă contributor', empty: 'Nu au fost adăugați contributori la acest manuscris.', remove: 'Elimină contributorul', moveUp: 'Mută contributorul în sus', moveDown: 'Mută contributorul în jos', givenName: 'Prenume', familyName: 'Nume de familie', affiliation: 'Afiliere', orcid: 'ORCID', invalidOrcid: 'Suma de control sau formatul ORCID este nevalid.', role: 'Rol de contribuție', corresponding: 'Contributor corespondent', roles: { author: 'Autor', editor: 'Editor', translator: 'Traducător', reviewer: 'Recenzor', dataCurator: 'Curator de date', software: 'Software', methodology: 'Metodologie', visualization: 'Vizualizare', other: 'Altul' } },
  history: { title: 'Istoricul reviziilor', description: 'Revizii OMI-SPEC-160 imuabile înregistrate pentru acest manuscris.', empty: 'Nu au fost înregistrate revizii.', current: 'Curentă', revision: 'Revizie', events: 'evenimente', groupedChanges: 'modificări grupate', unknownActor: 'Actor necunoscut', completeHistory: 'Istoric complet', shallowHistory: 'Istoric prescurtat', pendingTitle: 'Stare de lucru neconfirmată', pendingDescription: 'Editările recente sunt grupate și vor deveni o singură revizie imuabilă de punct de control.', pendingBadge: 'În așteptare', checkpoint: 'Salvează punctul de control', discard: 'Renunță la modificări', confirmDiscard: 'Renunțați la toate modificările neconfirmate și restaurați ultima revizie confirmată?', revert: 'Restaurează', confirmRevert: 'Creați o nouă revizie care restaurează această stare anterioară a manuscrisului?', revertBlocked: 'Salvați sau renunțați la starea de lucru în așteptare înainte de a restaura o revizie confirmată.', tombstonesTitle: 'Înregistrări ale obiectelor șterse', tombstonesDescription: 'Înregistrările persistente OMI-SPEC-160 tombstone păstrează identificatorii obiectelor șterse și dovezile restaurării.', tombstoneActive: 'Șters', tombstoneRestored: 'Restaurat', operations: { snapshotCreated: 'Instantaneu al manuscrisului creat', titleChanged: 'Titlul manuscrisului modificat', abstractChanged: 'Rezumatul manuscrisului modificat', sectionCreated: 'Secțiune adăugată', blockChanged: 'Conținutul blocului modificat', contributorAdded: 'Contributor adăugat', contributorChanged: 'Identitatea contributorului modificată', contributorRemoved: 'Contributor eliminat', contributionChanged: 'Rolul de contribuție modificat', contributorsReordered: 'Contributorii reordonați', reverted: 'Revizie anterioară restaurată' } },
  editor: { addSection: 'Adaugă secțiune', addParagraph: 'Adaugă paragraf', addNote: 'Notă', addCitation: 'Citare', untitledSection: 'Secțiune fără titlu', emptyParagraph: 'Începeți să scrieți…', paragraph: 'Paragraf', heading: 'Titlu', quote: 'Citat', insertNote: 'Inserează notă semantică de manuscris', insertCitation: 'Inserează citare semantică', loading: 'Se încarcă editorul…' },
  status: { draft: 'Ciornă', submitted: 'Trimis', accepted: 'Acceptat', published: 'Publicat' },
  validation: { requiredField: 'Acest câmp este obligatoriu.', invalidDocument: 'Structura documentului este nevalidă.', unsupportedSchema: 'Versiunea schemei documentului nu este acceptată.' },
  languages: { en: 'Engleză', hu: 'Maghiară', de: 'Germană' },
  auth: { brand: { name: 'Open Manuscript Studio', description: 'Redactare academică colaborativă' }, login: { title: 'Autentificare', description: 'Autentificați-vă pentru a continua.', submit: 'Autentificare', submitting: 'Se autentifică…', noAccount: 'Nu aveți încă un cont?', registerLink: 'Înregistrare' }, register: { title: 'Creează cont', description: 'Creați-vă contul.', submit: 'Înregistrare', hasAccount: 'Aveți deja un cont?', loginLink: 'Autentificare' }, fields: { name: { label: 'Nume complet', placeholder: 'Numele dvs. complet' }, email: { label: 'E-mail', placeholder: 'nume@example.ro' }, password: { label: 'Parolă', placeholder: 'Introduceți parola' } }, errors: { invalidEmail: 'Adresă de e-mail nevalidă.', invalidCredentials: 'Adresă de e-mail sau parolă incorectă.', userNotFound: 'Contul de utilizator nu a fost găsit.', accountNotActive: 'Contul de utilizator nu este activ.', authenticationRequired: 'Este necesară autentificarea.' }, alphaNotice: 'Versiune alfa – autentificarea este utilizată în prezent pentru testare.' }
};
