import type { TranslationDictionary } from '../types';

export const sv: TranslationDictionary = {
  common: { save: 'Spara', cancel: 'Avbryt', close: 'Stäng', delete: 'Ta bort', edit: 'Redigera', add: 'Lägg till', loading: 'Läser in…', language: 'Språk' },
  navigation: { documents: 'Dokument', editor: 'Redigerare', metadata: 'Metadata', preview: 'Förhandsvisning', settings: 'Inställningar' },
  studio: {
    menu: 'Manuskriptmeny', closeMenu: 'Stäng manuskriptmenyn', languageSwitcher: 'Gränssnittsspråk', saved: 'Sparat', pending: 'Sparar…', editorAria: 'Manuskriptredigerare', titlePlaceholder: 'Ange manuskriptets titel', noSection: 'Ingen sektion är vald.',
    navigation: { document: 'Dokument', manuscript: 'Manuskriptdata', notes: 'Noter', references: 'Referenser', contributors: 'Medverkande', history: 'Historik', tools: 'Export och verktyg', settings: 'Inställningar' },
    document: { title: 'Dokumentstruktur', description: 'Välj den sektion du vill arbeta med. Struktur- och objektinformation hålls utanför skrivytan tills du behöver den.', addSection: 'Lägg till sektion', sections: 'Sektioner', objects: 'Objekt', annotations: 'Annoteringar', citations: 'Citeringar' },
    manuscript: { title: 'Manuskriptdata', description: 'Redigera information på manuskriptnivå separat från skrivytan.' },
    tools: { title: 'Export och verktyg', description: 'Sekundära, tekniska och potentiellt destruktiva åtgärder hålls utanför skrivytan.', export: 'Exportera .omi.json', exportDescription: 'Skapa en kanonisk portabel OMI-manuskriptfil efter att väntande ändringar har sparats som kontrollpunkt.', reset: 'Återställ exempel', resetDescription: 'Ersätt det aktuella alfaexemplet med ett nytt rent exempelmanuskript.', confirmReset: 'Återställa det aktuella exempelmanuskriptet? Osparade och aktuella exempeldata kommer att ersättas.', technicalData: 'Tekniska data', technicalDescription: 'Granska den semantiska representationen endast när tekniska detaljer behövs.', liveJson: 'JSON för aktuell sektion', synced: 'Synkroniserat' },
    settings: { title: 'Gränssnittsinställningar', description: 'Välj vilka gränssnittsspråk du vill ha tillgängliga medan du arbetar. Inställningarna sparas på den här enheten.', interfaceLanguages: 'Tillgängliga gränssnittsspråk', interfaceLanguagesDescription: 'Aktiverade språk visas i den snabba språkväxlaren i redigerarens sidhuvud.', currentLanguage: 'Aktuellt gränssnittsspråk', currentLanguageHint: 'Språket som används just nu måste förbli aktiverat. Växla till ett annat språk innan du inaktiverar det.', enabledLanguage: 'Tillgängligt i snabbväxlaren', disabledLanguage: 'Dolt i snabbväxlaren', futureLanguages: 'Språkregistret kan utökas. Nya översättningsordlistor kan läggas till utan att den här inställningsvyn behöver göras om.' }
  },
  manuscript: { newDocument: 'Nytt manuskript', documentTitle: 'Dokumenttitel', abstract: 'Sammanfattning', keywords: 'Nyckelord', contributors: 'Medverkande', sections: 'Sektioner', annotations: 'Noter', citations: 'Citeringar', bibliography: 'Bibliografi', documentLanguage: 'Dokumentspråk', originalLanguage: 'Originalspråk' },
  notes: { title: 'Noter', description: 'Hantera semantiska manuskriptnoter. Nottexten förblir ett fristående annoteringsobjekt medan dess infogade ankare ligger kvar i texten.', empty: 'Det här manuskriptet har ännu inga noter.', emptyHint: 'Placera markören i texten och använd knappen Not eller Ctrl/Cmd+Alt+N.', note: 'Not', type: 'Nottyp', body: 'Nottext', bodyPlaceholder: 'Skriv noten…', footnote: 'Fotnot', endnote: 'Slutnot', authorNote: 'Författarnot', delete: 'Ta bort not', confirmDelete: 'Ta bort den här noten och dess infogade ankare från manuskriptet?', closeEditor: 'Stäng notredigeraren', goToNote: 'Gå till not', autoSave: 'Sparas tillsammans med manuskriptrevisioner' },
  citations: {
    referencesTitle: 'Referenser', referencesDescription: 'Lägg till ett verk en gång i manuskriptets referensbibliotek och återanvänd det sedan i så många citeringstillfällen som behövs.', addReference: 'Lägg till referens', editReference: 'Redigera referens', referenceEditorDescription: 'Lagra strukturerade bibliografiska metadata oberoende av en enskild citering eller utdataformat.', emptyLibrary: 'Manuskriptets referensbibliotek är tomt.', emptyLibraryHint: 'Lägg till en bok, artikel, arkivkälla, webbresurs eller annat citerat verk innan du infogar citeringar i texten.', searchReferences: 'Sök i referenser', searchPlaceholder: 'Sök efter titel, upphovsperson, år, DOI…', untitledReference: 'Referens utan titel', occurrences: 'citeringar', bibliographyPreviewDescription: 'Neutral förhandsvisning av poster som för närvarande citeras i manuskriptet. Slutlig formatering styrs av publiceringsprofilen.', resourceType: 'Resurstyp', title: 'Titel', titlePlaceholder: 'Titel på det citerade verket', subtitle: 'Undertitel', creators: 'Upphovspersoner och medverkande', creatorsDescription: 'Behåll namnen strukturerade så att citeringsstilar och exporter kan återge dem korrekt.', addCreator: 'Lägg till upphovsperson', removeCreator: 'Ta bort upphovsperson', noCreators: 'Ingen upphovsperson har lagts till.', creatorRole: 'Roll', givenName: 'Förnamn', familyName: 'Efternamn', containerTitle: 'Titel på tidskrift, bok eller överordnad publikation', issued: 'Publiceringsdatum / år', volume: 'Volym', issue: 'Nummer', pages: 'Sidor / omfattning', publisher: 'Utgivare', place: 'Utgivningsort', duplicateReference: 'En sannolik dubblett finns redan i referensbiblioteket:', insertTitle: 'Infoga citering', insertDescription: 'Välj ett verk från manuskriptets referensbibliotek och ange vid behov den citerade platsen.', noReferences: 'Ingen referens är tillgänglig ännu.', noReferencesHint: 'Lägg till verket via Manuskriptmeny → Referenser och återvänd sedan hit för att citera det.', insert: 'Infoga citering', citation: 'Citering', reference: 'Citerat verk', locatorType: 'Lokalisatortyp', locator: 'Lokalisator', locatorPlaceholder: 't.ex. 45–47, 12r–13v, kapitel 4', prefix: 'Prefix', prefixPlaceholder: 't.ex. se även', suffix: 'Suffix', suffixPlaceholder: 't.ex. betoning tillagd', openSource: 'Öppna källa', closeEditor: 'Stäng citeringsredigeraren', deleteCitation: 'Ta bort citering', confirmDeleteCitation: 'Ta bort den här citeringsförekomsten från manuskriptet? Den bibliografiska posten ligger kvar i referensbiblioteket.', unresolvedReference: 'Den citerade bibliografiska posten kan inte lösas eller saknas.',
    roles: { author: 'Författare', editor: 'Redaktör', translator: 'Översättare', compiler: 'Sammanställare', contributor: 'Medverkande' },
    resourceTypes: { 'journal-article': 'Tidskriftsartikel', book: 'Bok', 'book-chapter': 'Bokkapitel', 'conference-paper': 'Konferensbidrag', thesis: 'Examensarbete', dissertation: 'Avhandling', report: 'Rapport', preprint: 'Preprint', dataset: 'Dataset', software: 'Programvara', standard: 'Standard', 'archival-source': 'Arkivkälla', manuscript: 'Manuskript', 'web-page': 'Webbsida' },
    locators: { page: 'Sida', 'page-range': 'Sidintervall', chapter: 'Kapitel', section: 'Sektion', paragraph: 'Stycke', figure: 'Figur', table: 'Tabell', folio: 'Folio', line: 'Rad', timestamp: 'Tidsstämpel' }
  },
  contributors: { description: 'Hantera portabla vetenskapliga identiteter och deras manuskriptspecifika bidragsroller.', add: 'Lägg till medverkande', empty: 'Inga medverkande har lagts till i detta manuskript.', remove: 'Ta bort medverkande', moveUp: 'Flytta medverkande uppåt', moveDown: 'Flytta medverkande nedåt', givenName: 'Förnamn', familyName: 'Efternamn', affiliation: 'Affiliering', orcid: 'ORCID', invalidOrcid: 'ORCID-kontrollsumman eller formatet är ogiltigt.', role: 'Bidragsroll', corresponding: 'Korresponderande medverkande', roles: { author: 'Författare', editor: 'Redaktör', translator: 'Översättare', reviewer: 'Granskare', dataCurator: 'Datakurator', software: 'Programvara', methodology: 'Metodologi', visualization: 'Visualisering', other: 'Annat' } },
  history: { title: 'Revisionshistorik', description: 'Oföränderliga OMI-SPEC-160-revisioner registrerade för detta manuskript.', empty: 'Inga revisioner har registrerats.', current: 'Aktuell', revision: 'Revision', events: 'händelser', groupedChanges: 'grupperade ändringar', unknownActor: 'Okänd aktör', completeHistory: 'Fullständig historik', shallowHistory: 'Kort historik', pendingTitle: 'Obekräftat arbetsläge', pendingDescription: 'Senaste redigeringar grupperas och blir en enda oföränderlig kontrollpunktsrevision.', pendingBadge: 'Väntande', checkpoint: 'Spara kontrollpunkt', discard: 'Kassera ändringar', confirmDiscard: 'Kassera alla obekräftade ändringar och återställ den senaste bekräftade revisionen?', revert: 'Återställ', confirmRevert: 'Skapa en ny revision som återställer detta tidigare manuskriptläge?', revertBlocked: 'Spara eller kassera det väntande arbetsläget innan du återställer en bekräftad revision.', tombstonesTitle: 'Poster för borttagna objekt', tombstonesDescription: 'Beständiga OMI-SPEC-160-tombstone-poster bevarar identifierare för borttagna objekt och bevis på återställning.', tombstoneActive: 'Borttaget', tombstoneRestored: 'Återställt', operations: { snapshotCreated: 'Ögonblicksbild av manuskript skapad', titleChanged: 'Manuskripttitel ändrad', abstractChanged: 'Manuskriptsammanfattning ändrad', sectionCreated: 'Sektion tillagd', blockChanged: 'Blockinnehåll ändrat', contributorAdded: 'Medverkande tillagd', contributorChanged: 'Identitet för medverkande ändrad', contributorRemoved: 'Medverkande borttagen', contributionChanged: 'Bidragsroll ändrad', contributorsReordered: 'Medverkande omordnade', reverted: 'Tidigare revision återställd' } },
  editor: { addSection: 'Lägg till sektion', addParagraph: 'Lägg till stycke', addNote: 'Not', addCitation: 'Citering', untitledSection: 'Sektion utan titel', emptyParagraph: 'Börja skriva…', paragraph: 'Stycke', heading: 'Rubrik', quote: 'Citat', insertNote: 'Infoga semantisk manuskriptnot', insertCitation: 'Infoga semantisk citering', loading: 'Läser in redigeraren…' },
  status: { draft: 'Utkast', submitted: 'Inskickat', accepted: 'Accepterat', published: 'Publicerat' },
  validation: { requiredField: 'Det här fältet är obligatoriskt.', invalidDocument: 'Dokumentstrukturen är ogiltig.', unsupportedSchema: 'Dokumentschemats version stöds inte.' },
  languages: { en: 'Engelska', hu: 'Ungerska', de: 'Tyska' },
  auth: { brand: { name: 'Open Manuscript Studio', description: 'Samarbetsbaserat vetenskapligt skrivande' }, login: { title: 'Logga in', description: 'Logga in för att fortsätta.', submit: 'Logga in', submitting: 'Loggar in…', noAccount: 'Har du inget konto ännu?', registerLink: 'Registrera' }, register: { title: 'Skapa konto', description: 'Skapa ditt konto.', submit: 'Registrera', hasAccount: 'Har du redan ett konto?', loginLink: 'Logga in' }, fields: { name: { label: 'Fullständigt namn', placeholder: 'Ditt fullständiga namn' }, email: { label: 'E-post', placeholder: 'namn@example.se' }, password: { label: 'Lösenord', placeholder: 'Ange ditt lösenord' } }, errors: { invalidEmail: 'Ogiltig e-postadress.', invalidCredentials: 'Felaktig e-postadress eller lösenord.', userNotFound: 'Användarkontot kunde inte hittas.', accountNotActive: 'Användarkontot är inte aktivt.', authenticationRequired: 'Autentisering krävs.' }, alphaNotice: 'Alfaversion – autentisering används för närvarande för teständamål.' }
};
